### ISSUE TITLE
View name in drop-down menu: italicised & gray

### ISSUE THREAD

**Issue by gitany** [felixhayashi/TW5-TiddlyMap#103]
Hi Felix,

I noticed the view name appears italicised & gray if there is a second Uppercase letter preceded by a lowercase letter.

Best illustrated by this screenshot:

![tw-issue103](https://cloud.githubusercontent.com/assets/11840950/7078380/859296be-dee6-11e4-957d-facbc224f67d.jpg)

Not sure if this is intentional, but if described in the documentation, I guess a user can take advantage of it.

**Comment by felixhayashi** [comment]
Hi gitany

> Not sure if this is intentional, but if described in the documentation, I guess a user can take advantage of it.

True! Thanks, I'll fix that. It happens because I use TiddlyWiki's "transclude widget" (which translates camel case into links) and not the "view widget"...
