### ISSUE TITLE
It seems edge-filter types are not displaying properly in live view?

### ISSUE THREAD

**Issue by ryanl888** [felixhayashi/TW5-TiddlyMap#105]
Hi @felixhayashi
 
Unfortunately, I keep running into problems!  I really like the added enhancement showing on the tiddlymap sample site of what I believe are called edgetype filters - where a tiddler's tags (tagged with) and links (linked to) etc can be shown in live view.  However, when I tried to get it working on my test tw, I did not get that behaviour - even after changing the neighborhood setting.  

I also noticed that even though I 're-installed' - ie deleted then re-imported- the tiddlymap tiddlers, some edgetype tiddlers were NOT present ie $:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/tmap:link - even though they were configured in the edge-type manager.  

Alas, I tried importing them but no success either.  I then tried a 're-install' on a blank TW5.1.8 and couldn't get the edge types working either.  

I suspect some settings are changed, or there is difficulty in the 'upgrade', or maybe you are just testing it?  What I did as a stop-gap to get it working was just download a copy of the sample site - as explained here: https://groups.google.com/forum/#!searchin/tiddlywiki/download$20tw$20site|sort:date/tiddlywiki/9G-t9m6N0XM/9ImE9JgYTx4J - and used that as a template.  

Regards,
Ryan

**Comment by felixhayashi** [comment]
Hi @ryanl888 

> Unfortunately, I keep running into problems!

As long as they are solvable ;)

> However, when I tried to get it working on my test tw, I did not get that behaviour - even after changing the neighborhood setting. 

Strange, I just added tiddlymap to TW 5.1.8 (just open tiddlywiki.com and drag'n'dropped the tiddlymap stuff for import and everything works.

Does your live view's edge filter look like this: 

    [prefix[$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes]]

And your live view's node filter like this

    [!is[system]field:title{$:/temp/focussedTiddler}]

?

> I also noticed that even though I 're-installed' - ie deleted then re-imported- the tiddlymap tiddlers, some edgetype tiddlers were NOT present ie $:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/tmap:link - even though they were configured in the edge-type manager.

You mean there were no edges of the type "tmap:link" displayed in the graph? An edge-type can exist even when there are no edges of that type in the wiki. A type is just a class that defines how links look and behave.

Also please note that only manually added links are recognized by TiddlyMap ([[A link to a Tiddler]]; CamelCaseLinks; `<$link ...`). Links that are generated through a list are not displayed in a graph (see https://github.com/felixhayashi/TW5-TiddlyMap/issues/58#issuecomment-75435065 and https://github.com/felixhayashi/TW5-TiddlyMap/issues/58#issuecomment-75452076).

If you open the edge-type manager and go to the overview section of "tmap:link", how many edges of this type does your wiki contain ("Edges of this type")?

-Felix

**Comment by ryanl888** [comment]
Hi @felixhayashi 
> I just added tiddlymap to TW 5.1.8 (just open tiddlywiki.com and drag'n'dropped the tiddlymap stuff for import and everything works.

Interesting - how did you do this without saving and reloading?  Or did you create a new tiddlyspot with it?

>Does your live view's edge filter look like this:

>>[prefix[$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes]]

>And your live view's node filter like this

>>[!is[system]field:title{$:/temp/focussedTiddler}]

Yes

>You mean there were no edges of the type "tmap:link" displayed in the graph?

Um - I am not sure - are you referring the edge 'links to'? I was pointing to the fact that the actual tiddler wasn't there under $:/plugins/felixhayashi/tiddlymap/graph/edgeTypes  - though it was configured in the edgetype manager.

>Also please note that only manually added links are recognized by TiddlyMap

Ok, here is what I did: on Tiddlymap demo: create tiddler test, add tag example.  Check live view - Test tiddler should be showing an edge to tagged with example.  I couldn't get this working on my tw.

Also, I forgot to mention this is done in Firefox browser - which one did you use?


I will still work on it, thanks!

Regards,
Ryan

**Comment by ryanl888** [comment]
Hi @felixhayashi 

I found the problem - seems like adblock in Firefox was causing the issue - I got to remember that :-p

Everything is working now on a new tw.  I probably will just move my tiddlers over to that one.

Regards,
Ryan

**Comment by felixhayashi** [comment]
Hi @ryanl888 

> I found the problem - seems like adblock in Firefox was causing the issue - I got to remember that :-p

glad you identified the the troublemaker ;)

> Interesting - how did you do this without saving and reloading? Or did you create a new tiddlyspot with it?

Ehm, of course after saving and refresh.

> Um - I am not sure - are you referring the edge 'links to'? I was pointing to the fact that the actual tiddler wasn't there under $:/plugins/felixhayashi/tiddlymap/graph/edgeTypes - though it was configured in the edgetype manager.

Ah, then maybe you searched for normal or system tiddlers? This one (and all other "tmap:") comes directly with the plugin and you can only find it (if you haven't overridden it by changing the option) if you use "advanced search" and open the "shadow tiddlers" tab and search for something like "/tmap:".

> Also, I forgot to mention this is done in Firefox browser - which one did you use?

FF and chrome on linux.

-Felix

**Comment by ryanl888** [comment]
Hi @felixhayashi 
Just one other observation - not sure if this is the case for you to or not.  It seems that if I download a **blank** empty TW5.1.8, I can only get live view working as I described earlier (no further edge types using the test I mentioned).  Does it work properly for you?

I checked the edgetype config as you mentioned and it seems to be correct.  I also tested on three browsers - just to be sure.  

This behaviour seems to be different from a full download of a TW5.1.8 as you mentioned.  

Is it possibly that the empty tw5.1.8 hasn't been updated in some way that the full has?

Regards,
Ryan

**Comment by felixhayashi** [comment]
Hi @ryanl888 

Sorry, maybe is a bit hidden. But please have a look at the docs

http://felixhayashi.github.io/TW5-TiddlyMap/index.html#How%20to%20install%20TiddlyMap%3F

> If you want to use the "live view", change your wiki's story view to "Top" (Configuration ➡ Appearance ➡ Story view ➡ Current view).

I think this will solve your problem :)

That said, I think I should disabled the live view when this configuration is not present. Or at least open a modal that says "Dude, you forgot to enable the top story view" :)

-Felix

**Comment by ryanl888** [comment]
Hi @felixhayashi 

yeah, I had already done that and did notice tiddlymap used to ask you to enable top view - so that is a good idea ;)  Still, I **cannot** get edgetypes working on the blank TW5.1.8.  when I enable top story view, I get a live view with no edge types - using the example above - I get a test tiddler in live view - with no showing edge types (ie tagged with Example).  Does it work for you?

Regards,
Ryan

**Comment by felixhayashi** [comment]
I have to admit. This is weird.

**Comment by felixhayashi** [comment]
No wait! it did not work because I used the tag "GettingStarted" which is a shadow tiddler.

Did you do the same? Because the tag needs to exist and not be a shadow tiddler!

**Comment by ryanl888** [comment]
Hi @felixhayashi 
hmm - I used the tag "Example".  I tried closing "GettingStarted" and added another.  Seems to be same result...

Regards,
Ryan
![screen shot 2015-04-11 at 2 09 47 pm](https://cloud.githubusercontent.com/assets/11003603/7103098/a7ae13f8-e054-11e4-8160-e93fd5d991e7.png)

**Comment by felixhayashi** [comment]
But does the tiddler "Example" exists?

**Comment by ryanl888** [comment]
Oh!  Does it matter?? No kidding, I had no idea it worked like that.  OK, problem solved - my stupidity noted :-p

Regards,
Ryan

**Comment by felixhayashi** [comment]
> Oh! Does it matter?? No kidding, I had no idea it worked like that. OK, problem solved - my stupidity noted :-p

Haha, no problem :D - you are not the first that fell for this.

-Felix

**Comment by ryanl888** [comment]
And thanks for all the help!

Regards,
Ryan
