### ISSUE TITLE
Disable the live view until top story view is active

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#107]
I think I should disabled the live view when the top story view is not present or not activated. Or at least open a modal that says "Dude, you forgot to enable the top story view"

**Comment by felixhayashi** [comment]
see https://github.com/felixhayashi/TW5-TiddlyMap/issues/105#issuecomment-91914274

**Comment by xnmp** [comment]
Since updating, whenever I close a tiddler, the map just disappears, even if there's other tiddlers open (I'm using live view). Also the "top view" isn't working as intended, new tiddlers will still open at the bottom.

**Comment by felixhayashi** [comment]
Hi @xnmp 

> Since updating, the "top view" isn't working as it used to, tiddlers opened with the map open at the top, but tiddlers opened with links are at the bottom,

Yes, this is true. I originally wanted to wait with publishing TiddlyMap updates until TiddlyWiki 5.1.9 is out where it is possible to decide where tiddlers are opened (at top, at bottom, below, above). The top story view doesn't do that anymore. what it does is, it scrolls the tiddler till it reaches the top of the window (classic story view doesn't do that). But in order to remove the "graph search" I now had to publish the new version even though 5.1.9 is only in prerelease state. So please update to 5.1.9-prerelease or wait a week or two till its released.

Sorry for this

-Felix

**Comment by felixhayashi** [comment]
For the demo site, I already use TW5 v5.1.9 and set the config (settings) to "open tiddlers above".

**Comment by xnmp** [comment]
Thanks for your quick responses. I have one more issue - when I close tiddlers sometimes the map just disappears completely. This always happens when I use the "close other tiddlers" button. I'm using the HotZone plugin as well.

**Comment by felixhayashi** [comment]
Thanks @xnmp for telling me. I'll definitely have a look at that this week :)

-Felix

**Comment by felixhayashi** [comment]
> I have one more issue - when I close tiddlers sometimes the map just disappears completely. 

Just to be clear: the live view does not show system tiddlers (and displays nothing). But you are talking about "normal" non-system tiddlers, right?

**Comment by xnmp** [comment]
Yes, that's right. It seems to happen whenever I close tiddlers that aren't in focus.

**Comment by felixhayashi** [comment]
Hi @xnmp 

> Yes, that's right. It seems to happen whenever I close tiddlers that aren't in focus.

Ah ok I see now.

> Also, with live view when I have it on "1 step distance" for example, and I'm focused on tiddler A, it'll show a link from A to B and one from A to C, but not a link from B to C. Is there any way to show this link?

Unfortunately not with "1 step distance". You would need to set "2 step distance" because it only adds edges to the map that it travelled along when it searched for neighbours so B -> C would be 2 steps when you started from A.

**Comment by xnmp** [comment]
But given that both B and C appear on the 1 step distance map, and that there's a link between them, wouldn't it make sense to show that link? 

The view with step distance (say N) would then become "the set of nodes that are within N of the current node, together with all the links between such nodes."

At the moment it's "the set of link chains originating from the current tiddler of length at most N, together with all nodes that they connect", which I think is less intuitive.

**Comment by felixhayashi** [comment]
> But given that both B and C appear on the 1 step distance map, and that there's a link between them, wouldn't it make sense to show that link? 

Yes, I do not disagree. I was just explaining how it is implemented at the moment. I also think it is more intuitive to display links between B and C.

**Comment by felixhayashi** [comment]
Hi @xnmp 

I added a view option for your request which allows you to show inter-neighbour relations on a per-view level.

I also fixed the bug with maps disappearing.

**Comment by felixhayashi** [comment]
please note: updating the hotzone plugin is also necessary

**Comment by xnmp** [comment]
Thanks again Felix, it's quite amazing how responsive you've been in the last few days. Now if only there were a field to set the size of the node on the map... that's a feature I'm dying to see. I know you have your own plans for what to do with the node size, but surely a temporary fix wouldn't hurt?

**Comment by felixhayashi** [comment]
> Thanks again Felix, it's quite amazing how responsive you've been in the last few days

Thanks :)

> Now if only there were a field to set the size of the node on the map... that's a feature I'm dying to see. I know you have your own plans for what to do with the node size, but surely a temporary fix wouldn't hurt?

I could have sworn I already answered this one but seems like I didn't. Now I did (https://github.com/felixhayashi/TW5-TiddlyMap/issues/13)
