### ISSUE TITLE
Tags visualisation paradigm ?

### ISSUE THREAD

**Issue by ybabel** [felixhayashi/TW5-TiddlyMap#108]
Tags are an important part of tiddlers, and a way to regroup them.
I don't know what would be the best way to achieve that, but I think it would be nice to have a feature that allows to enrich graph with tags : 

At least we can have an automatic feature to create edges from tag relationship ? (labelled "tagged by" for example), but I think we can do better.

maybe with some kind of layer (transparent ?), subgraphs, sets (a set = a tag, and node a grouped inside a circle that represent a tag ? but in this case I don't know how treat multi tags), lanes or whatever suits ?

**Comment by felixhayashi** [comment]
Hi @ybabel 

> I don't know what would be the best way to achieve that, but I think it would be nice to have a feature that allows to enrich graph with tags : At least we can have an automatic feature to create edges from tag relationship ? (labelled "tagged by" for example), but I think we can do better.

but this is already possible (see demo site). See also #93 and #14. You can label the "tmap:tag" type as you wish (via edge-type manager; see demo site docs).

> maybe with some kind of layer (transparent ?), subgraphs, sets (a set = a tag, and node a grouped inside a circle that represent a tag ? but in this case I don't know how treat multi tags), lanes or whatever suits ?

I depend on vis.js for this. Maybe in Visjs 4.0 this will be possible. But we have to wait. See also #13

**Comment by felixhayashi** [comment]
Hi @ybabel 

I'll close this issue now. If I misunderstood you, please let me know.

**Comment by ybabel** [comment]
I just took time to play with the last release : it's indeed already doing what I ask, and more !
thx

**Comment by felixhayashi** [comment]
@ybabel 

Ah, glad to hear that. I don't want to appear rude by closing issues but when there are too many issues open, I feel like cleaning up a bit ;)
