### ISSUE TITLE
Feature request: light colored text in dark colored tiddlers on graph title

### ISSUE THREAD

**Issue by ryanl888** [felixhayashi/TW5-TiddlyMap#111]
Hi @felixhayashi 
I noticed that when I change a tiddler on the graph to a dark color, maroon for example, the text on the graph tiddler remains dark - making it harder to see.  I noticed that in a Tiddler, in a tag for instance, the text is changed to white when a dark color is selected - to help it stand out.  Wondering if this is possible in TMap?  Thanks!

Regards,
Ryan

**Comment by felixhayashi** [comment]
Hi @ryanl888 

>  I noticed that in a Tiddler, in a tag for instance, the text is changed to white when a dark color is selected - to help it stand out.

Wow! I never noticed that.

I agree. This is would make sense. I'll try to add this feature!

-Felix

**Comment by ryanl888** [comment]
Hi @felixhayashi 
>Wow! I never noticed that.

Hehe, I guess working all day with spreadsheets may have made me more sensitive to color schemes ;)
>I agree. This is would make sense. I'll try to add this feature!

Great, thanks!

Regards,
Ryan

**Comment by felixhayashi** [comment]
Hi Ryan, I think this is fixed now.

-Felix

**Comment by ryanl888** [comment]
Hi @felixhayashi 

Yeah, looks good :)

Regards,
Ryan
