### ISSUE TITLE
TiddlyMap causes TiddlySpot plugin to fail on save

### ISSUE THREAD

**Issue by ed-n1n2** [felixhayashi/TW5-TiddlyMap#112]
Testing TiddlyMap on TiddlyWiki 5.17. Existing TiddlyWiki with a large number of entries for test. TiddlyMap will import just fine, but afterwards the provided store.php (Version 1.6.1) generates save error and the file is not saved on the server.

Saving locally however works just fine, and after reload, TiddlyMap functions without issues (font color issue - but that's a feature request).

The new file however, is strangely incompatible with store.php. I located the offending line of code, but other than the addition of TiddlyMap, there are no other variables to explore.

**Comment by felixhayashi** [comment]
Hi @ed-n1n2 

I do not use TiddlySpot and I am not accustumed with it so there is a possibility that I am not able to fix it :(

>  provided store.php (Version 1.6.1) generates save error and the file is not saved on the server.

Any error output here?

> The new file however, is strangely incompatible with store.php. 

Incompatible in what way?

> I located the offending line of code, but other than the addition of TiddlyMap, there are no other variables to explore.

Any error messages?

-Felix

**Comment by felixhayashi** [comment]
@ed-n1n2 **cannot** confirm for 5.1.8 on tiddlyspot and will close this now.
