### ISSUE TITLE
Font color issue (possibly)

### ISSUE THREAD

**Issue by ed-n1n2** [felixhayashi/TW5-TiddlyMap#113]
I have tags with associated icons that are rendered in the map, but have their captions (IIRC) as white text against a white background. Bug, or possible additional parameter to be configured?

Current version of TiddlyMap with TiddlyWiki 5.1.7.

**Comment by felixhayashi** [comment]
Hi @ed-n1n2 

could you please post a screenshot? thanks

-Felix

**Comment by felixhayashi** [comment]
Could not reproduce the error with your setup and will close this now. 
Please reopen if it still occurs.
