### ISSUE TITLE
feature request: live maps work with zoomin view

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#114]
THis is a rather specific issue to my setup.  I have long prefered a tabbed view where the story order remains fixed in the order tabs/tiddlers were opened.  I am working on developing such a creature with my nonexistent coding skills and have an early semi-working version at https://github.com/rcrath/TW5-TabStory.  The problem is that when I turn on the Zoom view so that only the current tiddler is displayed, I seem to lose tiddlymaps.  Is there some way to make a view that is capable of doing both?  For now I just use the top story view, but it does not look right to have an open river when the tabs are in effect.

**Comment by felixhayashi** [comment]
> I have long prefered a tabbed view where the story order remains fixed in the order tabs/tiddlers were opened. I am working on developing such a creature with my nonexistent coding skills and have an early semi-working version at https://github.com/rcrath/TW5-TabStory.

Cool stuff @rcrath 

> I seem to lose tiddlymaps.

Please be more specific here.

> Is there some way to make a view that is capable of doing both? 

Both what?

> For now I just use the top story view, but it does not look right to have an open river when the tabs are in effect. 

I hope I can remove the TopStoryView plugin soon once Jeremy accepts my pull request (https://github.com/Jermolene/TiddlyWiki5/pull/1662). The plugin will be called "TW5-FocussedTiddler" or something like that and also react to navigation changes (history changes). This way Tiddlymap's live view will also work with other story-views except "top".

**Comment by rcrath** [comment]
@felixhayashi , sorry for vagueness.  Its past my bedtime here :)  

> Cool stuff @rcrath. I tried the demo. But isn't it really similar to the "zoomin" story view with the "open tiddlers" list open on the right?

yes, the only difference is the tabs at the top, which would mean I can have tiddlymaps open and still have my tabbed story.  

>Please be more specific here.

When I use the zoomin view instead of "top", the live view of the map does not update when I open new tiddlers.  actually, no map at all appears unless I reload.  Then opening linked tiddlers does not update the map, and clicking on live view map nodes does not update the map or open the clicked tiddler.

>Both what?

Both the zoomin view with my tabs plugin and the live view of tiddlymaps, as discussed above. I hope this clarifies.

> This way Tiddlymap's live view will also work with other story-views

OK, looks like it will be fixed then.  I'll just track the changes and upgrade my TW when the pull gets merged.  Thanks.

**Comment by felixhayashi** [comment]
> yes, the only difference is the tabs at the top, which would mean I can have tiddlymaps open and still have my tabbed story. 

Ahh, I get it! :) also you have other tabs open in the sidebar and still see the open tiddlers. Great idea I have to say it is like a dynamic non-hierachical navigation bar.

> When I use the zoomin view instead of "top", the live view of the map does not update 

Ok got it.

> Both the zoomin view with my tabs plugin and the live view of tiddlymaps, as discussed above. I hope this clarifies.

Yes it does.

> OK, looks like it will be fixed then. I'll just track the changes and upgrade my TW when the pull gets merged. Thanks.

I will try to implement this quickly as I also want TiddlyMap's live to be usable without the top story view. I'll give you a heads-up once everything is ready.

**Comment by felixhayashi** [comment]
> sorry for vagueness. Its past my bedtime here :)

Hehe yes, you are truly an antipode compared to my location here in germany :)

**Comment by felixhayashi** [comment]
HI @rcrath 

I think the solution is even simpler. You just need to put the title of the tiddler you want to see in the live view as text inside "$:/temp/focussedTiddler". I suggest you use the action-setfield widget for setting the text field when one of your tabs is clicked

Should work out of the box :)

-Felix

**Comment by felixhayashi** [comment]
Hi @rcrath 

once 5.1.9 is out, I'll publish an update that will make the live view work with zoomin. See #121.

-Felix

**Comment by felixhayashi** [comment]
Hi @rcrath 

I made big changes to support this. Zoomin should work now after you installed the hotzone plugin. please read #123 before updating.

-felix

**Comment by rcrath** [comment]
THanks @felixhayashi ...just dug out of grading hell and will be testing it out soon.

**Comment by felixhayashi** [comment]
> just dug out of grading hell and will be testing it out soon.

:D :+1:
