### ISSUE TITLE
Javascript Error when selecting "Configure View"

### ISSUE THREAD

**Issue by cmari2** [felixhayashi/TW5-TiddlyMap#115]
In an otherwise empty new ver5.1.8 (not a prerelease), in either Firefox or Chrome, drag in the ContextPlugin and the three other plugins listed in the Installation tiddler, save, and reload.  
Clicking "Configure View" gives this result:
TypeError: this.getView(...).getCreationDate(...) is undefined

**Comment by felixhayashi** [comment]
uhh. Need to fix that! thanks for telling me @cmari2
