### ISSUE TITLE
Nitpick word correction #2

### ISSUE THREAD

**Issue by twMat** [felixhayashi/TW5-TiddlyMap#117]
The initial default popup (not sure if "popup" is correct term but I mean when it is a blurred backround) - it refers to *Configurate [something]". But when you actually go to the menu there are *two* entries containing the word Configurate and the one starting with it is noth the correct one.

**Comment by felixhayashi** [comment]
Ah, I see. Thanks Mat for pointing that out

I completely removed that line. Its too confusing.

New text:

* In case you need any help, please consult the [[online docs|http://bit.ly/tiddlymap#Documentation]] first.
* You are welcome to create an [[issue|https://github.com/felixhayashi/TW5-TiddlyMap/issues]] at ~GitHub for any bug you discover.
* Make sure to revisit the [[demo site|http://bit.ly/tiddlymap]] to see whether your version is up-to-date.
* If you like ~TiddlyMap, please give it a star at ~GitHub :)

**Comment by twMat** [comment]
Excellent. And I'm reminded I must give it a star right away!

**Comment by felixhayashi** [comment]
> Excellent. And I'm reminded I must give it a star right away!

Hehe, thanks... my 16th star :triumph::sparkles:

**Comment by twMat** [comment]
Assuming that smiley depicts a very angry little fella' I think it's worth considering that stars in github don't reflect how many people actually use or like the project since starring requires you're a registered github user.

**Comment by felixhayashi** [comment]
> Assuming that smiley depicts a very angry little fella' 

Haha, no, it's quit hard to make me angry :dancers: - If you move your mouse over the symbol in my previous post it will reveal its true meaning to you ;) (more precisely http://www.iemoji.com/view/emoji/822/people/face-with-look-of-triumph) But your interpretation will be a lesson for me not to use symbols that may be misinterpreted.

**Comment by twMat** [comment]
Aha. I thought that was froth from anger coming out from his mouth. Even if it isn't, I still can't see how those angry eyebrows go with "triumph"... But never mind. Those hot dancing twins girls are more to my liking, just the right 1:3 head:body proportion...

**Comment by felixhayashi** [comment]
> Those hot dancing twins girls are more to my liking, just the right 1:3 head:body proportion...

Haha Mat, I never knew you had such an exquisite taste when it comes to women :D
