### ISSUE TITLE
Highlight directly connected nodes when click on a node

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#12]
When a graph grows in size can be hard to distinguish connections. Highlighting connected nodes and the connections itself when a node is selected will improve usability a lot, and also will add meaningful information.

**Comment by tobibeer** [comment]
I think the current styles are a bit heavyweight. I'd simply increase the stroke size a tiny wee bit and leave the color for something else.

**Comment by felixhayashi** [comment]
ok I will see what I can do.

**Comment by danielo515** [comment]
Hello,

I like it as it is right now. Is there any chance to move this into a configuration option?

**Comment by felixhayashi** [comment]
Hi @danielo515,

Yes, I am working on it.

**Comment by tobibeer** [comment]
Some preferences / suggestions from [here](https://groups.google.com/d/msg/tiddlywiki/OXjZ_hFU1ok/FqhtcOmPHYcJ) (sorry for double-posting)...

```
svg.railroad-diagram path,
svg.railroad-diagram rect {
stroke-width: 2;
stroke: #333;
}

svg.railroad-diagram path.arrow {
stroke-width: 2;
}

svg.railroad-diagram path,
svg.railroad-diagram rect {
stroke-width: 2;
stroke: #333;
}

svg.railroad-diagram path.arrow {
stroke-width: 2;
}
```

**Comment by felixhayashi** [comment]
Hi @danielo515 @tobibeer 

To edit locales:

`$:/plugins/felixhayashi/tiddlymap/options/vis/locales`

Defaults:

    {
      "locale": "en_EN",
      "locales": {
        "en_EN": {
          "edit": "Edit",
          "del": "Delete selected",
          "back": "Back",
          "addNode": "Add Node",
          "addEdge": "Add Edge",
          "editNode": "Edit Node",
          "editEdge": "Edit Edge",
          "addDescription": "Click in an empty space to place a new node.",
          "edgeDescription": "Click on a node and drag the edge to another node to connect them.",
          "editEdgeDescription": "Click on the control points and drag them to a node to connect to it.",
          "createEdgeError": "Cannot link edges to a cluster.",
          "deleteClusterError": "Clusters cannot be deleted."
        }
      }
    }

To edit styles (color) etc:

`$:/plugins/felixhayashi/tiddlymap/options/vis/styles`

Defaults:

    {
      "nodes": {
        "radiusMin": 10,
        "radiusMax": 30,
        "radius": 10,
        "shape": "box",
        "widthMin": 16,
        "widthMax": 64,
        "fontColor": "black",
        "fontSize": 14,
        "fontFace": "verdana",
        "level": -1,
        "color": {
          "border" : "#2B7CE9",
          "background" : "#97C2FC",
          "highlight": {
            "border": "#2B7CE9",
            "background": "#D2E5FF"
          },
          "hover": {
            "border": "white",
            "background": "white"
          }
        }
      },
      "edges": {
        "widthMin": 1,
        "widthMax": 15,
        "width": 1,
        "widthSelectionMultiplier": 4,
        "hoverWidth": 1.5,
        "style": "arrow",
        "color": {
          "color": "#848484",
          "highlight": "#B90000",
          "hover": "B90000"
        },
        "fontColor": "gray",
        "fontSize": 14,
        "fontFace": "arial",
        "fontFill": "transparent",
        "arrowScaleFactor": 1,
        "dash": {
          "length": 10,
          "gap": 5
        },
        "inheritColor": false
      },
      "groups": {
        "special": {
          "borderWidth": 1,
          "color": {
            "background": "#E6B293",
            "border": "#FF6700"
          }
        },
        "neighbours": {
          "shape": "box",
          "radius": 5,
          "widthMin": 16,
          "widthMax": 64,
          "fontColor": "black",
          "fontSize": 14,
          "fontFace": "verdana",
          "color": {
            "border" : "#ADADAD",
            "background" : "#DCDCDC",
            "highlight": {
              "border": "#ADADAD",
              "background": "#E8E8E8"
            }
          }
        }
      },
      "tooltip": {
        "delay": 300,
        "fontColor": "black",
        "fontSize": 14,
        "fontFace": "verdana",
        "color": {
          "border": "#666",
          "background": "#FFFFC6"
        }
      }
    }

Please note that once you changed a value, you override the plugins shadow tiddler and won't receive updates for these tiddlers anymore when installing a new plugin version (I mean, this is of course what you try to achieve, I am just saying to be clear about it).

For an explanation what these properties do see:

* http://visjs.org/docs/network.html#Nodes_configuration
* http://visjs.org/docs/network.html#Edges_configuration
* http://visjs.org/docs/network.html#Groups_configuration
* http://visjs.org/docs/network.html#Localization
* http://visjs.org/docs/network.html#Tooltips

**Comment by tobibeer** [comment]
Overwriting or not, it is awesome that these things are configurable. There could possibly be a way to construct the config from individual tiddlers for each setting under some `$:/config/tiddlymap/` namespace but that's for another day.

**Comment by felixhayashi** [comment]
@tobibeer 

yes, using a single tiddler for each option would solve this.

Your suggestion about converting an object to a set of tiddlers where the prefix equals the property structure of an object is really worth a thought! In fact, this could be easily acquired by modifying a  flattening mechanism (strings to objects and vice versa) like https://github.com/felixhayashi/flat (fork from tim oxley). I'll keep this idea in the back of my head.

-Felix

**Comment by tobibeer** [comment]
@felixhayashi thanks, that would possibly be a powerful addition for developers allowing to enable plugin configurability in a fine-grained manner, but defining the defaults with a simple object notation.

**Comment by felixhayashi** [comment]
yes exactly

**Comment by linsteina** [comment]
Hi @felixhayashi and @tobibeer , Thanks a lot for discussing this feature. May I ask if this is possible now? P.S. I really like TiddlyMap!

**Comment by felixhayashi** [comment]
Hi @linsteina highlighting connected nodes is a not possible and not planned. But what has been implemented in the meantime is that all edges are highlighted when you select a node and you can also change the "highlight" behavior (color) of selected edges. 

To globally change the egde highlight color go to "configure tiddlymap" and in the "graph" section go to "edges".

![2018-07-26 09 24 46](https://user-images.githubusercontent.com/4307137/43247798-146c072e-90b6-11e8-8ed7-04e8b3e1b153.png)

> P.S. I really like TiddlyMap!
Thanks

**Comment by linsteina** [comment]
Thanks, @felixhayashi for your swift reply! This helps.

I will also try to create views for each node to only show the ones related to a clicked node.

**Comment by felixhayashi** [comment]
glad I could help :)

> I will also try to create views for each node to only show the ones related to a clicked node.

fyi: you can open a view from a node via http://tiddlymap.org/#Open%20a%20view%20by%20clicking%20on%20a%20node

**Comment by linsteina** [comment]
Thanks @felixhayashi This also helps. 
I will come back to the 'highlighting' way once I have more data for my project. The showcase from 
Kenedict http://visjs.org/showcase/index.html looks like there are a lot of potentials.
