### ISSUE TITLE
Make live view work in different scenarios

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#121]
The live view should be usable without installing the TW5-TopStoryView. This would allow TiddlyMap to be usable in combination with other views (e.g. classic, zoomin; also see #114).

How can this be achieved:

* In TiddlyWiki, navigating (clicking on a link) changes the history (`$:/HistoryList`). When the live view is active, TiddlyMap should listen to history changes and switch to the tiddler that most recently occurred in the history.
* **If people want to trigger a live view refresh based on scrolling**, they need to install the new **TW5-HotZone Plugin**. The TW5-HotZone plugin will fire a change everytime another tiddler is scrolled into a certain "hotzone", allowing the live view to update while the user is scrolling.
  * **For a better experience it is highly recommended to install the TW5-TopStoryView**.
  * Once TW v5.1.9 is out, it is suggested to change the link opening behaviour to "open tiddlers above".

The TW5-TopStoryView itself will be refactored (see https://github.com/felixhayashi/TW5-TopStoryView/issues/8).

**Comment by felixhayashi** [comment]
|           | Story view                            | User Installs      | Experience                                                           | Explanation                                                                                                                                                                   |
| --------- | ------------------------------------- | ------------------ | -------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Live view | Zoomin                                | TW5-Hotzone plugin | **Optimal**                                                          |                                                                                                                                                                               |
| Live view | Zoomin                                |                    | **Suboptimal**                                                       | Only navigation events are reflected in the live view (this excludes e.g. tiddler closing or deletion)                                                                        |
| Live view | Classic                               | TW5-Hotzone plugin | **Suboptimal** (TW5-TopStoryView is suggested)                       | Unless the user changes the opening behavior of tiddler to "open links above" (feature becomes available with 5.1.9) the navigation and the hotzone information may conflict! |
| Live view | Classic                               |                    | **Suboptimal** (TW5-TopStoryView is suggested)                       | Only navigation events are reflected in the live view (this excludes e.g. tiddler closing or deletion)                                                                        |
| Live view | Top (needs to be installed as plugin) | TW5-Hotzone plugin | **Optimal**                                                          |                                                                                                                                                                               |
| Live view | Top (needs to be installed as plugin) |                    | **Suboptimal** (Installation of the TW5-Hotzone plugin is suggested) | Only navigation events are reflected in the live view (this excludes e.g. tiddler closing or deletion)                                                                        |
| Live view | Pop                                   |                    | **Suboptimal** (TW5-TopStoryView is suggested)                       | Only navigation events are reflected in the live view (this excludes e.g. tiddler closing or deletion)                                                                        |
| Live view | Pop                                   | TW5-Hotzone plugin | **Suboptimal** (TW5-TopStoryView is suggested)                       | Unless the user changes the opening behavior of tiddler to "open links above" (feature becomes available with 5.1.9) the navigation and the hotzone information may conflict! |
|           |                                       |                    |                                                                      |                                                                                                                                                                               |

**Comment by felixhayashi** [comment]
I'll wait with publishing of the updates until 5.1.9 is out

**Comment by tobibeer** [comment]
That table right there is a great example of well structured development and figuring out what can be improved and how... and, what can't. Simple, but essential. Great to see a great developer and a thorough tester in one. Would possibly spare a lot of projects from plenty round-trips.

**Comment by felixhayashi** [comment]
Thanks for the compliment @tobibeer :)
