### ISSUE TITLE
Timeline & date created

### ISSUE THREAD

**Issue by gitany** [felixhayashi/TW5-TiddlyMap#122]
1) I would like a list of all my tiddlers based on the date created.

Currently, there is a "Recent" tab that lists Tiddlers by date last modified. Any chance a "Timeline" tab can be made and listed in reverse chronological order?

2) In the meantime, I created a Tiddler using the TiddlyWiki timeline macro outlined here: http://tiddlywiki.com/#timeline%20Macro

```
<<timeline dateField:"created">>
```
For some reason, when I then modify an older tiddler, it disappears from my timeline tiddler.

3) Lastly, tiddlers currently display the date last modified as a gray subtitle. Is there an easy way to automatically include the date of original creation (e.g. aligned right, on the same line in the subtitle)?

I know I can add ```<$view field="created" format="date" template="MMM DD, YYYY"/>``` in the body text of each tiddler manually, but if it's possible to apply this to all tiddlers, then then it would be wonderful.

Thank you!

**Comment by gitany** [comment]
I solved 1) by simply tagging my Timeline tiddler with ```$:/tags/SideBar```

Still unsure why my problem in 2) occurs though. I realise these questions might not be TiddlyMap-specific, so I will do some more playing around with customisation.

**Comment by felixhayashi** [comment]
Hi @gitany 

>Currently, there is a "Recent" tab that lists Tiddlers by date last modified. Any chance a "Timeline" tab can be made and listed in reverse chronological order?

This is not what TiddlyMap is used for. For timelines, there once was a plugin by a tiddlywiki user called "emkay" (just search this name in the tiddlywiki google groups). Also see https://groups.google.com/d/msgid/tiddlywikidev/7a9df38e-f6b3-4230-b4cd-55ad9f1ef53e%40googlegroups.com.

> For some reason, when I then modify an older tiddler, it disappears from my timeline tiddler.
> 3) Lastly, tiddlers currently display the date last modified as a gray subtitle. Is there an easy way to automatically include the date of original creation (e.g. aligned right, on the same line in the subtitle)?

Again, I think these are really tiddlywiki issues and I am sure you can solve it by posting it at the google groups. Tiddlymap is just about displaying tiddlers as nodes in a graph, it is not about creating timelines or using other widgets in the tiddler's body.

**Comment by gitany** [comment]
Hi Felix, thanks for your reply!

You are correct. I got a bit too excited trying new things on TiddlyMap, and momentarily forgot that these issues relate more to TiddlyWiki than TiddlyMap. I had a look at emkay's Timeline plugin, which looks wonderful, but is not what I am after. Since I have many tiddlers which get revised, I was hoping to have a list of tiddlers based on the date when they were created.

After a bit more playing around, my issue outlined in 2) above seems to persist even when I start from a vanilla TiddlyWiki. I am guessing something about the "created" field (which stores the date a tiddler was created) is not be detected correctly when I subsequently edit a tiddler, but I will ask on the Google Groups.

**Comment by felixhayashi** [comment]
> You are correct. I got a bit too excited trying new things on TiddlyMap, and momentarily forgot that these issues relate more to TiddlyWiki than TiddlyMap

Hehe, no problem.

> UPDATE: Looks like there was a bug responsible in TiddlyWiki v5.1.7 that was fixed in v5.1.8. Therefore, my problems are all solved :)

Ah, great you solved it!
