### ISSUE TITLE
Internal JavaScript error on startup (FireFox)

### ISSUE THREAD

**Issue by pmario** [felixhayashi/TW5-TiddlyMap#125]
To reproduce: 

 - FireFox 38.0.1
 - It seems Chromium is swallowing the error. 
 - open http://felixhayashi.github.io/TW5-TiddlyMap/index.html
 - <shift><F5> to trigger it again

If the dev tools are open <f12> it looks like this 

```
timer: Assembling Graph: 55.22ms ... caretaker.js:213
"Assembled graph:" Object { nodes: Object, edges: Object } ... caretaker.js:205:6
timer: Reloading Network: 56.87ms ... caretaker.js:213
"NS_ERROR_NOT_AVAILABLE: " ... index.html:11538:1      <---------------------

timer: Caretaker handling changes: Timer gestartet ... caretaker.js:209
"Modified:" Object { fields: Object } ... caretaker.js:205:6
"Modified:" Object { fields: Object } ... caretaker.js:205:6
timer: Caretaker handling changes: 1.31ms ... caretaker.js:213
NS_ERROR_NOT_AVAILABLE:  ... vis.js:51:0       <----------------------
timer: Caretaker handling changes: Timer gestartet ... caretaker.js:209
"Modified:" Object { fields: Object } ... caretaker.js:205:6
timer: Caretaker handling changes: 0.78ms
```

**Comment by felixhayashi** [comment]
Hi @pmario 

Thanks for telling me, I got this as well when updating to 38.0.1 but I thought it has something to do with my browser configuration.

Really strange and after closing the error it is no problem to work with the wiki...

I have to fix that.

**Comment by felixhayashi** [comment]
What is really strange is that it only happens once at the beginning when a window is opened and then never again (Pressing F5 will not produce the same error)?! What is this?

**Comment by felixhayashi** [comment]
I just catch it as it seems to be just a minor issue related to the canvas. When migrating to vis.js 4.0 this is hopefully gone...

**Comment by pmario** [comment]
`<shift><f5>` triggers it again. ... I also managed to crash the browser while doing weird things in full screen mode :)  ... but I can't reproduce :/

**Comment by felixhayashi** [comment]
Hi @pmario 

> <shift><f5> triggers it again.

so the error still exists, even after the fix (online demo; v0.7.34)? Because the error is gone for me...

**Comment by pmario** [comment]
seems to be fixed. thx

**Comment by felixhayashi** [comment]
No problem
