### ISSUE TITLE
Use URL parameters to influence how TiddlyMap starts when the page (wiki) is loaded

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#130]
This feature is inspired by this forum post:

> I'd love to be able to save the sidebar TiddlyMap window state to be able to share a link to the wiki and a reader would see it either full screen or half screen.
I guess this is restricted by browsers in the same way that TiddlyWikis own full screen mode is - however if if *is* possible to save one of these states between sessions - that would be a very nice feature - i.m.o...  

> Måns Mårtensson, https://groups.google.com/d/msg/tiddlywiki/xAuccFXqTNg/SzbRu6mNHEkJ

**Comment by felixhayashi** [comment]
Will be awesome ;) You will be able to send somebody a link e.g.

     http://mywiki.tiddlyspot.com?tmap-enlarged=fullscreen&tmap-view=myview123

and it will start in fullscreen.

**Comment by felixhayashi** [comment]
A little demo (**DO NOT INSTALL THIS VERSION, IT'S EXPERIMENTAL**)

* Open map "Activities" in fullscreen
  * http://tiddlymap.org/experimental/index.html?tmap-enlarged=fullscreen&tmap-view=Activities
* Open map "Overview" in halfscreen
  * http://tiddlymap.org/experimental/index.html?tmap-enlarged=halfscreen&tmap-view=Overview

-Felix

**Comment by tobibeer** [comment]
@felixhayashi, nice ...eventually it would be nice to leave some pointers (to your code) how you implement it. thanks.

**Comment by felixhayashi** [comment]
> @felixhayashi, great stuff. Thanks! Please leave some pointers (to your code) how you implement it.

Hi @tobibeer, I think this is actually of value for TW in general so I created a post at the TW GitHub repo with more information.

P.S. Great plugins you developed in the recent past! Well, documented and useful. I wish I had more time to push the agenda on plugin dependencies in TW so I could include them as modules in TMap at some point. In the middle/end of this year I guess I'll have more time to occupy myself with this topic.

**Comment by tobibeer** [comment]
> Great plugins you developed in the recent past! Well, documented and useful.

Thanks, @felixhayashi ... much appreciated.

> I wish I had more time to push the agenda on plugin dependencies in TW so I could include them as modules in TMap at some point.

Feedback as to how they're used in a professional manner is always highly welcome. Sometimes I feel not even I can anticipate the uses some of that stuff can be put to.

> In the middle/end of this year I guess I'll have more time to occupy myself with this topic.

Looking forward to that!
