### ISSUE TITLE
The Ok button and the creation of nodes and edges

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#132]
A few thoughts. Firstly, could the Ok button in the node and edge creation dialogs be very slightly larger and be labelled OK rather than Ok? It's a critical element and anything that makes it quicker to find is good.

Secondly, could there be an option to automatically accept a new value typed into the Node and Edge creation fields followed by pressing the Enter key rather than having to click Ok? 

Likewise, is it possible to close the dialog on selecting an existing hyperlinked entry from the list rather than having to press Enter?

**Comment by felixhayashi** [comment]
You are really optimizing workflows here @Peter-Miller  :) Thanks for sharing the experience.

> Firstly, could the Ok button in the node and edge creation dialogs be very slightly larger and be labelled OK rather than Ok?

I can rename it to "OK" but I do not want to make it larger because they already consume much space. What about coloring instead?

![selection_656](https://cloud.githubusercontent.com/assets/4307137/7959702/b99f54fc-09fb-11e5-99b4-1029e6ad5311.png)

> Secondly, could there be an option to automatically accept a new value typed into the Node and Edge creation fields followed by pressing the Enter key rather than having to click Ok? 

I think I can listen for enter keys when a dialog is open. Added a ticket: #132

> Likewise, is it possible to close the dialog on selecting an existing hyperlinked entry from the list rather than having to press Enter?

I think this is too abrupt for the user. What if he / she clicked by accident or missed the title by milimeters. But with #132 you could simply hit the "return" key which is a good compromise in my eyes.

**Comment by Peter-Miller** [comment]
I think colouring is potentially distracting. Having the Enter key work in either case is the way to go if possible. 

And yes, I spent a couple of hours creating a map from the map interface this morning. It was both enjoyable and productive. As you have gathered, I added a node to keep track of any issues I encountered ;)

**Comment by felixhayashi** [comment]
> I think colouring is potentially distracting. Having the Enter key work in either case is the way to go if possible. 

Ah ok.

> And yes, I spent a couple of hours creating a map from the map interface this morning. It was both enjoyable and productive. 

Nice to hear that!

> As you have gathered, I added a node to keep track of any issues I encountered ;)

Thanks. I am always glad to receive some feedback :)

**Comment by felixhayashi** [comment]
Hi @Peter-Miller 

What about bold instead of a bigger size?

![selection_365](https://cloud.githubusercontent.com/assets/4307137/8252563/3d025f0a-1687-11e5-8565-4e26b7422eb5.png)

**Comment by Peter-Miller** [comment]
I agree -- good compromise.

Best wishes

Peter

**Comment by felixhayashi** [comment]
Hi @Peter-Miller 

Next release will auto focus first input fields in various dialogs directly so no need to click anymore and we can directly start typing :) Also I managed to add keylisteners successfully. So workflow in the case above would be

1. double click on canvas
2. start typing a name
3. hit enter to confirm; hit escape to cancel

However, keyboard shortcuts only work when inputfields are focussed.

-Felix
