### ISSUE TITLE
Moving nodes as a group

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#136]
I know you can drag nodes individually but can you move them as a group or move one and have its immediate neighbours move as well? (One for the future)

**Comment by felixhayashi** [comment]
This is supported by vis.js but I have not implemented it yet. I'll do so.

**Comment by danielo515** [comment]
I'm interested on this so :+1:

**Comment by felixhayashi** [comment]
Hah! That's fixed now AND EVEN BETTER: you can copy/cut n paste! See #168. There is also a short [video](https://www.youtube.com/watch?v=3GbH_xMOYNg) on this new feature. But'll certainly record it again, it misses to mention some aspects… Anyhow, I'll close this now.
