### ISSUE TITLE
Node statistics

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#137]
A count of nodes and edges as a start. No rush :)

**Comment by felixhayashi** [comment]
Haha this time I was faster then you @Peter-Miller... that feature already exists :) 
Please see #44

Open Menu -> Configure view and have a look at the top.

**Comment by felixhayashi** [comment]
And yes yes, I know. It is somewhat hidden there but I didn't want to many menu entries for the moment ;)

**Comment by Peter-Miller** [comment]
Thanks -- I looked at that dialog but not closely enough :)
