### ISSUE TITLE
auto-generated views for tagging / references

### ISSUE THREAD

**Issue by tobibeer** [felixhayashi/TW5-TiddlyMap#14]
Reading [this](https://github.com/felixhayashi/tw-taskgraph/issues/8#issuecomment-64972759)...

> http://wkpr.de/hosting/tmp/tw5/taskgraph/#Adapter

...this could allow creating some form of plugin that auto-generates / -updates a "tagging" view or a "references" view or preferably one containing both as different types of edges.

Perhaps such a view might even be the default view for taskgraph?

However, rather than having a monstruous graph of all tiddlers, one might just want to see x-levels deep starting from the current tiddler, i.e. the last one displayed in the story column / the last one clicked in taskgraph... so the graph would have some awareness of levels with respect to a centered / selected node or edge.

Such a view could be opened in a popup from a toolbar button at the current tiddler, so as to explore its relations, even navigate around...

**Comment by tobibeer** [comment]
> I think this is similar to what you had in mind?

As for the browsing behavior, indeed! As for what relations are shown... not yet, I assume. The relations would be dynamic in nature, i.e. all of **tagging to**, **referencing**, as well as **tagged by**, and **referenced by**... and maybe some future, generic relations not yet mentioned, e.g. things like **listed by** and **listing**?

**Comment by felixhayashi** [comment]
> As for the browsing behavior, indeed! As for what relations are shown... not yet, I assume. The relations would be dynamic in nature, i.e. all of tagging to, referencing, as well as tagged by, and referenced by... and maybe some future, generic relations not yet mentioned, e.g. things like listed by and listing?

Ah I get what you are up to. My plan is to make the plugin extensible so in the end we can add the "dynamic edge calculation" as another plugin. But this is a great idea.

**Comment by tobibeer** [comment]
Needed to drop this here from https://github.com/Jermolene/TiddlyWiki5/issues/1326#issuecomment-69039362...

> you store the relations as independent information, did you think about storing it to each tiddler? (where is the tiddler pointing to and how)
> my feeling is that this would make it clearer in structure, right?

We need to distinguish two fundamentally distinct use-cases...
(and so should TiddlyMap, also see: https://github.com/felixhayashi/TW5-TiddlyMap/issues/14)

1. We model graphs that relate tiddlers.
    * with such a **view**, we model entirely independent relationships
        * different views of that kind are entirely independent, both in terms of nodes and edges
        * view **foo** could thus display relationships that view **bar** would **never** display
    * therefore, an update to the graph never updates a represented tiddler

2. We define a graph that represents (inherent) tiddler relations.
    * such a graph is completely tied to the underlying (standard) wiki relations, e.g.
        * tagging to
        * tagged by
        * linking to
        * linked by
        * listed in
        * listing
        * custom foo
        * inverse of custom foo
        * etc...
    * therefore, if such a **view** was editable, it would **always** update the corresponding tiddlers and their relations (which will work for things like "tagged" and "listed", but not "linked")
    * **views** based on this paradigm are **not** independent
        * if view **foo** updated relations also displayed in view **bar**, both would reflect the changes

**Comment by felixhayashi** [comment]
Yes. I call the first type of relations "global" or "shared" and the latter "private". TiddlyMap stores global relations in a central path "[...]/edges/" and local edges are stored in a subpath of each view like "[...]/view/exampleview1/edges/". This is a common approach used in unix (e.g. /usr/bin and /usr/local/bin). When using TiddlyMap, a user has to decide whether to use a global or private approach.

A use case for private edges is e.g. isolated mind maps: No global edges are displayed and on the other hand the private edges are nowhere else displayed (not spamming the global edge pool).

If the edges should be displayed everywhere because they, as tobi puts it, describe the "(inherent) tiddler relations", then a global mode should be used.

Only one addition:

> different views of that kind are entirely independent, both in terms of nodes and edges

The problem is that tiddlywiki cannot create nodes with the same name, so independence of nodes is hard to achieve as we cannot create nodes with the same name. Even when using captions, a node is bound to a tiddler and the tiddler is global so I cannot prevent that a tiddler appears in another graph context if it matches the views filter.

-Felix

**Comment by tobibeer** [comment]
> The problem is that tiddlywiki cannot create nodes with the same name, so independence of nodes is hard to achieve as we cannot create nodes with the same name. Even when using captions, a node is bound to a tiddler and the tiddler is global so I cannot prevent that a tiddler appears in another graph context if it matches the views filter.

Of couse, I was not implying to have different nodes, that is correct.  Luckily, edges are not (yet?) top-level tiddlers. What I was implying was that how those tiddlers are displayed in such a graph is independent from that tiddler, in **all** regards, thus edges and node properties relating to a tiddler but not persisted at it.

For example, if such a graph allowed to enter some additional "node-note" then that note would **not** be stored at that tiddler but rather in some system tiddler with respect to that "private" view along with any other properties, such as icons, colors, etc...

However, when we're looking at a "global" view, we're looking at that very tiddler, so any modifications and additions we do for that tiddler should probably be stored at that very tiddler or stored in a way that any other global view refers to the very same globally accessible information.

Personally, I think the amount of graph-data that is dumped on actual tiddlers should be as minimal as possible, if not non-existent. Only global relationship-stuff should be directly persisted at a tiddler, e.g. making an actual tagging relation.

**Comment by felixhayashi** [comment]
Yes, I agree. Only stuff that would play a role if the plugin were not installed should be stored in tiddlers. For example I would never store position information or something in a tiddler.

**Comment by christophvarga** [comment]
i also think by standard there should only the neighborhood of one tiddler be visible.
as follows some further thoughts on the map-view

-
*data which is good to have from relations. 
what maybe is new here is the strength*



>* title (eg. 'uncle of', 'leads to', 'contains')
>* classification (direction from, direction to, parent (step up in hierarchy), child (step down in hierarchy), similar meaning,)
>* strength (1-100)


*you know the technical process better but these i think are relevant informations to have when visualizing the neighborhood network*


>* manual relations
 >  * strength
 >  * classification
>  * (title)
 
>* automatic and more distant relations
 >  * nodes with similar tags
 >  * nodes without similar tags, but similar tags with 'nodes with similar tags'
 
-
*thoughts on graphical rendering layout*
>* description can be on the visual node representation or invisible without 'mouse over' or on the side with caption lines
>* the size of nodes can be used to make recent activity/ popularity in the tiddlywiki visible (if necessary at all)
>* the distance for example can represent the strength of a relation, depending on the design. also the opacity can do that.


-
*i did a research and here is a list of graphic and information designers from students to agencies wich adressed me by their work. maybe one of them like to contribute to this project?*

>links
 info graphic design agencies
  http://www.cleverfranke.com/cf/en/index.php
  http://www.densitydesign.org/research/visualizing-controversy-in-wikipedia/
  http://truth-and-beauty.net/
  http://emmanuellebories.com/
  http://www.tizianaalocci.com/
  https://www.behance.net/federica_bardelli
  https://www.behance.net/kirstinmck
  https://www.behance.net/valeriopellegrini
  http://saravrbinc.com/
  http://cargocollective.com/federicafragapane
  http://www.bernardimarco.it/pages/work.php
  http://cargocollective.com/francescomajno
  http://linepointpath.com/
  http://szucskrisztina.hu/
  https://www.behance.net/JavierVillarroel   Physicist, Creative coder 
  https://www.behance.net/catherinebrand
  https://www.behance.net/czelmatyas

-
*here are some examples i came to
Mood Board*
![map a29cha-773x1024](https://cloud.githubusercontent.com/assets/653247/5691720/0029e1dc-98d5-11e4-8e82-8c205d1fdbd2.gif)
![8a6c310ec86a6f497160f9ae62e71adb](https://cloud.githubusercontent.com/assets/653247/5691677/ccdfda94-98d3-11e4-9b46-6658021d5bf6.jpg)
![8d0a65114e884373e8dd16e72f34ebc8](https://cloud.githubusercontent.com/assets/653247/5691722/1f72a024-98d5-11e4-8e65-f3d9eefb7ec9.jpg)
![33d7e230d05ad78a92c0553e81edb3c5](https://cloud.githubusercontent.com/assets/653247/5691672/ccb704d4-98d3-11e4-8c7f-710671494fd1.jpg)
![815eaa41a95a759189459db020d6d533](https://cloud.githubusercontent.com/assets/653247/5691724/2cffe30a-98d5-11e4-928a-688706f0c6dc.jpeg)
![797726cf8405a46f1cb93bbffd5691fe](https://cloud.githubusercontent.com/assets/653247/5691673/ccd67b98-98d3-11e4-8138-7468235e661d.jpg)
![c2c90c6fbad19d862d966b657a91df05](https://cloud.githubusercontent.com/assets/653247/5691679/ccec34a6-98d3-11e4-8923-25728156e9fb.jpg)
![img-tesi2](https://cloud.githubusercontent.com/assets/653247/5691680/ccf1c97a-98d3-11e4-8fd9-9a9168eb6a08.jpg)
![map 785_big01](https://cloud.githubusercontent.com/assets/653247/5691681/ccf62966-98d3-11e4-9450-690d69ababb8.jpg)
![map 785_big02](https://cloud.githubusercontent.com/assets/653247/5691682/ccf7cd66-98d3-11e4-8973-6076af107c69.jpg)
![map 987](https://cloud.githubusercontent.com/assets/653247/5691683/ccfa4348-98d3-11e4-9889-3f394514d79f.jpg)
![map col_top_vis](https://cloud.githubusercontent.com/assets/653247/5691684/ccfe1a0e-98d3-11e4-9543-dd4082587d69.jpg)
![map f21chav2-1](https://cloud.githubusercontent.com/assets/653247/5691685/cd059ea0-98d3-11e4-916d-564ced5c17cd.jpg)
![map p83_0](https://cloud.githubusercontent.com/assets/653247/5691687/cd11178a-98d3-11e4-9d5c-4981dc920541.jpg)
![map population](https://cloud.githubusercontent.com/assets/653247/5691689/cd1601c8-98d3-11e4-83ed-5ba09bd62c26.jpg)
![map world_map_internet-1120x1102](https://cloud.githubusercontent.com/assets/653247/5691688/cd11df12-98d3-11e4-9812-d0f1b4cc3bd1.jpg)
![p70_0](https://cloud.githubusercontent.com/assets/653247/5691690/cd17fab4-98d3-11e4-9656-8ba99774162a.jpg)
![5b008a4b14f3a645b7e45bac34eea83c](https://cloud.githubusercontent.com/assets/653247/5691691/cd1c7ec2-98d3-11e4-9e41-2d4dfae9f691.png)
![0983f5c07a7888f4615ca0ddb5ab6667](https://cloud.githubusercontent.com/assets/653247/5691692/cd21c3d2-98d3-11e4-9394-e26301c5bed3.png)
![599545fd695ef0e50064fd8f998bcca0](https://cloud.githubusercontent.com/assets/653247/5691693/cd25fcd6-98d3-11e4-8626-1d35648c5846.png)
![f5ad6b2469170cccfc1e5a660b7caa85](https://cloud.githubusercontent.com/assets/653247/5691694/cd28759c-98d3-11e4-8bd7-08026db73d40.png)
![f34b83e295f04f0975d4086bcfe36ff2](https://cloud.githubusercontent.com/assets/653247/5691695/cd2eba38-98d3-11e4-9988-fed5d9087de0.png)
![map envisioning-the-future-of-education](https://cloud.githubusercontent.com/assets/653247/5691696/cd307c56-98d3-11e4-8e04-d0be321555dc.png)
![map static squarespace com](https://cloud.githubusercontent.com/assets/653247/5691697/cd3254d6-98d3-11e4-9329-e1322f126cb0.png)

-
*ps: maybe you can close the #1324 issue?

**Comment by tobibeer** [comment]
@christophvarga, would it be ok for you to link to those images instead of embed them?
They don't seem to directly relate to the issue.

**Comment by felixhayashi** [comment]
Hi @christophvarga, 

> as follows some further thoughts on the map-view

I am sorry, I didn't quite get your point. Also why the blockquotes and why is some of your text italic?

> i did a research and here is a list of graphic and information designers from students to agencies wich adressed me by their work. maybe one of them like to contribute to this project?

What do you mean by *adressed me by their work*? Do you correspond with the authors? And why do you ask me if they would like contribute, I don't really know them...

> here are some examples i came to

What is the meaning of these examples? I mean, I know what cluster networks and graphs look like...

Maybe you could clarify this or open a new issue.

-Felix

**Comment by pmario** [comment]
@christophvarga 
As Felix pointed out, please clarify. ... IMO this is spam and should be removed.

**Comment by christophvarga** [comment]
@felixhayashi you offered me in an other issue to contribute to the graphic style of the map. since is don't know to do that i thougth i search for people who are specialized in visualizing data. and these are only contacts i found so if there is any interest in working together with an graphic designer i am shure one of them could be interested in contributing to this project.  ?

if this post is not in place here, where should it be moved to? (i didn't get the structure of all conversations going on here, so thank's for helping)

**Comment by tobibeer** [comment]
> if this post is not in place here, where should it be moved to?

Make a new issue with a well defined purpose and scope... to open up discussion.

**Comment by felixhayashi** [comment]
@christophvarga,

it's nice that you want to help but I think Mario and Tobias are right. Please be concise about your suggestions and create a new topic for your thoughts and do not make such big posts, it's hard to read and understand.

> and these are only contacts i found so if there is any interest in working together with an graphic designer i am shure one of them could be interested in contributing to this project. ?

It's not necessary to reference people that are professionals with visualization software. Unless I ask, I don't need help with that.

> you offered me in an other issue to contribute to the graphic style of the map.

Then I certainly meant that if you have any *specific* ideas how to improve TiddlyMap, you could open a separate issue on that while clearly explaining your point.

-Felix

-Felix

**Comment by tobibeer** [comment]
I am beginning to think that — next to global and private edges — these are a third type of edge, call them "system" or "dynamic" or "computed" edges. They are dynamic in the sense that instead of querying any stored TiddlyMap node-relationships, you call core functions (or functions calling core functions) that create the relationships via predefined queries.

So, you would have helper functions for directed relationship pairs, e.g....

* `tagNodes(tiddler)` — tagged
* `taggingNodes(tiddler)` — tagging

>

* `referencedNodes(tiddler)` — referenced
* `referencingNodes(tiddler)` — referencing

>

* `listedNodes(tiddler)` — listed
* `listingNodes(tiddler)` — listing

>

* etc...

In some ui you would tick off each of these implemented auto-relations. Once activated, the view would call those funtions to query relationships rather than the generic ones you use to store otherwise persisted, default TiddlyMap relationships. (Sorry, haven't yet taken a closer look at the code). The key is to reroute that query to something dynamic and maybe later even respond to updates to the store accordingly and update the graph when a tiddler gets a new tag or link, etc...

**Comment by felixhayashi** [comment]
Hi @tobibeer,

what you describe makes perfect sense. This is actually how "display neighbours" works (see node filter in editor). "display neighbours" is dynamically calculated and not based on any filter. So I think it should also work for the scenarios you described (of course, I need to write some code, but it is the same idea). It is good that you listed some examples above, then I have some orientation when I actually implement it. 

-Felix

**Comment by tobibeer** [comment]
Perhaps a good starting point on how to gather such tiddler references in a function call is to take a look at the corresponding filters.

**Comment by rcrath** [comment]
Am I correct in understaninding that tags do not show up in live view unless they have a tiddler with the name of the tag as its title that has content in it?

**Comment by felixhayashi** [comment]
@rcrath, yes correct!

I cannot show nodes in the graph that do not correspond to an existing tiddler. Therefore, the tag-link is only displayed if it points to an existing tiddler.

**Comment by rcrath** [comment]
@felixhayashi  THnx!

**Comment by tobibeer** [comment]
> I cannot show nodes in the graph that do not correspond to an existing tiddler. Therefore, the tag-link is only displayed if it points to an existing tiddler.

May I ask: Why? ...or can you not do without and apply some fallback info for tids that don't exist, like a missing tiddler link does?

**Comment by felixhayashi** [comment]
It's not that it is not possible, it is just that this premise "a tiddler has to exist in order to be displayed" is essential to many operations. This made/makes it easier for me to develop the plugin.

For example I always operate on ids. Once the graph is drawn, I expect all nodes to have ids that correspond to tiddlers and all of the various user actions trigger handlers that expect the nodes to relate to a real tiddler. It would require a huge effort and much concentration to implement checks everywhere, whether a tiddler really exists.

But I also think it would be nice to allow showing nodes even though the tiddler does not exist. Maybe I can add this in the future at some point when I have more time :)

**Comment by tobibeer** [comment]
> It's not that it is not possible, it is just that this premise "a tiddler has to exist in order to be displayed" is essential to many operations. This made/makes it easier for me to develop the plugin.

I understand, you would need conditionals in some places so as to have a tiddler created before you can modify / add properties.

Perhaps you can have "not editable" nodes, or some way to "create first"... that way the user would be aware that here we have a node that ain't a tiddler.

But yes, all that means for the ui to have modifications, I understand.

Not sure what your code will do if a title won't return an id => perhaps the error handling can do the rest of interpreting something as being a missing tiddler.
