### ISSUE TITLE
[Question] Create hierarchical layouts.

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#142]
Hello again, and sorry for opening so may issues.

As you know I'm using TMap to create a view of some DBs. Since tiddlers are created and added automatically, this does not provides the best visual experience. How can I create -automatically- hierarchical layouts? I saw that this is a feature (listed on features list) but I can not see any reference to creating this kind of layouts.

Thanks in advance.

**Comment by felixhayashi** [comment]
Hi Danielo,

sorry, but the feature is removed at the moment because the code/design was ugly and I did not have time to redo it. It is on my list (#15).

-Felix

**Comment by danielo515** [comment]
Ok,

whenever you re-enable it please ping me. Is there at least a way to define a minimum space between nodes? Currently is my results are... too close to each one

![image](https://cloud.githubusercontent.com/assets/2270425/8150162/c7232d6a-12de-11e5-87b9-2b9ac3850e96.png)

**Comment by felixhayashi** [comment]
> whenever you re-enable it please ping me.

I'll do that.

> Is there at least a way to define a minimum space between nodes

No :( Maybe when I finished migrated to 4.0 we can figure out a way how to do it.

But you can always use the "lense" button to search for nodes in the map and focus on them.

P.S.

Look how many links point to tiddlywiki :D - pure chaos
https://github.com/felixhayashi/TW5-TiddlyMap/issues/58#issuecomment-78397190

**Comment by danielo515** [comment]
Seems that you have removed a lot of features that are still mentioned on the main site, like the search view ($:/tags/SearchResults) and the hicherachical layout. It could be cool if you add a mention about they are not available and optionally a way to enable it again (in case of the searchResults, which is extremely helpful in my project)

Regards.

**Comment by felixhayashi** [comment]
> Currently is my results are... too close to each one

Hi @danielo515 since v9 you can change the physics settings globally or locally (per view) to make it look better for views with "floating nodes" enabled. All options are documented at http://visjs.org in the network section. So I'll close this issue now.

**Comment by danielo515** [comment]
Hello @felixhayashi 

I have been experiencing some issues about that. Specifically the opposite situation: nodes are sooo far away that the map becomes giant and unusable. I have edited the physics settings (before seeing this ticket) and the results was the same.

Here you can see a screenshot:

![image](https://cloud.githubusercontent.com/assets/2270425/10572569/e78ee89a-7649-11e5-8eae-341acfafd1eb.png)


I have to edit the filters to exclude those nodes that are not "linked" to any node, but I actually want to see them. Any recommendation ?

**Comment by felixhayashi** [comment]
Hi @danielo515 

if you haven't already, please update to the newest version as I optimized physics options!

Is the "floating nodes" option enabled in your view? If yes, you need to increase central gravity!!

If "floating nodes" not enabled, then my physics optimizations only work for maps that are newly created. In this case, try creating a new map and add the nodes with a filter and the nodes will be added near the center automatically! See https://github.com/felixhayashi/TW5-TiddlyMap/issues/177.

**Comment by tobibeer** [comment]
Not sure, but it appears that — and I would be incredibly astonished — the distance handling in vis is not as exponential as it needs to be ...or maybe, it was just TiddlyMap that implemented a simple "linear distance" approach. I have no clue.

**Comment by danielo515** [comment]
Hello @felixhayashi 

Sorry for not answering this before. I have increased the central gravity, activated the floating stuff and then nodes got closer. Then I have deactivated the floating stuff again and everything was good. Thank you.

**Comment by felixhayashi** [comment]
> I have increased the central gravity, activated the floating stuff and then nodes got closer. Then I have deactivated the floating stuff again and everything was good.

Very nice, great idea to do it that way, even better than my suggestion!
