### ISSUE TITLE
Migration to vis.js v4 takes some time

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#143]
Just wanted to communicate that I am heavily working on the migration to vis.js v4. This is the reason that prevents me to work on all the other issues on the list...

Much changed in v4 and I have to fix many details in TiddlyMap; do much testing; do upstream bug reporting to the guys from vis.js and wait till they solved the reported problems.

Hope this is over soon and I continue to implement all the pending issues.

-Felix

**Comment by felixhayashi** [comment]
Hi @kixam

I expect TiddlyMap being ready for vis.js v4 the next week (in any case before the end of June). I'll update the vis.js plugin then and eventually you can update your timeline widget plugin site :)

**Comment by kixam** [comment]
Hi @felixhayashi 

Thanks for your hard work. My timeline demo site is ready for update when you are.
