### ISSUE TITLE
Mouse scroll on map

### ISSUE THREAD

**Issue by nameanyone** [felixhayashi/TW5-TiddlyMap#149]
Affects both live view (zooming) and story scrolling.

**Comment by felixhayashi** [comment]
Sorry, I do not understand the issue. Could you elaborate a bit more?

**Comment by nameanyone** [comment]
I'm on http://tiddlymap.org/, mouse pointer is hovering on the Map (right-hand side). I scroll down with the mouse wheel, and observe the map zooming out as well as story (left-hand side) scrolling down.

**Comment by felixhayashi** [comment]
This doesn't happen on my system. If my mouse is over the map editor in the sidebar and I am scrolling it only zooms out and does not scroll the story. I am using Firefox 38 and Google Chrome 43.  which browser/os are you using?

**Comment by felixhayashi** [comment]
A guess: Did you change from mobile mode to desktop mode without refreshing?

**Comment by nameanyone** [comment]
I checked at home, doesn't happen. I suspect it's caused by a touchpad driver. I have both a mouse and a touchpad at work.

**Comment by felixhayashi** [comment]
Still thanks for telling me.
