### ISSUE TITLE
Hierarchical Graph Layout

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#15]
Allowing to select an edgetype that defines a hierarchy (acyclic) and build the graph accordingly

**Comment by felixhayashi** [comment]
> Ok, can you perhaps word that in a slightly more prosaic fashion? ^^

Well, yes should have done that :) Now it's implemented already, so I can show you some screenshots (maybe @pmario is also interested in this, as he originally proposed this):

You switch the mode and specify the relations that define the order

![selection_416](https://cloud.githubusercontent.com/assets/4307137/5593867/3f8a6186-922b-11e4-9c93-9807c05b2e26.png)

And the you can get something like this:

![selection_415](https://cloud.githubusercontent.com/assets/4307137/5593869/5a8c1862-922b-11e4-9547-bf072a7cff32.png)

Demo here: http://wkpr.de/hosting/tmp/tw5/taskgraph/#Hierarchical%20layouts

Do not use in production - still experimental ;)

-Felix

P.S. @pmario this took quite long to build as vis doesn't calculate the hierarchical layout based on a defined set of edges. see here: https://github.com/almende/vis/issues/528

**Comment by pmario** [comment]
looks good. I'm testing :)

**Comment by Peter-Miller** [comment]
Congrats on the new release, Felix -- looks great! 

Bit confused by the demo wiki which says you can't change vertical positions in hierarchical maps -- I could (unless I'm missing something like all the maps are the same now...).

**Comment by felixhayashi** [comment]
Hi @Peter-Miller,

> Congrats on the new release, Felix -- looks great!

thanks! There is a problem with the data structure updater I will fix in the next minutes so please do not update your own wiki with 0.7.0 until #70 is resolved.

> Bit confused by the demo wiki which says you can't change vertical positions in hierarchical maps -- I could (unless I'm missing something like all the maps are the same now...).

Really? I am pretty sure it is impossible since vis.js prevents this (since otherwise it would conflict with the mechanism that calculates the hierarchy...).

I really have to update all the docs now as 0.7.0 changed a lot.

Sadly, I removed the hierarchical layout for the time being since I disliked the way I had implemented it. :( 

-Felix
