### ISSUE TITLE
TiddlyMap nodejs and images

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#150]
Hello,

I am not sure if this is Tiddlymap's fault, but it is not happening if I remove tiddlymap. I'm getting some errors related to images on node side. This does not happens on the browser, you can only see it on node console, and there is no need to open any tiddler, it just "happens". If you have tiddly-map installed in a TW running under node and you have images then you will get an error like the one I posted below. I think this is more related to meta files than with the image itself.

```
$:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:127
.writeFile(fileInfo.filepath,tiddler.fields.text,{encoding: typeInfo.encoding}
                                                                    ^
TypeError: Cannot read property 'encoding' of undefined
    at $:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:127:74
    at FileSystemAdaptor.getTiddlerFileInfo ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:76:3)
    at FileSystemAdaptor.saveTiddler ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:116:7)
```

**Comment by felixhayashi** [comment]
Hi @danielo515 

strange, I do not get this error in my node console.

**Comment by felixhayashi** [comment]
...also I do not have a variable that is called "typeInfo" in my system.
