### ISSUE TITLE
Making the vis.js configurator available in tiddlymap

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#151]
...for styling nodes and edges. maybe also for changing certain aspects of a graph on a view level...

Currently edges are styled by directly writing json...

**Comment by felixhayashi** [comment]
This critically depends on https://github.com/almende/vis/issues/1075

**Comment by felixhayashi** [comment]
Will be available in the next release for all vis-related styling.
For some impressions see: #152

**Comment by felixhayashi** [comment]
Configuration will be possible on 3 levels:

* global (= counts for all views)
* local (= for each view; inherits global settings)
* node- and edge-types (= element level; inherits local settings)

**Comment by tobibeer** [comment]
Now that's what I call a release! Kudos.

**Comment by felixhayashi** [comment]
Thanks Tobi. Glad you like this one :)
