### ISSUE TITLE
Node-types and node-type manager

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#152]
TiddlyMaps are currently build from the [following constructs](http://tiddlymap.org/#Map%20Constructs):

* Views
* nodes
* Edges
* Edge-Types
* Edge-Type Namespaces

In order to deliver #16 and #133 I need to introduce another concept:

* Node-Types

Node-types shall be used as blueprint for tiddlers displayed as nodes in the map. These node-types are then related to actual nodes using fields or a filter mechanism as described in #16 

This issue depends on #151 and is quite complex so it may take a while but it will critically enhance tiddlymap!

**Comment by felixhayashi** [comment]
# Impressions

![selection_421](https://cloud.githubusercontent.com/assets/4307137/8833593/e019c754-30af-11e5-9c98-e42d84cf6445.png)

![selection_419](https://cloud.githubusercontent.com/assets/4307137/8833597/e2d6ee54-30af-11e5-9941-13ea1ff3ac8b.png)

![selection_422](https://cloud.githubusercontent.com/assets/4307137/8833613/fc8e70ba-30af-11e5-8c21-a712fb32760d.png)

**Comment by felixhayashi** [comment]
At the moment, a node is explicitly bound to a type, this **does not** solve #16 yet.

**Comment by felixhayashi** [comment]
Maybe I can release v0.9 this week. It's really nice already.

For anybody who is interested, here is a demo video at youtube: 
https://youtu.be/DC7r744NCCg

In v0.9, I also want to allow individual node styling of nodes in a graph (not based on types), but I have not fully implemented this yet. Individual styles will override styles inherited by node types.


```
--------------------------------------------< Affects all nodes in a view

Global prototypical node style             // Defined via "TiddlyMap configuration"
└── View specific prototypical node style  // Defined via "View configuration"
    |
--------------------------------------------< Affects specifc nodes in a view
    |
    ├── Styles defined through node types  // Type-specific style; inherits local style
    ├── Manually global/default node style // Defined via "edit node / global style"
        |
        └── Manually created local style   // Bound to view; Overrides all other styles
   

-Felix

**Comment by tobibeer** [comment]
Just wanted to say: fantastic work, @felixhayashi :+1:

**Comment by felixhayashi** [comment]
Much thanks @tobibeer! Took a lot of time, almost a year, to design and build #16 so I am happy it is finally done. Of course there is much room for improvement but at least the fundament now exists ;)

-Felix
