### ISSUE TITLE
Automatic zoom out after adding new node

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#153]
Not sure whether this is related to #40 or #41 but I have a moderately large map and want to work on a part of it so I zoom in, create a new node and then the map re-loads, zooms out and re-centres so I have to drag and zoom in again to get to the area of interest before I can add the next node. Is there a way to avoid that?

**Comment by felixhayashi** [comment]
Hi @Peter-Miller,

yes, that is annoying. I will change that!

**Comment by felixhayashi** [comment]
Hi Peter,

I fixed this now. Adding/Removing edges/nodes in the graph will not reset the zoom. 

-Felix

**Comment by Peter-Miller** [comment]
Many thanks, Felix. Works fine now.

**Comment by felixhayashi** [comment]
There are also cases when the user zoomed the editor and then makes changes to a tiddler in the river and then TiddlyMap automatically zooms out, which is not nice. So for the next release I also prevent a zoom when modifying a tiddler in the river that is also displayed in the graph.
