### ISSUE TITLE
Unexpected behaviour from sidebar map resize button

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#157]
When in half-screen mode, clicking the full-screen button reverts map to default/minimized instead of full-screen.

**Comment by felixhayashi** [comment]
Hi @Peter-Miller 

thanks for telling me :) I am aware of this since a long time, just been too lazy to fix it. Thanks for the heads up.

-Felix

**Comment by felixhayashi** [comment]
Now fixed in a better way.
