### ISSUE TITLE
Scrolling issue when editing tiddlers in fullscreen

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#158]
When I try to add text to the bottom line in a moderately long text field, the field repeatedly scrolls back to the top.

**Comment by felixhayashi** [comment]
I know!! This is a tiddlwiki issue :(:( I hope Jeremy can fix it

See https://github.com/Jermolene/TiddlyWiki5/issues/1575

**Comment by felixhayashi** [comment]
Hi @Peter-Miller 

I proposed a fix for this to Jeremy at the tiddlywiki repo. If he accepts, then this bug will be history and we can finally edit big tiddlers while in fullscreen.

See https://github.com/Jermolene/TiddlyWiki5/pull/1933

-Felix

**Comment by felixhayashi** [comment]
Jermolene/TiddlyWiki5#1933 has been merged at the TW upstream and will be fixed in TW v5.10.0

![borat_great_success](https://cloud.githubusercontent.com/assets/4307137/11958285/3939537e-a8c7-11e5-8422-9b2015576c48.jpg)

**Comment by tobibeer** [comment]
:D
