### ISSUE TITLE
Importing TiddlyMap breaks image imports

### ISSUE THREAD

**Issue by sivaraml** [felixhayashi/TW5-TiddlyMap#159]
Hi,
After I import the tiddlymap in standalone tiddlywiki, Whenever I import a image or pdf file, It creates a node in the map.

**Comment by felixhayashi** [comment]
Hi @sivaraml 

what is the name of the view (map) you are talking about? what is the node-filter of the view? The default-view usually shows the last 50 tiddlers added to the system...

**Comment by sivaraml** [comment]
Hi,
Oh I am sorry, I misunderstood, I thought default view also will show only the tiddlers added via 'add node'.

**Comment by felixhayashi** [comment]
No problem, maybe you are right and I should change the filter of the default view not to show any nodes per default... it can cause confusion as in your case.
