### ISSUE TITLE
Styling nodes according to tag or filter combinations

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#16]
Allow individual styling of nodes or set of nodes. For example a user wants to make the font-size of a single node really big or color a single or set of nodes.

**Comment by tobibeer** [comment]
I think your "tiddler" is a graph or "view" tiddler... where you store all the configuration of that graph / view, including which tiddlers it entails.

In other words, I think you should never store graph related data at the tiddler being depicted. However, as for the color or icon, you could surely use a tiddler's color or icon as the default, which can be overriden on a per-graph basis, even with a number of "icons" or "styles".

**Comment by asampal** [comment]
I agree with using the tiddler's color/icon as defaults in the graph views. This would follow the principle of least surprise.

**Comment by felixhayashi** [comment]
Yes, I could use this as default and on top of it (in a later version) allow coloring on a tag or filter basis.

**Comment by felixhayashi** [comment]
> Nodes, aka tiddlers, can come with a color field... and the corresponding logic to calculate the black or white foreground color that goes with it.

Implemented

**Comment by tobibeer** [comment]
:+1:  nice one, Felix — I like simple, but useful quick wins

**Comment by felixhayashi** [comment]
> I like simple, but useful quick wins

exactly :)

**Comment by felixhayashi** [comment]
Relates to #11

**Comment by andtheWings** [comment]
+1

**Comment by aCandidMind** [comment]
Thanks for this nice plugin! It would quadruple it's usefulness for me if the ideas above regarding per graph configuration inside graph/view tiddlers were implemented. Or if there was another option to have per tag node colors.

**Comment by felixhayashi** [comment]
Hi @aCandidMind 

> Thanks for this nice plugin! 

Thanks!

> It would quadruple it's usefulness […}

I AGREE. This is one of the first things on my list ;) What currently prevents me from implementing #16 is #143

-Felix

**Comment by fowles** [comment]
It looks like #143 is now marked as closed.  I see screenshots for #152 but I cannot find any commits that support it.  I would be happy to do some of the coding for this feature, but could use a pointer to
- where the relevant code is
- how to run a dev version of tiddlywiki and tiddlymap

**Comment by felixhayashi** [comment]
Hi @fowles,

Thank for your interested in the project :)

> It looks like #143 is now marked as closed. I see screenshots for #152 but I cannot find any commits that support it.

Yes, you are correct, this feature has not been pushed yet. It is still in development and also requires more testing time. I posted the screenshots at #152 just to inform the repo-followers of the current state...

> I would be happy to do some of the coding for this feature, but could use a pointer to […]

Much thanks for this offer, but in case of this node-styling feature, I am already in the middle of development and the local codebase differs much from to the code at GitHub. I cannot say when I commit the code though because I have much to do at the moment. Might take a week or two :(

As for contributions in general, I feel responsible to first do a big final refactoring and code commenting effort before accepting pull requests (except for minor issues of course). Once this is done, you are highly welcome to directly contribute code.

-Felix
