### ISSUE TITLE
Allow Font Awesome icons to be used with TiddlyMap

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#162]
In TiddlyWiki we can easily use [Font Awesome](https://fortawesome.github.io/Font-Awesome/) icons  (e.g. with the [TW5FontAwesome Plugin](https://github.com/TheDiveO/TW5FontAwesome) by @TheDiveO, which I am also using for tiddlymap.org). For those who don't know Font Awesome is… awesome: It is fully open source and is GPL friendly!

At the moment TiddlyMap only support icons stored in TiddlyWiki as icons but I want to change that so starting from v0.9 we can simply use the font code (e.g. "\uf007") in the icon field to make TiddlyMap display the icon.

**Comment by felixhayashi** [comment]
#### Think of all the possibilities !!! All icons of Font Awesome in TiddlyMap!! BAAAAM

---

#### A small set of icons from the Font Awesome icon set:

![2015-09-04 13 42 29](https://cloud.githubusercontent.com/assets/4307137/9682868/e1136e44-530a-11e5-864a-462eec6200f5.png)

**Comment by jfontany** [comment]
So you would style nodes as fontawesome-icons? Would you also be able to
attach an icon to a relationship line?

Note to self, learn the TW5FontAwesome Plugin
<https://github.com/TheDiveO/TW5FontAwesome>! :D

**Comment by felixhayashi** [comment]
Hi @jfontany 

> So you would style nodes as fontawesome-icons?

yes, you can use an image as node icon by adding an icon field an referencing a tw-image. Now with v0.9 it will be possible to use the font awesome plugin and paste the icon code into a tiddler field `tmap.fa-icon: f02d` for e.g. adding the book icon…

> Would you also be able to attach an icon to a relationship line?

No, that is not possible :( But you could do something like "a -> likes -> b" where "likes" is a node as well and has an image.

-Felix

**Comment by jfontany** [comment]
Cool, thanks for the reply Felix. This is definitely a great addition to
TiddlyMap, making styling nodes a much simpler proccess. I wonder how hard
it would be to style relationship lines....

For a quick overview of my intended use-case, I plan on using TiddlyMap to
present RPG "Adventure/Sourcebook" data in a novel and semantically rich
way. Basically, we take an old D&D adventure, such as "T1: The Village of
Hommlet". We make a data set and nodes for each of "Factions" represented
in the town, nodes for the "Location numbers", and nodes for each of the
"NPC" characters. Then, by arranging in various ways or views, we can get
very rich semantic data onto a concept map.

For an example of this that I made in V.U.E. see this link:
https://plus.google.com/104849355407989263028/posts/9w8GjkFmqfL
For the "overview of the village" map see this link:
http://www.cartographersguild.com/showthread.php?t=19525&p=192710&viewfull=1#post192710

It would be awesome to have a "The Party" node and be able to track
individual relationships, like "Lord Rufus [is Friendly to] The Party",
"Jaroo Ashstaff [is Loyal to] The Party", etc, etc.

Visual styling of these relationships links is just a bonus, I think I can
get everything else out of the existing TiddlyMap functionality. Thanks
again for the great tool.

**Comment by felixhayashi** [comment]
Hi @jfontany 

> For a quick overview of my intended use-case, I plan on using TiddlyMap to
present RPG "Adventure/Sourcebook" data in a novel and semantically rich
way […]

thanks for sharing this.

> I wonder how hard it would be to style relationship lines....

Well, if you are just talking about the style( e.g. orange color, edge-thickness etc.), it is very easy. You can use the "edge style editor" (which you find in the tiddlymap drop down menu). Just adding images is not supported. In v0.9 you will have a form for styling (with sliders etc.) instead of a text editor.

> It would be awesome to have a "The Party" node and be able to track individual relationships, like "Lord Rufus [is Friendly to] The Party", "Jaroo Ashstaff [is Loyal to] The Party"

But isn't that what the "Live view" already does? you create three nodes "Rufus", "The Party" and "Jaroo Ashstaff"; then link them accordingly and then open the live view and you can see all relationships…

> Thanks again for the great tool.

You are welcome :)
It's not done yet, there are many nice ideas that are still waiting to get implemented and much can be improved.

-Felix

**Comment by tobibeer** [comment]
This is awesome! :+1: 

Out of curiosity, is it an architectural restriction of TiddlyMap or vis.js that node labels cannot display images?

**Comment by felixhayashi** [comment]
Good point! I also couldn't get that to work, so I think it is visjs related. I'll test it once more and if it still doesn'I work, I should probably file an issue at the visjs repo.

**Comment by felixhayashi** [comment]
Also the font awesome plugin by thediveo does not contain the latest Font Awesome version. I created an issue (https://github.com/TheDiveO/TW5FontAwesome/issues/2), I hope he has not abandonned his repo.

**Comment by tobibeer** [comment]
Ah, thanks for the note, I'll try to update as well. First attempts have me fail miserably at trying to update 

http://tobibeer.github.io/tw/fa/#%24%3A%2Ffonts%2FFontAwesome

...to 4.4

**Comment by felixhayashi** [comment]
Ah cool @tobibeer, I did not know that you also maintain a FA "plugin" for TW. It is nice that you also provide a do-it-yourself-description ("Installation") of how to create the FA tiddler and do the base64 encoding!

**Comment by tobibeer** [comment]
Sorry for perhaps bloating your issue (although it's closed already ;-)...

For some odd reason I am failing to update to FontAwesome 4.4. I have updated the font according to my instructions, but any new icons won't render. Check out the tag **4.4** or see the first image called **fa-500px**.

http://tobibeer.github.io/tw/fa/4.4.html

**Comment by felixhayashi** [comment]
Yeah, strange, especially since some 4.4 icons render fine like "fa-battery-empty [&#xf244;]" in your demo. Maybe a bug by Font Awesome itself?

**Comment by tobibeer** [comment]
Actually, that's not fa-battery-empty either, it's just another "faux icon" that's not blank, more like a "can't display this unicode icon" character.

**Comment by felixhayashi** [comment]
Very strange, for me it's not a faux icon:

![2015-09-17 12 25 36](https://cloud.githubusercontent.com/assets/4307137/9930882/391ec918-5d37-11e5-9802-47c732adee32.png)

**Comment by tobibeer** [comment]
Now that is decidedly weird. In **all** browsers I use, I get this:

![font-awesome error](https://cloud.githubusercontent.com/assets/97566/9931282/9d7928d8-5d3a-11e5-9db6-4a7e827974f1.jpg)
