### ISSUE TITLE
Permission denied to access property 'type'

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#163]
Crazy Firefox error that sometimes occurs. No idea what this is. Never happens on Chrome or other browsers.

**Comment by felixhayashi** [comment]
I will simply catch the error message.

**Comment by tobibeer** [comment]
What was ff nagging on about?

**Comment by felixhayashi** [comment]
Hi Tobi.
I really don't know :D 

See this post here: https://github.com/almende/vis/issues/1088
