### ISSUE TITLE
Flash Tiddler on open / scroll-to

### ISSUE THREAD

**Issue by tobibeer** [felixhayashi/TW5-TiddlyMap#167]
Regarding https://github.com/Jermolene/TiddlyWiki5/issues/1543#issuecomment-141922750...

> At tiddlymap.org I use the TW5-TopStoryView plugin to always scroll to the top and I combine it with the TW5-HotZone plugin to add a short flash.

I just opened TiddlyMap.org to see if I can find anything flashing, but I'm not seeing it. Do I need to turn that on somewhere?

**Comment by Peter-Miller** [comment]
It's quite subtle -- pale cream background. Works OK in Firefox.

**Comment by tobibeer** [comment]
Ha, this is not just quite subtle, it's entirely unnoticably subtle :D 

Tbh, I think the more noticable flashing would be transitioning the color of the dropshadow to something colorful, e.g. the link color.

**Comment by pmario** [comment]
IMO plugin territory. There are several plugins that do the job, as felix pointed out in #1543

**Comment by pmario** [comment]
I deleted my first post, since I was posting in the wrong context. sry :)

**Comment by felixhayashi** [comment]
> A more noticable flashing might be transitioning the color of the dropshadow around the egdes to something colorful, e.g. the link color. That would create a higher contrast than changing the background.

@tobibeer Ehm… the flash is not really part of TiddlyMap at all. It is just a way to make use of the HotZone plugin. You can add any css you want for styling (see e.g. http://tiddlymap.org/#%24%3A%2Fme%2Flayout.css). I didn't want to have a "bam in your face" color change but I agree, it might be too subtle. Once I've the time, I'll try your idea with the shadow color ;)

I'll close this now.

**Comment by tobibeer** [comment]
Ah, thanks, that works. Was just an observation, or rather lack thereof ;-)

This looks quite nice, do as you please...

```
@-moz-keyframes flash {  
  50% { border-color: #999; }
  100% { border-color: white; }
}

@-webkit-keyframes flash {  
  50% { border-color: #999; }
  100% { border-color: white; }
}

@keyframes flash {  
  50% { border-color: #999; }
  100% { border-color: white; }
}
```

**Comment by felixhayashi** [comment]
> This looks quite nice, do as you please...

It does, I only realized just now that in mobile we do not have borders and also no shadow :( Still thanks for the suggestion.

> On second thought, I think for the live-view it is quite important to know when something actually entered the hotzone, which I simply don't notice right now.

So you mean this should be also used in TiddlyMap? Hmm, I could make it an option that is enabled by default…

**Comment by felixhayashi** [comment]
I should implement this and make it optional for TiddlyMap.

**Comment by tobibeer** [comment]
@felixhayashi, a minor thing... looking at http://www.hallo-sme.uni-hamburg.de in admin mode, I can see that the map redraws even if I hover a system tiddler, which it can't do much with, afaics. Perhaps there could be a global filter on what to include in a map at all / what to respond to, hot-zone-wise? ...so that it won't update the map when hovering a system tiddler.

**Comment by felixhayashi** [comment]
Hi @tobibeer 

> in admin mode

:D I was not expecting anyone to do that. Seems like I failed. I'll make it harder to reach system tiddlers or going into admin mode in the future ;)

> I can see that the map redraws even if I hover a system tiddler

When a system tiddler makes it into the hotzone, the map in the sidebar just goes blank. I thought this makes more sense than leaving it at the state where it shows the last non-system tiddler…

> Perhaps there could be a global filter on what to include in a map at all / what to respond to, hot-zone-wise?

Maybe you could explain this a bit more. Do you mean something like https://github.com/felixhayashi/TW5-TiddlyMap/issues/166?

**Comment by tobibeer** [comment]
> Maybe you could explain this a bit more. Do you mean something like #166?

Nope. More like: When the currently hot-zoned tiddler matches that filter: don't update the map.

**Comment by felixhayashi** [comment]
> When the currently hot-zoned tiddler matches that filter: don't update the map.

I did that in the beginning but it was strange if a system tiddler or draft opened and the map stayed as it was. But maybe you are right and it is more intuitive to leave the live view in the last valid state and update it when the focus is on a valid tiddler again… I'll have a look at it again.

**Comment by tobibeer** [comment]
not utterly important ...I just don't think an empty map makes sense when hovering a system tiddler .. so I'd leave it to whatever content it was...

and since you have to specify anyhow how to handle it, I'd make it a generic filter, not just "system tiddlers"... for who knows what reasons :D

**Comment by felixhayashi** [comment]
@tobibeer, I made up my mind and eventually decided to use your flash variant for tiddlymap.org. Looks better ;)

    @-moz-keyframes flash {  
      50% { border-color: #999; }
      100% { border-color: white; }
    }

    @-webkit-keyframes flash {  
      50% { border-color: #999; }
      100% { border-color: white; }
    }

    @keyframes flash {  
      50% { border-color: #999; }
      100% { border-color: white; }
    }

**Comment by tobibeer** [comment]
@felixhayashi :+1:  nice, glad you find it useful
