### ISSUE TITLE
Allow moving portions of a map to a new map

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#168]
When a map has grown too big it should be possible to somehow cut the nodes of one map and transfer them into a new map. The new map should be an exact clone of the old map, except that it contains only a subset of the nodes in the old map.

**Comment by felixhayashi** [comment]
This is somewhat a TiddlyMap analogy to Jeremy's slicer plugin for TiddlyWiki.

**Comment by felixhayashi** [comment]
I think I'll go with the "create empty view" dialog and rename it to "create view" and in this dialog add some options to clone parts of the current view. This seems like a good place for this feature and doesn't bload the menu bar with another button".

**Comment by felixhayashi** [comment]
##### Preview of how it looks on my local dev branch

1.Before
2. Create view Dialog
3. Added nodes with same positions to new view
4. Old view (nodes removed since we moved the files…

<img src="https://cloud.githubusercontent.com/assets/4307137/10125038/87aeb0b6-6566-11e5-81bc-7b608cd13110.png" width="24%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/10125031/3a2e641c-6566-11e5-9e6f-30e473524f85.png" width="24%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/10125032/4216bc4c-6566-11e5-9e17-e46377bbe206.png" width="24%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/10125033/48d48d20-6566-11e5-9539-fd849f6f530e.png" width="24%"></img>

**Comment by naomileweck** [comment]
Thank you! I cannot wait to use this function once it is available!

**Comment by tobibeer** [comment]
If vis.js allowed multiple selection, it would be a wee more straight forward to shift+click all desired nodes before opening that dialog and thus having them preselected.

**Comment by felixhayashi** [comment]
@n-le I'll hurry up with this :)

@tobibeer 

> If vis.js allowed multiple selection, it would be a wee more straight forward to shift+click

I agree with you! Because I do not have a method to revert (something like `ctrl-z`), I thought it would be a bit dangerous to make the user select and then allow to press `ctrl+x` … But your comment make me rethink this. IMO it is most natural to make a multiselect (vis allows you to do that by holding down the pointer for 2 seconds on a node without releasing) and then only allow a `ctrl+c` action and if the user wishes to delete, he/she can come back later and delete the nodes (but this requires a multiselect again). So I'll also implement a multidelete as it was already suggested in another issue (at the moment, hitting delete will only delete one single node, even if multiple nodes are selected).

> but I can see how that could be mildly problematic with (disabling / enabling) other map-editing features.

This is why I also decided against copy paste in the first place, because I cannot simply clone the view's config to ensure that nodes look the same in the view where you paste into (since with copy paste, we can also paste into an existing view). But, I think this is fine. Most important is that the node positions remain the same when being copied into another view.

I think it is about time that TiddlyMap gets a node context-menu that opens up on right click. I don't know where to put all the features anymore :)

**Comment by tobibeer** [comment]
> I think it is about time that TiddlyMap gets a node context-menu that opens up on right click. I don't know where to put all the features anymore :)

So, I would perhaps hold back on that. ;-)

What I meant was, that if you'd allow multi-select operations, then your editing toolbar should probably change.

I wasn't actually suggesting to allow for CTRL-X, CTRL-C, CTRL-V ...but only for a way to have your "create new view" dialog pre-populated. You could have an option to either "copy" or "move" the nodes into the new view, i.e. "remove" from the old.

**Comment by felixhayashi** [comment]
> What I meant was, that if you'd allow multi-select operations, then your editing toolbar should probably change.

That's fine, I just hide edit edge/edit node when multiselect is active.

> I wasn't actually suggesting to allow for CTRL-X, CTRL-C, CTRL-V ...but only for a way to have your "create new view" dialog pre-populated. 

Too late @tobibeer :D I liked the idea too much. It is far more dynamic because we can then move nodes between existing graphs, otherwise you need to create new views all the time.

But I won't add a context menu for now…

**Comment by felixhayashi** [comment]
I created a small demo video: https://youtu.be/3GbH_xMOYNg. Tomorrow I'll hopefully release v0.9.3 ;)

**Comment by tobibeer** [comment]
Wow, now that brings map editing to  a whole new level.
Bows down. :bow:

**Comment by felixhayashi** [comment]
> Wow, now that brings map editing to a whole new level.

Thanks Tobias. That's what I thought too!! :)

**Comment by felixhayashi** [comment]
This is now implemented and the new TiddlyMap version can be found at http://tiddlymap.org ;)

**Comment by tobibeer** [comment]
Just way too cool. :D

**Comment by danielo515** [comment]
That it's absolutely amazing @felixhayashi !! Good job, and well presented.

Tiddlymap is awesome.

**Comment by felixhayashi** [comment]
Thanks guys! :blush:

**Comment by jfontany** [comment]
Oh, very well done! :D
