### ISSUE TITLE
Allowing system tiddlers to be displayed in graphs

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#17]
From the google groups discussion (https://groups.google.com/d/topic/tiddlywiki/72ik_hyXafg/discussion):

>>> Is it possible that system tiddlers are never shown in the graph? If yes, is there an option to enable them?

>> yes you are right, they are never displayed. I could display them but I decided against that for now because system tiddlers should stay hidden in any case in my opinion. or not? if you have good arguments I might implement to show system tiddlers in graphs as well. 

> Not really, no... they should not be hidden from a graph, especially when I specifically add them, or am about to, e.g. via that button in the toolbar or one of the other ways. I sure see how I may want to add system-tiddlers to graphs. Actually, I may especially want to have those in a graph... to document those under the hood relationships of inner workings.
> So, perhaps a global checkbox that allows to at least add, although not necessarily show them by default, would be nice.

**Comment by tobibeer** [comment]
I see. Any chance of indexing system tiddlers differently? ...or, in fact, all tiddlers? The question is: Should updating a tiddler's representation in a graph update the tiddler? Me thinks not.

**Comment by felixhayashi** [comment]
> The question is: Should updating a tiddler's representation in a graph update the tiddler? Me thinks not.

Me neither, there is no case when this happens except when I give tiddlers ids so they can be used in a graph. but this can be disabled in the options and taskgraph then only relies on the title. problem is then: title changes cannot be tracked. The user has to decide: No ids -> renamed tiddlers will disappear if the graph's node filter is using the title. Ids -> Tiddlers are getting ids.

What is really problematic is that cloning will dublicate ids. So using taskgraph with ids and cloning is not a good idea.

It is the intrinsic problem of tw that only titles are unique.

-Felix

**Comment by asampal** [comment]
Should cloning not produce a different ID since the clone is a new instance (though all other attributes might be the same)?

**Comment by felixhayashi** [comment]
Hi @asampal,

unfortunately tiddlywiki does not have any notion of what an id-field is. It only ensures the title is unique when cloning.

See Jeremy's comment here: https://groups.google.com/d/msg/tiddlywiki/Y1V7oyBLpSs/i9gNJH3VkegJ

I added the following "Common Pitfalls" tiddler to the demo site at http://bit.ly/tiddlymap

> TiddlyMap comes with the default configuration that every tiddler used in a graph gets automatically assigned an id. The field used as id is per default "id" and not "title". This may create problems when you use tiddlywiki's cloning feature as the id field will also be cloned. You may set TiddlyMap to use the title as id field by setting "field_nodeId": "title". The consequence is that all nodes added to a graph via a filter such as [field:title[XYZ]] or [[XYZ]] will disappear after a renaming operation.

-Felix
