### ISSUE TITLE
edge configuration in groups

### ISSUE THREAD

**Issue by n-le** [felixhayashi/TW5-TiddlyMap#170]
Hello :)

I am not sure if opening a whole new issue just for this is necessary, but here it goes:

Is there anyway to use two different edge configurations within one view? 
"Straight" in most of the view, but "smooth" in one group/area of the view? (or vice versa)

It is not absolutely necessary, however it would speed things up if you wanted the edges in one area to look different from the rest despite not having a common name. Perhaps there already is another way of solving this situation that I have not noticed.

It would also help if only one area of my map is especially crowded/messy, but I want the rest to keep the "straight" edges. 

Thank you in advance and best regards!

**Comment by felixhayashi** [comment]
Hi @n-le 

> I am not sure if opening a whole new issue just for this is necessary

That's fine! You can create an issue whenever you feel that the topic has not been brought up yet ;)

> Is there anyway to use two different edge configurations within one view? 
"Straight" in most of the view, but "smooth" in one group/area of the view? (or vice versa)

Unfortunately, that is not possible :(
You can define, however, whether edges of a certain type should be straight or not (by double clicking on an edge to open the edge-type manager and then go to the tab "style"). But this doesn't really solve your problem and it is not view-specific (= it will affect all views).

> It would also help if only one area of my map is especially crowded/messy, but I want the rest to keep the "straight" edges.

I'll upload a preview of the new TiddlyMap version in one or two hours where you can copy nodes of one graph and paste them into the other graph (as we discussed in #168). This will certainly help to make your big graphs smaller! Sorry for the delay :(

-Felix

**Comment by n-le** [comment]
Thanks for the quick answer!
Also, what delay??? You work very fast.

**Comment by felixhayashi** [comment]
> Also, what delay??? You work very fast.

Thanks :)

**Comment by tobibeer** [comment]
Seems to be along the same lines as #164.

> You work very fast.

Indeed, so allow yourself a wee more delay once in a while. ;-)
