### ISSUE TITLE
Font Awesome Icons do not appear next to the Tiddler Title

### ISSUE THREAD

**Issue by jfontany** [felixhayashi/TW5-TiddlyMap#173]
Just something I noticed in the demo site, & didn't find anything searching the issues here.

Compare:
http://tiddlymap.org/#Plane
to
http://tiddlymap.org/#%40felixhayashi

The [[@felixhayashi]] tiddler has an icon on both the map and the tiddler's title-bar. [[Plane]] does not.

**Comment by tobibeer** [comment]
That's because one is an actual image and the other an icon from fontawesome for which @felixhayashi hasn't yet modified the subtitle ViewTemplate so as to show it.

**Comment by felixhayashi** [comment]
Hi @jfontany 

what @tobibeer said is right. 







Update to TiddlyMap v0.9.10 then follow the manual/screenshots

Screenshot manual (click on the image to view them in large):

1. To have a FA icon to be displayed in the tiddler title you need to override `$:/core/ui/ViewTemplate/title` and add the following to your code: `<span style="font-family: FontAwesome">{{!!tmap.fa-icon}}</span>`
1. Open your tiddler that contains the icon
1. Specify the icon in the `tmap.fa-icon` field and use the FA **full** unicode string (e.g. `&#xf167;`).
1. close the tiddler

<img src="https://cloud.githubusercontent.com/assets/4307137/10267687/2d3f8b54-6a9e-11e5-8189-4ad2006fbcc5.png" width="15%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/10267686/2d3e0810-6a9e-11e5-845d-65ee9c8d1f92.png" width="15%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/10267688/2d409f6c-6a9e-11e5-921d-d76649b779be.png" width="15%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/10267689/2d42817e-6a9e-11e5-9938-f080cd7b2b08.png" width="15%"></img>

**Comment by tobibeer** [comment]
I think it would be more natural to use the fontawesome icon names not the unicode strings

**Comment by felixhayashi** [comment]
> but perhaps that's problematic with tmap.

Yes, I cannot pass the icon names as vis doesn't understand this :(

**Comment by tobibeer** [comment]
But you could have an object to make a lookup... it's just, as a user, that is so much more preferable.

**Comment by felixhayashi** [comment]
Yes, I agree but I don't want to be the one spending time on creating
this huuuge hashmap and also keeping it up to date.

I wish there was a maintained font awesome plugin that adds a function
to tw like `$tw.fa.getUnicode(iconName)`.

Both, yours and thediveos FA plugins do not include such a function :(

**Comment by tobibeer** [comment]
> Both, yours and thediveos FA plugins do not include such a function :(

That's because they're nothing but a plain css font. ;-)
Perhaps there's some way to add variable to the global scope, e.g. ``$fa``

**Comment by felixhayashi** [comment]
@jfontany did my instructions work for you?

I'll close this issue now.

**Comment by jfontany** [comment]
They did, thanks. :)
