### ISSUE TITLE
Annoying behaviour: Nodes sometimes float far far away

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#177]
This happens because the central gravity is set to almost zero to ensure visjs support nodes (smooth edges) are not drawn to the center. However, this is very annoying, especially when:

* new nodes are added because they match a filter
* when floating mode is enabled, nodes are displayed too far outside.

This is an issue that has been around since day one and it should be solved.

**Comment by tobibeer** [comment]
You turned it off by default, right? I was also wondering the other day how come the plane is flying in circles. :D
