### ISSUE TITLE
Enhance export image dialog

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#178]
A the moment, the user can trigger a download dialog to save the image to his/her drive.

Enhancements would include:

* Save the image as image-tiddler in his/her wiki
* Use the image as placeholder image in static mode
  * a solution for #176

**Comment by felixhayashi** [comment]
@erlanger Ok, I implemented this now.

Steps:

![2015-10-09 15 23 19](https://cloud.githubusercontent.com/assets/4307137/10394844/05285ee8-6e9a-11e5-83c1-351a998bdf1b.png)
![2015-10-09 15 23 33](https://cloud.githubusercontent.com/assets/4307137/10394849/08a4de8e-6e9a-11e5-8154-3e059086d513.png)

### Export (note when you do mouse over it says "static")
![2015-10-09 15 27 00](https://cloud.githubusercontent.com/assets/4307137/10394880/3e720564-6e9a-11e5-92bb-4a635a01e123.png)

**Comment by erlanger** [comment]
That is great! Good work and more than that, amazingly quick!!!

**Comment by felixhayashi** [comment]
> @felixhayashi That is great! Good work and more than that, amazingly quick!!!

Thanks and glad you like it :) Now you have to do the screenshots manually but it also gives you more control over what is displayed in the static export.

**Comment by tobibeer** [comment]
:+1: very good stuff, @felixhayashi

**Comment by myvolkov** [comment]
It dosen't work for me. I try do according your steps here https://github.com/felixhayashi/TW5-TiddlyMap/issues/178#issuecomment-146871532
1) There is no view title:
![notitle](https://user-images.githubusercontent.com/44474329/47591453-5333b280-d978-11e8-9532-e22c398f9d3c.png)
2) As I understand after snapshot saving it should apper here: ` $:/plugins/felixhayashi/tiddlymap/graph/views/[view]/snapshot` but no
![noview](https://user-images.githubusercontent.com/44474329/47591816-9cd0cd00-d979-11e8-8252-a9b8639c0453.png)
3) And as a result - no preview in static HTML
![nopreview](https://user-images.githubusercontent.com/44474329/47592094-8a0ac800-d97a-11e8-8706-e815d8825ef5.png)

Thanks for your work.

**Comment by felixhayashi** [comment]
Thanks @myvolkov, I created a dedicated ticket for this bug! #299
