### ISSUE TITLE
Find a suitable name for the plugin

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#18]
Taskgraph as a name makes the user think, this plugin is only for organizing tasks. However, with the help of the plugin, a user can

* Create mindmaps and quickly manifest ideas in tiddlers (wiki entries).
* Create task-dependency graphs to organize and describe tasks.
* Visualize topic structures to get an immediate grasp of topics and relations.

In general the user may create, visualize and describe any network-structure he/she has in mind.

So what name to choose?

**Comment by tobibeer** [comment]
TreePlugin
