### ISSUE TITLE
Option to add a background image to a map

### ISSUE THREAD

**Issue by joshuafontany** [felixhayashi/TW5-TiddlyMap#182]
Hi felix,

I'm still learning all the ins-and--outs of TiddlyMap and TiddlyWiki5. Something occurred to me that would extend the usability of the map/views a bit, and I can't see that it's been mentioned yet.

If you could set a background image (or other genreated Vis.js object), and then "pin" certain nodes to the background (or static X,Y locations) you could create robust visualizations of data, or present a location map in a unique way. The static "pinned" nodes would act as a Key for the map or graph, and you could hide or show dynamic/phsyics-driven clusters of linked nodes that are X-hops-away around the statically pinned nodes. I've looked at the Vis.js docs and it seems possible, but I'm not far enough into TiddlyWiki code to ponder how to make it happen. :D

As an example, think of a trail map or bus/train transit map with Tiddler-nodes describing each stop/location pinned to their X,Y location on the map.. Then each Location Node could be linked bus/train schedules, nearby businesses, etc, etc.

(As I said before, I'm going to be using TiddlyMap to "semantically map" some old-school D&D adventures - so you can see where this functionailty would be amazing for displaying and tracking a dungeon -or other location- with "rooms/keyed-locations", associated "location contents", "location traps", and "location monsters". Or an overland Hex Map with cities, towns, landmarks, etc.)

**Comment by felixhayashi** [comment]
Thanks for this vivid description :) So basically it boils down to the feature of adding a background image to the map right? Drawing multiple background images in a view would be too complicated but you could create different views each possessing a different background. Once #102 is completed (not sure when I find the time) then in your D&D game you could add a node with a portal or door icon which opens another map when clicked…

**Comment by joshuafontany** [comment]
Yup, one background image per view would be fine. Love the synergy with
#102 there, great idea.

**Comment by felixhayashi** [comment]
Hi @joshuafontany seems like this will be added along with #102 in the next release (not sure when it is released though).

I'll try to add a little example in the docs at http://tiddlymap.org to demonstrate how to use both features.

It would be nice, if you could post a link here when you are done creating your D&D RPG adventure (if it is publicly available).

-Felix

**Comment by felixhayashi** [comment]
Preview: 

![2015-10-30 12 33 06](https://cloud.githubusercontent.com/assets/4307137/10845012/a8d13c84-7f04-11e5-80f6-84b6ff32d11e.png)

**Comment by joshuafontany** [comment]
Brilliant. This really opens up a lot of possibilities for me, thanks a lot
@felixhayahi! I'll have to really dive into TiddlyMap this weekend and get
my demo-adventure characters & locations database together. :D

**Comment by felixhayashi** [comment]
> Brilliant. This really opens up a lot of possibilities for me, thanks a lot @felixhayahi!

Thanks @joshuafontany. you are welcome.

>  I'll have to really dive into TiddlyMap this weekend and get my demo-adventure characters & locations database together. :D

I hope I can upload the new release (v.0.10.0) tomorrow (saturday) then – it still needs some testing.

**Comment by tobibeer** [comment]
brilliant @felixhayashi ...love the example :-)

**Comment by felixhayashi** [comment]
> brilliant @felixhayashi ...love the example :-)

Much thanks @tobibeer. I really got into the mood when creating this map ;)

@joshuafontany I won't be able to upload the TiddlyMap update this weekend, too much to do at the moment. I will, however, release it at some time in the next week.
