### ISSUE TITLE
Node Style Based on Edges

### ISSUE THREAD

**Issue by tgrosinger** [felixhayashi/TW5-TiddlyMap#183]
Is it possible to assign a node style based on the edges the node has? For example,

tgrosinger --Is A--> Person

I would like tgrosinger to be displayed as a Person node because it has an `Is A` edge connecting it to `Person`.

I found [some info](http://tiddlymap.org/#Node%20and%20edge-type%20filters) about node filters, but couldn't get this particular use case to work.

**Comment by felixhayashi** [comment]
Hi @tgrosinger 

@tobibeer asked a similar question (#164). While I agree that such a feature would make much sense, it is quite a complex task, would be computional intensive (multi level style inheritence A is a B is a C …; recursion checks to prevent people doing inheritence cycles) and would require a complex user interface (which edges define inheritence? Which inheritence has precendence?).

So this feature is definitely out of reach :(

**Comment by tgrosinger** [comment]
Ah darn, but definitely not surprising. I can imagine it gets quite complicated.
Thanks for the response!
