### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by jho1965us** [felixhayashi/TW5-TiddlyMap#191]
The "here" link of following text is broken

> **Drag'n'drop installation / Standalone installation**
> Please follow the instructions given here

**Comment by tobibeer** [comment]
Should probably point to:

http://tiddlymap.org/#Installation

**Comment by felixhayashi** [comment]
Yes, should point to http://tiddlymap.org/#Installation
Thanks @jho1965us for reporting!
