### ISSUE TITLE
Allow adding node information (text/tags/fields) when creating a node

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#192]
When creating a new node in TiddlyMap, it is often annoying that the "create node" dialog only allows the title to be entered nothing else. This forces a user who wants to immediately enter some text/tags/fields to open the node aftewards to add more information.

* It would be nice if the user could have mask that allows adding node information already in the dialog
* Moreover, a dropdown of tiddlers that serve as templates would be nice (related to #171)

**Comment by felixhayashi** [comment]
Will be nice…

**Comment by felixhayashi** [comment]
Some screenshots…

<img src="https://cloud.githubusercontent.com/assets/4307137/11702580/1e93a9fa-9ed8-11e5-8eea-527114a02e7f.png" width="23%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/11702583/1e9a8dd8-9ed8-11e5-8e64-a1c6d7e162ef.png" width="23%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/11702581/1e939d48-9ed8-11e5-9222-f175c2fcb4b7.png" width="23%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/11702582/1e94c5ec-9ed8-11e5-9e44-23c3dba5bc44.png" width="23%"></img>

**Comment by danielo515** [comment]
Cool! definitively a time saver!

**Comment by felixhayashi** [comment]
Hi @danielo515 

> Cool! definitively a time saver!

Glad you like it :)
