### ISSUE TITLE
Add more keyboard shortcuts

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#197]
Existing shortcuts: [Copy & paste nodes between views](http://tiddlymap.org/#Copy%20%26%20paste%20nodes%20between%20views)

More shortcuts planned:

* Edge creation via keyboard:
  * `ctrl+1` Specify node to serve as "from" part
  * `ctrl+2` Specify node that serves as "to" part
  * Ones "from" and "to" nodes are specified, the edge dialog is opened where the type may be specified.
* Searching (zooming/focussing) a node
  * When the canvas is selected or the widget has focus, `ctrl+f` opens the "zoom on node" dropdown. Another `ctrl+f` or `ESC` closes it.
* Opening a tiddler
  * `ENTER` will open the tiddler corresponding to the selected node.
* Full- and halfscreen
  * `F11` will toggle fullscreen mode
  * `F10` will toggle fullscreen halfscreen mode (if possible)

More ideas welcome

**Comment by tobibeer** [comment]
@felixhayashi, big fan of keyboard support

**Comment by felixhayashi** [comment]
Yeah, me too ;)

Here is what is now possible: http://tiddlymap.org/#Keyboard%20shortcuts

![2016-01-02 17 01 10](https://cloud.githubusercontent.com/assets/4307137/12075049/2db3cd04-b173-11e5-80dd-294967428b14.png)

**Comment by mtekman** [comment]
### Quick node insertion

 * Press `n` and then `n` again to insert a node either under the mouse or at a free location in the view
        * Spawns a tiddler which user can edit without having to use the mouse between node placement and editing the associated tiddler.

 * Press `n` and then `e` to initiate edge drawing mode with the *from* anchored on the currently highlighted node.
     * Hopefully this would compliment and not conflict with the existing `ctrl+1` and `ctrl+2` shortcuts
