### ISSUE TITLE
Extract builtin edge types into modules

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#198]
Hello!

I'm using Tiddlymap for a project I'm doing, and it's been absolutely fantastic. In particular, the tw-body:links edge types have been super useful in conjunction with another plugin that I wrote. However, I found myself needing the same kind of edge types for transclusions.

And so I made them. And it works just fine. I started by writing a wikimethod module-type in my plugin that creates the getTiddlerTranscludes method, which is exactly like getTiddlerLinks... only transcludes. The problem is, in order to get tiddlymaps to use this, I had to modify the shadow tiddler: `$:/plugins/felixhayashi/tiddlymap/js/Adapter` and then add a system tiddler: `$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/tw-body:transclude`.

Neither of these are in my plugin namespace.

I'm not suggesting that we add the **tw-body:transclude** edge type to tiddlymap. It's super esoteric. But I think Tiddlymap could be made more extensible by allowing other plugins to create custom-behaving edge types if it did two things:
1. Instead of looking in the `$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes` namespace for built-in edges. If custom-behaving edge types were to instead have their own module-type. This way, people extending TiddlyMap with new edge types could add their edges within their own plugins and thereby integrate with TiddlyMap automatically without futzing about with tiddlymap.
2. If Tiddlymap were to abstract out all the custom behavior of the custom edge-types like **tw-body:links** and **tw-fields** into these modules, then anyone adding new edge-types wouldn't have to modify `$:/plugins/felixhayashi/tiddlymap/js/Adapter` to add their special handing.

I think this would be a nifty improvement. I'm not sure how feasible it is though. I'm still pretty new to Tiddlywiki. But I can totally see other people wanting to create their own dynamic edge-types. If it were abstracted out like that, anyone could do whatever they wanted.

By the way, if anyone is curious how I modified `$:/plugins/felixhayashi/tiddlymap/js/Adapter`, all I added was...

```
if(!s||s["tw-body:transclude"]) {
    g["tw-body:transclude"]=$tw.wiki.getTiddlerTranscludes(a)
}
```

... inside of **_addBodyAndFieldEdges**, right after the code that handles tw-body:links. It was so easy, I worked entirely on the uglified code, which is what gives me high hopes for this improvement.

-Thanks for reading,
Flibbles

**Comment by felixhayashi** [comment]
Hi @flibbles 

> I'm using Tiddlymap for a project I'm doing, and it's been absolutely fantastic.

Glad to hear that :)

> And so I made them. And it works just fine. I started by writing a wikimethod module-type in my plugin that creates the getTiddlerTranscludes method, which is exactly like getTiddlerLinks... only transcludes. […] I'm not suggesting that we add the tw-body:transclude edge type to tiddlymap. It's super esoteric.

That's not esoteric, its quite reasonable actually. Transcludes are important relationships, I often thought a method would be nice to know where a tiddler has been transcluded. Maybe do a pull request in the TW repo, so your method gets integrated into the core.

> I had to modify the shadow tiddler: $:/plugins/felixhayashi/tiddlymap/js/Adapter and then add a system tiddler: $:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/tw-body:transclude.
> […] all I added was...
> if(!s||s["tw-body:transclude"]) {
    g["tw-body:transclude"]=$tw.wiki.getTiddlerTranscludes(a)
}

Yes, the adapter class is the right place for this modification, very well spotted :) it's only a bit problematic as you won't receive updates for this tiddler anymore and function calls may break soon when you upgrade TW. Moreover,  your code will break soon because the js-uglyfier may change variable names from `s` and `g` to something else. 

So what I'll do for now, is to add your function as an unofficial hack into the adapter class so you can work with TiddlyMap without needing to override the adapter. I'll leave this hack active until a better solution is available.

> But I think Tiddlymap could be made more extensible by allowing other plugins to create custom-behaving edge types if it did two things:

> 1. Instead of looking in the $:/plugins/felixhayashi/tiddlymap/graph/edgeTypes namespace for built-in edges. If custom-behaving edge types were to instead have their own module-type. This way, people extending TiddlyMap with new edge types could add their edges within their own plugins and thereby integrate with TiddlyMap automatically without futzing about with tiddlymap.

Hmm **this is already possible**. Just because edges have the prefix `$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes`, which looks like they belong to the TiddlyMap plugin, it doesn't mean your plugin can't include tiddlers with this prefix. So you should be able to ship your own edge-types just by giving them this prefix.

That said, there are some very specific reasons, why I originally decided to store edges below a path instead of using a type or a flag to denote edge types.

1. To ensure that no dublicate edge types exist (with the same name) as titles in tw are unique
1. Faster retrival of specific edges because the title is the index

**However,** in the meantime, several arguments came up which made me think that this datastructure is suboptimal and it makes more sense to mark tiddlers that are edge types using [content types](http://tiddlywiki.com/#ContentType). This would allow users to declare any tiddler as edge type and would be a huge step toward treating edge types as first class citizens (since they could be even included as nodes in the graph and are not forcably locked up behind a long system-tiddler prefix). But I need time for this refactoring since much depends on the current implementation. But should be hopefully done before June. Anyhow, this should not bother you since you can, as said above, specify edge-types in your plugin by giving them the edge type prefix as described above and I'll add your function into the current code.

> 2. If Tiddlymap were to abstract out all the custom behavior of the custom edge-types like tw-body:links and tw-fields into these modules, then anyone adding new edge-types wouldn't have to modify $:/plugins/felixhayashi/tiddlymap/js/Adapter to add their special handing. I think this would be a nifty improvement. I'm not sure how feasible it is though. I'm still pretty new to Tiddlywiki. 

I agree, this makes sense. TiddlyMap needs to consider user-created edge-type handlers.

I'll deal with this properly once I find the time, i.e. create a module where the user can specify:

1. a function for retrieving the edges per Tiddler (like your `getTiddlerTranscludes`).
2. functions to specify how to process edges of the type in case of deletion or modification (`Adapter.prototype._processEdge`).

However, I am pretty busy in in the next months and this is a complicated task that requires much thinking and lots of carefull refactoring, so I am sorry to say but don't expect big things happening in the next months. Yet, I hope I can come up with some results before June ;)

-Felix

**Comment by felixhayashi** [comment]
@flibbles Ok I updated Adapter.js (https://github.com/felixhayashi/TW5-TiddlyMap/commit/38f9ab69d7680aa91a2ad5452f8f6b7d2016dcc8). So please remove the tiddlymap plugin (simply updating doesn't work as I didn't increment the version number) and add it again and your wiki. Then `tw-body:transclude` type should be acknowledged along with `$tw.wiki.getTiddlerTranscludes(a)`.

-Felix

**Comment by flibbles** [comment]
Thank you!

I've updated to the latest release, and it's working fine. I'll also go ahead and propose my getTiddlerTranscludes method to Tiddlywiki5, as soon as I figure out this Node.js stuff. That'll probably happen this week as soon as I get a moment.

I'll look forward to the changes you might make, but it's by no means a requirement anymore with the hack, and with my finally bothering to clone the source. I know I already have other edge-type requirements, but I'll write them myself now that I know the Tiddlymap code somewhat. I'll make a pull request if I think my new types would be helpful to anyone else.

-Flibbles

**Comment by flibbles** [comment]
Actually, hold on. Not sure if I should close this. That was dumb.

**Comment by felixhayashi** [comment]
Hi @flibbles 

>I've updated to the latest release, and it's working fine. 

Great 

> I'll also go ahead and propose my getTiddlerTranscludes method to Tiddlywiki5, as soon as I figure out this Node.js stuff.

Yes, I would suggest that.

> I'll make a pull request if I think my new types would be helpful to anyone else.

If you plan to make a PR, please create an issue first before making the actual PR so it can be discussed beforehand.

> Actually, hold on. Not sure if I should close this. That was dumb.

Yap, better leave it open ;)

**Comment by flibbles** [comment]
Hey, it's me. I'm back. I've been plugging away on my project and I've got 500+ nodes now. The tw-filter types are great and I use them everywhere.

I've made more personal alterations to the code:

1. I added code for tw-filter for drawing edges.
```javascript
Adapter.prototype._processFilterEdge = function(tiddler, edge, type, action) {
  if(action !== "insert") {
    // if it's not insert, it's delete. And we can't delete from filters
    return null;
  }

  // get the name without the private marker or the namespace
  var name = type.name;

  var tObj = utils.getTiddler(tiddler);
  var filterValue = tiddler.fields[name] || "";

  // transform
  var toTRef = $tm.indeces.tById[edge.to];

  if (toTRef.indexOf(" ") >= 0) {
    toTRef = "[[" + toTRef + "]]";
  }
  if (filterValue.length > 0) {
    toTRef = " " + toTRef;
  }
  filterValue = filterValue + toTRef;

  if(!type.exists()) {
    type.save();
  }

  // save
  utils.setField(tObj, name, filterValue);

  return edge;
};
```
and a little connecter bit in _processEdge to hook that up. This lets me draw edges for filters, since technically adding a tiddler title to the end of any filter (sometimes in double brackets if it has a space) is always legal if the filter is legal.
2. The other thing I've done is change `Adapter.prototype.makeEdge` with the following code:
```javascript
if(utils.isTrue(type["show-label"], true)) {
    // This section was altered by Mythos.
    var toTRef = $tm.indeces.tById[to];
    var toObj = utils.getTiddler(toTRef);
    var label_content = toObj.fields[label];
    //edge.label= $tw.wiki.renderText("text/plain", "text/vnd-tiddlywiki", label_content);
    edge.label = label_content;
    // edge.label = label;
}
```
This makes it so instead of displaying the same word like "links to" for all of a certain edge type, it treats the label as specifying a field in the `edge.to` to display. It looks kind of like this:

![example](https://cloud.githubusercontent.com/assets/205465/16511523/e9c189f8-3f1e-11e6-8a55-809851e1beee.png)

Both of these changes would be pretty seemless if edge types were modules. I wouldn't have my personal adapter.js file, but you're already aware of this. I'm really only mentioning them to see if there's any interest in opening another issue to discuss making these features. The tw-filter one is _mostly_ intuitive... mostly. The custom edge labels one is such a hack it's leaving furballs laying around, but a more generic version of dynamic edge labels might be of interest to other people.

Either way, TiddlyMap has been working great for me, and even though I'm making some changes to the source to make it work for me, they've been easy changes. Just cause I've been silent for six months doesn't mean I haven't been benefiting from this project's work.

Thanks for providing this plugin.
-Flibbles

**Comment by flibbles** [comment]
Okay.

Okay okay okay okay.

I'm taking a crack at this. I think I'm familiar enough with TiddlyWiki and TiddlyMap to do this at least _mostly_ right. I'll have some code to show on my own fork in a few days which can be used to outline a solution and discuss design.

**Comment by flibbles** [comment]
Okay. I have a [working repository](https://github.com/flibbles/TW5-TiddlyMap) where edges are modules. It works just fine, and it lets me install my plugin edge types beautifully. It does need some cleaning up before committing, but I'm reaching out now to discuss design decisions.

There are a ton of tiny changes to make it work but there are 4 major parts where things changed.

## The modules

First. I created a module for each built-in edge type namespace: tw-body, tw-field, tw-list, and tw-filter.

Here is what tw-field looks like:

```javascript
/*\

title: $:/plugins/felixhayashi/tiddlymap/js/EdgeType/tw-field
type: application/javascript
module-type: tmap.edgenamespace

@preserve

\*/

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

/*** Exports *******************************************************/

exports["tw-field"] = TwField;

/*** Imports *******************************************************/

var EdgeType = require("$:/plugins/felixhayashi/tiddlymap/js/EdgeType");
var utils    = require("$:/plugins/felixhayashi/tiddlymap/js/utils");

/*** Code **********************************************************/

/**
 * @constructor
 */
function TwField(id, data, options) {
  // call the parent constructor
  EdgeType.call(this, id, data, options);
}

// !! EXTENSION !!
TwField.prototype = Object.create(EdgeType.prototype);
// !! EXTENSION !!

/**
 * This method handles insertion or deletion of an edge that
 * is stored inside a field that can only hold one connection.
 *
 * @param {Tiddler} tiddler - A tiddler reference or object that
 *     represents the from part of the edge and will be used as store.
 * @param {Edge} edge - The edge to be saved. Required properties: `to`.
 * @param {string} [action=delete] - Either "insert" or "delete".
 * @return {Edge} The processed edge.
 */
TwField.prototype.processEdge = function(tiddler, edge, action) {

  if(!edge.to) return;
  var toTRef = $tm.indeces.tById[edge.to];
  if(toTRef == null) return; // null or undefined

  var val = (action === "insert" ? toTRef : "");

  // only use the name without the private marker or the namespace
  utils.setField(tiddler, this.name, val);

  if(!this.exists()) {
    this.save();
  }

  return edge;

};

/**
 * This is an overload of the EdgeType base method. That has more details.
 */
TwField.prototype.addEdge = function(tObj, toWL) {

  var fieldValue = tObj.fields[this.name];

  return fieldValue? [ fieldValue ]: null;

};
```

It declares itself as a `tmap.edgenamespace` module-type, which tiddlywiki will automatically group together with others like it. It takes care of all field-specific stuff regarding tw-field. lib.adapter.js no longer needs code to manage tw-field explicitly.

## EdgeType is the base of all those modules

EdgeType has a the functions `processEdge` and `addEdge` which are overloaded by the modules. (Currently, `processEdge` is doing the work that the tmap namespace should do. This is part of the stuff that'll need cleaning up once a design is settled on.)

More importantly. EdgeType has a factory method now.

```javascript
EdgeType.getEdgeInstance = function(id, data, options) {

  if(id instanceof EdgeType) return id; // bounce back!

  var root = $tm.path.edgeTypes;

  var parts = EdgeType._getIdParts(id, root);
  if(!parts.name) return new EdgeType("tmap:unknown");

  // This is where we gather all the tmap.edgenamespace modules to see
  // If we've got a direct match. If not, for now we proceed with the old
  // Edge type constructor method.
  EdgeType.namespaces = EdgeType.namespaces || $tw.modules.applyMethods("tmap.edgenamespace");

  var customEdgeType = EdgeType.namespaces[parts.namespace];
  if(customEdgeType) {
    return new customEdgeType(id, data, options);
  }
  // Rely on the old method for now.
  return new EdgeType(id, data, options);
}
```
This takes care of looking at the namespace and finding the correct module to use. All through the code, anything that used to use `new EdgeType(...)` now uses `EdgeType.getEdgeInstance(...)`. I'm not sold on that function name, by the way.

## lib.adapter.js has cleaned right the hell up.

the adapter is no longer responsible for the following methods

* _processTmapEdge
* _processListEdge
* _processFieldEdge
* _processFilterEdge

This cuts out about 150 lines out of lib.adapter's beastly 1300 line file. Also, it no longer has that `if...elseif....elseif...else` in _processEdge. Instead it just calls a single polymorphic method on the edgeType. The only part that's still dirty is the following:

```javascript
Adapter.prototype._addBodyAndFieldEdges = function(edges, tObj, toWL, typeWL) {

  // never assign a default to the typeWL. if it is not assigned it means
  // all types!! NEVER: typeWL = typeWL || utils.makeHashMap();
    
  var fromTObjFields = tObj.fields;
  var fromTRef = utils.getTiddlerRef(tObj);
  var indeces = $tm.indeces;
  var maETyFiNa = indeces.maETyFiNa; // magic edge-type field names
  var refsByType = utils.makeHashMap();
  var edgeTypesOfInterest = (typeWL || indeces.allETy);
  
  // 1) Prepare
  
  for(var edgeTypeId in edgeTypesOfInterest) {

    if(edgeTypeId.indexOf("tw-body:") == 0) {
      var edgeType = indeces.allETy[edgeTypeId];
      refsByType[edgeTypeId] = edgeType.addEdge(tObj, toWL);
    }
  }

  for(var f in fromTObjFields) {
    
    var type = maETyFiNa[f];
      
    if(!type || (typeWL && !typeWL[type.id])) continue;
    
    refsByType[type.id] = type.addEdge( tObj, toWL );
  }
  
  if(!refsByType) return;
  // 2) Add edges to list
  ...
```
This is still cleaner than before, but it could be even cleaner. I'm just confused as to why the code is iterating through `maETyFiNa` and then looking for the corresponding type, instead of iterating through `typeWL` or `indeces.allETy` and then looking for the corresponding field. If we do it the latter way, this method becomes a single for loop. `_addTmapEdges` will also probably fold in.

## tw-body takes it a step farther with modules

`tw-body:link` is the only built in tw-body edgeType, but I personally made several other tw-body types, and I think others may as well. Which is why it's constructor looks like this:

```javascript
// This is near the top
var bodyMethods = $tw.modules.applyMethods("tmap.edgenamespace-body");

function TwBody(id, data, options) {
  // call the parent constructor
  EdgeType.call(this, id, data, options);

  this.bodyMethod = bodyMethods[this.name] || function(tObj, toWL) {
    // Maybe this should throw an error instead?
    //throw new Error("Unsupported tw-body type: " + this.name);
    return [];
  };
}
```

What it's doing is looking at module-types `tmap.edgenamespace-body` for methods to use for sifting tiddler bodies.

the `Link.js` module looks like this:

```javascript

/*\
title: $:/plugins/felixhayashi/tiddlymap/js/EdgeType/tw-body/link
type: application/javascript
module-type: tmap.edgenamespace-body

@preserve

\*/

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

/*** Imports *******************************************************/

var utils    = require("$:/plugins/felixhayashi/tiddlymap/js/utils");

/*** Code **********************************************************/

/**
 * This specifies the functionality of the tw-body:link type.
 * Like all of tmap.edgenamespace-body, this is responsible for looking
 * into tObj and returning a list of tiddlerTitles that this tObj should
 * be linking to.
 */
exports.link = function(tObj, toWL) {

  var fromTRef = utils.getTiddlerRef(tObj);

  return $tw.wiki.getTiddlerLinks(fromTRef);
};
```

Very simple. I have a few other classes that look just like that. One for transcludes, one for other stuff of my own. I'm debating if returning a function is correct, or if it should derive from tw-body.

# Further notes

...And that's it. This code works on my 400+ project which uses more than a dozen types of edges. Besides making the code more modular and extensible, I think it makes it easier to understand, particularly since lib.adapter.js is smaller.

Things left to do...
* Between the EdgeType constructor and factory method, there's some redundancy. I'll clean that up after and discussion we have.
* There is no `tmap:` edgeType, and there should be. Unfortunately, the code isn't laid out perfectly for that. the `tmap.edges` field is divided by edgeID. It would be much more helpful if it were divided by edgeTypes instead. That way each edgeType wouldn't have to reparse that field when its polymorphic `addEdge` method is called. I _can_ make it work now, it just won't be as efficient as the code is now. Probably not a big deal.
* This entire thing is just the barebones of making edges modular. There's still more those modules could be responsible for, such as label naming and id creation, but this is a good start I think.
* Let me know if any of my naming conventions don't gel with you. For the module-types and design, I tried to mimic Tiddlywiki as much as possible.

All my code is available [here](https://github.com/flibbles/TW5-TiddlyMap) if you want to look at it.

Thanks,
-Flibbles

**Comment by felixhayashi** [comment]
Hi @flibbles,

Many thanks for your contributions! That is a lot to read and I cannot do it today, but I'll read it this week and respond :)

-felix

**Comment by felixhayashi** [comment]
Hi @flibbles,

sorry for responding so late. very interesting additions. I still need some time to get my head wrapped around this. generally speaking, I am very open to this idea and it is great that you already shared so much code! very cool.

I'll respond in greater detail as soon as I find the time.

Greetings and thanks.

-felix

**Comment by flibbles** [comment]
Feel free to bounce any questions you have off me. Like I said, the code isn't perfect yet. More improvements could be made. I just didn't want to change things too much without feedback.

**Comment by felixhayashi** [comment]
Hi @flibbles,

I was able to spend a few hours today on this one :) Since I hadn't spend much time on TiddlyMap in the past months, your code was extremely helpful to me and I was able to quickly identify the critical parts in the code that need to be changed. Although my solution will differ a tiny bit from yours, I am sure it will suit your needs.

Before I'll publish a new version that includes the update for this issue, I'll upload it to develop branch and do a pull request to the master so we can (if you want) discuss the changes.

Not sure when I can finish this but I am on it and will inform you once I am done.
Thanks again for this ticket and your code suggestions!

-Felix

**Comment by flibbles** [comment]
Sure. take your time. I feel that there's more that can be done, actually. The tmap edge types aren't managed by this new system, but they could be, and I think they should. The adapter could be made completely agnostic to the edge type. I didn't do this myself yet because I was a little worried about tearing down ``maETyFiNa`` without knowing what it does.

Also, the ``tmap.edges`` field doesn't really lend itself to this idea as it is. It's sorted by edge ID instead of by edge type, which means each tmap type would have to sort through it again. But I realize changing the structure of ``tmap.edges`` would mean making some non-backward compatible changes.

So yeah, I'd be up for discussing it. I know that what I presented isn't a final product. There's still work to do.

Also, to clarify. I have _one_ project with _400_ nodes, not four hundred projects. That would be insanity.

**Comment by flibbles** [comment]
By the way, if your dissatisfied with the way I went about this solution, you can let me know what you would rather see and I can adjust my code. That way, you might not have to recreate the solution yourself (in case you're not finding any time).

**Comment by felixhayashi** [comment]
Hello @flibbles 
sorry for the bad communication on my side. I uploaded a solution to the develop branch two weeks ago, but I was not fully satisfied with some details and interfaces and I didn't want to bother you with an incomplete solution, which is why I did not respond so far. But you can have a look at it (https://github.com/felixhayashi/TW5-TiddlyMap/commits/develop) and especially at the files in `src/plugins/felixhayashi/tiddlymap/js/EdgeTypeSubscriber/`.

My solution is similar to yours, except that it doesn't place too much logic into the EdgeType.

Anyway, I hope to find the time soon to improve and eventually merge the code I already uploaded in the dev branch into the master. If you have any suggestions or crititcism, please tell me or comment on the code.

best wishes
felix

**Comment by flibbles** [comment]
Hey @felixhayashi 

Thanks for letting me know. I've looked over the new code and it's definitely much more polished than my "it-all-works-don't-touch-it" quality code I sent you. Your naming scheme makes more sense, it make better use of polymorphism, and it looks like it handles tmap edge types better than mine (which is not saying much. My project doesn't use tmap edges _at all_, or any namespaces that aren't "magic" in some way. So they might be broken for all I know). I'm looking forward to making my own plugins work with the _official_ TiddlyMap again, instead of my half-assed fork.

That being said, there are two major questions I have about your implementation, which may just stem from my misunderstanding.

## This subscription thing

I think I understand what this is trying to solve, but it's a little redundant. I think the solution might be cleaner without it (if possible). It looks like it's solving four problems

1. "Fallback". Specifying which EdgeTypeSubscriber is used when a new EdgeType doesn't correspond to any subscriber, with tmap specified as the default. It's a neat idea, but if someone were to want to _change_ the default in some way, they can't just put "fallback" in the subscription of their own module. This results in undefined behavior. The one that the Registry takes is whichever one Tiddlywiki loads second. Since there can only be one default, wouldn't it make more sense for it to be specified in startup.environment? Or maybe in a configuration tiddler so it can be overridden?
2. "Ignore". Yeah... Transclude only exists on my machine, I know. It creates this weird need. It might be worth just junking. With this spiffy new module solution, I don't need to monkey patch my own anymore, and I think I'm the only one using it. If you _do_ want to keep it, I recommend this solution: Wrap the entire module in the ``if(typeof $tw.wiki.getTiddlerTranscludes === "function") { ... }`` bit. I'm pretty certain all wikimethods will be loaded before that module would be called. If getTiddlerTranscludes isn't there, then it's not added to its ``exports`` at all.
3. "Name". Yeah, the tw-body types make it weird. I solved it by breaking it up into another type of module-type managed by the tw-body class. I might be showing my ignorance with this one, but the name part of the edgeType ID struck me as a parameter while the namespace delineated which edgeTypeHandler class to use. But it looks like you're using both the name and namespace to determine which RefEdgeTypeSubscriber to use. Might it be more consistent of "tw-body: anything" be managed entirely by the "LinkEdgeTypeSubscriber"? It would mean that user-created types like "tw-body: banana" would return a not-implemented exception instead of just treating it as a default tmap type... but shouldn't it? tw-body is a reserved word in TiddlyMap. Also, if tw-body handled all body types, the registry wouldn't need separate lists for FullType and Namespace. It could be more agnostic.
4. "Namespace". If the other stuff is dropped, then I think this can be done away with too. It's always the same as the name in module.exports, so the SubscriberRegistry will already know it (or whatever ultimately calls $tw.modules.applyMethods). There are only a few cases where EdgeTypeSubscribers need to know this, and I think the code might be cleaner if those cases are done away with (I explain more below). In the meantime, this single bit of data could just be passed along as an argument in the constructor, and the Registry can pass it in (``var subscriber = new (subscribers[id])(id);``).
5. "Magic". This is all that would be left. It's only used so the caretaker can update ``maETyFiNa``, which leads me to my second question...

## maETyFiNa (Magic Edge-type Field Names)

I'm not sure what this is for. In my fork, I was able to do away with it entirely (But again, I can't say whether that works with tmap types since I don't use them). I feel like there must be some bug or something maETyFiNa is addressing that I don't know about.

Looking at it again, I _think_ I see why I could, and why you still have it. I was able to get rid of it because I created an "EdgeTypeSubscriber" (or my equivalent of it), for every single edge type. And my EdgeTypeSubscriber took the _name_ part of the ID as a constructor argument. So if I had: "tw-list: tags", and "tw-list: references". allETy would have two EdgeTypeSubscriber instances--one for each (in my case, it was EdgeType itself, which is why it worked more naturally for me). Once instance would say its ID was "tw-list: tags", the other "tw-list: references". They were both ListEdgeTypeSubscribers, just made with different arguments.

So I didn't have to deal with maETyFiNa. I just took allETy (filtered by typeWL), and told each one to _do its thing_. The "tw-list: tags" instance would go straight for the ``tags`` field. I never had to iterate through the _magic_ fields.

I think this would be much cleaner. I guess since you separated EdgeTypeSubscribers from EdgeTypes, you could pass a subscriber instance to EdgeType maybe in the ``updateEdgeTypeIndeces`` method.


**Done**

Wow. I just typed a lot and it's late. Don't get me wrong. Your code is much cleaner than mine was. I'm only bringing these points up because my project (and my eventually published plugin) will heavily integrate with TiddlyMap, so I have a vested interest. My knowledge of TiddlyMap is still pretty flakey though, so I hope my questions are at least valid.

Anyway, thanks for reading, and thanks for implementing this. It makes my life much easier.

Flibbles

**Comment by flibbles** [comment]
Actually, scratch what I said about "ignore". The $tw.wiki.getTiddlerTranscludes is not guaranteed to be loaded before your "startup.caretaker.js" is executed.

I suppose another solution would be to make its method return immediately if it doesn't detect the needed method. Sort of like...

```javascript
TranscludeEdgeTypeSubscriber.prototype.getReferences = function(tObj) {
  var  (typeof $tw.wiki.getTiddlerTranscludes === "function") {
    return $tw.wiki.getTiddlerTranscludes(tObj.fields.title);
  }
}
```

I'm sure it could be cleaner, or that there are better solutions, but at least this fully encapsulates transclude edges. The rest of TMap doesn't have to think about whether a subscriber should be ignored or not.

Your call obviously. I'm just nosy.

**Comment by felixhayashi** [comment]
Hi @flibbles 

thanks for your thoughts on this!

> but if someone were to want to change the default in some way, they can't just put "fallback" in the subscription of their own module. This results in undefined behavior.

Yes, good point. The fallback should be deterministically overridable. I think I'll go with your advice and put this into the configs.

> With this spiffy new module solution, I don't need to monkey patch my own anymore

yeah you are right. I just included this for backwards compatibility reasons.

> "Namespace". If the other stuff is dropped, then I think this can be done away with too. 

Hmm but I need a distinction between `name` and `namespace` because otherwise a user could not register a subscriber that is just meant to react to namespaces.

> Might it be more consistent of "tw-body: anything" be managed entirely by the "LinkEdgeTypeSubscriber"?

Sorry, I did not quite understand this one :(

>  I feel like there must be some bug or something maETyFiNa is addressing that I don't know about.

This thing only exists to improve the speed of TiddlyMap.
* It allows us to quickly skip fields that do not contain edges
* It gives us easy access to the edge type objects so we do not constantly have to recreate them.

> My knowledge of TiddlyMap is still pretty flakey though, so I hope my questions are at least valid.

Your points are very insightful and It's nice to read about some pros and cons of my solution. thanks a lot!

best wishes
-felix

**Comment by flibbles** [comment]
Sorry for the late response.

All I was trying to say with the tw-body: anything stuff is that it seems like you could let the EdgeTypeSubscriber classes do more of the lifting. You've just about extracted everything into subscriber subclasses, but you still have this registry thing that's having to manually look up the subscriber type based on the name and namespace of each edge type. On top of that, the registry is maintaining separate lists for the same stuff. It looks first for a match against "namespace: name", and then "namespace: *", and then just returns the default.

It works, and maybe it's the best solution. It just seems like you could take better advantage of the polymorphic behavior.

What I was trying to say was: instead of having a single instance of each Subscriber, create a new instance for each EdgeType. For a constructor argument, they get the "name" and "namespace". That way, each instance would know exactly what fields to look at to process edges, and you don't have to maintain a list of magic field types, or multiple lists in a registry.

All you'd need is for each edgeType in $tm.indeces.allETy to have their own instance of an EdgeTypeSubscriber. In getEdges, you'd just have to go down the list of $tm.indeces.allETy, sort of like:

```javascript
for(var edgeTypeId in $tm.indeces.allETy) {
  var edgeType = $tm.indeces.allETy[edgeTypeId];
  refsByType[edgeTypeId] = edgeedgeType.subscriberInstance.loadEdges(tObj, toWL);
}
```

So for example. If a graph had edge types:

* tw-body: link
* tw-body: transclude
* tw-list: tags
* arbitrary-namespace: foo

During set up, you'd create four EdgeTypeSubscriber classes and hand them to the edges in $tm.indeces.allETy:

* `new BodyEdgeTypeSubscriber("tw-body", "link")`
* `new BodyEdgeTypeSubscriber("tw-body", "transclude")`
* `new ListEdgeTypeSubscriber("tw-list", "tags")`
* `new TmapEdgeTypeSubscriber("arbitrary-namespace", "foo")`

But not _quite_ like that, because I know there's a part to the EdgeType Id I'm forgetting.

So this is just what I'm suggesting. Feel free to ignore this. But do you see what I mean? Each EdgeTypeSubscriber instance would know exactly what field or $tw.wiki method it needs to use to derive its edge data.

What I mentioned `tw-body: anything`, what I was trying to point out is that this method requires only "namespaces" to correlate to EdgeTypeSubscriber classes, not "namespaces: names", so there'd have to be a BodyEdgeTypeSubscriber that could handle all possible "tw-body: *", either through a factory constructor, or another module-type like I tried in my initial solution. It would mean you couldn't just plug in any ol' tw-body: name though. `tw-body: randomstuff` would throw an exception instead of defaulting to the Tmap type.

Damn, I wrote a lot again. I hope this is clear. I haven't looked at the code in a few weeks. It's not all in my head right now. And just to clarify, the solution you already have would work just fine. I'm just pointing out what I think _might_ be more maintainable, but I know the codebase like you do.

-Flibbles

**Comment by felixhayashi** [comment]
Hi @flibbles 

sorry again for the late response, I finally found the time to consider your suggestions and give the code at the dev branch a refactoring.

This includes:

* Dropped the "fallback subscriber" thingy in favor of "priotized" subscribers
  * This means multiple subscribers can be registered for the same edge type give
  * Subscribers with a higher priority get evoked earlier
  * Subscribers can decide to skip subsequent subscribers with a lower prio, otherwise, all subscribers that are capable of handling a type are called – this may be useful for e.g. logging or other stuff.
* removed the `maETyFiNa` index. I now use a [different strategy](https://github.com/felixhayashi/TW5-TiddlyMap/commit/518d55cd266fcffc21f6ea749391f2a189160964#diff-f3a4046333690b2d03ff7f38f3a35e69R33) (in alignment with your suggestion) where the subscriber get the edge types passed at the time it is created. This is quite close to what you proposed in https://github.com/felixhayashi/TW5-TiddlyMap/issues/198#issuecomment-249478252 ("This subscription thing / bullet point 4")
* I also dropped the "namespace" and "name" thingy in all subscribers.
  * Instead, each subscriber has a method named `canHandle(edgeType)`, which allows each subscriber to dynamically state whether it is able to handle the edge type or not.

I uploaded the code to develop and I am planning to push it to master next week after a bit of clean up. This time, I feel a bit better about the code :) Sorry for the delay.

-Felix

**Comment by flibbles** [comment]
Looks good. Also, good job removing all that end-of-line whitespace.

As far as I can tell, the whole ``canHandle``, ``priority``, and ``skipOthers`` paradigm is to deal with the "tw-body:bananas" situation. By that I mean "tw-body:link" gets picked up by the ``LinkEdgeTypeSubscriber``, while "tw-body:bananas" would get picked up by ``TmapEdgeTypeSubscriber``, which is completely unrelated, despite the two edgetypes having the same namespace. I guess this takes care of legacy issues, where existing TMap users might have made "tw-body:???" edgeTypes of their own that behave like Tmaps. Am I right? Was this your reasoning?

I still believe delineating EdgeTypesSubscribers by namespace would be cleaner, but I admit that wouldn't be backward compatible. ("tw-body:bananas" would throw an exception since the namespace give it to a hypothetical ``twBodyEdgeTypeSubscriber``, which would only know how to deal with ``link`` and ``transclude``)

Other than that one remark, it all looks good. I look forward to updating my own projects to using your new system!

**Comment by felixhayashi** [comment]
Hi @flibbles 

> […] I guess this takes care of legacy issues, where existing TMap users might have made "tw-body:???" edgeTypes of their own that behave like Tmaps. Am I right? Was this your reasoning?

Yes, this is one point, well analyzed :) But there is also another thought to that:

Say you want to write a TiddlyWiki "plugin" that includes its own custom LinkEdgeTypeSubscriber that does more fancy stuff than the current LinkEdgeTypeSubscriber. Now the first thought would be that this could be done by overwriting the "shadow" tiddler that comes with the original TiddlyMap plugin. This way of doing it, however, is indeterministic because it is unclear, which LinkEdgeTypeSubscriber module is eventually registered to the wiki's core – because two plugins both register this tiddler module. Now with `priority` and `skipOthers` you can solve this problem in a clean way: Simply give your handler a new name, e.g. `MyLinkEdgeTypeSubscriber` make `canHandle` return "tw-body:link", set the priority quite high (e.g. to 200) so it beats other handlers and the set `skipOthers` to true to avoid other link handlers to be called.

**Comment by flibbles** [comment]
All right. I have considered overwriting "tw-body: link" occasionally. It would be nice to be able to do that. I look forward to the changes going live.

**Comment by felixhayashi** [comment]
Hi @flibbles,

I finally pushed the code to master. sorry for the long and tedious discussion and the freuquent postponements. Your suggestions were helpful and I hope the final result suits your needs.

I upgraded the most of the codebase to ec6 so in case you plan to write your own subscriber, you can use the gulp build scripts I host at this github repo to write ec6 code.

Please do not hesitate to ask, if you have any questions :)

Best wishes
Felix

**Comment by flibbles** [comment]
Thanks!

Awesome work. This should suit my needs just fine.

Flibbles
