### ISSUE TITLE
Tiddler rendering as node icon

### ISSUE THREAD

**Issue by asampal** [felixhayashi/TW5-TiddlyMap#20]
It would be nice if for certain views miniature renderings of tiddlers (as in Jeremy's Cecily) could be used as the representation of node. These would not be rendered every time the graph is re-drawn, but would be generated once (as a bitmap) and cached. The miniature tiddler views could be refreshed manually, either individually or all in a given view. 

When generating the miniature renderings, it would make sense to have them generated so that at the zoom level a view is most likely to be viewed at there would be some useful information retained in the bitmap.

For additional flexibility, the use of miniature tiddler renderings for a view should not be an all-or-nothing switch - it should be a setting that can be enabled for all or only a subset of nodes.

**Comment by felixhayashi** [comment]
Sorry @asampal 

this is not possible.

Cecily does not produce miniture renderings but a its just the browser zoom. The graph can only contain images, its elements are not dom-elements. Also, there is not such a thing that I can create "screenshots" of tiddlers.

Nonetheless, it will be possible at some point to use images as graph nodes. But this is another milestone.

-Felix

**Comment by asampal** [comment]
Felix, wrt Cecily I was just giving it as an example where you can see miniature or thumbnail tiddlers. The actual method for producing these would be by using something like [html2canvas](http://html2canvas.hertzen.com). This lib can take a document or div, say, and renders it to a canvas at 1:1 size. This of course can be resized using drawImage as shown [here](http://stackoverflow.com/a/16304718/1792095).

Another similar library is  [rasterizerHTML.js](https://github.com/cburgmer/rasterizeHTML.js).

**Comment by felixhayashi** [comment]
Hi @asampal,

thanks for the links. Still, to include this functionality is too special for this plugin.

Here is how I envision such a case in the future:

# A plugin xy (not written by me) periodically goes through all the tiddlers and creates snapshots.
# The snapshots are referenced by tiddlers let's say via the `icon` field.
# When drawing a graph, TiddlyMap looks at the `icon` field of a tiddler and uses this image to render the node.

My job is to ensure the last point. And as said above, I will work on that at a given point in time for sure.

-Felix

**Comment by felixhayashi** [comment]
Hi @asampal,

I you look at the examples at the demo site, the graph uses images specified in the tiddler's icon field

-Felix

**Comment by asampal** [comment]
That's great Felix. Can they only be SVG images, though?

**Comment by felixhayashi** [comment]
Hi @asampal, 

No, I recently added support for all image mime types. So it can also be png. But only local images (stored in tw) are displayed and I cannot scale the image size in the graph, so you need scale it to the right size before adding it as icon.

-Felix
