### ISSUE TITLE
Introduce notation that excludes an edge type from all views per default

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#201]
### What is this about

Some edges or types should be only visible in a certain view and nowhere else. This means, they should never appear in another view (unless the filter is explicitly set to allow them).

### Intro

In the far past of TiddlyMap, edges (and their edge types) [were distinguished as private or public](https://groups.google.com/d/msg/tiddlywiki/Nj885Ia8kGA/alb-X-VzqsAJ). I then abandoned that concept (see #71) because the distinction between private and public edges (and types) was extremely hard to manage and made it impossible for an edge to be turned into a public edge later on (or vice versa).

### Status quo (and problem)

At the moment, the user can specify a filter to include or exclude edges based on the name of the edge (see docs: [edge type filters](http://tiddlymap.org/#Node%20and%20edge-type%20filters)).

E.g. I can say: Only edges of types having the prefix `project1` are allowed in the map.

`[prefix[$:/plugins/felixhayashi/tiddlymap/graph/edgeTypes/project1:]]`

This will allow the edges of e.g. types `project1:manages` or `project1:uses` to be shown in the map.

That's great. However, here is the…
**Problem:** What if I don't want to have the edges prefixed `project1:` shown in other maps? I need to add an exclude filter `-[regexp[project1:]]` for every map, including every new map that is added to the system! That sucks.

### Solution

I will enforce the following rule, which is inspired by Javascript and PHP programming conventions:

**Rule:** If an edge type is prefixed with an underscore (e.g. `_father of`), then it is never shown in a map per default.

So the user needs to explicitly say: I want edges of this type in my map. So in case of the example given in the status quo section above, the user would need to add `+[regexp[_project1:]]` to the view's edge filter.

This functionality works well together with the default edge-type namespace a user can specify per view.

### Roadmap

I'll add this rule and properly document this in the next release.

**Comment by tobibeer** [comment]
:+1:
