### ISSUE TITLE
Navigation among nodes as in Personal Brain

### ISSUE THREAD

**Issue by Gutalean** [felixhayashi/TW5-TiddlyMap#202]
Hi! First of all, thanks for the great plugin for TiddlyWiki. Is there in this plugin an ability to do navigation among my thoughts (nodes?) as in Personal Brain's style?

http://www.youtube.com/watch?v=3nYNn8zbcwk

**Comment by felixhayashi** [comment]
Hi @Gutalean 

> First of all, thanks for the great plugin for TiddlyWiki.

Thanks!

> Is there in this plugin an ability to do navigation among my thoughts (nodes?) as in Personal Brain's style?
> http://www.youtube.com/watch?v=3nYNn8zbcwk

Not sure, which second of the video are you refering to?

You can use the double click to open tiddlers. Or do you mean something like TiddlyMap's live view: https://youtu.be/FimZ2dEGQc4?t=32

-Felix

**Comment by Gutalean** [comment]
Yes, live view seems good. Didn't know about it.

**Comment by felixhayashi** [comment]
@Gutalean TiddlyMap has become quite complex, some features are hidden in the docs and some are not even properly documented. So if you neither find it in the docs, nor at youtube or in the issue list here at GitHub, always feel free to ask (or at the TW google groups). If the live view is what you want, maybe the livetab is also suited for you. It adds the live view as tab (plus a bit more, see docs).
