### ISSUE TITLE
Completely remove "click-to-use" feature

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#205]
"Click to use" was introduced to prevent widgets embedded in the story river to prevent that scrolling the river results in a zoom action in the map (thus swallowing the scroll and turning it into a zoom).

However, this makes it really unpleasant to work with the nodes in the embedded map. For example every navigation requires an extra click to activate the map before one is able to do a double click on the nodes to navigate…

Hence, the click to use feature will be removed and instead zooming per scroll is prevented unless the `ctrl` key is held down. This way the map is actively usable from the beginning on, yet makes scrolling the story river possible, i.e. it doesn't swallow scrolling events in the river.

**Comment by tobibeer** [comment]
> Hence, the click to use feature will be removed and instead zooming per scroll is prevented unless the ctrl key is held down. 

I appreciate using CTRL, perhaps keep mobile environments in mind.

**Comment by felixhayashi** [comment]
> perhaps keep mobile environments in mind.

@tobibeer Hmm right, I often forget about mobile :D I think TiddlyMap makes more sense on large screens anyway. Still I described some possibilites how zooming is possible (for mobile) in #207.
