### ISSUE TITLE
Remove the majority of buttons in embedded maps.

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#207]
Embedded maps are usually small since not much space is available in the story river. The little space available should be consumed by the map not by buttons or the GUI.

* So since moving the map is possible via dragging the background, I'll remove the left/right/top/bottom buttons.
* Also zoom in/out buttons will be removed. If a user wants to zoom, he/she can use the mousewheel (in combination with ctrl see #205) or enter fullscreen where zooming is activated and all buttons are shown or click on the lense icon ("zoom on a specific node").

#### Before

![2016-01-15 11 27 31](https://cloud.githubusercontent.com/assets/4307137/12351240/7b71535a-bb7c-11e5-8300-865e6e5403fd.png)

#### After

![2016-01-15 11 29 38](https://cloud.githubusercontent.com/assets/4307137/12351236/748cb246-bb7c-11e5-9979-78150b9b7739.png)

**Comment by tobibeer** [comment]
:+1:
