### ISSUE TITLE
fullscreen graph

### ISSUE THREAD

**Issue by tobibeer** [felixhayashi/TW5-TiddlyMap#21]
if possible, it seems helpful to be able to toggle the size of the graph viewer to cover the whole page (if not actual fullscreen) and back.

Perhaps this could be done using a (temporary) modal.

**Comment by felixhayashi** [comment]
nice idea! implemented! ;) Main editor -> view actions -> fullscreen

**Comment by felixhayashi** [comment]
ups, only works in firefox at the moment -.- have to fix that

**Comment by tobibeer** [comment]
:+1:  wow, nice... and impressive

only just, where did that test-site move? ^_^
I imagine you're doing some restructuring.

**Comment by felixhayashi** [comment]
> :+1: wow, nice... and impressive

thanks!

> only just, where did that test-site move? ^_^
> I imagine you're doing some restructuring.

Oh boy... yes I am moving to github to host the demo page as it is makes it easier to commit the demo with code changes. I have to update all the docs and readmes with the new links. Updating broken links and keeping track of redirects is really annoying...

The proxy is now: http://bit.ly/tiddlymap (oh yes, it's now tiddlymap by the way, thought this name makes it easier to recognize that it's a plugin for tw.)

-Felix

**Comment by tobibeer** [comment]
>  I have to update all the docs and readmes with the new links. Updating broken links and keeping track of redirects is really annoying...

Can imagine, take your time.

TiddlyMap sounds good, too, better than taskgraph. :+1: 

Ping back here when you figure out why chrome denies fullscreen, thanks!

**Comment by tobibeer** [comment]
fantastic! *bows down*

**Comment by tobibeer** [comment]
Oh, I just noticed, if I first open fullscreen mode from the graph in the sidebar after I did the same for a graph in the story, the story will have a higher z-index.

Should this ticket perhaps stay open until this is fixed?
Perhaps, I leave it up to you to eventually close it.

**Comment by felixhayashi** [comment]
> Oh, I just noticed: If I open fullscreen mode from the graph in the sidebar after I first did the same for a graph in the story, the story will have a higher z-index.

Correct. Thanks. I have to fix this.
