### ISSUE TITLE
node "icon tags"

### ISSUE THREAD

**Issue by tobibeer** [felixhayashi/TW5-TiddlyMap#213]
Not sure if this is too (visually) loaded for your taste.

Imagine this:

* A user can add icon tags — possibly in the form of simple unicode emojis — to nodes
    * a popup ui would provide a couple of the most popular ones assorted into sections, filterable via text search
* Clicking or hovering an "icon tag" / emoji in the viewer opens a list / popup of all other tiddlers / nodes that have that emoji ...in this view / or globally

Put differently, these would be somewhat like "icon tags" for nodes, so not "node-icons". For example, they could come in the form of dictionaries with named indexes, each dictionary representing a section grouping icons by topic. Whether a user wanted to use plain unicode or fancy svg or images is perhaps entirely up to them. However, the simplest, most light-weight implementation probably being basic unicode emojis.

## Background

The reason I am pitching this here at TiddlyMap — while emojis are also discussed at TiddlyWiki repo in their own issue — is that I have always found that stuff to be an integral part to mind mapping.

What I have not liked about freemind — and, quite frankly, possibly the reason why I refused to use it at all — was how it implemented icons. You always had to add icons in the right sequence and could only remove the last one. I simply would not bear the frustration of such a limiting implementation. :D

**Comment by felixhayashi** [comment]
Hi @tobibeer,

This sounds very much like  #34: **Nodes display "badges" pertaining to defined tags.**

I highly agree, it would be awesome to have "icon tags" or "badges" for nodes in TiddlyMap. I want to implement something like that at some point.

My idea to implement this so far was analog to tiddlywiki: if a tiddler A is tagged with tiddlers that have icons assigned, TW will show that icon in the tag **and**, in case of tiddlymap, the node corresponding to the tiddler A will als show all icons as "badges". Icons could be emoji or other images.

**Comment by tobibeer** [comment]
> If a tiddler A is tagged with tiddlers that have icons assigned, TW will show all icons in the tag-boxes and, in case of tiddlymap, the node corresponding to the tiddler A would show all icons as "badges". Icons could be emoji or other images.

Not sure I would make that dependent on tags, but it is sure one way to go about it.

Anyhow, I'm closing this ...with reference to #34.

**Comment by felixhayashi** [comment]
> Not sure I would make that dependent on tags, but it is sure one way to go about it.

Me neither, I am open for ideas :)

**Comment by tobibeer** [comment]
I was working on something I called "itags" (inline tags) that would cater for something like:

* `::inline-tag::`
* `::category:item::`

Whereas the parser would cascade down possible options for how to fetch the actual content for an "inline tag", starting at:

1. an actual (system) tiddler defining each category item, with a range of options (also definable for the category)
2. a dictionary tiddler at the "category"

e.g.:

```
$:/plugins/tobibeer/itags/categories/my-cat/item-foo
```

used as:

```
::my-cat:item-foo::
```

...possible options like styles or classes or tooltips being read from either the above or from:

```
$:/plugins/tobibeer/itags/categories/my-cat
```

...for all items in the category `my-cat`, wheras the above could also be a dictionary tiddler holding items as indexes, as a fallback.

Eventually there'd also be:

```
$:/plugins/tobibeer/itags/defaults
```

...being a dictionary to hold simple, default items that don't require either "categories" or "category items"... for those inline tags.

**Comment by felixhayashi** [comment]
Very interesting and highly dynamic approach @tobibeer. It looks similar to https://github.com/Jermolene/TiddlyWiki5/issues/2144 but for tags. Would be nice to see a demo at one point. For TiddlyMap I have also implemented a symillar idea, a "style cascade" where higher level node styles are extended through lower level styles. Maybe it makes sense to reuse this mechanism to apply badges. This way you could also mix badges by combining different "group styles". Also it is possible to prioritize "group styles"… Anyway, I'll wait a bit with this feature as it needs some thorough thinking ;)

> With regard to the table displayed above, all styles on a lower level inherit from styles defined on a higher level and view styles always inherit global styles.

> The arrow (←) means "inherits from" and the index refers to the index in the table.

> (1) ← (2) ← (3) ← (4) ← (5) ← (6)
> http://tiddlymap.org/#Styling%20Nodes
