### ISSUE TITLE
dynamically update "diving mode"

### ISSUE THREAD

**Issue by tobibeer** [felixhayashi/TW5-TiddlyMap#22]
When a tiddler is opened in the main story, e.g. by clicking a link, and the graph in the sidebar is dynamic, "dive" to the current tiddler.

**Comment by felixhayashi** [comment]
Hi @tobibeer, I finished working on that. With the help of the *TW5-TopStoryRiver plugin* it is now possible. TiddlyMap now has a live view on its right side (its the tab next to "editor"). When you scroll it changes (using the diving mode).

-Felix

P.S. I fixed a bug in the TW5-TopStoryRiver plugin (to make it work with small displays) so if you have the chance, please update.

**Comment by tobibeer** [comment]
That is even better than responding to click events (only). Absolutely great implementation, Felix.
Perhaps make it work for Chrome, too. ;-)

**Comment by felixhayashi** [comment]
Copy pase from discussion https://github.com/Jermolene/TiddlyWiki5/issues/1290

> oh boy.. thanks for telling me @tobibeer. why can the world not decide on one browser to use (as long its not internet explorer). I hate all these browser discrepancies. Well, guess I have to fix that -.-

> **Edit** tested in Chrome 39 Linux and works fine. I will check tomorrow when I have a windows PC. Not sure why same browsers behave differently on different OS.

> **Edit 2** I forgot to ask: could you give me a hint what is not working? (Also maybe we can further discuss this here https://github.com/felixhayashi/TW5-TiddlyMap/issues/22)

**Comment by tobibeer** [comment]
> could you give me a hint what is not working?

Sorry, a poor man's bug report there.
Situation: the graph doesn't display anything at all.

**Comment by felixhayashi** [comment]
Hi @tobibeer 

I now tested with **IE11** and **Chrome** (39.0.2171.95 m) on **windows 7**

Works fine here

**Comment by tobibeer** [comment]
This is what I get after changing to the live tab...

```
These tiddlers changed: Object {$:/state/tab/sidebar--1835078512: Object}
@LIVE_VIEW Retrieving or generating the view holder reference
@LIVE_VIEW User wants to bind view "live" to graph
@LIVE_VIEW Created an independent temporary view holder "$:/temp/felixhayashi/tiddlymap/holders/548e5db3-5a66-4479-a3eb-972e8d3d1dea"
@LIVE_VIEW View "$:/plugins/felixhayashi/tiddlymap/graph/views/live" inserted into independend holder
@LIVE_VIEW Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/live" from holder "$:/temp/felixhayashi/tiddlymap/holders/548e5db3-5a66-4479-a3eb-972e8d3d1dea"
View's config is requested to be rebuild -> trigger full rebuild
@LIVE_VIEW Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
A callback was registered for changes of "$:/temp/focussedTiddler"
@LIVE_VIEW Rebuilding graph
These tiddlers changed: Object {$:/temp/felixhayashi/tiddlymap/holders/548e5db3-5a66-4479-a3eb-972e8d3d1dea: Object}
@LIVE_VIEW Network stabilized after 1 iterations
A graph has been removed.
```

**Comment by felixhayashi** [comment]
Well this looks all good. :confused: 

And after that if you scroll down a bit nothing changes? I mean in the very beginning, nothing is displayed but as soon as you start scrolling, it should change... but it doesn't?

**Comment by tobibeer** [comment]
All empty...

> A graph has been removed.

Is telling me what?

Does the deletion of the previous graph in the editor tab
somehow remove the new one?

I would also call the Editor tab the Map tab.
That would go better with "TiddlyMap" and
make it more clear what we're talking about.

**Comment by felixhayashi** [comment]
> A graph has been removed.

This is fine. Its the editor graph that is removed when you switch to the live view.

> Scrolling and scrolling... all empty...

I don't get it. Are you testing in the online demo? It only works if TW5-TopStoryView is version 0.0.2.
Do you see something like 

>  These tiddlers changed: [$:/temp/focussedTiddler,] { $:/temp/focussedTiddler=[modified,]}

when you scroll down? If not, I think it is the TopStoryView plugin that doesn't work correctly.

> I would also call the Editor tab the Map tab.

Maybe this is a good idea, its also shorter.

-Felix

**Comment by tobibeer** [comment]
This is what I get...

![fail](https://cloud.githubusercontent.com/assets/97566/5696498/f72535fa-99d3-11e4-9b81-e0901fdb2976.jpg)

TiddlyMap's caretaker was started
Registered namespace and options
Caretaker's filter: "[prefix[$:/plugins/felixhayashi/tiddlymap/options]!has[draft.of]]"
@MAIN_EDITOR Retrieving or generating the view holder reference
@MAIN_EDITOR Using default (global) view holder
@MAIN_EDITOR Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/All Tiddlers" from holder "$:/plugins/felixhayashi/tiddlymap/misc/defaultViewHolder"
View's config is requested to be rebuild -> trigger full rebuild
@MAIN_EDITOR Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
@MAIN_EDITOR Rebuilding graph
@47C2EEFF-304A-45EB-8C35-566BA1578C45 Retrieving or generating the view holder reference
@47C2EEFF-304A-45EB-8C35-566BA1578C45 User wants to bind view "All Tasks" to graph
@47C2EEFF-304A-45EB-8C35-566BA1578C45 Created an independent temporary view holder "$:/temp/felixhayashi/tiddlymap/holders/107a68a3-fd28-4d2a-8593-a74362957875"
@47C2EEFF-304A-45EB-8C35-566BA1578C45 View "$:/plugins/felixhayashi/tiddlymap/graph/views/All Tasks" inserted into independend holder
@47C2EEFF-304A-45EB-8C35-566BA1578C45 Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/All Tasks" from holder "$:/temp/felixhayashi/tiddlymap/holders/107a68a3-fd28-4d2a-8593-a74362957875"
View's config is requested to be rebuild -> trigger full rebuild
@47C2EEFF-304A-45EB-8C35-566BA1578C45 Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
@47C2EEFF-304A-45EB-8C35-566BA1578C45 Rebuilding graph
@249BA41C-25DA-4727-AE72-EAD6513CF186 Retrieving or generating the view holder reference
@249BA41C-25DA-4727-AE72-EAD6513CF186 User wants to bind view "All Tasks" to graph
@249BA41C-25DA-4727-AE72-EAD6513CF186 Created an independent temporary view holder "$:/temp/felixhayashi/tiddlymap/holders/86119c41-d57f-4c9c-8db6-74c21f6c0dac"
@249BA41C-25DA-4727-AE72-EAD6513CF186 View "$:/plugins/felixhayashi/tiddlymap/graph/views/All Tasks" inserted into independend holder
@249BA41C-25DA-4727-AE72-EAD6513CF186 Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/All Tasks" from holder "$:/temp/felixhayashi/tiddlymap/holders/86119c41-d57f-4c9c-8db6-74c21f6c0dac"
View's config is requested to be rebuild -> trigger full rebuild
@249BA41C-25DA-4727-AE72-EAD6513CF186 Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
@249BA41C-25DA-4727-AE72-EAD6513CF186 Rebuilding graph
@206A65AC-C502-4975-8FDB-EAECE278D8E7 Retrieving or generating the view holder reference
@206A65AC-C502-4975-8FDB-EAECE278D8E7 User wants to bind view "All Tasks" to graph
@206A65AC-C502-4975-8FDB-EAECE278D8E7 Created an independent temporary view holder "$:/temp/felixhayashi/tiddlymap/holders/0a215e34-ca5e-4eca-8afb-c3d3c84aadfb"
@206A65AC-C502-4975-8FDB-EAECE278D8E7 View "$:/plugins/felixhayashi/tiddlymap/graph/views/All Tasks" inserted into independend holder
@206A65AC-C502-4975-8FDB-EAECE278D8E7 Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/All Tasks" from holder "$:/temp/felixhayashi/tiddlymap/holders/0a215e34-ca5e-4eca-8afb-c3d3c84aadfb"
View's config is requested to be rebuild -> trigger full rebuild
@206A65AC-C502-4975-8FDB-EAECE278D8E7 Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
@206A65AC-C502-4975-8FDB-EAECE278D8E7 Rebuilding graph
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 Retrieving or generating the view holder reference
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 User wants to bind view "Family Tree" to graph
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 Created an independent temporary view holder "$:/temp/felixhayashi/tiddlymap/holders/75c923f9-857a-4624-bed5-4c94a43221e4"
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 View "$:/plugins/felixhayashi/tiddlymap/graph/views/Family Tree" inserted into independend holder
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/Family Tree" from holder "$:/temp/felixhayashi/tiddlymap/holders/75c923f9-857a-4624-bed5-4c94a43221e4"
View's config is requested to be rebuild -> trigger full rebuild
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 Rebuilding graph
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 Retrieving or generating the view holder reference
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 User wants to bind view "Components" to graph
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 Created an independent temporary view holder "$:/temp/felixhayashi/tiddlymap/holders/4f7d03e8-a992-4d18-b68e-9197fed29a2a"
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 View "$:/plugins/felixhayashi/tiddlymap/graph/views/Components" inserted into independend holder
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/Components" from holder "$:/temp/felixhayashi/tiddlymap/holders/4f7d03e8-a992-4d18-b68e-9197fed29a2a"
View's config is requested to be rebuild -> trigger full rebuild
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 Rebuilding graph
These tiddlers changed: Object {$:/StoryList: Object, $:/HistoryList: Object, $:/temp/felixhayashi/tiddlymap/holders/107a68a3-fd28-4d2a-8593-a74362957875: Object, $:/temp/felixhayashi/tiddlymap/holders/86119c41-d57f-4c9c-8db6-74c21f6c0dac: Object, $:/temp/felixhayashi/tiddlymap/holders/0a215e34-ca5e-4eca-8afb-c3d3c84aadfb: Object…}
@MAIN_EDITOR Network stabilized after 1 iterations
@47C2EEFF-304A-45EB-8C35-566BA1578C45 Network stabilized after 1 iterations
@249BA41C-25DA-4727-AE72-EAD6513CF186 Network stabilized after 1 iterations
@206A65AC-C502-4975-8FDB-EAECE278D8E7 Network stabilized after 1 iterations
@E1DD658F-2C65-42CA-B5C4-9AA99CCB8691 Network stabilized after 261 iterations
@A9C24076-BD90-49A5-AA7C-34CD8BF25534 Network stabilized after 1 iterations
These tiddlers changed: Object {$:/state/tab/sidebar--1835078512: Object}
@LIVE_VIEW Retrieving or generating the view holder reference
@LIVE_VIEW User wants to bind view "live" to graph
@LIVE_VIEW Created an independent temporary view holder "$:/temp/felixhayashi/tiddlymap/holders/922e9908-4ae0-460c-833d-01afae3c3147"
@LIVE_VIEW View "$:/plugins/felixhayashi/tiddlymap/graph/views/live" inserted into independend holder
@LIVE_VIEW Retrieved view "$:/plugins/felixhayashi/tiddlymap/graph/views/live" from holder "$:/temp/felixhayashi/tiddlymap/holders/922e9908-4ae0-460c-833d-01afae3c3147"
View's config is requested to be rebuild -> trigger full rebuild
@LIVE_VIEW Initializing and rendering the graph
A callback was registered for changes of "$:/state/sidebar"
A callback was registered for changes of "$:/temp/focussedTiddler"
@LIVE_VIEW Rebuilding graph
These tiddlers changed: Object {$:/temp/felixhayashi/tiddlymap/holders/922e9908-4ae0-460c-833d-01afae3c3147: Object}
@LIVE_VIEW Network stabilized after 1 iterations
A graph has been removed.

**Comment by felixhayashi** [comment]
Hi Tobi,

thanks for the log, everything looks correct. sorry to ask but just to be really clear: the screenshot you posted is not scrolled, in this position it is correct that nothing is displayed in the live view as it only reacts to scrolls. If you scroll a little bit down, do you see something like 

`@LIVE_VIEW $:/temp/focussedTiddler triggered a refresh`

or

`These tiddlers changed: [$:/temp/focussedTiddler,] { $:/temp/focussedTiddler=[modified,]}` ?

-Felix

**Comment by tobibeer** [comment]
I sure scrolled down and up and down again... ^^

**Comment by tobibeer** [comment]
Not sure if anything changed (or beause I just did a CTRL+5), but now it seems to work, even though the graph is still initially empty when I switch to the tab.

**Comment by tobibeer** [comment]
Also, is it possible to rather / as well update the graph on mouseover? It seems that it gets updated rather late (when that heading is almost out of view).

**Comment by felixhayashi** [comment]
Hi Tobi

> Not sure if anything changed (or beause I just did a CTRL+F5), but now it seems to work, 

What a relief. I almost was about to visit a friend that runs windows 8.1 with chrome and debug it there...

> even though the graph is still initially empty when I switch to the tab.

Yes. I will solve that.

> Also, is it possible to rather / as well update the graph on mouseover? It seems that it gets updated rather late (when that heading is almost out of view).

I thought about mouseover but rejeceted it because checking on everymouse move is too much calculation (dom retrival of title and comparissons) and if you just want to move the pointer away from the current tiddler (by accident or because it prevents you from reading) the graph shouldn't change.

> It seems that it gets updated rather late (when that heading is almost out of view).

Yes, I could bring the threshold lower, actually, I think its a good idea to outsource this as an option so every user can decide for him/herself.

-Felix

**Comment by tobibeer** [comment]
> checking on every mouse move is too much calculation

not mouse-move, mouse-over... one event, not one per pixel

> if you just want to move the pointer away from the current tiddler (by accident or because it prevents you from reading) the graph shouldn't change

of course not, so... you trigger mouseover and if you've not received a mouse-out after x milliseconds you set the graph to the mouse-overed tiddler... doesn't sound too demanding in terms of processing

**Comment by rcrath** [comment]
Hi, I made a case for always opeing on top in tiddlywiki 2 
https://groups.google.com/forum/#!searchin/tiddlywiki/open$20top/tiddlywiki/FxwyYBM3RUg/ATqQM4l8CVgJ
and with a lot of help from devs and many obsessive hours implemented it in FiddlyWIki. 
http://way.net/FiddlyWiki/FiddlyWiki.html

 What I found to be better was a tabbed view ultimately, but I think if there is going to be a river of text and it is nonlinear (i.e. more than one link per tiddler and tiddlers can be linked to from different places) then the best way of reading for my purposes is always opening tiddlers on top, including reopening already open ones on top.  I actually held off updating to 5 til today because I have always found the classic TIddlywiki behavior disorienting.  I hope the open on top is made available as an option or if not as a plugin.  

ALso, Jeremy's tabbed version looks really interesting too and I hope that becomes available in some form as TW5 develops.

I guess this is a long way of saying +1 for the suggestion (as summarized in Jeremy's post.  )

**Comment by tobibeer** [comment]
@rcrath ...

> Jeremy's tabbed version looks really interesting too and I hope that becomes available in some form as TW5 develops

...which one is that?

**Comment by rcrath** [comment]
shoots...I was reading a bunch of things and saw a link to it either from google groups or github issues, but cannot find it now.  Basically it put the tabs on the left in a parabolic layout (focus tab is largest, with others receding to give it a rolodex sort of look.  But I can't find it now, sorry...Jeremy?

**Comment by felixhayashi** [comment]
;) http://jermolene.wordpress.com/2008/11/14/tabbedsinglepagemode-for-tiddlywiki/

**Comment by tobibeer** [comment]
I see, I believe it was even implemented in the early days of TW5 but then possibly got under the wheel. I didn't quite miss it as it seemed rather imposing to actually see it at work. I don't remember it as just showing the history, but rather this fisheye navigation thingy that actually listed aalllll tiddlers.

As a way to navigate the history this may indeed be worth exploring. In SinglePageMode, it could simply unfold like an accordeon by clicking the title of the current tiddler or resting on it... with the oldest viewed titles being lowest, all tiny unless hovered. However, this way, previewing would not work well anymore as it would possibly cover the list.

**Comment by rcrath** [comment]
ctually still just getting my head around TW5 and it looks like the "open tiddlers" tab on the right might get me most of the way to TW nirvana.  I had not noticed that feature til then.  I would still love an open at top or situate newly opened tiddlers at the top of the screen anyway, even if there is stuff above and below (although I think it is easiest to orient myself when the newest always opens at the top, in the same absolute and relative position, and whatever I was just doing is always immediately following.  I find it disorienting to have to look around the bottom of the page for the newly opened stuff and having it be in a different absolute position much of the time, but I understand others prefer it that way for other good reasons.  So I would hope for this as a setting in options, or lacking that, a plugin like the TWC version.  Oh, and thank you Felix for finding the fisheye link.  I am a huge fan of parabolic type viewers and trees
