### ISSUE TITLE
Duplicate ID renaming can cause data loss on node.js hosted wiki

### ISSUE THREAD

**Issue by michaelballantyne** [felixhayashi/TW5-TiddlyMap#222]
I use TiddlyWiki in its [node.js-hosted form](http://tiddlywiki.com/#TiddlyWiki%20on%20Node.js), and often have multiple browser windows with my wiki open.

If I rename a tiddler in one such window, other windows will eventually refresh with a new list of tiddlers from the server that reflects the rename (this can be triggered immediately with the refresh button in the server tab of settings).

At that time, TiddlyMap detects that the new tiddler object (the renamed tiddler) has the same tmap.id field value as the tiddler of the old name in its store and tries to adjust the field on the renamed tiddler.

Somehow the result is that the content of the renamed tiddler is totally lost.

**Comment by felixhayashi** [comment]
Hi @michaelballantyne 

thanks for reporting! pretty busy at the moment, but I'll see what I can do about this.

-felix

**Comment by marceloakira** [comment]
I have experienced the same problem, a long tiddler was lost :-(

**Comment by felixhayashi** [comment]
I did some investigations on this and this bug has two causes:

1. **Tiddlywiki** lazy loads text fields of synced tiddlers

> In the [[configuration for TiddlyWeb|TiddlyWiki in the Sky for TiddlyWeb]], the browser first requests a "skinny" version of each tiddler (consisting of all the fields apart from the text field). Subsequently, an attempt to read those skinny tiddlers with `wiki.getTiddler()` returns just the skinny fields, but an attempt to read one using `wiki.getTiddlerText()` will trigger an asynchronous load of the full tiddler text, which in turn triggers a refresh cycle… [[tw docs](https://raw.githubusercontent.com/Jermolene/TiddlyWiki5/ffc0899f52b45ba2b5a5a20fb909dcc587e80b3e/editions/dev/tiddlers/from%20tw5.com/mechanisms/LazyLoadingMechanism.tid)]

2. **TiddlyMap** assigns an empty text to every changed tiddlers having no text fields (this is to prevent a critical recursion bug from occurring; see https://github.com/Jermolene/TiddlyWiki5/issues/2025)

I'll see what I can do about this.

**Comment by felixhayashi** [comment]
Ok this case is solved, however, I really discourage the use of TidddlyWiki in multiple windows (regardless whether run in server mode or not). In server mode, system tiddlers are not synced and this will result in diverging wiki states held in runtime and may lead to lost updates.

**Comment by tobibeer** [comment]
> I really discourage the use of TidddlyWiki in multiple windows (regardless whether run in server mode or not).

I'd rather think it should be a core priority for that to be permissible.

> In server mode, system tiddlers are not synced and this will result in diverging wiki states held in runtime and may lead to lost updates.

Are you sure that not system tiddlers are synced? I don't think that's true at all. Perhaps you meant temp tiddlers?

Anyway, if I am losing some, say, plugin update, then that's not as critical as losing content.

**Comment by felixhayashi** [comment]
Hi @tobibeer 

> I'd rather think it should be a core priority for that to be permissible.

true :)

> Are you sure that not system tiddlers are synced? I don't think that's true at all. Perhaps you meant temp tiddlers?

Open tw in server mode in two windows and change the title of one wiki… if I am not mistaken, it won't sync.
