### ISSUE TITLE
Source code older than release package

### ISSUE THREAD

**Issue by Cdric49** [felixhayashi/TW5-TiddlyMap#224]
Hello,

I notice packages available on http://tiddlymap.org/ is more updated (according to version number) than github packages.
How can I pull last plugins packages ? (useful for nodejs upgrade)

Thanks,

**Comment by felixhayashi** [comment]
Hi @Cdric49 thanks for the heads up. I'll try to sync the versions so they are all at the same stage.

**Comment by felixhayashi** [comment]
Hi @Cdric49,

The build version (x.x.x+buildversion) may sometimes differ as I sometimes rebuild the wiki without pushing changes to github. In this case, however, the actual codebase did not change.

So you can pick packages from github or tiddlymap.org – they are all on the same stage of development.
