### ISSUE TITLE
Compatibility Issue with the Newest Tiddlywiki Release (5.1.12)

### ISSUE THREAD

**Issue by gesundelehre** [felixhayashi/TW5-TiddlyMap#225]
I downloaded a new Tiddlywiki (Release 5.1.12) and then added Tiddlymap to it through the website. Now when i want to **add a Node or an Edge in Fullscreen-Mode, then no popup shows up**, only **after i leave the fullscreen mode, the popup is visible**. The **same also happens if i doubleclick on a node to edit it**. The popup only shows up if i leave the fullscreen-mode.

This is somehow really hindering productivity.

I'd be glad if you could fix that issue.
Thanks

**Comment by silvyn** [comment]
+1
I've notice this bug too, and don't make link with 5.1.12, thanks @gesundelehre for opening this issue.

**Comment by felixhayashi** [comment]
Whoops ok I'll have a look thanks @gesundelehre and @silvyn for reporting

**Comment by felixhayashi** [comment]
This is now solved with v0.11.3 :)
