### ISSUE TITLE
Feature-Request: Layout Algorithm to automatically align Nodes and Edges

### ISSUE THREAD

**Issue by gesundelehre** [felixhayashi/TW5-TiddlyMap#226]
Would it be possible to **add a Funcitonality** that allows to **automatically align Nodes and Edges** with the **clicking of a Button?** 
- **This would help** really a lot to **save space** when displaying and organizing a Tiddlymap
- This would **result in bigger fontsize** of the Nodes and Edges in when clicking the "Fit whole Graph"-button

Here it can be seen what i mean with my request: https://youtu.be/WwiKrhyfAUY?t=2m4s

Thanks and Greetings

**Comment by felixhayashi** [comment]
Hi @gesundelehre 

something like this is not planned yet but the idea is nice. Also thanks for pointing me to vis-a-wiki, looks neat and I didn't know it. I'll keep the ticket open as a feature idea.

-Felix

**Comment by felixhayashi** [comment]
Closed. it is possible to use a raster since #94
