### ISSUE TITLE
Feature-Request: Selecting multiple Nodes in the Map at once

### ISSUE THREAD

**Issue by gesundelehre** [felixhayashi/TW5-TiddlyMap#229]
Would it be somehow possible to **draw out a window/rectangle with the mouse (click-and-drag)** and then **every node** that is **completely inside** of that **rectangle gets selected**?

**This would** really **help** in organizing and **rearranging nodes in the Map** more **quickly**.
Thanks

**Comment by flibbles** [comment]
Actually, yeah. I've thought about making an issue about this. I second this.

**Comment by felixhayashi** [comment]
Hi, 

will be included in the next release.

![2016-12-20 14 20 36](https://cloud.githubusercontent.com/assets/4307137/21351963/a7c27318-c6bf-11e6-874c-0151051e4698.png)
![2016-12-20 14 20 51](https://cloud.githubusercontent.com/assets/4307137/21351969/acf78ddc-c6bf-11e6-90dc-3a09a3fa7966.png)

**Comment by gesundelehre** [comment]
what must one do to use this rectangle? is there a key on the keyboard that has to be pressed at the same time while clicking and dragging with the mouse? I haven't figured it out yet. Thanks

**Comment by gesundelehre** [comment]
Ok i found it out, you have to press CTRL+mouseclick+dragging to create the rectangle

**Comment by jonathan-chin** [comment]
sorry to dig up an old ticket but I would love this feature. I'm using v0.15.3+9736 but holding control and clicking and dragging doesn't work. I tried this on my own copy and on the demo site and neithe work.

**Comment by felixhayashi** [comment]
Hi @jonathan-chin 
Strange, it works for me with FF Quantum and Chrome 71. You need to use `ctrl` + the right mouse button.

**Comment by jonathan-chin** [comment]
@felixhayashi I could have sworn I tried ctrl + right mouse click. just tried it now and it works. Thanks!

**Comment by darthdesi** [comment]
after selecting, how do i drag the nodes?

**Comment by flibbles** [comment]
You should be able to just click-and-hold on one of the selected nodes and move them all through that.

**Comment by darthdesi** [comment]
I'm able to multi select, but then it will not drag as a group.. only the node drags.

**Comment by flibbles** [comment]
I'm not sure what to tell you. Maybe your browser? It works for me on the main tiddlymap site.

Is it possible you're double clicking to drag? All selected nodes will have their labels bold while selected. If the others go unbold, then something has caused them to unselect.

**Comment by darthdesi** [comment]
i tried a bunch of views (on latest chrome) on https://tiddlymap.org/ and none of them drag together after multiselecting.

I'm on the latest Chrome browser release on a Win11 laptop. I'm multiselecting with ctrl + rightmouse click. A box appears.. and a Tooltip appears that confirming multiple nodes have been selected.

I then left-click and HOLD the mouse down on one of the nodes... and only that node drags. Is there some other key combo?

**Comment by flibbles** [comment]
I really don't know what to say. Everything you describe should be working, and it works on my machine when I do it exactly the way you describe. So it's definitely unbolding the other nodes when you drag?

I once looked into the mechanism TM uses to do multiselection, and it's some home-brewed sorcery, so I'm not sure how easily I could fix this, especially since I'm unable to replicate the problem.

**Comment by darthdesi** [comment]
yes as soon as i drag one of the nodes, it unbolds the rest... not able to multi-drag on Chrome or Edge (latest release builds).

What browser are you using?

**Comment by flibbles** [comment]
Chrome and Firefox.

The only way I'm able to replicate what your describing is if I click and hold for a good 1/3rd of a second or so before moving anything. I normally click and drag immediately. It works fine when I don't hesitate.

**Comment by flibbles** [comment]
It's not ideal. It's something I may be able to tackle with my newer project, although I don't think multi-select will be in the initial release.
