### ISSUE TITLE
"What it should look like..."

### ISSUE THREAD

**Issue by twMat** [felixhayashi/TW5-TiddlyMap#23]
First just: Please update the github link in the GettingStarted tiddler.

Ok, see screendump below. Other than having clicked "What it should look like.." in GettingStarted I have done nothing here (e.g I have not touched the sidebar tabs or changed river width).

I use FFlatest Win8.

![temp_tiddlymap](https://cloud.githubusercontent.com/assets/4534056/5673606/c3b3e662-979e-11e4-916e-ae4481ef7daf.PNG)

**Comment by tobibeer** [comment]
What would be the problem, Mat?
