### ISSUE TITLE
Feature-Request: Link directly to a TiddlyMap

### ISSUE THREAD

**Issue by gesundelehre** [felixhayashi/TW5-TiddlyMap#230]
Is it possible to link directly to a Tiddlymap with a permalink - would i be possible to add such a functionality, so that it can be linked to a certain Map instead of only just to the tiddlers in the flow.

Thanks and greetings

**Comment by felixhayashi** [comment]
I think this is already possible. You mean described here: #130 ?

E.g. http://tiddlymap.org/experimental/index.html?tmap-enlarged=fullscreen&tmap-view=Activities

-felix

**Comment by gesundelehre** [comment]
Yes, this is exactly what i mean. How can one create automatically such a link? Would it be possible to maybe add a Dialog for creating such a link. That will be very useful. Then one doesn't have to memorize that snippet of Code.

Thanks a lot

**Comment by felixhayashi** [comment]
Hi @gesundelehre 

have a look at this comment: https://github.com/felixhayashi/TW5-TiddlyMap/issues/130#issuecomment-169867952

It is also described in the docs: http://tiddlymap.org/#Using%20URL%20parameters
