### ISSUE TITLE
Feature-Request: Faster way to add new Nodes (just like Edges)

### ISSUE THREAD

**Issue by gesundelehre** [felixhayashi/TW5-TiddlyMap#231]
Would it be possible to somehow add the **possibility** to **add new Nodes** just **like Edges**? 

With that i mean, **when i add a new Edge**, then i can **enter a text** and **hit enter** and **then** the **edge appears**. To **confirm** the **creation of a new Node likewise** with the Enter key would be a **huge benefit**. (as of **now it is not possible**)

Is it possible to add such a feature? 

Thanks in advance, Greetings

**Comment by felixhayashi** [comment]
Hi @gesundelehre 

Good point

**Comment by gesundelehre** [comment]
Thanks this is awesome

**Comment by felixhayashi** [comment]
you are welcome, glad you like it.
