### ISSUE TITLE
Cant set neither icon nor font icon.

### ISSUE THREAD

**Issue by Losiara** [felixhayashi/TW5-TiddlyMap#232]
- Installed all plugins and font awesome in the empty tiddlywiki.
- Created new node 
- Placed file.jpg in the empty.html directory
- Set icon field as file.jpg
  Nothing changes.
  Also when try to set example font icon f206, it appears only empty rectangle with black borders, but no icon.
  Firefox 47, windows 7x64

upd font awesome works in browser on other sites

**Comment by Losiara** [comment]
I managed with image icons, but font awesome steel doesn't work.

**Comment by felixhayashi** [comment]
Hi @Losiara,

> it appears only empty rectangle with black borders, but no icon. Firefox 47, windows 7x64

that's strange, did you make sure you entered `f206` in the field `fa-icon`? At tiddlymap.org it works…

**Comment by Losiara** [comment]
>  did you make sure you entered f206 in the field fa-icon?

Sure

**Comment by felixhayashi** [comment]
Hi @Losiara this should be fixed now. 

In contrast to map background images, for node icons you cannot directly reference an image that is placed relative to your wiki. Instead, you need to follow these steps here: https://github.com/felixhayashi/TW5-TiddlyMap/issues/247#issuecomment-268052951

Hope this helps
