### ISSUE TITLE
Can't set filter for node type

### ISSUE THREAD

**Issue by mrbeeny** [felixhayashi/TW5-TiddlyMap#233]
In several tutorials i've seen and read that there is a possibility to associate tiddlers to custom node styles automatically e.g. via tags. But i can't find the scope field to enter the filter in the 'General'-tab of the node type manager (there is only 'Identifier' and 'Priority'). Can anybody give me a hint? 

Thx in advance!

**Comment by felixhayashi** [comment]
Hi @mrbeeny, sorry, this is a bug. I'll fix this

**Comment by felixhayashi** [comment]
fixed now :)
