### ISSUE TITLE
A unique ID is cloned when cloning tiddlers cloned?

### ISSUE THREAD

**Issue by Serj-Aleks** [felixhayashi/TW5-TiddlyMap#236]
I began to actively use and TiddlyMap. First I thought it was a trifle. But I sometimes forget to remove the field with a repeating IDs by cloning. It was a bit annoying.

**Comment by felixhayashi** [comment]
Hi @Serj-Aleks, 

> I began to actively use and TiddlyMap.

:+1: 

> But I sometimes forget to remove the field with a repeating IDs by cloning. It was a bit annoying.

You don't have to remove the dublicate ID after cloning. Tiddlymap usually sees that you are cloning a tiddler and then creates a new ID. It also shows you a dialog (if you don't see a dialog, open `$:/plugins/felixhayashi/tiddlymap/config/sys/user` and make sure the following is set: `suppressedDialogs.dublicateIdInfo: false`).

-felix

**Comment by Serj-Aleks** [comment]
Hi Felix

Danke.
Ich habe verstanden.

Wenn Sie interessiert sind
https://dl.dropboxusercontent.com/s/f9h3ioaoyw826et/twmaprudoc.html?dl=0

Und Beispielen
http://chwiki.tiddlyspot.com
https://tiddlylang.github.io/Dictionary

Noch mal vielen Dank. Ich mag Ihr Projekt.

Mit freundlichen Grüßen
Sergey

**Comment by felixhayashi** [comment]
Hi @Serj-Aleks 
Wow, seems like you translated all the docs into russian! Spasiba :)
I created a link to your dropbox on http://tiddlymap org
Glad to hear that you find the project useful!

-felix

**Comment by Serj-Aleks** [comment]
Hi, Felix.

It is thanks to you for your project.

I have two projects:
1. Historical information
2. Plain language (TiddlyLang
https://plus.google.com/u/0/communities/103308345354185795860)

And it will be very important for both TiddlyMap projects. So now I'm an
eternal user TiddlyMap. Do not throw your project please.

It is said that the Dropbox will not support the ability to display html.
https://groups.google.com/forum/#!topic/tiddlywiki/Zdzz_vb6h84
It is necessary to transfer the file to tiddlyspot. When I do that, I'll
tell you later.

Once again, thank you very much.

Best regards, Sergey

2016-09-01 21:27 GMT+02:00 Felix Küppers <notifications@github.com>:
