### ISSUE TITLE
TiddlyMap Icon issues

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#24]
1. the icon could look prettier
2. the icon is not integrated correctly into tiddlywiki

The current icon is created with inkscape. No matter what I do, the hover fill 

    .tc-tiddler-controls button.tc-btn-invisible:hover svg {
      fill: #888888;
    }

is not applied when hovering...

**Comment by tobibeer** [comment]
1. exchange that connector line with an actual shape that has a fill
    * combine all shapes into one

1. that inkscape file looks bloated
    * try save as normal svg, not inkscape

1. do not set `type=image/svg+xml`
    * must also remove xml header

**Comment by felixhayashi** [comment]
oh sweet I will try that thanks.
