### ISSUE TITLE
Internal JavaScript Error: TypeError: undefined is not an object (evaluating 'a.color')

### ISSUE THREAD

**Issue by bifidotftw** [felixhayashi/TW5-TiddlyMap#241]
100 % reproducible.
Browser: qutebrowser
OS: Gentoo Linux
Tiddlywiki version: 5.1.13
TiddlyMap version: Not sure, I installed it on 09.12.2016, so I guess it's the latest one (v0.11.5)
Node.js version: 4.4.1

Description:
After clicking "Add Edge" and then upon clicking a random tiddler in the map this error pops up in a red box.

Internal JavaScript Error

Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: undefined is not an object (evaluating 'a.color')

I have not found this error postet anywhere therefore I am posting it here.
The error message is annoying but not breaking any functionalities.
Sometimes I have to close it multiple times, apparently the same error is stacked multiple times.

**Comment by felixhayashi** [comment]
Hi @bifidotftw

thanks for the report. Due to my limited spare time, I can only offer support for firefox and chrome. – and I couldn't reproduce the problem there, sorry :(

So if you want to use TiddlyMap, maybe consider switching browsers for this.

-Felix
