### ISSUE TITLE
TW5-TiddlyMap and vis is standalone run？

### ISSUE THREAD

**Issue by jianxia612** [felixhayashi/TW5-TiddlyMap#242]
TW5-TiddlyMap and vis  is standalone run

**Comment by jianxia612** [comment]
I Want use  TiddlyMap and vis  create Map

**Comment by felixhayashi** [comment]
Hi @jianxia612,

I suggest you use "Standalone".
Here is a tutorial: https://youtu.be/dmeIxuN0L5w

good luck

-Felix

**Comment by jianxia612** [comment]
I want only use TW5-TiddlyMap not use tiddlywiki

**Comment by felixhayashi** [comment]
TiddlyMap uses Visjs but TiddlyMap is a **Plugin** for TiddlyWiki, you cannot separate the two.

**Comment by jianxia612** [comment]
thanks,I want to  use TiddlyMap map！
