### ISSUE TITLE
Upgrade to ec6 via babel

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#244]
include babel in build task and update code syntax to ES2015.

Sitenote: Because the "polyfill aspect" of babel is quite difficult to integrate with the current state of TW5, this part of babel will not be used.

**Comment by danielo515** [comment]
Quite interesting. Looking forward to see how do you achieve this

**Comment by felixhayashi** [comment]
Hola amigo,

it is quite simple actually, I just pipe the code through the babel gulp task (https://github.com/felixhayashi/TW5-TiddlyMap/blob/develop/gulpfile.babel.js#L213) and then am able to write ec6 syntax which includes classes, constants, arrow functions etc. (for example as done in this file: https://github.com/felixhayashi/TW5-TiddlyMap/blob/develop/src/plugins/felixhayashi/tiddlymap/js/EdgeTypeSubscriber/EdgeTypeSubscriberRegistry.js#L16).

If you employ my gulp script in your projects, you can also achieve this :)

-Felix
