### ISSUE TITLE
External image used as icon

### ISSUE THREAD

**Issue by 5rise** [felixhayashi/TW5-TiddlyMap#247]
Hi,

Just wondered whether there are any plans to allow external images to be used as icons to be shown in the map (to avoid bloating the size of the wiki with the embedded images).

Thanks
Jon

**Comment by felixhayashi** [comment]
Hi @5rise, not sure when to implement this, but I'll have a look. I marked this topic as feature request.

**Comment by 5rise** [comment]
Appreciated, thanks Felix.

**Comment by felixhayashi** [comment]
Hi @5rise 

I just checked, this is already working.

Steps:

1. save a png image, e.g. "myimage.png", in the folder where your wiki.html resides in
1. in your wiki create a new tiddler "mynewtiddler" and set the type to `image/png` and create a field `_canonical_uri` which points to your file via `file:./myimage.png`.
1. set the image of a node in your map to the name of the tiddler and it should show up as image. in your map

-felix

**Comment by 5rise** [comment]
Hi Felix,


Just noticed your email.

Thanks for the update and I'll try this.


Regards

Jon

________________________________
