### ISSUE TITLE
Can not use local external image as background image for a view.

### ISSUE THREAD

**Issue by Kasuko** [felixhayashi/TW5-TiddlyMap#248]
Hi, I am using Tiddlywiki to handle a D&D campaign and when I saw TiddlyMap I had to have it! So far it is working great as a map for managing relationships with NPCs and plot mapping etc.

However, I would also like to use it to handle dungeon maps with, where I can show the tiddler of the information about a room on the room on the map. Pretty much exactly like your Quest example on [your site](http://tiddlymap.org/#Think%20epic.%20Map%20your%20quests!) (which when searching through the issues I see was requested specifically for D&D, pretty cool!)

Now I am not hosting this wiki on a server, and I have the maps stored locally in the same directory tree as the Tiddlywiki.

When I create an external image tiddler using a local image path like so 
![external image tiddler path](https://cloud.githubusercontent.com/assets/86419/21169360/72281aa4-c189-11e6-8cb4-41256014457a.png)

This creates an image tiddler just fine.
![external image tiddler](https://cloud.githubusercontent.com/assets/86419/21169362/7d8091ce-c189-11e6-9f8b-b6e43d089ce0.png)

However, when I set the Background Image of the View to use that tiddler
![layout options](https://cloud.githubusercontent.com/assets/86419/21169368/8c9fb838-c189-11e6-9b62-8a55f6543502.png)

Then nothing shows up in the map view.
![map view](https://cloud.githubusercontent.com/assets/86419/21169376/956a9ba4-c189-11e6-9b96-9982e991c985.png)

Note, this does work if I import the image into the wiki, however, I would really like to avoid that since some of these images can be quite large and I want to avoid major wiki bloat.

I have tried changing the filename to all of the following and none work (with the 3rd even breaking the image tiddler.

> ./Maps/Ehntheri/C1/Wave Echo Cave/GM.jpg
> Maps/Ehntheri/C1/Wave Echo Cave/GM.jpg
> /Maps/Ehntheri/C1/Wave Echo Cave/GM.jpg

Is there anything I can do?

Thanks
Kasuko.

**Comment by Kasuko** [comment]
Alright, had a couple minutes this morning so I looked into it more. I see you are using XHR to request the file which is denied as a cross-origin request 😞 

I wonder if there is a way around this. Since Tiddlywiki can display the files I'm assuming there must be some way to view them. Possibly get the browser to request it somehow?

**Comment by Kasuko** [comment]
Alright, looks like I should be able to launch Google Chrome with the `--allow-file-access-from-files` flag set that should allow you to make XHR. When I do so the error about the XHR goes away but the image still does not show.

**Comment by felixhayashi** [comment]
Nice debugging you did there, @Kasuko ! :) ...and thanks for your interest in tiddlymap...
Your PR looks good, but please also add your name to the bottom of the [contributers list](https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/licenses/CLA-INDIVIDUAL.md) – many thanks. (your signature means, you contribute your PR-code to the project)

**Comment by Kasuko** [comment]
@felixhayashi Thanks, updated contributors list.
