### ISSUE TITLE
Can node size depend on number of connections?

### ISSUE THREAD

**Issue by Acknar** [felixhayashi/TW5-TiddlyMap#250]
hi,
I'm wondering if nodes in the tiddlymap plugin can be bigger or smaller depending on how many connections they have (or rather how many are displayed in the current view). 

I'm pretty new to this platform so I don't know how to attribute a label

**Comment by felixhayashi** [comment]
Hi @Acknar 

sorry to say such a feature does not exist.

> I'm pretty new to this platform so I don't know how to attribute a label

that's fine, only moderators can do that ;)

-felix

**Comment by Acknar** [comment]
then I have a followup question. I import a database into my wiki and I want to attribute diffrent sizes depending on groups. I tried to use the node manager but doesn't work that way from what I understood.

**Comment by felixhayashi** [comment]
There is currently a bug in TiddlyMap that you cannot set the sizes of icons. In any other case, you can use the node type manager and select a shape and then set the size for that shape. All nodes that match the filter of the node type should then have this size.
