### ISSUE TITLE
TiddlyMap Wikipedia page 

### ISSUE THREAD

**Issue by x9t9** [felixhayashi/TW5-TiddlyMap#252]
Not really a direct issue - but you should check your wikipedia page @ [https://en.wikipedia.org/wiki/TiddlyMap](https://en.wikipedia.org/wiki/TiddlyMap)
There is a warning that the page will be deleted after  `10:15, 7 February 2017 (UTC).`

I am really sorry to write it here , I know it is not a direct code-related issue, but then again, someone has gone into the trouble of writing that wikipage , it would be a shame if it were deleted ...

**Comment by felixhayashi** [comment]
Thanks for telling me @x9t9,

I wrote the page a while ago to publicly document some of the basic features of TiddlyMap.
Sad to see the page will be removed :( …but I don't know what to do about it.

-Felix

**Comment by x9t9** [comment]
@felixhayashi - I think it say in the warning itself what can be done - if you do want to do something about it :-)
