### ISSUE TITLE
Minor issues with the latest version

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#253]
Hello!

I've gotten around to updating my own projects to work with the latest TiddlyMap version, and I'm noticing a few minor issues.

1. In **edge-type-handler/filter** on line 51: `utils.getMatches(filter, toWL)` fails to interpret because `toWL` is not defined. It looks like it can just be removed; worked for me. Though you may consider that a bad solution as it has the filters consider _everything_ again.
2. In **TranscludeEdgeTypeSubscriber** on line 38: the `canHandle` method looks like it's testing for the wrong namespace:name pair. It's "tw-body:link" and I'm pretty sure "tw-body:transclude" is correct. Probably just a copy-paste error?
3. You've switched TiddlyMap over to using EC6 syntax and you're piping the source through babel. That's cool; it does make the code cleaner. However, people writing plugins like me (and maybe this was just me because I wasn't familiar with babel), might hit some confusion when trying to write modules such as edge managers. `import` and `export` are not supported innately in TiddlyWiki, so unless someone is writing a plugin through NodeJS and they're able to use babel themselves, they have to resort to interacting with your base classes without it. It's possible. I got it to work, there was about an hour of getting weird errors because `export default AbstractRefEdgeTypeSubscriber` actually puts the class under `exports.default` and not `module.exports` or `exports.AbstractRefEdgeTypeSubscriber` like I was expecting. Honestly, this might not be an issue, just my inexperience, but I didn't figure out what was going on until I studied the uglified, generated dist code. Maybe just a single line comment near the exports might clear it up for anyone else doing in-browser work (my work is a mix of both NodeJS and in-browser)?

All minor issues, otherwise I really like the changes. The babel thing might just be me being an idiot. Feel free to ignore. I may switch over to babel myself. It really does clean the code.

-Flibbles

**Comment by flibbles** [comment]
By the way, I can provide fixes for those first two points and make a pull request...

Not a problem. Already done on my repository.

**Comment by felixhayashi** [comment]
Hi @flibbles,

many thanks for the feedback and great to hear you updated your projects to the new version. Sorry for the inconvenience with EC6, I'll make a few comments in the GitHub README about this. 

Yeah, it would be nice if you could do a PR. Your first point is indeed a copy paste error. In case of your second point: i got the whole function signature wrong in `TranscludeEdgeTypeSubscriber`, it should be `getReferencesFromField(tObj, fieldName, toWL)` (see also the call made from here: https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/js/edgeTypeSubscriber/AbstractMagicEdgeTypeSubscriber.js#L76).

Best wishes
Felix

**Comment by flibbles** [comment]
Pull request made.

**Comment by felixhayashi** [comment]
Hi @flibbles, merged it, thanks!
