### ISSUE TITLE
reset layout for wizened ‎maps

### ISSUE THREAD

**Issue by mll0** [felixhayashi/TW5-TiddlyMap#254]
Blessed be TiddlyWiki and TiddlyMap which I just discovered !

Yet, while making a map, it looked very wizened ‎and barely readable:
https://i.imgur.com/k0OGc4y.png

Is it possible to have it automagically rorder its nodes, quite like the live view does ?

**Comment by tobibeer** [comment]
With the amount of tiddlers you want displayed, I think a "hyperbolic tree" would be a more meaningful representation. Would be cool if vis.js at some point supported something like:

https://www.youtube.com/watch?v=pwpze3RF55o

...an if it could be switched to by ticking a checkbox.

**Comment by felixhayashi** [comment]
Hi @mll0 

> Blessed be TiddlyWiki and TiddlyMap which I just discovered

thanks :)

>Is it possible to have it automagically rorder its nodes, quite like the live view does ?

sure, just go to the view config and put it to "floating nodes". You could also change the physics settings for your view.

But I have to say, such a dense graph is hard to arrange, as each node is connected with at least two other nodes...

> I think a "hyperbolic tree" would be a more meaningful 

Yeah, but as you said it already, it really depends on what visjs provides.

Best wishes
Felix
