### ISSUE TITLE
Change node-type for existing nodes.

### ISSUE THREAD

**Issue by feluxe** [felixhayashi/TW5-TiddlyMap#258]
Hi there,

thanks for this amazing mind-mapping tool! I tried several open source mind-mapping tools for Linux the last couple days and this one is by far the best. It's simple and intuitive and I really enjoy working with it!

There is one thing I couldn't figure out, though:
I have a bunch of *nodes* which I would like to style differently. I know that you can create styles (*types*) for *edges* and *nodes*. It works fine for *edges*. I just have to double click the arrow and select a *type*. But when I try to change *nodes* the same way, I can't find any *types* to choose from. In the *Edit Node* menu I can't find anything either. May I ask how to do this?

**Comment by felixhayashi** [comment]
Hi @feluxe 

many thanks for the positive feedback :)

> I can't find any types to choose from. In the Edit Node menu I can't find anything either. May I ask how to do this?

You need to open the node type manager in the menu dropdown and then just start typing a name. a plus button should appear that allows you to add a new node type.

What is strange is that if the list is empty, the plus button should also be visible at the very beginning. I should fix that!
