### ISSUE TITLE
don't set fixed filterbar height

### ISSUE THREAD

**Issue by tobibeer** [felixhayashi/TW5-TiddlyMap#26]
Use min-height instead...

![minh](https://cloud.githubusercontent.com/assets/97566/5711836/cbe13f62-9aad-11e4-95b3-f2154528d605.jpg)

![minhfixed](https://cloud.githubusercontent.com/assets/97566/5711869/0c5e6830-9aae-11e4-9030-2475cffd4deb.jpg)

Perhaps also give those in-graph buttons the background color of the graph?

**Comment by felixhayashi** [comment]
good point. now editor cannot grow smaller than 350px.

> Perhaps also give those in-graph buttons the background color of the graph?

I cannot style the buttons because its png and provided by vis...

**Comment by tobibeer** [comment]
Not sure what you mean, but you can sure give...

`network-manipulationDiv`

...a background other than transparent, if you wanted to.

**Comment by felixhayashi** [comment]
Ok, this was a misunderstanding I thought by graph buttons you mean the *navigation buttons*. But you are talking about the *manipulation buttons* in the graph's manipulation bar.

Yes, I think I should add a background color.

**Comment by tobibeer** [comment]
Also, not sure how much effort is involved, it would be helpful if all tiddlymap classed had a common class prefix assigned to them, e.g. **t-map** or some such, e.g. **t-map-graph**, **t-map-graph-button**, **t-map-graph-filters-button**, etc...
