### ISSUE TITLE
Zoom into map with mousewheel

### ISSUE THREAD

**Issue by Acknar** [felixhayashi/TW5-TiddlyMap#260]
Hi, 
I asked a while back for a way to use the mouse-wheel to zoom into a map rather than having to use the mouse-wheel with hotkeys. Since ctrl+mouse-wheel doesn't work in Firefox and I also need my site to be user-friendly for low-end users, hotkeys aren't a valid option in my opinion. You explained it was necessary for mobile navigation but my site doesn't really have mobile use in mind. My whole site revolves around these maps, and the maps are rather useless without the ability to zoom and see what you are clicking on. Could you tell me how to get rid of those hotkeys? For a next release, I'd suggest adding a button in the same manner as the full-view one to activate zooming so as to make the map usable on mobile without hindering navigation through the site.

**Comment by felixhayashi** [comment]
Hi @Acknar,

sorry for the delay, I can imagine that it is frustrating not to be able to zoom. I am quite busy at the moment but I'll try to fix this at the weekend.

Best wishes
Felix

**Comment by felixhayashi** [comment]
Hi @Acknar 

the ctrl key works in firefox now.
Moreover, if you go to the map menu, click the "grab widget code" button and then select "click to use" and copy the widget code and paste it into a tiddler, you will be able to zoom without the ctrl key – however, the user needs to click into the widget once to "activate" the map.

Hope this suits your needs.
Felix

**Comment by Acknar** [comment]
Hi,
Thanks, I didn't know the "click to use" option allowed simple scroll-wheel navigation. This is a satisfying solution thanks.
