### ISSUE TITLE
Cannot open tiddlywiki with tiddlymap in Internet Explorer 11

### ISSUE THREAD

**Issue by rlaza** [felixhayashi/TW5-TiddlyMap#262]
Hello Dev Team,
I have installed current latest TiddlyMap 0.13.2+9628 to current latest TiddlyWiki 5.1.13 and have realized that when I try to open it in **Internet Explorer 11**, I get Internal JavaScript Error, **Object doesn't support property or method 'assign'.**
Same message is also raised when trying to open www.tiddlymap.org site. I have tried to open the site on three windows machines running Windows 7 and IE11 with same result.
In Firefox tiddlymap works properly.
In IE it works only when I disable the TiddlyWiki plugin.
I am trying to publish tiddlywiki with tiddly map on internal Sharepoint site in company where default browser is unfortunately IE11.
Please advise.

Thank you,

Radek.

**Comment by felixhayashi** [comment]
Hi @rlaza 

sorry to hear that.

I am working on a linux machine so I cannot really check whats going on. The only browsers that I can offer support for are Chrome and Firefox.

Maybe I can figure out at some point whats causing this in IE11 but I am sorry to say that this won't happen in the near future, so your only chances to work with TiddlyMap is with FF or Chrome (or Safari or Opera, which work as well but are not officially supported) :(

Best wishes
Felix

**Comment by georox** [comment]
Hi Felix,

It would be great if you could look into IE11 compatibility for TiddlyMap. Maybe it's something relatively minor to fix? For some users on corporate intranets, this legacy browser is their only option for running TW.

Microsoft provides a free VirtualBox VM for IE compatibility development that you can download from here:
https://az792536.vo.msecnd.net/vms/VMBuild_20180102/VirtualBox/IE11/IE11.Win7.VirtualBox.zip (5GB)

I would be happy to provide financial support for this feature, if necessary.

Thanks for your consideration,
Georo

**Comment by felixhayashi** [comment]
Hi @georox I understand the problem but supporting IE11 would consume too much time. I would need to polyflll missing functions and always look out not to break things in the future. It is not just about the missing `Object.assign`. It would also mean I need to be careful with css/stylings etc. 

What about another solution: Why not use a portable version of chrome or firefox that doesn't need to be installed? This ways corporate user can also use it without installing any software.

Further reading:

* https://medium.com/gtricksdotcom/how-to-easily-use-chrome-without-installing-it-43929b83e9e1
* https://portableapps.com/apps/internet/google_chrome_portable
