### ISSUE TITLE
IPFS support

### ISSUE THREAD

**Issue by uzerus** [felixhayashi/TW5-TiddlyMap#263]
New InterPlanetary File System protocol (what aims to replace http(s) ) is currently in alpha, but this alpha is usable and stable (in mean all is working fine, without heavy buggs, buggy things are shortly repaired).

Support for things like creating new pages (what is a problem of IPFS, cos it's working on static files), it must be hashed again after every change of a single file. 

One guy tried do a plugin for IPFS on TW5, maybe its official, idk. https://github.com/sbruce/TW5-ipfs but better documentation for that is welcome. 

Another guy did a minimal wiki dedicated to ipfs https://github.com/jamescarlyle/ipfs-wiki

You can try yourself the IPFS on your local PC.  @ [ipfs.io](https://ipfs.io)

I am not a programmer, but i want to be one, so i only can help by finding goodies at internet :+1:

**Comment by felixhayashi** [comment]
Hi @uzerus, thanks for this interesting text :) Yet, I do not seem to grasp the relationship between IPFS and TiddlyMap… please be more specific about the aim of the issues you create and how they relate to the TiddlyMap project.
Best wishes
Felix
