### ISSUE TITLE
The Family Chart Isn't So Good :-) 

### ISSUE THREAD

**Issue by TiddlyTweeter** [felixhayashi/TW5-TiddlyMap#264]
For a long time I held back from commenting on http://tiddlymap.org/#Using%20the%20Map%20Raster. 

NOT the raster illustration, but the depiction of family connections.

I'm an anthropologist & TiddlyWiki enthusiast.

I tried to use TiddlyMap to depict kinship charts. **It doesn't work for that, unfortunately.** 

Why? Because Western kinship is BI-LATERAL, meaning that descent is from the joining of TWO people. The way you depict it in your diagram is UNI-LINEAL descent. As if there were only ONE parent. That applies to a few societies (strictly "Matrilineal" or "Patrilineal"), but not to most Westerners who have bi-lateral descent.

I am in no way criticising what you have done, and it does no damage to leave it be.  

But what it brought out for me is that the Javascript library behind TiddlyMap isn't suited to that kind of relationship diagram as soon as you have "marriage" or "partnership", which requires the CONJUNCTION of two entities (man, woman) to be the branch point, NOT them individually.

Love your work & am very grateful for it.

Best wishes
Josiah

**Comment by felixhayashi** [comment]
Hi @TiddlyTweeter 
many apologies for the late reply.
Sad to hear that TiddlyMap does not cater for your need to draw kinship diagrams. While TiddlyMap is good at depicting networks and relations, it only does so by relying on a very primitive node-arrow syntax, which is not exactly what is needed when drawing kinship diagrams :(  …maybe somebody jumps in and creates a dedicated plugin for this as I can imagine it to be quite common for people to map their ancestry lines.
in any case: thanks for your kind words and for giving me some insights about your usecase.
I hope you still find TiddlyMap useful for some other tasks. 
Best wishes
Felix
