### ISSUE TITLE
How to modify popup behavior

### ISSUE THREAD

**Issue by Acknar** [felixhayashi/TW5-TiddlyMap#266]
Hi felix, 
I'd like to know where I can modify the popup behavior to display title and picture (and make them centered) rather than have description text displayed.

**Comment by felixhayashi** [comment]
Hi @Acknar,
the tooltip field is per default the text (the body) of the tiddler in focus. you can, however, add a `description` field to the tiddler and add wikitext which will be rendered. using wikitext means you can make  use of widget-markup in the `description` field to e.g. transclude the content of another tiddler, e.g. an image.
best wishes
felix
