### ISSUE TITLE
bug report : Using URL parameters doesn't work

### ISSUE THREAD

**Issue by lejocelyn** [felixhayashi/TW5-TiddlyMap#267]
I tried using URL parameters but it doesn't work. For instance, if I typed : 
http://tiddlymap.org/?tmap-enlarged=fullscreen&tmap-view=Quest

I get : 
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
ReferenceError: mainEditor is not defined

**Comment by felixhayashi** [comment]
thanks for reporting, I will have a look at it.
