### ISSUE TITLE
Question : Halfscreen mode by default ?

### ISSUE THREAD

**Issue by lejocelyn** [felixhayashi/TW5-TiddlyMap#268]
Hi, I'm trying to use Tiddlymap as a navigation system for an online exhibition experiment. For this, I'd like to have halfscreen toggled on by default. I can't figure out how to do so. Any idea ?

**Comment by felixhayashi** [comment]
yes, this is possible with url parameters, however as you noticed, it seems to be broken at the moment (#267)
