### ISSUE TITLE
Assign prefix to all tiddlymap classes

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#27]
By @tobibeer

> Also, not sure how much effort is involved, it would be helpful if all tiddlymap classed had a common class prefix assigned to them, e.g. t-map or some such, e.g.

> t-map-graph
> t-map-graph-btn
>  t-map-filterbar
>  t-map-filterbar-btn
>  t-map-tiddler-btn
>  t-map-popup-foo
>  etc...

> ...but don't sweat about it

**Comment by felixhayashi** [comment]
Good Point, I already used `tmap-` as prefix for some parts (e.g. for all the fullscreen classes). I was just afraid to update all other css since I need to be careful when doing it but you're right, it should be done and it's on my list.

-Felix

**Comment by tobibeer** [comment]
great job, @felixhayashi!

the little things may just turn out quite important later down the road

**Comment by felixhayashi** [comment]
Jap, I think so too :)
