### ISSUE TITLE
Complete Uninstallation

### ISSUE THREAD

**Issue by diego898** [felixhayashi/TW5-TiddlyMap#271]
I installed tiddlymap to try to it out. When I first installed there was a popup that ran letting me know that since this was my first install it went ahead and made changes to tiddly to make it behave better with tiddlymap. 

After having decided I did not need tiddlymap right now, I went ahead and disabled all 4 of the plugins and restarted. But those "extra changes" persisted. For example, I had to go back and change my wiki to once again be fluid story, fixed sidebar. How do I **completely** undo all changes made by tiddlymap to my wiki? How do I completely uninstall it?

**Comment by felixhayashi** [comment]
Hello @diego898,
disabling or removing tiddlymap in tiddlywiki will effectively uninstall it. The settings that tiddlymap changed at the time it was installed have to be reset manually, however, so far that only means you have to reset the the "fixed sidebar" and the "opening behaviour" of tiddlers.

Nonetheless, I think it would be a good idea to inform the user beforehand about the changes tiddlymap is about to perform and to ask whether that is ok (I created a ticket for that: #272).

**Comment by diego898** [comment]
Thanks for the reply. I also see I have a `tmap.id` and `tmap.edges` fields across all my tiddlers now. How can I remove those from all tiddlers?

Also, I see there is a `not nice` tag to this question. I apologize if my question came off as rude. I appreciate all your efforts toward TiddlyMap.

**Comment by felixhayashi** [comment]
Hi @diego898,

> Also, I see there is a not nice tag to this question. I apologize if my question came off as rude. I appreciate all your efforts toward TiddlyMap.

Thanks. Everything is fine, the "not nice" is simply an indicator for me that some tiddlymap behaviour is not nice but it is not "bug" :)

> I also see I have a tmap.id and tmap.edges fields across all my tiddlers now. How can I remove those from all tiddlers?

That's true. You could remove these fields by pasting the following lines alltogether in your javascript developer console (opens by pressing F12). The command will iterate over all tiddlers and remove the unwanted fields.

**Disclaimer**: This should effectively remove the unwanted fields while leaving your wiki intact, nonetheless, make sure to create a backup of your old wiki for safety reasons before executing the command to prevent any unforseen loss of data. I am not responsible if something breaks or data is lost.

```
$tw.wiki.forEachTiddler(function(tRef, tObj) {
  $tw.wiki.addTiddler(new $tw.Tiddler(tObj, {
    'tmap.id': undefined,
    'tmap.edges': undefined,
  }));
});
```

In the console it would look like this after pasting, then you just hit enter to execute it.

![2017-10-31 10 40 12](https://user-images.githubusercontent.com/4307137/32217326-f0a1b71e-be27-11e7-88a5-5283c8ba5828.png)

Hope this helps :)
Best wishes.
Felix
