### ISSUE TITLE
Question: switching from vis.s to d3.js?

### ISSUE THREAD

**Issue by diego898** [felixhayashi/TW5-TiddlyMap#274]
Just curious to hear you're thoughts about this topic -

 Have you ever thought about switching to d3.js? Would it be difficult/hard? Would it offer performance improvements/loss? Why did you choose vis.js instead of d3.js? 

Thanks for your excellent work!

**Comment by felixhayashi** [comment]
Hi @diego898 

the reason I chose visjs over d3 is that visjs already comes with a graph-manipulation GUI (creating deleting nodes, drawing edges) including an event-subscriber system for all these events, that's something you cannot do with d3. So visjs is designed to manipulate data, while d3 is rather a way to visualize data.

Switching to d3 would be difficult as TiddlyMap depends on the visjs actions and GUI. I added several visjs-independent middlewares that allow to create and modify nodes/edges without having to use visjs, but for the whole node/edge styling and manipulation TiddlyMap heavily depends on visjs.

> Thanks for your excellent work!

Thanks :)

Best wishes
