### ISSUE TITLE
Content Structuring with TiddlyMap

### ISSUE THREAD

**Issue by samuelwiechmann** [felixhayashi/TW5-TiddlyMap#276]
Hello,

before I start: thank you all very much for creating such a beautiful piece of software. I really appreciate it :)

I am currently creating a TiddlyMap trying to capture and structure as much interesting content as I can. It is continuously updated, but you can have a look at: [https://samuelwiechmann.github.io/understand2/](https://samuelwiechmann.github.io/understand2/)

The basic idea is to include myself into the view to clarify my relation to the content. This is necessary because many of the relations between topics are subjective and I want to make visible that the map only reflects my personal view.

**The map runs smooth** on my computer, but on a less powerful computer it is quite slow.
My first approach in order to increase performance would be to simplify node styles by reducing the amount of different colours and font sizes. What I would not like to do is to break up the map into different topics and make navigation to a specific topic only possible by clicking a node. This would rather be suitable for opening a whole new view that represents the perspective of the corresponding field, e.g. "Psychology", because a psychologist might select and link the topics in a completely different way.

**The hope for this approach of modeling different views inside the same knowledge base is to really visualize different world views and thus make them easy to understand.**

This might be a bit far into the future, but connecting those different views with each other is an interesting topic to me. The greatest thing I can imagine would be a multidimensional network-graph with different views modeled as different perspectives of the whole structure. I imagine you could actually **pan and tilt your perspective until it matches someone elses perspective.**  
But for now it would just be great to have some kind of connection between the node locations in different views to make orientation after switching views easier.

I also imagine creating past world views to show how the world has changed from a human perspective. It would then not just be a continuously changing knowledge representation, like Wikipedia, but also a documentation of what has been held as true and important in the past.
Going back as far as the big bang, I could also imagine visualizing the growth of complexity in our universe, a growing map with more and more things popping into existence while the oldest things (like gravity) just remain there forever. I guess this could somehow implemented with the moment.js library, but actually it's not very important right now.

So, this should be enough for now. 

If you have any suggestions, ideas or comments, you're welcome :)

**Comment by felixhayashi** [comment]
Hi @samuelwiechmann,

thanks for your positive feedback and for sharing your use case.

That map looks impressive and I think TiddlyWiki + TiddlyMap is the right tool to capture your personal perspective on matters and to portray entities and their relationships in different constellations (views). 

> The map runs smooth on my computer, but on a less powerful computer it is quite slow.

1. Use Chrome!! runs x times faster than Firefox or other browsers.
2. Use non-floating maps! + consider resetting your physics settings because edges look strangely drawn to the center afterwards with your existing settings.
3. Consider disabling "smooth" edges (under "edit view"). This will make it faster but the drawback is that edges will not magicaly move away from each other anymore.
4. Although you mentioned that this is not an option; still mentioning it for the sake of completeness in case other people read this: Outsource some parts of your view into different views. You can link nodes to views by selecting a node and editing its "local node style" modifying the "open view". – you can cut and paste nodes from one map to another using keyboard shortcuts (see docs). Make a backup before doing these operations!
5. As you mentioned: Don't use too many styles in your map. However, your map does not look overloaded with styles.

> This might be a bit far into the future, but connecting those different views with each other is an interesting topic to me. The greatest thing I can imagine would be a multidimensional network-graph with different views modeled as different perspectives of the whole structure. I imagine you could actually pan and tilt your perspective until it matches someone elses perspective.

Sounds interesting. The cool thing about TiddlyMap here is that you can display the same concepts in different maps. You can also use filters to hide edges in different views. So in a view "love" the compound "bob loves alice" is shown and in a view called "family" "bob engaged with alice" is displayed. (see docs on using filters)

> But for now it would just be great to have some kind of connection between the node locations in different views to make orientation after switching views easier.

The problem is that the node might exist in the other view so it cannot be centered. Nonetheless I added a ticket: #277.

>  also imagine creating past world views to show how the world has changed from a human perspective. It would then not just be a continuously changing knowledge representation, like Wikipedia, but also a documentation of what has been held as true and important in the past.

Again interesting idea :) But don't lose yourself in trying to capture all the knowledge and changes of this world, there is way too much out there than a person is capable of reflecting about – which makes it a difficult and never ending task ;)

Best wishes

**Comment by samuelwiechmann** [comment]
Hi @felixhayashi,

thank you for you reply! Glad to hear that you think this is the right tool. 
Unfortunately, I didn't notice your answer right away, even though I've been working on GitHub all the time.

1. I will try, but I think Opera also does its job pretty well.

2. I guess non-floating maps are a "must" if you have less computing power, so this is my default now.

3. This is a good idea! I don't really care about the edge labels, so it doesn't really matter.
   I would rather like to have the nodes avoid overlapping each other.
   In the [vis.js physics documentation](http://visjs.org/docs/network/physics.html) I noticed that the forceAtlas2Based solver also provides an **"avoidOverlap"-function**.
Is there an easy enough way for me as someone who at least learned Java in school to include that parameter into TiddlyMap or, even futher, **switch to another gravity model like "barnesHut"?**

4. I think the one thing bloating my map are all the images I use for most of the "content"-nodes. They are nice because you can see a snapshot of what awaits you behind the link, but **I think they are the real bad guys**. Any ideas on how to better integrate images into the map (or get rid of them and replace them) are welcome.

5. I simplified the styles by overlaying two different kinds of styles: One for the font size and one for the color. This doesn't make the map notably faster but **it works good and makes editing the styles much easier.**


>  The cool thing about TiddlyMap here is that you can display the same concepts in different maps. You can also use filters to hide edges in different views. So in a view "love" the compound "bob loves alice" is shown and in a view called "family" "bob engaged with alice" is displayed. (see docs on using filters)

**This is indeed really cool!** There had been no way of doing this in Cmap Tools, but for polyscopic modeling, as Dino Karabeg coined it, this is key. How can you model different networks if you cannot define which connections to show in which view?
The thing I still got no clue on how to do it is the multidimensional network of multiple views. But as I said, this is a bit into the future as I only got one view so far. **First I got to figure out how to effectively use 2D maps.**

> The problem is that the node might exist in the other view so it cannot be centered. Nonetheless I added a ticket: #277.

I think I don't quite understand the problem here. What I imagined was a map with a unified physics simulation. So I would see different views as different layers of visibility and similar nodes connected between those views would pull each other to similar locations (but still have some freedom).

But I'm also thinking about how I can make the transition between a normal Tiddler and the map. It's great that I can embed a map into a Tiddler but since I am using a very large map it would also be great to **define a zoomed in detail of one view** (and also be able to embed it in a Tiddler).

Another great option, getting more complicated now, would be to **set the zoom depth for the search function** to determine how far the map will zoom in on the searched node.


> But don't lose yourself in trying to capture all the knowledge and changes of this world, there is way too much out there than a person is capable of reflecting about – which makes it a difficult and never ending task ;)

Great piece of advice :) 
But I see the chance to make a point here. I believe that when you assess information from the point of view of its effect on its recipient, then suddenly there is not so much information that is really important. 
And with the right tools and the right mindset this selection of relevant information could soon be automated.
Also I see a lack of content on the web really capturing the history of our universe in one crisp animation. What I would love to build is a kind of animation that shows how complexity has built up over time. you could just move a time slider and things would split apart and come together to form new things. 
I could imagine doing this with a 3D model where one axis represents time and the slider represents a cutting plane defining what is visible to the user.
But again, this is too far off and I have to continue working on what I have.

You can take another look at [the map](https://samuelwiechmann.github.io/understand2/) as there is now much more content added. 

Again, thank you very much for your feedback :)

Kind regards

Samuel

**Comment by samuelwiechmann** [comment]
> 4. I think the one thing bloating my map are all the images I use for most of the "content"-nodes. They are nice because you can see a snapshot of what awaits you behind the link, but I think they are the real bad guys. Any ideas on how to better integrate images into the map (or get rid of them and replace them) are welcome.

I am now going to set all "content"-nodes to just be "dots". No image, no title. I am quite sure that the map will run very smooth even with a big amount of nodes. 
The tile, as well as info and image will only be visible via mouseover or opening the Tiddler.
But in return I will have the opportunity to scale the dots according to relevance or simplicity and colour them by their type (video, talk, article, etc.).

**Comment by felixhayashi** [comment]
> Is there an easy enough way for me as someone who at least learned Java in school to include that parameter into TiddlyMap or, even futher, switch to another gravity model like "barnesHut"?

It is on purpose that I whitelisted the visjs parametrization the user is allowed to do.
See https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/js/widget/ConfigurationWidget.js#L296
I did this so it is easier for me to integrate visjs in Tiddlymap and to ensure the average user does not overconfigurate (=slowdown/break) the application.

I am planning on upgrading the vis.js version and maybe I can then add the "avoidOverlap" config to the whitelist so it appears in your menu.

> any ideas on how to better integrate images into the map (or get rid of them and replace them) are welcome.

I think your decision to use a different shape for your nodes is the way to go as it effectively overrides the images.

> I think I don't quite understand the problem here. What I imagined was a map with a unified physics simulation. So I would see different views as different layers of visibility and similar nodes connected between those views would pull each other to similar locations (but still have some freedom).

Oh, then I didn't quite get your point. What you describe is a bit too abstract for me :)

> But I'm also thinking about how I can make the transition between a normal Tiddler and the map. It's great that I can embed a map into a Tiddler but since I am using a very large map it would also be great to define a zoomed in detail of one view (and also be able to embed it in a Tiddler).

Hmm, this is a bit difficult, I'll have to brainstorm about this.

> But I see the chance to make a point here. I believe that when you assess information from the point of view of its effect on its recipient, then suddenly there is not so much information that is really important.

Good point, but it really depends on the fluctuations in the recipient's focus/interest changes ;)

> just move a time slider and things would split apart and come together to form new things.

While this might not be exactly what you are envisioning, it may be also worth playing with this project: https://github.com/kixam/TW5-visjsTimeline (http://kixam.github.io/TW5-visjsTimeline/). You could map tiddlers representing your views to a timeline.

> You can take another look at the map as there is now much more content added.

Looks impressive :) 
I have read your "Project origin", glad somebody also felt that a wiki-map tool is a good combination.
I think you wiki-theme doesn't work well with tiddlymap though.

best wishes
