### ISSUE TITLE
filter edge types can't handle currentTiddler-referencing filters

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#278]
Hello! I'm back. Even though I've been silent a while, it's only because Tiddlymap has been working just fine for me. I'm still using it all the time. My project is nearing 2000 tiddlers now, and it would be impossible without this plugin.

I did discover a bug today though:

If you have an edge type __tw-filter:foo__, and a tiddler displayed on the map has field __foo__ equal to something like `[all[current]has[somefield]get[listfield]]` or `[<currentTiddler>...]` or `[{!!otherfield}...]` or _anything_ which requires access to the variable _currentTiddler_, Tiddlywiki will throw an exception upon rendering the map. And also whenever you do basically anything while you have the map up.

However, I've already got a fix. It's on my fork of the project (master branch), and I can do a pull request if you like. The gist of it is changing the `getReferencesFromField` method in FilterEdgeTypeSubscriber to this:

```javascript
/*** Imports *******************************************************/

import Widget from "$:/core/modules/widgets/widget.js";

.
.
.

/**
 * @override
 */
getReferencesFromField(tObj, fieldName, toWL) {

    const filter = tObj.fields[fieldName];

    const parentWidget = new Widget.widget({});
    parentWidget.setVariable("currentTiddler", tObj.fields.title);
    const widget = new Widget.widget({}, {"parentWidget": parentWidget});

    //noinspection UnnecessaryLocalVariableJS
    const toRefs = utils.getMatches(filter, toWL, widget);

    return toRefs;

}
```

Also, `utils.getMatches` needs to pass along that _widget_ argument to `filter.call`. But that's it.

Since these filters are not being called in the context of a widget, I'm just mocking one up (and it's parent because that's necessary for some reason), which can be used to do _currentTiddler_ lookups. No other variables are available, but none other would make sense in this context.

This is just my fix. If you've got a more appropriate way of fixing it, that's cool. Also, no rush, since I've got this fix on my version, and I know I'm probably the only person who uses these filter edge types.

Thanks,
Flibbles

**Comment by felixhayashi** [comment]
Hi @flibbles,

many thanks for bringing this up and already providing the fix!
Glad you are still happy with TiddlyMap. I am also not too active on the TiddlyMap repo myself, only here for fixing bugs, collecting ideas and answering questions. Too busy with my day jobs. Hopefully at one point I find some time to add some more features to the software again :D

> Since these filters are not being called in the context of a widget, I'm just mocking one up (and it's parent because that's necessary for some reason), which can be used to do currentTiddler lookups. No other variables are available, but none other would make sense in this context.

You are right with the parentWidget thingy. just double checked and found it [here](https://github.com/Jermolene/TiddlyWiki5/blob/ffc0899f52b45ba2b5a5a20fb909dcc587e80b3e/core/modules/widgets/widget.js#L93). To me, this definitely looks like a bug on TiddlyWiki's side as `widget.hasVariable` [would return true](https://github.com/Jermolene/TiddlyWiki5/blob/ffc0899f52b45ba2b5a5a20fb909dcc587e80b3e/core/modules/widgets/widget.js#L186) if a variable were set on the widget itself yet `getVariable` would still return `undefined` (unless it is set in the parent). Could be worth creating a TW issue at its repo, I don't know...

Anyhow, please open a PR and I will be happy to merge this. Please add a small comment above the added code at [this](https://github.com/flibbles/TW5-TiddlyMap/commit/651b2b8e4d11c8ecf8dbbe38db6e023ee19e3773#diff-56f385541634a700024629038fbf96efR51) line saying:

    // Solves https://github.com/felixhayashi/TW5-TiddlyMap/issues/278

Best wishes
Felix

**Comment by flibbles** [comment]
Pull request made.

Tiddlywiki issue at https://github.com/Jermolene/TiddlyWiki5/issues/3196 if anyone wants to know.

**Comment by felixhayashi** [comment]
Many thanks @flibbles. I'll publish a new version the next days that includes your fix.
