### ISSUE TITLE
exporting tiddler as HTML that contains a map will throw an error

### ISSUE THREAD

**Issue by dipenpatel235** [felixhayashi/TW5-TiddlyMap#283]
Hello..
i have created tiddly map but getting error same as below screenshot.

then i have try to check from your link with tiddlymap so in that also getting same error.
below is screenshot of that.

![screenshot 2018-04-24 12 01 27](https://user-images.githubusercontent.com/8135097/39169983-6fd333aa-47b7-11e8-80c0-c9f0c3205d13.png)

Thanks

**Comment by felixhayashi** [comment]
Hi @dipenpatel235 this is most likely not TiddlyWiki related. Please post such issues at the TiddlyMap repo: https://github.com/felixhayashi/TW5-TiddlyMap/issues.

Does this error occur just by visiting tiddlymap.org?
In this case, I assume it is an issue with your browser or one of your plugins.

**Comment by myvolkov** [comment]
Hello @felixhayashi!
I have the same bug:
![tidm](https://user-images.githubusercontent.com/44474329/47512516-0fac4c00-d885-11e8-8226-3d62620355cf.png)
I reproduced it on a different browsers and computers. (Windows/OS X, firefox, chrome, safari)
If you need some debug data I can provide it.

**Comment by felixhayashi** [comment]
Hi @myvolkov yes, please tell me in which situation it occurred.

**Comment by myvolkov** [comment]
Hi, sure.
I opened http://tiddlymap.org chose tiddler "TaskManagementExample 2.0" and clicked "export tiddler" to "Static HTML" and got error - "TypeError: el.classList is undefined"

**Comment by felixhayashi** [comment]
@myvolkov many thanks, I can reproduce that. :+1:  will fix it.

**Comment by felixhayashi** [comment]
fixed @myvolkov

**Comment by myvolkov** [comment]
@felixhayashi Thanks a lot,  export to static HTML works fine! But there is no preview image in resulted html-document. I tryed https://github.com/felixhayashi/TW5-TiddlyMap/issues/178 but it dosen't work for me.
![nopreview](https://user-images.githubusercontent.com/44474329/47590342-af94d300-d974-11e8-9d11-d4fe1b0135ed.png)

**Comment by felixhayashi** [comment]
Thanks @myvolkov, I created a dedicated ticket for this follow-up bug! #299
