### ISSUE TITLE
Feature-Request: variable physical constats depending on edge type

### ISSUE THREAD

**Issue by andresgongora** [felixhayashi/TW5-TiddlyMap#284]
**Is it possible to configure each edge type to have its own physical properties (i.e. spring length and constant)?**
In my particular cases I have a set of tiddlers tagged with a hierarchical structure, which looks gorgeous when I only plot the tag-edges. However, each tiddler links to a dozen or so other tiddlers, which, when plotting link-edges, completely obscure the former tag relationship. By having stronger physical constants for tag-edges than for link-edges I hope to overcome this problem. 
**Similarly, would it be possible to assign different physical constant depending on node type (i.e. gravitational constants)?**

**Comment by andresgongora** [comment]
Similarly, would it be possible to assign different physical constant depending on node type (i.e. gravitational constants)?

**Comment by felixhayashi** [comment]
Hi @andresgongora I am afraid this is not possible at the moment as this is not offered by visjs (http://visjs.org/docs/network/edges.html). The only edge options are those shown.

> Similarly, would it be possible to assign different physical constant depending on node type (i.e. gravitational constants)?

Neither is this possible. Visjs doesn't allow to change the physics setting per node :(

**Comment by andresgongora** [comment]
Oh, what a pity. Let's hope they add new features soon :)
Any way, thanks a lot for your quick reply and your awesome work!!

**Comment by felixhayashi** [comment]
You are welcome :) and sorry for these restrictions. Let's see how visjs evolves and hope that they add more features in the future ;)
