### ISSUE TITLE
Utilize Tiddlywiki's built in caching feature

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#286]
_This is a code improvement suggestion._

While I was looking through ViewAbstraction to figure out [node filter updating](https://github.com/felixhayashi/TW5-TiddlyMap/issues/285), I saw that it's implementing it's own caching system for `config`, `nodeData`, `nodeFilter`, and `edgeTypeFilter`.

Take the nodeFilter (which I looked at the most closely):
```javascript
  getNodeFilter(type, isRebuild = false) {

    let filter;

    if (!isRebuild && this.nodeFilter) {

      filter = this.nodeFilter;

    } else {

      filter = utils.makeHashMap();
      const tObj = $tw.wiki.getTiddler(this.nodeFilterTRef);

      filter.raw = (tObj && tObj.fields.filter) || '';
      filter.pretty = utils.getPrettyFilter(filter.raw);
      filter.compiled = $tw.wiki.compileFilter(filter.raw);

    }

    return (type ? filter[type] : filter);

  }
```
If it took advantage of Tiddlywiki's getCacheForTiddler, it would look something like this):
```javascript
  getNodeFilter(type) {

    let filter = $tw.wiki.getCacheForTiddler(this.nodeFilterTRef, "tmap-nodeFilter", function() {
      
      let filter = utils.makeHashMap();
      const tObj = $tw.wiki.getTiddler(this.nodeFilterTRef);

      filter.raw = (tObj && tObj.fields.filter) || '';
      filter.pretty = utils.getPrettyFilter(filter.raw);
      filter.compiled = $tw.wiki.compileFilter(filter.raw);

      return filter;

    });

    return (type ? filter[type] : filter);

  }
```

getCacheForTiddler will only store the same result so long as the underlying tiddler is never changed, otherwise, it flushes that tiddler's cache.

This means:
* ViewAbstraction doesn't need to store `this.nodeFilter`, or any of the others if converted to this system. It never has to worry about calling `_rebuildCache()` or anything like that. It doesn't even have to think about caching.
* I think it'll reduce the amount of unnecessary cache refreshing ViewAbstraction does, since right now it refreshes _everything_ for any kind of change, whereas getCacheForTiddler will only refresh the individual parts as needed.
* No need to explicitly rebuild the cache when calling `getNodeFilter`, or think about caching.

I'm only suggesting this change as a possibility. I know the code already works, and there's a saying about fixing something that isn't broken, and maybe there's a reason why that cache isn't used. But it looked like a nice refactoring. Simpler code, slightly more efficient.

Might be worth considering. And I can always make a PR of it.

**Comment by felixhayashi** [comment]
Hi @flibbles,

> I know the code already works, and there's a saying about fixing something that isn't broken, and maybe there's a reason why that cache isn't used. But it looked like a nice refactoring. Simpler code, slightly more efficient.

Many thanks for pointing that out. Suggestions about making code more readable are always welcome! Looks like a cleaner solution, did you test it? I'll also try it out the next days and if it works, a PR would be highly welcome of course :)

**Comment by flibbles** [comment]
PR made! Did some basic testing, and I'm working on my projects using these changes as well. I'll inform if I encounter any problems.

**Comment by felixhayashi** [comment]
Merged! thanks again!
