### ISSUE TITLE
Deleting edges leave empty garbage fields.

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#288]
When you delete a FieldEdge or a ListEdge in the graph, it can leave behind an empty field. Do this enough in a large project, and your tiddlers will be peppered with many empty, useless fields. Also, depending on your field, and _empty string_ field can have a different meaning from _no_ field.

Take `list-before`. If it's present, but empty, it'll sort it to the top of a tag list.

This means if you have `list-before` or something like it as a FieldEdge, adding the edge, and then deleting the edge does not return the tiddler to it's original behavior.

So I'm proposing that FieldEdge and ListEdge delete those fields if those modified fields would otherwise be empty. I'm creating a PR for this in about 10 seconds.

Actually, etiquette question: Is it okay if I just go straight to creating PRs if I've already got code for a suggestion like this? Or do you still want me to make issues first?

**Comment by felixhayashi** [comment]
I agree and your PR looks good, just a minor code style issue then we can merge this! Thanks!

> Actually, etiquette question: Is it okay if I just go straight to creating PRs if I've already got code for a suggestion like this? Or do you still want me to make issues first?

Sure, go straight for the PRs if you wish ;)

**Comment by felixhayashi** [comment]
Merged! many thanks!
