### ISSUE TITLE
Position node with x and y

### ISSUE THREAD

**Issue by linsteina** [felixhayashi/TW5-TiddlyMap#292]
Hi @felixhayashi 

Is it possible to define the position of a node with x and y? e.g. x = 0, y = 1 in a json format? (answered)

I have a follow-up question about the position of nodes. 
I am using Noetself (https://noteself.github.io/) to connect my TiddlyMap to CouchDB. The positions of nodes are defined in a JSON files for views. But the positions changed every time I reload my TiddlyMap and the new random positions are synced back to the JSON file. Is there a way to fix this? Maybe I should go back to NoteSelf to ask. 

Thanks,

Chun

**Comment by linsteina** [comment]
I found it from the JSON data   "text": "{\n \"nodeid1\": {\n  \"x\": 15,\n  \"y\": 98\n },\n \"nodeid2\": {\n  \"x\": 15,\n  \"y\": 98\n }\n}",

Thanks for making this great tool! @felixhayashi

**Comment by felixhayashi** [comment]
> I found it from the JSON data "text": "{\n "nodeid1": {\n "x": 15,\n "y": 98\n },\n "nodeid2": {\n "x": 15,\n "y": 98\n }\n}",

yeah! :)

> Is it possible to define the position of a node with x and y? e.g. x = 0, y = 1 in a json format?

btw: If you are interested in "programming" with TiddlyMap. There is also an API for tiddlymap generated via jsdoc (but some parts are really poorly documented, maybe even outdated): http://tiddlymap.org/api/

there you can see an example how to insert a node in a view "programmatically":

```
// create a new view
var myView = new $tm.ViewAbstraction("My View", { isCreate: true });

// insert a node in this view
var options = { view: myView };
var node = $tm.adapter.insertNode({ label: "I am a node" }, myView)

// some examples...
myView.getNodeFilter();
myView.saveNodePosition({ id: node.id, x: 4, y: 54});
//myView.destroy();
```

**Comment by linsteina** [comment]
The programming way is absolutely helpful! I do have a project with lots of nodes and edges and I will put them to multiple views. I will have a go.

P.S. Thanks for checking updates and replying to queries efficiently! This really encourages me to continue.
