### ISSUE TITLE
Adapt TiddlyMap for new commenting plugin available in pre-release 5.1.18

### ISSUE THREAD

**Issue by myii** [felixhayashi/TW5-TiddlyMap#294]
Relatively new user of TiddlyWiki & TiddlyMap here.  In fact, TiddlyMap was the killer feature that finalised that decision to adopt -- kudos for this wonderful plugin.

While using 5.1.17, felt the need for being able to comment on tiddlers, so was very pleased to find that there will be an official commenting plugin in 5.1.18.  See:

* https://tiddlywiki.com/prerelease/ -- Comment Plugin
* https://github.com/Jermolene/TiddlyWiki5/commit/acaa07a964a004759ddb8fb755484918b3322815
* https://tiddlywiki.com/prerelease/#$:/plugins/tiddlywiki/comments

Upgraded to the pre-release in order to work with this plugin, which works well.  Have run into a couple of issues in relation to TiddlyMap, though:

1. Live view is flooded with the comments as well, since every comment is a tiddler
    1. Wanted to edit the node filter to prevent these comments from being displayed but that is prohibited: "You must not change the live view's node filter!"
1. Existing comments are not displayed when editing a tiddler within TiddlyMap (i.e. when fullscreen has been toggled)

**Comment by felixhayashi** [comment]
Hi @myii Thanks for the kudos and your feedback :)

> Wanted to edit the node filter to prevent these comments from being displayed but that is prohibited: "You must not change the live view's node filter!"

I see your point. I will think about loosening this rule in the next version.

> Existing comments are not displayed when editing a tiddler within TiddlyMap (i.e. when fullscreen has been toggled)

Can you elaborate on that? Generally speaking, TiddlyMap does not update when a Tiddler is in draft mode. TiddlyWiki creates a new "Draft" tiddler at the time you start editing a tiddler, which is not the same as the "real" tiddler. So only once a draft tiddler is saved it becomes the new "real" tiddler (see TiddlyWiki docs) then TiddlyMap will trigger a rerender. Per design, TiddlyMap does not listen to draft changes in order to avoid performance issues (that would occur if the map gets rerendered on every keystroke).

**Comment by felixhayashi** [comment]
> Existing comments are not displayed when editing a tiddler within TiddlyMap (i.e. when fullscreen has been toggled)

Hmm I think I misunderstood your point. I checked out the new commenting plugin in the prerelease and it seems even TiddlyWiki itself does not show comments in editing mode. Only when exiting edit mode the comments are shown. TiddlyMap behaves exactly the same, it shows correctly comments below the tiddler when in fullcreen mode.

![2018-10-06 23 30 45](https://user-images.githubusercontent.com/4307137/46575966-118a9a00-c9c0-11e8-8b41-dd2a76a245a5.png)

**Comment by myii** [comment]
@felixhayashi You're absolutely right re: editing the tiddler.  To be more specific, I was speaking about the `Preview` tab in TiddlyMap, when in fullscreen mode.  Comments aren't displayed there.

**Comment by felixhayashi** [comment]
> Wanted to edit the node filter to prevent these comments from being displayed but that is prohibited: "You must not change the live view's node filter!"

Fixed in latest release.

**Comment by myii** [comment]
@felixhayashi Thanks for the fix.  Probably a bit late now but I was going to suggest that rather than allowing editing of the node filter for the live view, just adding another filter to cover the comments, since they all have the same prefix:

* `Comment by '{user}' on`

**Comment by felixhayashi** [comment]
> I was speaking about the `Preview` tab in TiddlyMap, when in fullscreen mode.  Comments aren't displayed there.

hmm are we seeing different things?

![2018-10-07 00 15 27](https://user-images.githubusercontent.com/4307137/46576276-308c2a80-c9c6-11e8-87e2-e7e6818dded2.png)

> Probably a bit late now but I was going to suggest that rather than allowing editing of the node filter for the live view, just adding another filter to cover the comments, since they all have the same prefix

yeah thought about that but there is no purpose for another filter field except in the live-view and I cannot conditionally hide the second filter field for other views (where the second filter textfield would not make sense). Hence I just allowed to edit the filter ;)

**Comment by myii** [comment]
@felixhayashi And I believe I've found out why, by the files saved via. TiddlyServer.

When a comment is saved with TiddlyWiki:

* Comment by 'user' on 'Test comments' 2.tid

And when saved with TiddlyMap:

* Comment by 'user' on 'Draft of 'Test comments' by user'.tid

**Comment by felixhayashi** [comment]
Ah that is a deadly dilemma :dagger: 

On the one hand the "preview" in TiddlyMap is only meant to show the stuff in the draft – so unsaved changes. On the other hand, the preview tab uses the original display-template provided by TiddlyWiki that also renders the comments (and if new comments are added they are "owned" by the draft.

**Comment by felixhayashi** [comment]
okay fixed it will upload new version now.

**Comment by myii** [comment]
@felixhayashi Looking forward to it.  I've looked a bit further but it seems a bit more than just the naming of the files... not sufficiently familiar with TiddlyWiki to pinpoint it immediately.  Perhaps something to do with `list` and/or `tmap.id`?

**Comment by myii** [comment]
@felixhayashi That works really well now, thanks.

In terms of d4bae2f8281dca3318f903c962ea33669d030a19:

* I haven't been able to take advantage of being able to modify the live view's node filter -- the comments are still being displayed
    * Tried `-[prefix[Comment by]]` and variations of this
* The only workaround I've found is by adding `-[[tw-list:list]]` to the live view's edge-type filter
    * But this filters more than just comments

If you would be so kind, what is the correct way to filter the comments (and only the comments)?  Note, if the solution doesn't involve modifying the live view's node filter, then d4bae2f8281dca3318f903c962ea33669d030a19 could potentially be reverted.

**Comment by felixhayashi** [comment]
> Tried -[prefix[Comment by]] and variations of this

The problem here is on TiddlyMap's side: TiddlyMap first applies the filters and then loads the "neighbourhood" nodes which are then not filtered :( I agree that this is counter intuitive. Let me have a look whether I can quickly change this behavior so neighbours are also considered by the filter.

**Comment by felixhayashi** [comment]
Here you go, follow the steps in the screenshot and use your node filter `-[prefix[Comment by]]` and it should work. :pray: 

![2018-10-14 02 33 56](https://user-images.githubusercontent.com/4307137/46911365-c3ded600-cf59-11e8-8127-5e75191c11f5.png)

**Comment by felixhayashi** [comment]
@myii if something doesn't work, please leave a comment. thanks.

**Comment by felixhayashi** [comment]
> Splendid, exactly what was needed -- thanks @felixhayashi.

cool. glad to hear that.

> Assertion: No use-case exists where these comments should ever be displayed on TiddlyMap
>    If true, wouldn't it be better to provide this filter by default?

good point – but I want to be backwards compatible, meaning, the original behaviour is that node filters do not affect neighbours. maybe some wikis depend on this and I dont want to break this with an update.

>    Or should this be mentioned in the documentation instead?

definitely. will add it.
