### ISSUE TITLE
New edge-types are not displayed in map until wiki is restarted [affects: > v0.14.0]

### ISSUE THREAD

**Issue by ManuNeuro** [felixhayashi/TW5-TiddlyMap#295]
Hi everyone, I'm pretty new to the Tiddly Community, and I've been very interested in TiddlyMap for organizing my bibliography ... 

But I have trouble to create new 'types' of edges, so I'm not sure if I am getting something wrong here.

So, first thing, I've been following this little tutorial : 
https://www.youtube.com/watch?v=-OES2oe9jqw

- When it comes to the node, the guy in the video enter a new type of nodes, in the old (2016) version from the video, thus, the window displays the following message : " A type with this name does not exist yet and will be created." 
- While in my current (last I guess) version, There is just two 'tags' : the ones I'm creating, and another : 'visible' in green.

=> Then, I click okay, but nothing happened in contradiction to the video ...

- So, I tried to understand what was happening, I've been learning about the existence of the 'namespaces', and if I understood well, while creating this new type, not specifying a namespace for it, it had the effect of adding a default : 'tmap:unknown' type of nodes which is indeed correctly displaying if I use it... Apparently I should always be using a namespace ?

- After that I've tried to add namespace to my edges, but it's still the same issue.

- And last, tried to check theses "filters", I partially get that the "configure view" is key in that displaying all nodes and edges, but I have no clue on how to add my own filters so that the edge types I wanted to create are shown ... 

I think I should be mentioning that I did try the exact same thing directly in the tiddly from tiddlymap.org, and I've been able to successfully use already existing types, but no matter what I've tried, I wasn't able to create my owns... I've also tried to modify styles options, so as to reproduce other existing edges options...

I'm currently working on chrome...

Thanks for your help !

**Comment by felixhayashi** [comment]
Hi @ManuNeuro 

ouch! this looks like a pretty mean bug. the new edge-types are only displayed if saving and restarting the wiki. :( Can you confirm?

Will fix that as soon as possible.

Felix

**Comment by felixhayashi** [comment]
steps to reproduce current bug:

1. go to tiddlymap.org
2. in e.g. "the overview" map create an edge from a node to another using an existing edge-type
3. see the edge being displayed correctly
4. now create an edge from a node to another using a **new** edge-type, e.g. "foobar"
5. see edge not being displayed.
6. save the wiki and restart
7. see edge being displayed.

@flibbles sadly, this bug was introduced with the new way of caching :( Any quick ideas how to fix this? I will also investigate. If we have no luck then I might revert to the old style (without native caching). Any help or hint would be appreciated, thanks.

![2018-10-11 10 38 58](https://user-images.githubusercontent.com/4307137/46791978-8bb17a80-cd42-11e8-8e19-575e6c50fb59.png)

**Comment by ManuNeuro** [comment]
Okay, indeed, what a surprise the day after to see my thousands of edges showing up after saving and refreshing my tiddly ! 

I won't be any helpful on that, but I hope you'll find a solution, thank you and good luck !

**Comment by felixhayashi** [comment]
@ManuNeuro should be fixed now. sorry for this and thanks for raising the issue.

@flibbles fyi: kept your version but introduced cache cleaning (based on tw's native cache cleaner): https://github.com/felixhayashi/TW5-TiddlyMap/commit/8831d74f05709189d25244d585d1b7c2149bc12c#diff-b741114bb913aaaaadbe77202fb207e4R760

**Comment by felixhayashi** [comment]
@ManuNeuro just for the record, here is a little demo how edge filter could be used:

![2018-10-11 09 45 15](https://user-images.githubusercontent.com/4307137/46812013-28d8d700-cd74-11e8-8de8-13e38bcd0f9e.png)
![2018-10-11 09 45 28](https://user-images.githubusercontent.com/4307137/46812021-2b3b3100-cd74-11e8-9ad8-f08836e2c8d9.png)
![2018-10-11 09 49 21](https://user-images.githubusercontent.com/4307137/46812036-31311200-cd74-11e8-9530-95e713abcfaa.png)

The result:

![2018-10-11 09 59 20](https://user-images.githubusercontent.com/4307137/46812043-342c0280-cd74-11e8-89ef-400a2b318ff3.png)
![2018-10-11 10 04 31](https://user-images.githubusercontent.com/4307137/46812057-368e5c80-cd74-11e8-9098-9a0670f10f0e.png)



![2018-10-11 10 04 46](https://user-images.githubusercontent.com/4307137/46812068-3b531080-cd74-11e8-89e9-b3b201376ab1.png)
![2018-10-11 10 07 34](https://user-images.githubusercontent.com/4307137/46812073-3db56a80-cd74-11e8-95e2-d38d145d9f06.png)

**Comment by flibbles** [comment]
Oof. I am really sorry, @felixhayashi. This is a case I hadn't considered during my testing. I'm also sorry I was only able to see this now, or I would have tried to be more help in tracking this down. I'll check out the solution you put in, but it sounds like it's the exact thing I would have done to solve this.

If there's anything more to do (besides be a more thorough tester in the future), let me know.

**Comment by felixhayashi** [comment]
Hi @flibbles, no problem – otherwise your PR was great  :slightly_smiling_face:. I also hadn't realized this problem exists as I just used existing edge-types and hadn't created any new ones recently.
