### ISSUE TITLE
fixed position of nodes in a view

### ISSUE THREAD

**Issue by linsteina** [felixhayashi/TW5-TiddlyMap#296]
Hi @felixhayashi ,

I noticed that the nodes in the "All Tasks" view in the TaskManagementExample 2.0 tiddler (http://tiddlymap.org/) cannot be dragged. I want to achieve the same result but don't know how. Could you help?

Thanks,

Chun

**Comment by felixhayashi** [comment]
Hi @linsteina
Well I added this feature after you opened this ticket: https://github.com/felixhayashi/TW5-TiddlyMap/issues/293 (that's why #293 is closed by the way).
just install v0.14.3 and it should work. :slightly_smiling_face:
