### ISSUE TITLE
Using background image forces update for every adjustment

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#302]
Hello!

I'm not sure whether this qualifies as a bug, or if this is an improvement suggestion. I'm using a background image in one view, and I'm getting this behavior where if I even so much as move a single node even a little bit, the graph zooms out to encompass the entire graph. Not only that, it uses a smooth transition which takes a full second where I'm not able to do anything. I have a large graph, and it's getting annoying to have to wait a second, and then zoom back in to make another tiny adjustment.

I'm looking at the source, and it looks like it's [happening here](https://github.com/felixhayashi/TW5-TiddlyMap/blob/fafd4dd7d221e85f94e3e7c9eda3960f8f729bd4/src/plugins/felixhayashi/tiddlymap/js/widget/MapWidget.js#L2715), where the MapWidget is forcing a full redraw on an update, but only if an image's onload method is called back.

Is this intended behavior? Could a solution be to disable the transitioned zoom-out? Because I actually have never enjoyed that behavior in any circumstance, such as when a node is added or removed.

I can implement a solution if you're busy. I just figured since I'm suggesting a behavior change, I'd discuss it first.

Thanks for reading!
You can take my months of radio silence to mean TiddlyMap has been working well for me otherwise.

-Flibbles

**Comment by felixhayashi** [comment]
fixed by moving `reloadBackgroundImage` a few lines higher :D https://github.com/felixhayashi/TW5-TiddlyMap/blob/09ca1e347810f73acd02fe2712146cd70124f8f3/src/plugins/felixhayashi/tiddlymap/js/widget/MapWidget.js#L602 – it should only reload if the view config changes.

**Comment by flibbles** [comment]
Yep. That fixed it. A better solution than what I duct taped together too. Thanks for getting to this so quickly!

**Comment by felixhayashi** [comment]
Always welcome! And thanks for quickly leading me to right place in the code!
