### ISSUE TITLE
Is the "npm-check-updates" dependency necessary?

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#305]
Just freshly reformatted my computer, so I had to rebuild my version of Tiddlymap, and I brought it up to date with 0.15.4. I hit a snag.

When running npm install, I encountered this within node-gyp:

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
It could probably be easily solved by installing XCode, but... ya know... _fuck that_. (11 GB? No thanks.) I looked into it. node-gyp doesn't actually require xcode. It's just a bug with `node-gyp@3.6.2` and lower, which Tiddlymap requires through it's `npm-check-updates` dependency.

Looks like this is easily fixed if you blast the package-lock.json file, and rebuild, the npm-check-updates seems to pull `node-gyp@3.8.0`. I guess package-lock.json files just need updating occasionally.

OR could npm-check-updates be removed? I did, and it didn't affect anything. I'm not sure what it does, other than pull 350+ dependencies into the project, including npm@3 (we're up to npm@6 now). You added it with the same commit you brought in ec6 compatibility, which is a huge commit. So I can't tell exactly why it was added.

Thoughts? This certainly isn't critical in any sense, but I thought it was worth noting troubles from a fresh build.

**Comment by felixhayashi** [comment]
Hi @flibbles just saw your comment now.

> OR could npm-check-updates be removed? I did, and it didn't affect anything. I'm not sure what it does, 
I used it to check for outdated packages but I understand

Will try to update all packages to their latest versions, I guess many packages are outdated. If this problem still exists, I will remove the npm-check-updates package

**Comment by flibbles** [comment]
Like I mentioned, this is a super low priority issue. Refreshing the package-lock.json file will probably resolve this, but if afterwards you want me to make sure, just let me know. I'll blast my repository and build from scratch.
