### ISSUE TITLE
How to add custom filters in quickConnectButton

### ISSUE THREAD

**Issue by lorenzgl** [felixhayashi/TW5-TiddlyMap#309]
Hello Felix,

I'm trying to add more semantic behavior to my wiki. I love the quickConnectButton for editing property fields of tiddlers and would like to extend the dialogs functionality to show me only fields based on the class of the active tiddler and then filter results based on the selected field. I know that this isn't a common use case that makes sense for a feature request. So I'm trying to do the modification myself, alas, I'mm a bloody amateur. Could you point me to where in the code I would be able to modify the filter filter=<<tmap "option" "selector.allEdgeTypesById">> that is referenced in the quickButtonConnect tiddler?

Thanks a bunch,

Lorenz

**Comment by lorenzgl** [comment]
Well, turns out it's easy to find once one discovers the GitHub search function: TW5-TiddlyMap/src/plugins/felixhayashi/tiddlymap/js/lib/environment.js

**Comment by felixhayashi** [comment]
yes, that's the place :slightly_smiling_face: good luck!
