### ISSUE TITLE
Outsourcing user config

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#31]
Some aspects of TiddlyMap should be configurable.

Outsourcing means these aspects should be...

* configurable via a form (either on a graph level or on a global level)
* outsourced as JSON tiddlers
* outsourced as single tiddlers (allows fine grained update mechanism)

The outsourcing styles can cooexist and what style is chosen depends on how frequently an aspect has to be configured by the user or how prominent the aspect is...

**Comment by tobibeer** [comment]
Configurability is a key issue for any graph.
So, thanks for picking up on this, Felix.
