### ISSUE TITLE
Additional feature development

### ISSUE THREAD

**Issue by Sparkblender** [felixhayashi/TW5-TiddlyMap#311]
@felixhayashi 
I understand you are the main developer of TiddlyMap.  I've been long searching for a tool that would do what TiddlyWiki does in combination with your plugin.  And I'm impressed of what I've seen so far.
I'm wondering if you'd be open to develop additional features with funding, as a way to fast-track the development process.
Let me know if you'd be interested and which would be the best channel to get in touch.
Thanks.

**Comment by felixhayashi** [comment]
Hi @Sparkblender 

Many thanks for your kind words :)

I appreciate your offer but the development of new TiddlyMap features cannot be "fast-tracked" since I am too occupied with day-job work.

Currently, my main focus is on bugfixing. Only sporadically I work on feature requests depending on how simple they are to program and how much benefit they bring.

Is there any specific feature you have in mind?

**Comment by Sparkblender** [comment]
Hi @felixhayashi 
thanks for your candid response.

We are currently working on generating functional specs to be more specific when it comes to describing our requirements.  Generally speaking, we are looking for auto-layout capabilities following a particular pattern.  We are also looking for "drill-down" capabilities, i.e. double-clicking on a graph object to "zoom into" underlying objects.

On a first impression, TiddlyWiki and TiddlyMap come close to the type of functionality we are looking for.  On the other hand, having someone on board that could help us evaluate if these platforms are suitable to implementing our requirements and eventually help to jumpstart the project, is equally if not more important for us moving forward.

**Comment by rcrath** [comment]
@Sparkblender, I am interested in drill-down features and the design of systems that use it. I'm a humanities scholar who links high-level visualizations and aggregate data linked via "drill-down" to underlying data that can be approached qualitatively after finding interesting quantitative or relational patterns.  Looked at your github, but nothing there.  I'm interested but not a coder per se.  Are you familiar with 90s xerox parc startup inxight? They had a product called [table lens](http://www.b-eye-network.com/view/3092) that was designed for drill-down.  They are no longer very visible, and changed names and switched to pretty secret contracting work. The tech is used in surveillance military, intelligence, and police applications, unfortunately.  Worth a look through the wayback machine

Hi @felixhayashi! thanks as always for tiddlymap.  Just heading over to my "fiddlywiki" to engage with it now! Inxight is the focus and context guys that I was referring to when I pitched hyperbolic trees to you.(#59 ).

**Comment by Sparkblender** [comment]
@rcrath, thanks for the tip.  Not sure if that's what I'm looking for though.  
When I mentioned "drill-down" I meant the capability of double-clicking on a node to reveal another TiddlyWiki drawing.  For instance, say you have a node called _Car_.  Then, double-clicking on it, would open another view showing its components such as _Motor_, _Radiator_, _Battery_, _Wheel_, etc.

**Comment by devurandom** [comment]
@rcrath @Sparkblender I think what you want has already been asked for and implemented in the past: felixhayashi/TW5-TiddlyMap#102

**Comment by felixhayashi** [comment]
Please have a look if release v0.17.1 suits your needs.

it introduces the "tracing" functionality that allows you to temporarily add nodes to your graph by clicking on the neighbouring nodes.

Tracing can also be enabled for the "live view", however in your case I suggest that you create dedicated maps for your decision trees.

More information and videos here:

* D&D Quest with TiddlyMap: https://www.youtube.com/watch?v=etjq_u3o1kU
* Creating an interactive decision tree https://www.youtube.com/watch?v=hge3PGnJM_A
* Documenation http://tiddlymap.org/#Tracing%20node%20clicks
