### ISSUE TITLE
Hide tmap.id field?

### ISSUE THREAD

**Issue by flibbles** [felixhayashi/TW5-TiddlyMap#314]
I was wondering if you ever considered hiding the `tmap.id` guid field which tiddlymap adds to every tiddler. Half a year ago, I created the following tiddler:

```
title: $:/config/EditTemplateFields/Visibility/tmap.id

hide
```

in order to hide it, and so far, I haven't had any trouble. The only time it even remotely comes up is when I clone a tiddler. Tiddlymap will say something about duplicate IDs, but it seems to sort itself out.

No one will ever modify `tmap.id` by hand, so maybe it is worth hiding?

No rush on this issue. Just a possible improvement.

-Flibbles

**Comment by felixhayashi** [comment]
Implemented via https://github.com/felixhayashi/TW5-TiddlyMap/pull/328
