### ISSUE TITLE
Doesn't display well with dark theme/palette

### ISSUE THREAD

**Issue by stigzler** [felixhayashi/TW5-TiddlyMap#318]
Hi. Looking forward to getting this up and running, but it doens't seem to work well with a dark theme. Also, can't find any changes made in TiddlyWiki palette that will resolve it in TiddlyMap. Screenshot:

![map1](https://user-images.githubusercontent.com/4856029/61570317-bb38a480-aa83-11e9-8b62-74c71daea0f9.png)

Any suggestions?

**Comment by stigzler** [comment]
Nevermind. Figured it. File you need to edit is:

$:/plugins/felixhayashi/tiddlymap/layout

I've attached a ready-made drop-in for those of you running a dark theme. You can just change the variables at the top of the file for easy adjustment.

**Comment by flibbles** [comment]
The latest release of TiddlyMap is much better about conforming to the current theme's palette.

Just in case you still cared.
