### ISSUE TITLE
Allow to show system tiddlers

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#32]
Hello @felixhayashi 

I want to use this plugin to write some graphs, but I don't want the nodes to "pollute" my wiki. So I tried with the `$:/` prefix. The problem is that your plugin will not show those nodes.

Is there any hidden option that I'm missing? I tried to edit the filters with no luck.

Regards.

**Comment by felixhayashi** [comment]
Hi @danielo515,

please see #17. I have no solution for this at the moment. I need some time to think about it.

**Comment by danielo515** [comment]
Then we can close this.

**Comment by felixhayashi** [comment]
Ok, I will leave #17 open until it is solved.
