### ISSUE TITLE
Filtering nodes based on edges

### ISSUE THREAD

**Issue by gylns** [felixhayashi/TW5-TiddlyMap#321]
I want to view nodes which has a specific edge type linked with other nodes, there already was a thread discussed on [google groups](https://groups.google.com/forum/#!searchin/tiddlywiki/tiddlymap$20$20edge%7Csort:date/tiddlywiki/ySedPVI2StM/Y1emIaMBAgAJ), but no good answer.

**Comment by gylns** [comment]
Maybe operator `regexp` is a solution: `[regexp:tmap.edges[.*"type":"edge-type name".*]]`

**Comment by felixhayashi** [comment]
Hi @gylns I do not have a good solution for this.

But a regex may be the right solution to tackle this. 

here are some google groups links with similar suggestions:

* https://groups.google.com/d/topic/tiddlywiki/l9HnoS342Hs/discussion
* https://groups.google.com/d/topic/tiddlywiki/0a0LEaHQ8DM/discussion

Hope this helps
