### ISSUE TITLE
"Edit Node" throws an error

### ISSUE THREAD

**Issue by ronniemukherjee** [felixhayashi/TW5-TiddlyMap#323]
If I click on a node in the Live View and then click "Edit Node" I always get an error as below.

![image](https://user-images.githubusercontent.com/11668348/65508140-7720b080-dec7-11e9-82db-d46a3763fe02.png)

**Comment by felixhayashi** [comment]
Hi @ronniemukherjee sorry, I cannot confirm, this. I just downloaded an empty TiddlyWiki.html with Firefox v70 added all plugins via dragndrop and everything works fine for me
![2019-11-22 11:37:39](https://user-images.githubusercontent.com/4307137/69419320-83d15180-0d1c-11ea-9a30-46b574fe9d6d.png)

Closing this now

**Comment by felixhayashi** [comment]
Just found this tutorial explaining quite well the initial setup: https://skills421.com/2019/10/08/add-tiddlymap-to-our-wiki/
