### ISSUE TITLE
Can I use <<tmap.edges>> as variable in a tiddler?

### ISSUE THREAD

**Issue by pimgeek** [felixhayashi/TW5-TiddlyMap#324]
I tried to create a neighbour tiddler list, but failed to use <<tmap.edges>> as a variable
PS: one of my self-defined edge_type is named `pimgeek:then`

```
<$tmap-connections>
  <ul>
    <li><$view tiddler=<<neighbour>> field="name"/></li>
    <li><$list filter="[regexp:title[<<tmap.edges>>]]" /></li>
    <li><<neighbour>></li>
  </ul>
</$tmap-connections>
```
However, the following code will work
```
<$tmap-connections>
  <ul>
    <li><$view tiddler=<<neighbour>> field="name"/></li>
    <li><$list filter="[regexp:title[then]]" /></li>
    <li><<neighbour>></li>
  </ul>
</$tmap-connections>
```

**Comment by pimgeek** [comment]
sorry, my mistake. `<<>>` should not be used inside `<$list>`. and `<<tmap.edges>>` is a wrong guess, `<<edge.label>>` work for me.

**Comment by pimgeek** [comment]
I changed my question to this:

I tried to create a neighbour tiddler list, but failed to use <<edge.label>> as a variable
PS: one of my self-defined edge_type is named `pimgeek:then`

```
<$tmap-connections>
  <ul>
    <li><$view tiddler=<<neighbour>> field="name"/></li>
    <li><$list filter="[regexp:title[<<edge.label>>]]"><$view field="title"/><br/></$list></li>
    <li><<neighbour>></li>
  </ul>
</$tmap-connections>
```
However, the following code will work
```
<$tmap-connections>
  <ul>
    <li><$view tiddler=<<neighbour>> field="name"/></li>
    <li><$list filter="[regexp:title[then]]"><$view field="title"/><br/></$list></li>
    <li><<neighbour>></li>
  </ul>
</$tmap-connections>
```

**Comment by pimgeek** [comment]
After repeated trial and error, now I use macrocall to solve this:

```
\define linkup(var1) <$list filter="[regexp:title[$var1$]]"><$view field="title"/><br/></$list>

... ...

<$tmap-connections>
  <ul>
    <li><$view tiddler=<<neighbour>> field="name"/></li>
    <li><$macrocall $name="linkup" var1=<<edge.type>> />
    </li>
    <li><<neighbour>></li>
  </ul>
</$tmap-connections>
```

**Comment by felixhayashi** [comment]
Hi @pimgeek sorry for the late response, yes your final solution makes sense otherwise you won't be able to access the variables `<<xxx>>` set by `$tmap-connections`. I think for such questions that involve interpolating variables in filters the TiddlyWiki google groups can also support you, since this aspect is more TiddlyWiki related.
