### ISSUE TITLE
Feature request: Node status indicator

### ISSUE THREAD

**Issue by protw** [felixhayashi/TW5-TiddlyMap#326]
A node status indicator would be very valuable feature. It can be an additional mark over the node icon with variation of color or size or one-two-digits number. Displaying of the status indicator might depend on the selected field values or on the neighboring nodes.

**Comment by felixhayashi** [comment]
HI @protw, There is a very similar ticket here: https://github.com/felixhayashi/TW5-TiddlyMap/issues/34 so I will close this one in favour of the other.

But as a quick feedback: I completely agree that this would be highly useful, but unfortunately additional markers or badges are not possible at the moment as this is not supported by visjs and it is too timeconsuming for me to implement this. :slightly_frowning_face: Your only chance is to work with colors, font-weights or tooltips to indicate a status
