### ISSUE TITLE
Exporting views

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#33]
Peter Miller wrote:

https://groups.google.com/d/msg/tiddlywiki/_KRy1WWlhHk/EY8eMaidp7UJ

> I'd like to use TiddlyMap (formerly TaskGraph) as a simple layout tool and hence to be able to export a view rather than just the tiddlers. I see that you can save node positions but is there any way that you can save them to a tiddler, ideally with node relationships, so that you can use them with other tools and/or re-import a view?

**Comment by felixhayashi** [comment]
Hi Peter,

Exporting a view would create the problem that you also need to export all the tiddler's referenced by that view's filter, if you want to recreate the exact graph. Actually, that is why I decided to call it a *view* since it is only a filter to assemble and display nodes but does **not** itself store the nodes.

> ..and the locations are here: $:/plugins/felixhayashi/tiddlymap/graph/views/[view]/map where [view] is the name of your view. 

Of course you can copy the view's data tiddlers into another wiki, but you also need to make sure to copy the edge stores (either global or private) and the tiddlers that are referenced by the edges as endpoints.

By the way, I updated the docs a bit, maybe [Advanced Topics](http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Documentation) gives you some clues on how the system is currently organized

-Felix

**Comment by tobibeer** [comment]
I guess the question really is if one actually wants an export / import of all those tiddlers in a graph. If I understand right, a graph will never show a missing tiddler.

**Comment by Peter-Miller** [comment]
Thanks for adding this issue, Felix. I should have clarified that I want to use the layout, i.e. tiddler node positions and edges, in an external application. Importing back to TiddlyWiki as some kind of "round trip" is not really necessary for my purposes. I probably have enough info to get started.

**Comment by felixhayashi** [comment]
@Peter-Miller,

@Peter-Miller Ah ok, I didn't quite understand what you mean by *layout*, but yes, feel free to use the data for your purposes.

**Comment by felixhayashi** [comment]
Hi @Peter-Miller

This is now possible if you go to "View configuration":

![selection_618](https://cloud.githubusercontent.com/assets/4307137/7214777/ee09b6d4-e5ba-11e4-9240-d10960c47e06.png)
