### ISSUE TITLE
specific Live View config caused error when trying to set node style in TiddlyMap Editor.

### ISSUE THREAD

**Issue by pimgeek** [felixhayashi/TW5-TiddlyMap#331]
The screenshot of the error message is here:

![image](https://user-images.githubusercontent.com/1609306/71656831-f13ebc00-2d77-11ea-99bb-5eeec55c8333.png)

It took me more than 6 hours to reproduce it, here is how:

### reproducing method 1

simply delete this user-created tiddler and use the default one: `$:/plugins/felixhayashi/tiddlymap/graph/views/Live View`.

### reproducing method 2

use the following tiddler to overwrite `$:/plugins/felixhayashi/tiddlymap/graph/views/Live View`.
```
config.neighbourhood_scope: 1
config.physics_mode: true
config.refresh-triggers: $:/temp/tmap/currentTiddler
config.vis: {"physics":{"forceAtlas2Based":{"springLength":25,"springConstant":0.09}},"edges":{"font":{"strokeWidth":4}}}
created: 20200102073650169
creator: pimgeek
isview: true
modified: 20200102075700278
modifier: pimgeek
title: $:/plugins/felixhayashi/tiddlymap/graph/views/Live View
type: text/vnd.tiddlywiki
```
or use this one below:

```
config.neighbourhood_scope: 1
config.physics_mode: true
config.refresh-triggers: $:/temp/tmap/currentTiddler
config.vis: {"physics":{"forceAtlas2Based":{"springLength":15,"springConstant":0.09}}}
created: 20200102080624888
isview: true
modified: 20200102080624888
title: $:/plugins/felixhayashi/tiddlymap/graph/views/Live View
type: text/vnd.tiddlywiki
```

**Comment by felixhayashi** [comment]
Hi @pimgeek thanks for reporting. this bug also occurs if you just open http://tiddlymap.org/ and go to `sidebar > view: "Live view"` and then click edit node.

While this is not pretty, it makes sense because in the live view, nodes are not allowed to be edited (it is a special view that does not store notes itself). Anyhow, I will leave this open and see what to do about it.

**Comment by felixhayashi** [comment]
Seems like this error is gone, not sure what recent code change fixed this though :man_shrugging:
