### ISSUE TITLE
Grow the graph:  Permanently adding nodes from the neighbourhood to the view

### ISSUE THREAD

**Issue by devurandom** [felixhayashi/TW5-TiddlyMap#334]
I would like to grow the currently displayed graph / view by selecting a neighbourhood scope and then permanently adding nodes to the current view.

I selected multiple nodes using ctrl+click and then tried to right click, to double-click > draft and also the four menu buttons, but could not find a function to add the selected nodes to the current view.

**Comment by felixhayashi** [comment]
Pplease have a look if release v0.17.1 suits your needs.

it introduces the "tracing" functionality that allows you to temporarily add nodes to your graph by clicking on the neighbouring nodes.

Tracing can also be enabled for the live view.

More information and videos here:
http://tiddlymap.org/#Tracing%20node%20clicks
