### ISSUE TITLE
Select multiple nodes by drawing a rectangle or circle

### ISSUE THREAD

**Issue by devurandom** [felixhayashi/TW5-TiddlyMap#335]
I would like to select multiple nodes efficiently. Drawing a rectangle (or circle, if possible) around them would solve the issue.

**Comment by felixhayashi** [comment]
Hi, this feature already exists: https://github.com/felixhayashi/TW5-TiddlyMap/issues/229

**Comment by devurandom** [comment]
Thanks. http://tiddlymap.org/#Keyboard%20shortcuts was really helpful.
