### ISSUE TITLE
Quick-create edges

### ISSUE THREAD

**Issue by devurandom** [felixhayashi/TW5-TiddlyMap#337]
Nodes can be quick-created by double-clicking the canvas, which is great. It would be nice if there was a way to also quick-create edges.

For example by shift-clicking a node and dragging, or whatever makes sense from a UX and technical point of view.

**Comment by felixhayashi** [comment]
> It would be nice if there was a way to also quick-create edges.

This feature already exists https://github.com/felixhayashi/TW5-TiddlyMap/issues/134

:point_right: http://tiddlymap.org/#Keyboard%20shortcuts

**Comment by devurandom** [comment]
Thanks. http://tiddlymap.org/#Keyboard%20shortcuts was really helpful.
