### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by myfta** [felixhayashi/TW5-TiddlyMap#339]
I am using Font Awesome icons. I would like to be able to color the icons. Now I can do that in the individual Node in its Tiddler by setting the color field. Question is, can this be done in the Node Type?

**Comment by felixhayashi** [comment]
> Question is, can this be done in the Node Type?

Hi @myfta 
yes, of course:

![2020-03-12 10:02:38](https://user-images.githubusercontent.com/4307137/76504833-b7a9c180-6448-11ea-8391-dcf9bc01900f.png)
