### ISSUE TITLE
Live View doesn't work with ListWidget

### ISSUE THREAD

**Issue by samjohn24** [felixhayashi/TW5-TiddlyMap#340]
Hi Felix,

First of all, congratulations and thanks for this amazing tool.

I have a question/issue: I generate a ToDo tiddler using FilterWidget:
```
<$list filter="[!has[draft.of]tag[task]!tag[done]sort[created]]">
<$checkbox tag="done">
 <$link to={{!!title}}>
<$view field="created" format="date" template="DDD 0DD/MM/YY : hh:mm"/>
 - <$view field="title"/> 
</$link>
</$checkbox>
"""

"""
</$list>

<$tmap view="Todo" ></$tmap>
```
![image](https://user-images.githubusercontent.com/7255188/76381352-0dd91080-6334-11ea-8f1f-3034e249543f.png)

However in the Live View the node "tasks" listed in ToDo node are not shown connected to it with "listed in" edge. They are only connected when an internal link is used "[[ ]]" without the ListWidget.

![image](https://user-images.githubusercontent.com/7255188/76381662-c56e2280-6334-11ea-9578-2717290e81de.png)

Is this supported?

Regards,
Sammy

**Comment by felixhayashi** [comment]
>They are only connected when an internal link is used "[[ ]]" without the ListWidget

Yes, your observation is correct. TiddlyMap relies on TiddlyWiki to get information about the links in a Tiddler, however, TiddlyWiki internally only provides methods to retrieve static links ("[[ ]]") in contrast to dynamic links generated by a widget. So as long as TiddlyWiki does not support this, TiddlyMap can only work with static links.

As an example, paste your code in a new Tiddler at https://tiddlywiki.com.

You can see in the info area of "Compose ballad" (in the second screenshot) that it says "No tiddlers link to this one", despite the fact, that there is a link generated by your widget in tiddler "test123"

![2020-03-12 10:08:23](https://user-images.githubusercontent.com/4307137/76505732-3e12d300-644a-11ea-97b4-2158ad627619.png)

![2020-03-12 10:13:44](https://user-images.githubusercontent.com/4307137/76505774-4965fe80-644a-11ea-9c47-aac450928105.png)
