### ISSUE TITLE
$:/plugins/felixhayashi/tiddlymap/misc/defaultViewHolder anways change by it self

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-TiddlyMap#342]
It always automatically do meanless move:

```diff
created: 20200409022623558
creator: Lin Onetwo - 林一二
-modified: 20200414104033109
+modified: 20200414135126182
modifier: Lin Onetwo - 林一二
title: $:/plugins/felixhayashi/tiddlymap/misc/defaultViewHolder
type: text/vnd.tiddlywiki
```

And this makes wiki pop "This page is asking you to confirm that you want to leave - data you have entered may not be saved" which is annoying.

see https://groups.google.com/forum/#!msg/tiddlywiki/i5hYDfaeghI/OsDKsH5vAgAJ and   https://wiki.onetwo.ren/#%E4%B8%8D%E4%BF%9D%E5%AD%98%E7%BB%8F%E5%B8%B8%E8%87%AA%E5%B7%B1%E5%8F%98%E7%9A%84%E7%B3%BB%E7%BB%9F%E5%92%8C%E6%8F%92%E4%BB%B6Tiddler

**Comment by felixhayashi** [comment]
Interesting, thanks for reporting @linonetwo, I will check this out.
