### ISSUE TITLE
Keep initial node position when in "Floating nodes" mode

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#345]
Currently, everytime a view with "floating nodes" is opened again, the nodes have completely repositioned themselves, which hinders the mind to memorize positions.

The layout should stay similar to how it was positioned itself before.

**Comment by gtothill** [comment]
Hi Felix,

Firstly - this is remarkable work and unlocks so many possibilities. For years I have been looking for a way to provide medical algorithms in a recognizable format, but with detailed notes on each decision step and branch. This looks like its a near perfect solution. I noticed this issue and thought I would ask a related question. I hope that it is appropriate to do so here.
I am building a COVID-19 screening algorithm using TiddlyMap and what I am trying to achieve is that as the user follows links in each tiddler they are taken down one or another of the decision tree branches in subsequently lower nodes. As they do this I want the map to only show the node that they are currently focused on and those below it in the tree.
I see that I can do this in live view, but the view formatting constantly changes, losing the required rigorous, hierarchical nature of the decision tree.
The alternative is to build the decision tree in a static view, but this loses the benefits of having a constantly updating contextual tree shown in the graph.
Is there any way currently of starting off with the entire decision tree shown and gradually hiding nodes as the user works thorough it, but retaining the structure and layout of the tree?
I have attached a screenshot of the (early) stages of the algorithm to give you an example of what I am trying to achieve. This is a static view. 

Again, apologies if this was entirely the wrong place for this question.

Thanks again for such a fantastically useful tool.

Regards and best wishes,

Geoff.

![2020-05-06_23-35-51](https://user-images.githubusercontent.com/52030855/81235334-8be32c00-8ff2-11ea-872a-ca08eed40996.png)

**Comment by felixhayashi** [comment]
> I am building a COVID-19 screening algorithm using TiddlyMap and what I am trying to achieve is that as the user follows links in each tiddler they are taken down one or another of the decision tree [...] I see that I can do this in live view, but the view formatting constantly changes, losing the required rigorous, hierarchical nature of the decision tree.

Hi @gtothill thanks for kind words and the positive feedback.
This ticket here is rather about maintaining node positions in "floating mode". What you described seems to be more related to this ticket: https://github.com/felixhayashi/TW5-TiddlyMap/issues/343. I will see what I can do, but I cannot make any promises about when this gets implemented.

**Comment by gtothill** [comment]
Thanks Felix,

Yes - I think that you are right - it is almost exactly what is being described by @damscal in his post. Doing what he described with the addition of more rigid formatting of the map would be incredibly useful and turn the combination of tiddlywiki and map into a near perfect algorithm deployment tool.  I completely understand the pressures that you must be under on this project and will wait with baited breath. Thanks again, I'll check back often to see if anyone else sees this to be useful. Thanks again for your reply. Cheers, Geoff.

**Comment by gtothill** [comment]
Felix - I have just re read @damscal post. It certainly suggests some very powerful features. In fact, to achieve what I am describing, all that really needs to change is that live view remembers the layout of the nodes and maintains that, showing the relationships as it does currently and re centering on the node in focus. Im guessing that this, reduced scope is less challenging (but then I don't claim any expertise!). Would you like me to start this as a new request?
Cheers,
Geoff.

**Comment by felixhayashi** [comment]
the original purpose of this ticket is solved, which is that in "floating nodes" mode, the positions are persisted as well so when visiting the same map later again after closing, nodes are found in (roughly) the same positions.
