### ISSUE TITLE
Sidebar map blanks when returning from fullwidth view

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#35]
I don't get the sidebar map refreshing when I close fullwidth view (Ff, Chrome). It's just blank until I choose another tab and then go back to Map.

**Comment by felixhayashi** [comment]
thanks for reporting, @Peter-Miller

**Comment by felixhayashi** [comment]
@Peter-Miller could you please go to the live demo and verify that it is fixed for you? thanks.

**Comment by Peter-Miller** [comment]
It works fine now. Many thanks. What do I need to do to upgrade my own wiki or is it best to wait for a new release? (Apologies but I'm a little new to GitHub)

**Comment by felixhayashi** [comment]
Hi @Peter-Miller,

All updates I commit are automatically reflected by the demo site. So the update-routine is basically the same as for installing a tiddlywiki plugin (assuming you are not running tiddlywiki with node.js): Just go to the demo site, drag the three required tiddlers into your wiki. save the wiki and restart. You can check if you have the newest version installed locally by comparing the demo-site's plugin version (see welcome tiddler) and the plugin version in your local wiki's config tiddler (configurations->plugins).

-Felix

**Comment by Peter-Miller** [comment]
Many thanks, Felix.

**Comment by felixhayashi** [comment]
No problem. Thank you too.
