### ISSUE TITLE
Externally loaded, locally stored images unable to be used for background images

### ISSUE THREAD

**Issue by RK-Shaw** [felixhayashi/TW5-TiddlyMap#355]
Hello,

I am currently working with a single, very large image that I would like to use as a map background. The image is showing/loading just fine in the story river using the `_canonical_uri` field 

![one](https://user-images.githubusercontent.com/47098368/82719124-de208000-9c75-11ea-8c4c-599c396ba092.png)
![two](https://user-images.githubusercontent.com/47098368/82719126-e24c9d80-9c75-11ea-8ca9-b82265f39354.png)
![three](https://user-images.githubusercontent.com/47098368/82719125-dfea4380-9c75-11ea-9817-f0e51cf9bccb.png)

but doesn't display when the target tiddler is listed for the background image.

The image is stored in the same folder as the wiki is, but the wiki is running locally on my machine. I am using Tiddlydesktop, though the issue seems to persist on whatever browser I use. I've tried every file syntax I can think of, though this doesn't seem to make much of a difference.

File Syntax: file:./Weymire_political.png

**Comment by felixhayashi** [comment]
Hi @RK-Shaw thanks for reporting, it looks like a bug to me.
For a temporary workaround, try to import the image into your wiki.

**Comment by felixhayashi** [comment]
Should work now :pray:

**Comment by RK-Shaw** [comment]
test success after updating, thanks!
