### ISSUE TITLE
How can I save  TiddlyMap "selected" node in $:/temp/tmap/currentTiddler ?

### ISSUE THREAD

**Issue by akhater** [felixhayashi/TW5-TiddlyMap#356]
Hi,

I want to use the liveview view in full screen mode but without having the actual tiddler come in focus in from on the map automatically, 

This can be achieved by. for example, one click switch to the node and saving it into a tiddler e.g.  $:/temp/tmap/selectedTiddler so that live view can work and then on double click the tiddler itself opens

is it something achievable ?

thank you

**Comment by felixhayashi** [comment]
Hi @akhater I don't think I understood you right, you want the live view in fullscreen mode but don't want the modal to be displayed when a node is double clicked?

**Comment by flibbles** [comment]
Closing for lack of followup.
