### ISSUE TITLE
Live View shows last open map instead of tmap.open-view field in 0.17.7+9982

### ISSUE THREAD

**Issue by ahilliard** [felixhayashi/TW5-TiddlyMap#359]
The latest tiddlyMap live view doesn't seem to behave as expected.  It reliably loads the "default" live view, but otherwise only shows the last selected view in the Live view tab.

Steps to reproduce:
- Open Tiddlymap.org 
- Switch to "Live" Tab
- Scroll story river down and see that "Overview" and the fallback "Live View" display OK.
- Edit "Task Management Example 2.0", add field tmap.open-view = All Tasks, and save.
- Observe that "Overview" view wrongly displays in live tab
- Scroll story river and observe that "Overview" displays for both the Getting Started and the Task Management example, but that the fallback live view displays fine.
- Open "Map" tab and change view manually to e.g. Caption example
- Reopen "Live" tab and note that while "Overview" still displays fine for the Getting Started tiddler, now the Task Management example displays the Caption example.

**Comment by felixhayashi** [comment]
Thanks @ahilliard for reporting and providing the detailed steps for reproducing the error. I will check this very soon and fix it.

**Comment by ahilliard** [comment]
@felixhayashi , really enjoying working with TiddlyMap.  I hope you are doing all right despite the pandemic and wonder if you might have any plans for a bugfix release?  I would like to send in a TiddlyMap model for scientific peer review and hope it could make the best first impression possible on reviewers :)

**Comment by felixhayashi** [comment]
Hi @ahilliard, thanks for your heads up and sorry for the delay.
I will go over some of the existing bugs in the list (including the one you mentioned) this weekend and fix them :slightly_smiling_face:
