### ISSUE TITLE
Edge-filter specific tags

### ISSUE THREAD

**Issue by xeor** [felixhayashi/TW5-TiddlyMap#361]
I am trying to create an edge-filter that creates links to other tiddlers that are tagged with tag `tag-a`.
I've tried a bunch of combination, but I find no way to do this using `[[tw-list:tags]]`.

I'm fairly new to tw5, but should this be possible, or have I missunderstand something?

The examples I find at [http://tiddlymap.org/#Edge-type filter examples](http://tiddlymap.org/#Edge-type filter examples) doesnt show any thing about this. Only for matching tiddly names, which I'm not all that keen on doing.

Any tips?

**Comment by felixhayashi** [comment]
Hi @xeor, sorry to say so but edge-filters only show/hide edges based on the **type** of the edge, not the **value** and what you are trying to achieve is to filter by the value of the tag name.

So the only solution I see for your case is to not use tags and instead create a dedicated edge-type and then create a filter based on this edge-type.

**Comment by xeor** [comment]
Aha! Thanks for the clarification! I did suspect there was a limitation like that.
Is it a good idea for a feature release tho? Or is there a limitation somewhere that makes this almost impossible to do?

If it's not a good idea, feel free to close the issue :)

**Comment by felixhayashi** [comment]
While this would be a nice feature, unfortunately it is too hard to achieve as it would break the underlying mechanism, so I have to close it. Thanks for your input, though!
