### ISSUE TITLE
Update to #102 Click Node Takes to other view but also opens tiddler in the river

### ISSUE THREAD

**Issue by adriankelly1** [felixhayashi/TW5-TiddlyMap#362]
Hi Felix
I am wondering if it is possible to change the feature #102 when you click a node it can be configured to open a new view which is awesome but is it also possible to open the tiddler in the river as well as open the new view? I don't think you lose much by making both actions available (open tiddler + change view) since the normal click node is the open tiddler action and this is what the user expects. 
Or maybe have it in the right-click context menu to open the tiddler?

Many thanks again for your amazing initiative 
Adrian

**Comment by felixhayashi** [comment]
Hi @adriankelly1, sorry for the belated response, this certainly makes sense! will add this feature in the next release.
