### ISSUE TITLE
Extra canvas used for png export results in extra scrollbar

### ISSUE THREAD

**Issue by chengtianhong** [felixhayashi/TW5-TiddlyMap#364]
Hi,
I noticed that there are two ugly scrollbars around the map in the sidebar. When I tried to reomve it, I found a element \<canvas class=" tmap-download-canvas"\>. The two scrollbar will disappear when I delete the element or set it to hidden="on". I wonder what is the usage of this element. Can it be removed or hide without any influence?

**Comment by felixhayashi** [comment]
Hi @chengtianhong ,

this canvas is used when downloading/exporting the map as png, however, it is a bug that it is having a visual effect.. it should definitely not cause a scrollbar to be displayed.
