### ISSUE TITLE
Reference to own list field results in error if popup activated

### ISSUE THREAD

**Issue by KendrickLamarck** [felixhayashi/TW5-TiddlyMap#365]
If there is a tiddler that contains the text `{{{ [list{!!title}] }}}` and I hover over it in the map, I get **Uncaught TypeError: Cannot read property 'length' of undefined.** Things seem to be fine if popups are disabled.

Here is the console output:
![image](https://user-images.githubusercontent.com/56130490/88837480-99b2e280-d1d8-11ea-9ee4-517252538c35.png)

Edit: Workaround found: Use `{{{ [list<currentTiddler>] }}}` instead. The popup is empty but there's no error in this case.

**Comment by felixhayashi** [comment]
Thanks for reporting, this looks like a bug!

**Comment by flibbles** [comment]
This should be fixed as of the latest release (v0.17.13)
