### ISSUE TITLE
JS file erroneous included

### ISSUE THREAD

**Issue by fkohrt** [felixhayashi/TW5-TiddlyMap#369]
There's a JS file erroneous included at [/home/felo/projects/Tiddlywiki/TiddlyWiki5/plugins/felixhayashi/tiddlymap/js/lib/TypeDefs.js](http://tiddlymap.org/#%2Fhome%2Ffelo%2Fprojects%2FTiddlywiki%2FTiddlyWiki5%2Fplugins%2Ffelixhayashi%2Ftiddlymap%2Fjs%2Flib%2FTypeDefs.js)

**Comment by felixhayashi** [comment]
Hi, what makes you think it is "erroneous"?

**Comment by fkohrt** [comment]
Oh, it looked like a build artifact to me, without a `type` field, and the tiddler's name (`/home/felo/projects/Tiddlywiki/TiddlyWiki5/plugins/felixhayashi/tiddlymap/js/lib/TypeDefs.js`) is irregular compared how you organize the rest of your code.

**Comment by fkohrt** [comment]
Would have expected a tiddler name starting with `$:/plugins/felixhayashi/tiddlymap/`...

**Comment by flibbles** [comment]
The latest release has this fixed.

The latest release is only available through github though. Not TiddlyMap.org
