### ISSUE TITLE
Connection Wizard Bug

### ISSUE THREAD

**Issue by andtheWings** [felixhayashi/TW5-TiddlyMap#37]
I'm using version 0.6.4+1379 in Firefox on Windows 7.

When I initially click on the search bar, the highlighted "current tiddler" appears but so do several other extra nodes and edges. When I type something into the search bar, about half of these extra nodes and edges will disappear but the rest do not (none of them fit the actual search criteria). The map will zoom out and center on these extra nodes. Sometimes immediately after searching, I will start to zoom in on the "current tiddler" node so I can see it more clearly and the map will override me, zooming back out and centering on the extra nodes.

**Comment by felixhayashi** [comment]
Hi @andtheWings, 

Could you check the demo site and see if it works now? If you start typing "tgfdgdfg" in your search field, it should only display the current tiddler.

That said, I plan to rewrite the "connection wizard" anyway as you already know from #19...

-Felix

**Comment by andtheWings** [comment]
Disabling the physics mode does help keep the map a little more static so thank you!

There are still couple issues I'm observing.

The first issue is how the map is initially populated after you click on the search bar but before you start typing anything in. In the demo map too, there's a seemingly random collection of extra nodes that show up in addition to the current tiddler. Do you know what determines which nodes pop up?

The second issue is that any nodes you add from within the wizard will not be filtered away by search criteria unless you manually delete them from the connection wizard graph view. If you plan on rewriting the wizard anyway, perhaps it's not necessary to fix this in the short term. Although, it might be sufficient to change editor="vis" to editor="advanced" for the connection wizard graph so that the node filter can be edited.

**Comment by felixhayashi** [comment]
> The first issue is how the map is initially populated after you click on the search bar but before you start typing anything in. In the demo map too, there's a seemingly random collection of extra nodes that show up in addition to the current tiddler. Do you know what determines which nodes pop up?

Yes, it is the tiddlywiki search result based on this filter

    [!is[system]search{$:/temp/search}] [!is[system]search:tags{$:/temp/search}] [!is[system]search:text{$:/temp/search}limit[10]]

> The second issue is that any nodes you add from within the wizard will not be filtered away by search criteria unless you manually delete them from the connection wizard graph view.

Yes, this is true and it's not nice. The reason is because a node is added like `[field:id[274892374892]]` to the views filter and then it stays there. The "connection wizard" was never meant to be used to add nodes. You correctly pointed out that I could set the editor to advanced but this would create the wrong impression on what to do in this mode.

> If you plan on rewriting the wizard anyway, perhaps it's not necessary to fix this in the short term.

Well, yeah, I have some issues on my list I want to fix as soon as I find the time and this is one of them. I rather put effort in creating the new mechanism than fixing the old one. ;)

-Felix
