### ISSUE TITLE
Emptied text field when using lazy loading with Node.js server

### ISSUE THREAD

**Issue by fkohrt** [felixhayashi/TW5-TiddlyMap#371]
If I create a new TiddlyWiki (`server` edition), install the plugins [TW5-TiddlyMap](https://github.com/felixhayashi/TW5-TiddlyMap) and [TW5-Vis.js](https://github.com/felixhayashi/TW5-Vis.js) and create a file called `tiddlers.json` inside the `tiddlers/` directory as below...
```json
[
    {
        "title": "HelloWorld",
        "text": "This is the content of the tiddler //HelloWorld//."
    }
]
```
...then starting the wiki with [lazy loading](https://tiddlywiki.com/#LazyLoading) enabled empties the tiddler `HelloWorld`. The server command I used is `tiddlywiki wiki/ --listen root-tiddler=$:/core/save/lazy-all`

**Comment by felixhayashi** [comment]
Hi Florian, I think lazy loading in general is a problem with TiddlyMap, see https://github.com/felixhayashi/TW5-TiddlyMap/issues/300. Unfortunately, as the problem seems to be deeply rooted in the tiddlymap logic, I do not recommend to use TiddlyMap with lazy loading.

**Comment by fkohrt** [comment]
I see, sorry for the duplicate, I'll close this.
