### ISSUE TITLE
Add more palantir-like feature

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-TiddlyMap#372]
Please see this article about Palantir's product https://mp.weixin.qq.com/s?__biz=MzAxNTgzMDI5MA==&mid=2650663338&idx=1&sn=d1205e873f1be3e7266c1a44d3d4b840&chksm=83f755d7b480dcc1ea976052caaa01fd710853aff55839c8856a66c695ef4df910c2b3a00d71&mpshare=1&scene=1&srcid=0812WogJ7ByJQs6RCOCz6Rz1&sharer_sharetime=1597238580734&sharer_shareid=45862499950c225ae58bd2f32e816f4e#rd

It will be cool to seee tiddlymap to be like this!

**Comment by felixhayashi** [comment]
Hi @linonetwo, under the hood TiddlyMap already provides several javascript functions that allow you to traverse tiddler relations, despite that, I do not plan to add any GUI-based analytical tools, it would be too much work.

Javascript example:

```
var myView = new $tm.ViewAbstraction("All Tasks");
var graph = $tm.adapter.getGraph({ view: myView });
var mySet = [Object.values(graph.nodes)[0].tRef]
$tm.adapter.getNeighbours(mySet, { steps: 1 })
```

![2020-09-16_17:18:07](https://user-images.githubusercontent.com/4307137/93357503-a949c180-f840-11ea-8fc8-79790f7053a6.png)

**Comment by flibbles** [comment]
I'm going to close this.

**Comment by linonetwo** [comment]
We may explore it in [https://github.com/tiddly-gittly/tw-echarts](https://github.com/tiddly-gittly/tw-echarts) , as echarts has more interaction example to learn from, than the visjs
