### ISSUE TITLE
Option to only display nodes having edges matching the edge-type filter

### ISSUE THREAD

**Issue by adriankelly1** [felixhayashi/TW5-TiddlyMap#373]
Hi I have a TW question (not sure if this is the right forum since its not an issue per see) 
Is it possible to create a view with a filter based only on edge types without a filter for the nodes. 
Example: I have NodeA and NodeB linked by edgeAB. I create a new view -> Configure View->Edge-type filter: [[edgeAB]] 

This doesn't seem to work as intended which I thought might be the view showing NodeA and NodeB linked by edgeAB. 
Can anyone help?

**Comment by felixhayashi** [comment]
Hi @adriankelly1 

A node filter is always the prerequisite to create a graph. Unfortunately, there is no way to filter nodes based on the edges they have. Edge filters will only influence which edges are displayed...

Nonetheless it is an interesting idea. There could be a checkbox "only display nodes having edges matching the edge-type filter".

I don't think this feature will be implemented anytime soon but I will keep this ticket open as feature request.

**Comment by ahilliard** [comment]
Hi @adriankelly1 , good feature request!  I have worked around it with a node filter to search the 'edges' field for a prefix of the edge type. [search:tmap.edges[ ]] .  But that only catches 'outgoing' edges, so you have to set a 'neighborhood' of 1 in order to include incoming links.

**Comment by felixhayashi** [comment]
> I have worked around it with a node filter to search the 'edges' field for a prefix of the edge type. [search:tmap.edges[ ]]

That is one hell of a workaround :laughing: :+1: very creative indeed!

I now added this feature as part of the next release. The user will be able to toggle the filter via a flag.

![2020-09-27_02:11:15](https://user-images.githubusercontent.com/4307137/94352554-c5323c00-0066-11eb-84d1-148102fa70ec.png)

**Comment by felixhayashi** [comment]
# Step1

![2020-09-27_22:42:49](https://user-images.githubusercontent.com/4307137/94375456-06ccf080-0114-11eb-8a67-d8220c0e06ba.png)

# Step2

![2020-09-27_22:43:16](https://user-images.githubusercontent.com/4307137/94375460-092f4a80-0114-11eb-96af-d6dd38961e2a.png)

# Step3

![2020-09-27_22:43:58](https://user-images.githubusercontent.com/4307137/94375462-0b91a480-0114-11eb-818c-b929670dd142.png)

**Comment by felixhayashi** [comment]
if you want to speed up the graph, you should use a more restictive node filter though instead of `[all[tiddlers]]`.
