### ISSUE TITLE
Show more level of link and tag relationship

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-TiddlyMap#375]
Currently, it only shows 1 level of tag or link, can it do this for 2-3 level? So I can see the whole tree of a tag.

**Comment by felixhayashi** [comment]
Hi @linonetwo 
you can enable the neighbourhood scope and set it to 2 or 3 steps.

**Comment by linonetwo** [comment]
I can't find "neighbourhood" in Graph setting in Live View...

**Comment by felixhayashi** [comment]
you can set the live view settings by going to the "Map" tab in the sidebar and then select the "Live View" and then set the scope to "no limit", then switching back to the live tab you will see all neighbours displayed in the map.

![2020-09-27_00:26:36](https://user-images.githubusercontent.com/4307137/94351363-3c140880-0058-11eb-999a-dff2c2622ca6.png)

**Comment by linonetwo** [comment]
Wow, I always go direct to the config, no seeing this view setting.

And it is quite slow, maybe there should be some cache mechanism...

**Comment by felixhayashi** [comment]
> And it is quite slow, maybe there should be some cache mechanism, or run the task in parallel inside workers...

yeah, the larger the scope, the slower it will get :slightly_frowning_face:

**Comment by linonetwo** [comment]
Do you have idea how roam and obsidian handle this?
