### ISSUE TITLE
Limit Zoom and Pan Function to Within Background Image

### ISSUE THREAD

**Issue by HazelMorris** [felixhayashi/TW5-TiddlyMap#377]
Hello, I love tiddlymap and I am currently using this plugin to create an interactive map for worldbuilding. However I have a question/feature request.

I want to have it so you cant zoom or pan out further then the edge of the background image (my map). 

In my leaflet version, I used this code:

  var map = L.map('map').setView([0, 0],  Zoom = 4);

var southWest = L.latLng(-85, -180),
northEast = L.latLng(85, 180);
var bounds = L.latLngBounds(southWest, northEast);

map.setMaxBounds(bounds);
map.on('drag', function() {
    map.panInsideBounds(bounds, { animate: false });
});

Can anyone help me out?
Thank you for creating this amazing plugin!
H
disclaimer: I have no idea how to code beyond the complete basics.

**Comment by felixhayashi** [comment]
Hi Hazel,
thanks for the feedback and glad you find TiddlyMap useful.
I am sorry to say, but unfortunately it is not possible to restrict the zoom of the map :slightly_frowning_face:

**Comment by HazelMorris** [comment]
Thank you for taking the time to write back, and thank you again for this amazing plugin - you really are a genius! I hope tiddlywiki continues to get the recognision it deserves as a ground breaking piece of software.

**Comment by felixhayashi** [comment]
Thanks for your warm words @HazelMorris :blush:  I know TiddlyMap has its limits and also several shortcomings, but I am glad you find it useful.
