### ISSUE TITLE
After I create new tiddler using edit button, I cannot use QuickConnect button.

### ISSUE THREAD

**Issue by pimgeek** [felixhayashi/TW5-TiddlyMap#378]
When I click the link of a non-exist tiddler, it asks me to **create new tiddler by "Edting"**

![image](https://user-images.githubusercontent.com/1609306/97839214-adf90500-1d1c-11eb-90f0-343494946be3.png)

But after I click Edit and created the tiddler,

![image](https://user-images.githubusercontent.com/1609306/97839393-18aa4080-1d1d-11eb-91d8-cf0ef22909d8.png)

weird things happen --- I cannot use QuickConnect button.

![image](https://user-images.githubusercontent.com/1609306/97839525-50b18380-1d1d-11eb-9cc8-0f660a9cf828.png)

But after I refresh my TiddlyWiki site, the error wll be gone, until I **"create new tiddler by editing again"**

**Comment by felixhayashi** [comment]
Hi @pimgeek 

> weird things happen --- I cannot use QuickConnect button.

Strange, I tested it with http://tiddlymap.org and could find any issue :thinking:

**Comment by pimgeek** [comment]
> Hi @pimgeek
> 
> > weird things happen --- I cannot use QuickConnect button.
> 
> Strange, I tested it with http://tiddlymap.org and could find any issue 🤔

I have found a way to reproduce this issue, could you have a look?

1. By default, do NOT open Live view or TiddlyMap Editor view
2. Create a new tiddler `X`, but don't show it in Live View or TiddlyMap Editor view
3. Now click the QuickConnect button on `X`, the error will occur
4. Then view the tiddler in Live view or TiddlyMap Editor view, after this operation, the error should be gone.

**Comment by pimgeek** [comment]
> I am also unable to replicate this. Do those reproduction steps work on tiddlymap?

It's been quite long since I first encountered this error, and I cannot remember how I configured my old TiddlyWiki site and what version it used.

But after a quick test on a newly initialized tiddlywiki, I think the problem no longer exists.

I have tested the latest version of TiddlyMap, both on Tiddlymap.org and my local Node.js server. 😃

**Comment by flibbles** [comment]
Glad it works for you. Sorry for such a long delay in reply.

I'm going to close this issue, but if you have any further problems, feel free to reopen this issue. I am manning the shop these days.
