### ISSUE TITLE
Change the font in tiddlymap

### ISSUE THREAD

**Issue by HazelMorris** [felixhayashi/TW5-TiddlyMap#379]
Hello! So I am using tiddlymap to create an interactive map and it is working great so far, but there is one thing that is bugging me still. 

There doesn't seem to be a way for me to control the font used on the map. I have tried everything I can think of! I even did some editing the CSS of $:/plugins/felixhayashi/tiddlymap/layout, but it is still the same font. 

Is there a setting I've missed somewhere? I have attached a screenshot of what I mean.

![Different fonts screenshot](https://user-images.githubusercontent.com/48735598/98160249-d0824e00-1ed5-11eb-8279-b347bd6cd5d9.JPG)

Thank you Felix and everyone for creating this amazing plugin, have a nice day!
(edited a typo)

**Comment by felixhayashi** [comment]
Hi @HazelMorris 
I think I can enable the option to change the font in the tiddlymap node config.
I will see what I can do.

**Comment by HazelMorris** [comment]
Thank you so so much!
