### ISSUE TITLE
Live map display persists when tiddlers are bulk closed

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#38]
I'm not sure how reproducible this is but in my wiki the Live display persists when the tiddlers have been closed using either the Close All button or the equivalent link on the Open menu.

**Comment by tobibeer** [comment]
What would you expect to happen?

**Comment by Peter-Miller** [comment]
When I say "the Live display", I mean the the most recent map. I would expect it to be blank when no tiddlers are open.

**Comment by felixhayashi** [comment]
Actually, good point. At the moment it displays the tiddler that was most recently focussed. I think I will clear the live view when no tiddler is open.

**Comment by Peter-Miller** [comment]
That would be simplest. Another alternative would be to have a toggle play/pause button that allowed users to freeze the display.

**Comment by Peter-Miller** [comment]
I'm not especially in favour of feature creep but an option to save a useful Live map as a view would be another possibility. It might speed up map creation?

**Comment by felixhayashi** [comment]
Hi @Peter-Miller, the point is the live view does not really know what it contains. It just uses the following configuration:

    title: $:/plugins/felixhayashi/tiddlymap/graph/views/live/filter/nodes
    filter: [field:title{$:/temp/focussedTiddler}]

and 

    title: $:/plugins/felixhayashi/tiddlymap/graph/views/live
    config.display_neighbours: true
    config.physics_mode: true

So if you want to recreate a live view, just create a view that does this. I don't want to create too many possibilities for users to interact with the system as each aspect would need explaining and might confuse.

Nonetheless, your original idea makes sense to me and I implemented this now.

-Felix
