### ISSUE TITLE
Floating and Non-Floating Nodes in the same View

### ISSUE THREAD

**Issue by samuelwiechmann** [felixhayashi/TW5-TiddlyMap#381]
Okay, I don't know if this is easily possible, but it would be incredibly nice.
Imagine to be able to set up nodes in a circle and then have all the connections in the middle float freely!
Or of course any other structure that is then surrounded by free floating nodes. 

As I understand, right now I can only set floating or not floating nodes on a view basis.

My wish would be to set that property for each node and / or for node-type.

Another maybe easier possibility might be to enable the raster while having nodes float.
But right now it seems that the raster doesn't work when floating nodes are enabled.

**Comment by flibbles** [comment]
Actually, this is totally possible. I've implemented it in the new release. Just uncheck the "physics" option for the nodes or node-types you don't want floating around.

**Comment by samuelwiechmann** [comment]
That sounds pretty amazing!
Maybe a stupid question, but how do I install the new release in a
standalone TW?

**Comment by flibbles** [comment]
Not stupid at all. It's trickier to do since I have no power to update the demo website.

1. Go to the github "Code" tab.
2. On the right you'll see "Releases", the current being v0.17.13. Click it.
3. In the "Assets", click on the "tiddlymap_0.17.13+10017.json. Dowload it, and drag the file onto your standalone TW.

OR

1. Click [this link](https://github.com/felixhayashi/TW5-TiddlyMap/releases/download/v0.17.13/tiddlymap_0.17.13+10017.json) and drag the downloaded file onto your standalone TW.

If you notice that the color of the graph buttons are a mis-match of black and green, that means you should (but don't need) to also switch over to the new [vis-networ](https://github.com/flibbles/tw5-vis-network).

You may be the first person who I know for sure will be using the new non-felix release. If you encounter problems, please let me know. I'm not as avid a developer on TiddlyMap, but I would like my non-felix release to work correctly.

**Comment by samuelwiechmann** [comment]
Hey Cameron,

Thank you for your help!
That's exactly what I tried, and in my TW that's hosted on GitHub pages and
updated through GitHub-Saver I get:
"JSON error: SyntaxError: Unexpected end of JSON input" in the Import
Tiddler.

If I open the wiki locally from my drive in my browser and add the file,
save and reload, I get:
"Uncaught TypeError: Cannot read properties of undefined (reading 'addNode')
"
(Same goes for the TiddlyMap Demo Site)

It might also be a browser issue as I'm using Opera.. I'll try in Firefox.
In Firefox and with an Empty TW I get:
"TypeError: locale is undefined"

Oh and when I drag your link into TW, I import "Untitled", a Tiddler that
contains the link to the JSON file.

All the best

Samuel

**Comment by flibbles** [comment]
Okay, the "TypeError: locale is undefined" was a careless mistake on my part. I thought I tested thoroughly enough, but I hadn't, and my backward compatibility to the old vis.js library was faulty. v0.17.14 has this fixed. (I hope this fixes both issues, but I guess we'll see.)

[Here's a link to it](https://github.com/felixhayashi/TW5-TiddlyMap/releases/download/v0.17.14/tiddlymap_0.17.14+10018.json). You need to make sure you download this file, and then drag the file over. Unlike in the demo site, I can't get literal dragging of links to work here.

**Comment by samuelwiechmann** [comment]
Wow, it works!
I'll check on my old TW instances where it would be most interesting.

**Comment by flibbles** [comment]
No worries. Thanks for helping me get the latest version ready.

**Comment by samuelwiechmann** [comment]
It's actually amazing! I can simply go into my node types and
deactivate physics for the highest level nodes in the graph so I can
rearrange them!
I'm testing the new version of TiddlyMap on a local copy of:
https://samuelwiechmann.github.io/understand2/#
I've deactivated physics for nodes with tag:0, tag:1 and tag:2 and started
re-arranging them, but as soon as I switch the view, add an edge, or change
anything else to the graph, they all realign based on physics.

**Comment by samuelwiechmann** [comment]
Is there any way to make the nodes permanently "stick" to their location?

**Comment by flibbles** [comment]
Oh yeah. I hadn't noticed that. Looks like if you...

1. turn off floating nodes on your view.
2. Position your "fixed" nodes.
3. turn floating nodes back on.

The nodes will be committed to where you left them. TiddlyMap doesn't appear to bother saving node locations when floating nodes is turned on, which makes sense. I'll have to go through and fix that, which will actually be more involved than enabling configurable physics was.

Hopefully my workaround will suit your needs in the time being.

**Comment by samuelwiechmann** [comment]
Hmm, it's quite nice to have the remaining nodes float freely when
repositioning the others.
But with a slight variation, your workaround still works for me:

1. position "fixed" nodes
2. turn off floating nodes on view
3. make changes to graph
4. turn on floating nodes back

Thanks a lot for your work and your advice! It makes TiddlyMap so much
better!
