### ISSUE TITLE
How to add same node twice

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-TiddlyMap#389]
For example, in this graph, ADN show up 2 times.

![截屏2021-03-22 下午2 07 39](https://user-images.githubusercontent.com/3746270/111947220-f83a2180-8b17-11eb-9199-4d8d07da72a5.png)

**Comment by flibbles** [comment]
I'm not sure I understand. You want ADN to appear twice in the same graph as two separate nodes?

**Comment by linonetwo** [comment]
Yes, but I'm now using mermaid-tw5 to draw this kind of diagram now...
