### ISSUE TITLE
Node menu inactive at low resolution

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#39]
At 1280x720 the sidebar node menu wraps behind the Edit bar and appears inactive. I appreciate this might be out of scope.

**Comment by felixhayashi** [comment]
True, but I think, at certain display sizes the graph is just not useful anymore. So I just suggest you turn it off then...

**Comment by felixhayashi** [comment]
Hi @Peter-Miller 

The next release will have a more compact layout.

![selection_539](https://cloud.githubusercontent.com/assets/4307137/6737754/e6a46ba0-ce6d-11e4-9b28-c58b293ce0de.png)
