### ISSUE TITLE
SVG Icon Color

### ISSUE THREAD

**Issue by tcj-one** [felixhayashi/TW5-TiddlyMap#396]
I have colorless SVGs for each of my tags, which, when combined with the color field, render nicely on the tiddlers, but in the map they're always black. I see that color styles font-awesome icons, is there a way to make it style embedded SVGs as well?

![YoloMouse_2021-05-21_04-46-01](https://user-images.githubusercontent.com/33038220/119109796-7bc89f80-b9ef-11eb-9464-f713acf7a45b.jpg)
![YoloMouse_2021-05-21_04-45-52](https://user-images.githubusercontent.com/33038220/119109797-7bc89f80-b9ef-11eb-8734-674277fcc9f5.jpg)

**Comment by dagelf** [comment]
Maybe dig a bit deeper with F12 developer mode and see if you can see what the difference between these and the others are in the rendered HTML... then we would know exactly what's missing and would have an idea of what needs to get added to Tiddlymap.

**Comment by flibbles** [comment]
Coloring SVG icons is possible. It uses node coloring though, not the `color` field on the tiddler. So you either need to set color on the TiddlyMap node, or you need to create a node group with a background color associated with it.
