### ISSUE TITLE
Rendering wikitext of caption field when using widgets relying on <<currentTiddler>> variable

### ISSUE THREAD

**Issue by damscal** [felixhayashi/TW5-TiddlyMap#397]
I'm experiencing issues when using widgets in the caption field that make use (explicitly or implicitly) of the `<<currentTiddler>>` variable, the node label appears blank. Is this behaviour to be expected and are there any workarounds?
Best Regards

_Originally posted by @damscal in https://github.com/felixhayashi/TW5-TiddlyMap/issues/57#issuecomment-842584622_

**Comment by dagelf** [comment]
I don't think the templates are processed... I've started digging into the code and will see what I can come up with as this will make quite a few things possible. It's sure to slow things down too.... but for a handful of nodes would be great and can look at performance optimizations later I guess.

**Comment by damscal** [comment]
Hello @dagelf, by any chance have you found some useful insights on this issue?
Regards

**Comment by flibbles** [comment]
This should be fixed as of the latest release (v0.17.13)
