### ISSUE TITLE
Enhancement request: Nodes > 400 performance and data export

### ISSUE THREAD

**Issue by Wildhair2** [felixhayashi/TW5-TiddlyMap#398]
I will be simply be using the barebones TW5 with TiddlyMap installed for a particular project rather than implementing it in the existing project wiki. 

I've noticed some comments on performance beginning to lag after 100 nodes are added. I somewhat doubt I will be affected using a minimally sized wiki file vs the larger ones that had comments on performance. 

I will be attempting to create a knowledge base using 3D hyperbolic tree and would like to be able to export the data to use with Django to display the information online.

**Comment by dagelf** [comment]
Isn't the export component part of Tiddlywiki and not related to TiddlyMap? I don't see how rendering performance relates to exporting of data... I think it's two separate components. 

If so then any performance related issues should be logged there and this issue can be closed.

**Comment by flibbles** [comment]
I agree with dagelf. This seems outside the scope of TiddlyMap. TiddlyMap does not handle 3D trees, and the exporting features are part of the core.

If all you're doing is exporting, you should be able to get up to several thousand nodes and still have the export take under a second. So you should be fine.
