### ISSUE TITLE
When creating an edge, allow to modify edge options given by vis

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#4]
Vis offers many options for edges
http://visjs.org/docs/network.html#Edges_configuration

I should make them available

**Comment by andtheWings** [comment]
+1 

Even just being able to make the edges different colors would be really helpful for me.

**Comment by felixhayashi** [comment]
Hi @andtheWings,

I think I might have a little time to work on that now. Maybe it is done in an hour.

-Felix

**Comment by tobibeer** [comment]
Not sure if relevant to you, but in this push I significantly simplified the contrastcolor macro so that you don't have to give it any parameters...

https://github.com/tobibeer/TiddlyWiki5/commit/b52f61b8ab89168ea0b84f21c9e6ade4fa6fa5ea
