### ISSUE TITLE
Showing larger neighbourhoods around a focussed tiddler

### ISSUE THREAD

**Issue by andtheWings** [felixhayashi/TW5-TiddlyMap#40]
Sometimes I want to see how a tiddler fits within a larger network picture, but my networks are so big, I'm reduced to scrolling around in search of the tiddler I'm interested in. I love the live view (it's awesome), but sometimes it would be nice if it would include everything connected to the designated tiddler, not just its immediate neighbors. Is there a way for me to accomplish this by tweaking configuration?

**Comment by andtheWings** [comment]
Although not ideal, I realized I can sort of do this by searching within the connection wizard.

**Comment by felixhayashi** [comment]
Good point. There needs to be a way to do that. Maybe a selectbox that allows you to adjust the scope of the neighbourhood (1 = direct neighbours, 2 = neighbours of neighbours,...). Displaying larger neighbourhoods needs faster computers though as its a complex calculation. So "1" should be the default if i implement it that way. I will experiment with it.

**Comment by felixhayashi** [comment]
I renamed the question if this is ok with you

**Comment by tobibeer** [comment]
That's a very interesting thing, especially if / when TiddlyMap were to produce automated graphs showing tagging / references / listing relationships... more than one level down.

In other words, the specified filter is applied to the root node, outputting immediate relations. This process is repeated for each connected node for x levels. Not sure how to handle duplicates / "multi-inheritance", e.g. nodes with two connections in the graph / the same children.

**Comment by andtheWings** [comment]
I think I unintentionally removed the milestone from this issue. Sorry!

**Comment by felixhayashi** [comment]
Don't worry @andtheWings I removed the "After the initial release" milestone anyway. If it is not included in the "initial release" milestone it will has to be done afterwards ;)
