### ISSUE TITLE
Populate widgets inside templates in the preview popups

### ISSUE THREAD

**Issue by dagelf** [felixhayashi/TW5-TiddlyMap#402]
Just a note that these don't seem to be populated either... ie. if there's a widget in the on-hover popup on a node, it doesn't seem to work. I haven't tried it without a template yet but I suspect it might... will test and revert.

**Comment by flibbles** [comment]
Could you give a concrete example of what you mean? I am seeing widgets work on tiddlers' popups when I hover over them. Where does the template come in? Is the node the template? Or is it transcluding a template?

**Comment by flibbles** [comment]
Also if you don't care anymore, that's cool too. (It has been a year.) I'll close out this issue if I don't hear from you in a while.

**Comment by flibbles** [comment]
This should be fixed as of the latest release (v0.17.13)
