### ISSUE TITLE
[FYI] Dockerized installation of TiddlyMap in TiddlyWiki

### ISSUE THREAD

**Issue by Semmu** [felixhayashi/TW5-TiddlyMap#406]
Hi there,

First of all thanks for this truly amazing TiddlyWiki plugin! It is very-very-very useful, I can't stress this enough!

Secondly, I want to show you a [very small project I made for myself](https://github.com/Semmu/docker-tiddlywikimap): a Dockerized version of TiddlyWiki which contains TiddlyMap pre-installed.

As installing plugins to the server edition of TiddlyWiki is P.I.T.A., I wanted to create an automated way of doing that and spinning up new TiddlyWiki instances. So I just did that.

Please check it out! Also if you see fit, I think it would be useful for others too to include or mention my project in your README, as it could save them some time of manually installing it.

What do you think?

**Comment by flibbles** [comment]
*I* think this is awesome! Dockers are a pretty amazing technology, and being able to spin up TiddlyWiki/TiddlyMap pair on command would be super useful. I do a lot of work with TiddlyWiki and TiddlyMap, so I find projects like this really neat.

Felix has been out of shop for ages. I hope my appreciation is validating :)
