### ISSUE TITLE
Is it possible to create a tree of the tagged tiddlers on TiddlyMap?

### ISSUE THREAD

**Issue by ramuyk** [felixhayashi/TW5-TiddlyMap#412]
Hi,

I have a very basic question... I've read some other issues here and it seems that what I'm trying to do is not possible. But I'm not sure. I'd like to make TiddlyMap display the tree of tagged tiddlers, just like TiddlyWiki can display the whole tree of tagged tiddlers when I use:

```
<div class="tc-table-of-contents">
<<toc 'Root Tag'>>
</div>
```

Is it possible to do with Tiddlymap? I'd like to use it this way because it'd automatically create graphs with my Tiddlers once I spend the time organizing the tags correctly...

**Comment by flibbles** [comment]
Late response, but yes.

1. Create a view called "Tags" or whatever
2. Set its Node filter to be `[[Main]subfilter{Tagger}]`
3. Create a tiddler called `Tagger` with the text:
    ```
    [all[]]
    [all[]tagging[]]
    [all[]tagging[]tagging[]]
    [all[]tagging[]tagging[]tagging[]]
    [all[]tagging[]tagging[]tagging[]tagging[]]
    [all[]tagging[]tagging[]tagging[]tagging[]tagging[]]
    [all[]tagging[]tagging[]tagging[]tagging[]tagging[]tagging[]]
    ```
    (I tried to find a way to do it recursively, but it was too messy).
4. Remove the `-[[tw-list:list]]` from the edge filter of your new view. (But add a `-[[$(edge-type)$]]` for every other edge type you don't want showing up.
5. In the `Graph` tab of view editing, under Layout,  hierarchical to be on, then tweak whatever settings you want.

This should give you what you want. But you'll definitely need to tweak those hierarchy settings to get something pretty.

Feel free to open this issue again if you have any trouble. Feel free to ignore this if 10 months was too long and you've moved on in life.
