### ISSUE TITLE
Internal JavaScript Error

### ISSUE THREAD

**Issue by wahidmounir** [felixhayashi/TW5-TiddlyMap#416]
When I've installed tiddlymap it shows error whenever I refreresh the browse, try acces more menu, Map tab, map config menu

Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by flibbles** [comment]
Do you have any other plugins installed?

**Comment by dongrentianyu** [comment]
Hello, I am a tiddlywiki user from China. I have encountered the above problem before. Recently I found out that my other wiki does not have this problem. It took me a while to find the problem.

I found a conflict between the plugin tiddlymap and another official plugin **Freelinks**. It would directly cause the wiki to be unusable.

I am not a programmer and cannot find deeper problems. That's as far as I can go with what I have. I will feedback this issue to Jeremy Ruston later.

I also found a slight problem with the live view mode of tiddlymap.
The following [field:title{$:/temp/tmap/currentTiddler}]
automatically jumps to the entry specified by home in full screen mode. Or maybe I didn't set it up properly. I've been searching all day and can't find the reason for this. I have recorded a video which you can watch.

https://user-images.githubusercontent.com/109711900/196258856-5e8228f8-f441-489e-b4e0-ea7ce6c9a102.mp4


 I did this by keeping the entries in the story river, which is [list[$:/StoryList]]. This barely does the job of live view.

Also, I don't speak English and this message was translated by machine. Please forgive my ignorance and send me a message if there are any errors or incomprehensions.

**Comment by flibbles** [comment]
You are correct, @dongrentianyu. The problem was with Freelink. And this problem is fixed with the latest build of TiddlyMap.

However, the latest build is not available at TiddlyMap.org. You must get it from the bundle [here](https://github.com/felixhayashi/TW5-TiddlyMap/releases/tag/v0.17.14).

As for your Live View problem, that is a separate problem. Please open a new issue for that. Live view is problematic, but there are some fixes which I can help you with in the other issue.

**Comment by dongrentianyu** [comment]
Thank you very much for your reply. I used the latest version of tiddlymap and it solved the previous problem very well. Thank you very much for your efforts.

**Comment by flibbles** [comment]
I'm happy to hear it. If you'd like help with the Live View, feel free to open a new issue.

**Comment by dantefromhell** [comment]
Thx for this fix.

I had the same issue using `tw5-bob` + `tiddlymap` on wikis other than the `rootWiki`. 
Upgrading `tiddlymap` to release 0.17.14 or newer resolved my issue.

I'm leaving this comment here in case someone else runs into the same issue.
