### ISSUE TITLE
custom macros output doesn't show in node labels

### ISSUE THREAD

**Issue by damscal** [felixhayashi/TW5-TiddlyMap#417]
It appears I'm unable to get the output of any custom (user defined) macro show within node labels, not even very simple macros

example: `\define testmacro() testoutput`  (global macro defined through `$:/tags/Macro`, works fine everywhere else in the wiki) 
when the macro is called with `<<testmacro>>` in the node label field (e.g. caption field), the label shows as an empty square

some core macros such as `<<now>>` and `<<version>>` successfully show their output within node labels

I was unable to understand what is causing this behaviour

**Comment by flibbles** [comment]
This should be fixed as of the latest release (v0.17.13)
