### ISSUE TITLE
Unable to use tiddlymap with krystal horizontal layout plug in

### ISSUE THREAD

**Issue by arunnbabu81** [felixhayashi/TW5-TiddlyMap#422]
I have tried many times, but I am unable to use tiddlymap with krystal horizontal layout plug in

https://crazko.github.io/krystal/

Is there any way around.
I even tried loading the map within a tiddler in the storyriver, but its also not working.

This is a test wiki attached.
[tiddlywiki (12).zip](https://github.com/felixhayashi/TW5-TiddlyMap/files/8500034/tiddlywiki.12.zip)

**Comment by flibbles** [comment]
v0.17.10 fixes this. Krystal's narrow panes aren't well suited for graphs, and I don't think TiddlyMap will be coding any official integration between the two, but it can handle the absence of the tc-sidebar-scrollable class better. Maybe you can fix the rest from here using css.

Also, I don't have the ability to update the demo site, and @felixhayashi has retired, so you'll need to update your project using the bundle file inside the repository [here](https://raw.githubusercontent.com/felixhayashi/TW5-TiddlyMap/master/bundle/tiddlymap_0.17.10%2B10014.json). Save it to your desktop, then drag it onto your project.

**Comment by arunnbabu81** [comment]
Thanks. Its working, but the bottom margin of tiddlers are getting cut short.
[TW 5.2.1 krystal + Tiddlymap 17.10=TM1.zip](https://github.com/felixhayashi/TW5-TiddlyMap/files/8500326/TW.5.2.1.krystal.%2B.Tiddlymap.17.10.TM1.zip)

How to correct that with CSS?

**Comment by flibbles** [comment]
That's not a TiddlyMap problem. That's a Krystal problem. It's messing up when the story mode is set to "top". You can either.

1. Report this issue with Krystal, or
2. Just turn off "top" story view mode. It's in ControlPanel -> Appearance -> Story View. "Horizontal" or "Classic" work fine.

**Comment by arunnbabu81** [comment]
> 2\. Just turn off "top" story view mode. It's in ControlPanel -> Appearance -> Story View. "Horizontal" or "Classic" work fine.

I wasn't aware of top story view. It works fine when I switch to horizontal story view. Thanks for the help @flibbles
