### ISSUE TITLE
Feature Request: Font Choices

### ISSUE THREAD

**Issue by HazelMorris** [felixhayashi/TW5-TiddlyMap#423]
Thank you for your amazing work with this plugin. 

There is an option to switch between Arial, Verdana, and Tahoma but I find this selection very limiting. Could this plugin support the option to use the fonts already on your computer?

If I am missing something and this (or another option) is already available, my apologies, and I'd love to know more. I'm not very familiar with coding.

P.S when I use TW-icons my font colour switches to black, is there any way to change that?

**Comment by flibbles** [comment]
I've looked into this for you. The fonts are hardcoded into TW-Vis, which is one of those dependency plugins you had to install to get TiddlyMap working. It's a port of the old Vis-JS project, which was shuttered eight years ago. And TiddlyMap itself is mostly in maintenance mode. (It's mostly just me minding the counter.)

I'm afraid you're probably on your own for this. What you might try is altering your TW-Vis shadow tiddler. Just search through the compressed code for the lists containing "Verdana" and add to those lists whichever fonts you want. There are only two. _Hopefully_ it'll show up in the dropdown list, but I haven't tested this myself.

I'm not familiar with TW-icons. That's a different plugin, right? What font is turning black? And what do you do that causes this?

**Comment by flibbles** [comment]
So I'm going to close this then?
