### ISSUE TITLE
Fullscreen not working properly from embedded map

### ISSUE THREAD

**Issue by Vishnu-Karthik** [felixhayashi/TW5-TiddlyMap#426]
Hi,

I am a beginner to tiddlymap and tiddlywiki as a whole. When I click toggle fullscreen button from a map embedded into a tiddler, I get something like this:
![2022-09-04-212127_1920x1080_scrot](https://user-images.githubusercontent.com/13926900/188322227-4ffec4a1-da3c-495d-8869-4de6cc6adae9.png)

I want the map to occupy the whole screen, not just the top. Is there an option that I'm missing or is this a bug?

**Comment by flibbles** [comment]
You want full screen to take up the full screen? What craziness is this? :)

It looks like you've got an odd set up from what I'm used to seeing. What kind of browser is that? And do you have any plugins installed?

**Comment by Vishnu-Karthik** [comment]
> It looks like you've got an odd set up from what I'm used to seeing. What kind of browser is that? And do you have any plugins installed?

Just TiddlyDesktop with a theme installed. Disabling the theme did not help. Only other plugins I have installed Latex/Katex and the defaults I think.

**Comment by flibbles** [comment]
Huh. I'm not able to replicate it. Are you able to send my your tiddlywiki file? Or a stripped down version of it?

**Comment by Vishnu-Karthik** [comment]
Thanks for trying to help. Since I had very few tiddlers, I just made a new wiki and it works fine now. Not the best way since I don't know why it happened but it was the fastest way.
