### ISSUE TITLE
Where is the section "Vis Configurations"?

### ISSUE THREAD

**Issue by trentlarson** [felixhayashi/TW5-TiddlyMap#428]
I'm trying to style the 'View Specific ("local")' style according to the "Styling Nodes" instructions. However, after step 2 when I open Configure View I see this:

![Screen Shot 2022-09-11 at 5 30 14 PM](https://user-images.githubusercontent.com/238296/189553664-cb4e0119-72e3-4ca7-837f-068afd4da453.png)

... and I don't see any "Vis Configurations" section. I searched around but haven't been able to find it. Pointers helpful, as I'm trying to apply some of the styling from https://github.com/felixhayashi/TW5-TiddlyMap/issues/383  Thanks in advance.

**Comment by flibbles** [comment]
Ooh. Yeah, that should say "Graph", not "Vis Configuration". Unfortunately that documentation is part of tiddlymap.org, which I don't have the power to correct. Node size is there.

BUT if you're trying to apply some of the styling from #383, specifically about the maximum width, then you'll need to do something even trickier. I'll be happy to walk you through it if you are.

**Comment by flibbles** [comment]
Ooh, wait. I see you are actually the person who opened #383, so you already know that.

**Comment by trentlarson** [comment]
Ah. OK: I figured the documentation needs to change. Funny: the TiddlyMap.org documentation points to this repo (in the Getting Started tiddler with the GitHub buttons). If you know where to find the source or maintainer of that site, let me know and I'll go to them about it.

**Comment by flibbles** [comment]
The maintainer of that site is also the owner of this repo. 😄 
He tossed me the keys to this repo and left, but he forgot to give me the keys to TiddlyMap.org. He's in the wind now as far as I know.
