### ISSUE TITLE
How should I be updating?

### ISSUE THREAD

**Issue by andtheWings** [felixhayashi/TW5-TiddlyMap#43]
The most convenient way to update seems like it would be to drag the latest plug-in version from the demo site into my wiki. When I do this I get the status: "Blocked plugin (due to incoming 0.6.4+1802 being older than existing 0.6.4+1652." So what I do instead is download an empty wiki from Tiddlywiki.com, drag the latest TiddlyMap plug-in from the demo site, then drag in my old wiki for import. Is there a better way to do this? I've consistently gotten the same behavior all four times I've tried updating the plug-in.

**Comment by tobibeer** [comment]
With the next release of the TiddlyWiki core you won't have that problem anymore, I believe... as the underlying core code was changed.

**Comment by felixhayashi** [comment]
Hi @andtheWings,

tobi is right on that, in Tiddlywiki 5.1.8 the incoming version will win if they are equal or it is a prerelease.

I will increment the patch version today, then it will work for you as well.

-felix

**Comment by felixhayashi** [comment]
@andtheWings should work now ;)

**Comment by andtheWings** [comment]
Cool thanks!

**Comment by felixhayashi** [comment]
maybe you should switch to tiddlywiki 5.1.8-prerelease so you can always update. Another option is to delete the plugin and then drag and dropping it again. Always backup!

**Comment by felixhayashi** [comment]
sorry I actually forgot to increase the version -.-
