### ISSUE TITLE
Make download link stable

### ISSUE THREAD

**Issue by linonetwo** [felixhayashi/TW5-TiddlyMap#430]
Like  https://github.com/felixhayashi/TW5-TiddlyMap/releases/latest/download/tiddlymap.json 

So we can automatically fetch latest release in Community plugin library [https://github.com/tiddly-gittly/TiddlyWiki-CPL](https://github.com/tiddly-gittly/TiddlyWiki-CPL)

Like my plugins' link https://github.com/tiddly-gittly/tiddlywiki-plugins/releases/latest/download/24.3A.2Fplugins.2Flinonetwo.2Fsmart-field.json

**Comment by flibbles** [comment]
Interesting idea. A few questions:

* How does this work given that TiddlyMap has three dependencies. I only control one of them, and I'm sure the other two are not configured the way you describe.
* How is Relink in the CPL list when I never configured it the way you describe.
* Why *aren't* my other awesome plugins, like Uglify, not there? Who's deciding what plugins go in?

**Comment by linonetwo** [comment]
Well, acturally we can extrace plugins from the HTML, the vis.js plugin is extracted directly from http://tiddlymap.org/index.html but this can be slow, and plugin in that HTML may not be updated.

So we hope all plugins can provide a json format.

For Relink, I personally use Relink library. But some community members may add plugins to CPL at their will, because they think installing/upgrading everything in a single library is comfortable. It is added by some random member. (but will be recorded in the git commit message) So they add plugins they are using to it, and enjoy one-click-upgrade.

You can clone the repo and add tiddler like https://github.com/tiddly-gittly/TiddlyWiki-CPL/blob/master/tiddlers/Plugin_202203225931551.json or https://github.com/tiddly-gittly/TiddlyWiki-CPL/blob/master/tiddlers/linonetwo_commandpalette.json

Then your plugins will be added.

**Comment by flibbles** [comment]
Okay. I think I've done this correctly. Your stable download link should be this:

https://github.com/felixhayashi/TW5-TiddlyMap/releases/latest/download/tiddlymap.json

I'll close this issue, but if that isn't correct, let me know and reopen. This is the first time I've set this up.

**Comment by flibbles** [comment]
For real though. Did I get it right? I'm noticing that the json file I produced has the plugin wrapped in a JSON array, and yours doesn't. Does that matter?

**Comment by linonetwo** [comment]
Yes, it worked. As long as it is a valid tid that can be loaded by tiddlywiki.

![截屏2022-10-30 13 56 38](https://user-images.githubusercontent.com/3746270/198864729-be81c5bf-541a-4c87-ad99-25a3e445e6dd.png)

**Comment by linonetwo** [comment]
I also copy the readme of this repo to it, as in the screenshot.
