### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')

### ISSUE THREAD

**Issue by turtlekey** [felixhayashi/TW5-TiddlyMap#432]
I have followed the full steps of the repo suggestion [option 2](https://github.com/felixhayashi/TW5-TiddlyMap) to install TiddlyMap, but I got the following error:
```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
```
more details as following:
```javascript
Uncaught TypeError: Cannot read properties of undefined (reading 'fields')
    at Object.e [as getDataUri] (tmap:12:1759)
    at command.datauri (tmap:11:1039)
    at MacroCallWidget.run (tmap:11:699)
    at Widget.evaluateMacroModule (widget.js:219:21)
    at Widget.getVariableInfo (widget.js:137:14)
    at MacroCallWidget.execute (macrocall.js:53:23)
    at MacroCallWidget.render (macrocall.js:33:7)
    at Widget.renderChildren (widget.js:450:15)
    at ElementWidget.render (element.js:78:7)
    at Widget.renderChildren (widget.js:450:15)
```
Tiddlywiki Version: `v5.2.3`
TiddlyMap Version: `v0.17.14`
Node.js Version: `v16.14.0`
Broswer: `Chrome 106.0.5249.119 (cohort: Stable)`
Other Tiddlywiki plugins installed:  `highlight`, `tiddlyweb`, `filesystem`

I can't figure out it, I'm looking forward your reply🙏🏼🙏🏼🙏🏼
Thank you all so much🌹🌹🌹

ps: It works using the option1( drag and drop) to install the TiddlyMap.

**Comment by flibbles** [comment]
On top of `highlight`, `tiddlyweb`, and `filesystem`, I assume you also have [tw5-vis-network](https://github.com/flibbles/tw5-vis-network), [TW5-HotZone](https://github.com/felixhayashi/TW5-HotZone), and [TW5-TopStoryView](https://github.com/felixhayashi/TW5-TopStoryView) installed, as those plugins are required for TiddlyMap?

**Comment by turtlekey** [comment]
@flibbles Yes, I have downloaded them and put them together with TiddlyMap in the `tiddlywiki/plugins` directory, just as the option2 mentioned.

**Comment by flibbles** [comment]
Just needed to make sure. You didn't list those plugins among the others you'd installed.

Looks like I may have introduced an issue regarding the image files a while back. I've pushed a change. Try the "Download ZIP" and copy of dist again for TiddlyMap (and only with TiddlyMap. The dependencies are fine). Let me know if that fixes it.

**Comment by turtlekey** [comment]
@flibbles Thanks so much, it works now. What a genius you are!🌹🌹👍👍

**Comment by flibbles** [comment]
...not so much, seeing as how I cause the problem to begin with. But I'll take the compliment 🥇 

I'm glad it's working for you now. I'll close out the issue.
