### ISSUE TITLE
Brave: Strict fingerprinting protection makes tiddlymap unusable

### ISSUE THREAD

**Issue by dantefromhell** [felixhayashi/TW5-TiddlyMap#437]
When using Brave as Browser and configuring "fingerprinting blocked (strict)" tiddlymap does not show titles for nodes and edges.

steps to reproduce
- Set fingerprinting protection to strict in Brave
- Open any tiddlymap, e.g. http://tiddlymap.org/#TaskManagementExample%202.0
- Find nodes & edges without names
- Click the shield and set fingerprinting protection to standard
- Reload page and find node and edge names displayed

**Comment by flibbles** [comment]
What is Brave?
What is *fingerprinting*?

It sounds like a security focused browser, and fingerprinting is disabling the ability for other websites to track you. Am I right? If so, then it will be disabling a lot of features that TiddlyWiki, and probably Vis-network, expect. like svg rendering.

Do you not get any other side-effects when you turn on strict? Like the Tiddlywiki button icons not showing up?

**Comment by flibbles** [comment]
Ima close this. I'm guessing you either figured it out or you don't care anymore.
