### ISSUE TITLE
Refresh mechanism

### ISSUE THREAD

**Issue by newmedicine** [felixhayashi/TW5-TiddlyMap#439]
Hi, loving TiddlyMap in particular in combination with the Kin filter and with Yaisog's [tagstree/taggingtree filters](https://talk.tiddlywiki.org/t/recursive-filter-operators-to-show-all-tiddlers-beneath-a-tag-and-all-tags-above-a-tiddler/3814/3).

Not infrequently however I wish there was a one click way of refreshing the TiddlyMap - two situations:
1. Map in floating mode keeps slowly rotating, can't catch the tiddlers!
2. I am using `field:title{$:/temp/tmap/currentTiddler}` and need to poke the map so it references a newly selected tiddler.

I can refresh by clicking the `Neighborhood scope` button then `none` but that's two clicks. Is there a better way of doing this?

Thanks again

Nick

**Comment by flibbles** [comment]
You should be using the Live View for that. It also uses `[field:title{$:/temp/tmap/currentTiddler}]` and it updates pretty much constantly.

As for dealing with floating nodes, it really helps to have at least one node that doesn't float inside of a graph. It grounds the rest of them. You need the latest version of TiddlyMap for that, which isn't available on tiddlymap.org.

**Comment by flibbles** [comment]
Does this mean it's all working for you? I'm closing this issue.
