### ISSUE TITLE
Modernise the UI of the map editor

### ISSUE THREAD

**Issue by arunnbabu81** [felixhayashi/TW5-TiddlyMap#440]
Can the map editor be modernized 
1. updating the stylesheet of the map editor to be compatible with all palettes - by using CSS properties like <<color background>> instead of using hard coded colors.
2. make the borders of the map editor in sidebar blend with TW page background by making the border-color of the map editor same as the background color
3. use better icons for the buttons in the map editor.
4. full-screen and half screen still show white background even if we are using dark palettes.

I tried to make [some stylesheet tweaks](https://new-demo.tiddlyhost.com/#Tiddlymap%20compatibilty) to make it look better as shown in [this demo wiki](https://new-demo.tiddlyhost.com/). It would be nice if the plug in also gets updated to a better looking UI.

**Comment by flibbles** [comment]
Are you using the latest version of TiddlyMap, because it should be doing a lot of that. The icons in the map editor are a Vis thing, so not really something I can control, but most of the rest of that is implemented.

**Comment by arunnbabu81** [comment]
> Are you using the latest version of TiddlyMap, because it should be doing a lot of that. The icons in the map editor are a Vis thing, so not really something I can control, but most of the rest of that is implemented.

I am using version 0.17.15+10019

**Comment by flibbles** [comment]
Oh I see. It's more that I missed a few things when I was making TMap compatible with palettes. I'll get around to fixing that eventually.

You're using the old vis.js version instead of vis-network by the way, which is why your buttons are mismatched colors.

**Comment by arunnbabu81** [comment]
> You're using the old vis.js version instead of vis-network by the way, which is why your buttons are mismatched colors.

How to use the vis-network version? Can you link some zip or json file for downloading it?

**Comment by arunnbabu81** [comment]
@flibbles Can you upload a json file for the latest tiddlymap and hotzone versions,  the vis-netwrok plug in as shown in this screenshot. 
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/67494083/212490161-38ec99c3-bc7a-424c-9818-2047ea7e5ccd.png">


I tried to add the vis-network plug in from the downloaded zip file, but it was giving error message like this.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/67494083/212490077-dada9cc1-ea66-464b-9085-2343044d6ab7.png">

**Comment by flibbles** [comment]
Here's a link for vis-network: https://github.com/flibbles/tw5-vis-network/releases/tag/v9.1.2

As for hotzone, I don't have the authority to create releases, but the one on the tiddlymap.org website should be fine.

As for tiddlymap, [there is already a package release for the latest version available](https://github.com/felixhayashi/TW5-TiddlyMap/releases/tag/v0.17.15).

**Comment by flibbles** [comment]
There, I put the dependencies in next to tiddlymap.json. Should be easy to figure out now.

**Comment by arunnbabu81** [comment]
Thank you @flibbles It works now

**Comment by flibbles** [comment]
I've slightly improved the palette support for fullscreen and halfscreen. Could probably be better, but I don't know what I'm doing in there.
