### ISSUE TITLE
How to use the live editor in the storyriver with zoom and navigation capabilities

### ISSUE THREAD

**Issue by arunnbabu81** [felixhayashi/TW5-TiddlyMap#441]
I want to use the [live editor in the storyriver ](https://new-demo.tiddlyhost.com/#Tiddlymap%20compatibilty)with zoom and navigation capabilities. I could not make zoom and navigation working with whatever I tried as shown in the link given above.

I even tried [this](https://www.reddit.com/r/TiddlyWiki5/comments/ma4d69/tiddlymap_in_storyriver_instead_of_the_sidebar/) method-but that also is not working for live tab

**Comment by flibbles** [comment]
You can zoom by holding ctrl.

As for an editing instance of a view in individual tiddlers, I just copied over the contents from tiddlymap/hook/editor into a tiddler and set the view attribute on the $tiddlymap widget, and it seems to work fine for me.

```
\whitespace trim
\define width() calc(100% - 15px)

<div class="tmap-mobile-editor">
  <div class="tmap-flash-message tmap-warning">
    &#32;
    The editor is not displayed in mobile mode.
  </div>
</div>
<div class="tmap-desktop-editor">
  <$tiddlymap
    class="tmap-sidebar-map-editor"
    editor="advanced"
    object-id="main_editor"
    view="VIEW OF YOUR CHOICE HERE"
    click-to-use="false">
  </$tiddlymap>
</div>
