### ISSUE TITLE
Is it possible to add the live map in halfscreen mode into the leftbar 

### ISSUE THREAD

**Issue by arunnbabu81** [felixhayashi/TW5-TiddlyMap#442]
https://leftbar.tiddlyhost.com/#
This is the leftbar plug in by Mat.
I have added the live map editor into the leftbar so that I can always seen the map while navigating the tiddlers-but I want it to be in halfscreen mode always. Is it possible?

Here is a demo of what I am trying to do -https://new-demo.tiddlyhost.com

**Comment by flibbles** [comment]
I'm going to say it's not possible, seeing as how I didn't even know there was a left bar. I am not the creator of TiddlyMap. The creator walked away a while ago. If you want this one done, you may need to figure out how to do it yourself. I'm not that experienced the the "fullscreen" and "halfscreen" features of tiddlymap.

**Comment by arunnbabu81** [comment]
```
body.tmap-has-halfscreen-widget .tmap-widget.tmap-halfscreen {
	background: white !important;
	height: 100% !important;
	width: 100% !important;
	/* position: fixed !important; */
	top: 0 !important;
	right: 0 !important;
	bottom: 0 !important;
	left: 0 !important;
	z-index: 999 !important;
	border: none !important;
	margin: 0 !important;
	position: absolute !important;
	border-left: 1px solid lightgray !important;
}
```


Above given is the CSS for the half screen widget of tiddlymap.
Below given is the CSS for leftbar content.

```
.leftbar-content {
	position: fixed;
	max-width: calc(42px + 350px);
	left: 0px;
	top: 1em;
	padding: 0em 10px 5px 10px;
	background: none;
	min-height: 50vh;
	max-height: 95vh;
	overflow-y: auto;
}
```

I tried to add this

```
.leftbar-content .tmap-has-halfscreen-widget .tmap-widget.tmap-halfscreen {
	background: white !important;
	height: 100% !important;
	width: 100% !important;
	/* position: fixed !important; */
	top: 0 !important;
	right: 0 !important;
	bottom: 0 !important;
	left: 0 !important;
	z-index: 999 !important;
	border: none !important;
	margin: 0 !important;
	position: absolute !important;
	border-left: 1px solid lightgray !important;
}
```

But it was not working. May be I will ask Mat's opinion on this

**Comment by arunnbabu81** [comment]
For the timebeing I am using this workaround.

https://leftbar-jdsidebar.tiddlyhost.com/

**Comment by flibbles** [comment]
Hope that workaround works for you, because this is never getting done. I just don't know tiddlymap well enough.
