### ISSUE TITLE
Error message on local media annotation using mediaplayer plug in when the focus tiddler is active in sidebar

### ISSUE THREAD

**Issue by arunnbabu81** [felixhayashi/TW5-TiddlyMap#443]
https://github.com/buggyj/mediaplayer/issues/9#issue-1567997000

Can you take a look at this issue.

I got an error message like shown below when I clicked on the button to start annotating a local video file using mediaplayer plug in by buggyj. This occurs only if there is focus tiddler active in the sidebar. Focus tiddler is taken from [this discussion](https://talk.tiddlywiki.org/t/an-invention-you-may-be-interested-in-focused-tiddler-types-and-setting-current-focus/6076/21)
![image](https://user-images.githubusercontent.com/67494083/216327635-b59ce7fe-87c1-49c9-9701-7e6613542035.png)

buggyj suggested that this issue may be related to Tiddlymap.

**Comment by flibbles** [comment]
I don't suppose you could install the non-uglified version of tiddlymap for that stack trace, could you?

**Comment by arunnbabu81** [comment]
> I don't suppose you could install the non-uglified version of tiddlymap for that stack trace, could you?

I didn't understand fully. How to use uglified version of Tiddlymap? What do you mean by stack trace?

**Comment by buggyj** [comment]
where is the non-uglified version of the plugin?

**Comment by flibbles** [comment]
You'd build it. Don't worry about it. I tracked down the bug already. I'll figure out a fix once I'm done with work.

**Comment by flibbles** [comment]
Fixed in latest release.

**Comment by arunnbabu81** [comment]
> Fixed in latest release.

Thanks for the fix. its working as expected.

**Comment by arunnbabu81** [comment]
I have to report another error with vis library which occurs only if the youtube parser shared in this [post](https://github.com/buggyj/mediaplayer/issues/3#issuecomment-1051179662) is installed in the wiki.

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/67494083/216841965-1befaeb1-dfcb-4132-900d-4ec24140d70b.png">


Here is the [demo](https://tiddlymap-utube-parser.tiddlyhost.com/)

**Comment by flibbles** [comment]
This is a separate issue.

**Comment by flibbles** [comment]
Also, this doesn't seem to have anything to do with TiddlyMap. That error points into that youtube plugin.

**Comment by flibbles** [comment]
The `$:/bj/parsers/utubeparser.js` is assuming that _canonical_uri is present, but that's not always true. It's a bug in whatever plugin hosts that file. It needs to test for undefined. Not a TiddlyMap issue.

**Comment by arunnbabu81** [comment]
I wasn't sure which plug in is the cause of this error....thats why I posted in both GitHub repos. I will wait for buggyj to respond. Thank for the comments @flibbles
