### ISSUE TITLE
How do I delete multiple nodes at once from the map?

### ISSUE THREAD

**Issue by UtopistList** [felixhayashi/TW5-TiddlyMap#444]
It would be great if we could say press CTRL and then be able to draw a rectangle and select many nodes on the map and delete them at once.
Is anything like this possible?

**Comment by UtopistList** [comment]
Ah I see it works with CTRL click.
Is it possible to visually select them by drawing a rectangle around them?

**Comment by flibbles** [comment]
Yeah. Hold down control and click-drag.

**Comment by flibbles** [comment]
Did you need anything else? Otherwise I'd like to close this.

**Comment by UtopistList** [comment]
Nothing else, thanks.
