### ISSUE TITLE
Node popups' dimensions

### ISSUE THREAD

**Issue by Alexandros81** [felixhayashi/TW5-TiddlyMap#445]
Hi!
How can I set bigger default dimensions for the popups which appear on mouse hoover over nodes (so that I do not need to enlarge the popup windows by acting on the right bottom corner of the popup)?
Many thanks
Alex

**Comment by flibbles** [comment]
Add the following tiddler to your tiddlywiki:

```
title: Alexandros81's css tweak
tags: $:/tags/Stylesheet

div.tmap-tooltip {
	max-width: 820px;
};
```

I've attached an export of it if I'm being unclear:

[Alexandros81's css tweak.csv](https://github.com/felixhayashi/TW5-TiddlyMap/files/10751131/Alexandros81.s.css.tweak.csv)

**Comment by flibbles** [comment]
Or better yet, just use the settings in "Configure TiddlyMap".
