### ISSUE TITLE
Feature request: Cascading node group styles

### ISSUE THREAD

**Issue by dowrite** [felixhayashi/TW5-TiddlyMap#446]
If a node belongs to 2 node-types, currently the node-type with the highest priority applies all of its style attributes to the node. It would be great if undefined style attributes would defer to the lower priority node-type.

For example: Suppose we have this node...
Title: Red Herring
Tags: fish (priority 1), red (priority 2)

Would love for it to take `fa-icon` from fish and `color` from red, but instead it only shows a black fish right now.

**Comment by flibbles** [comment]
What you're describing is implemented. The problem is that the fa-icon type doesn't have the color conditional to whatever the node is set to. And unfortunately I'm not even sure how to use icons, much less how to fix them.

**Comment by flibbles** [comment]
I've looked into this and confirmed that this behavior is entirely possible.

Create node groups inside of TiddlyMap with scopes of `[tag[fish]]` and `[tag[red]]` which have the "fa-icon" and "background" set respectively. You'll get exactly the outcome you're looking for. Let me know if you have any further trouble.
