### ISSUE TITLE
GLobal assignment problem, different from #447

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#448]
Hi @felixhayashi I have had to do a clean reinstall of linux for the first time in years, and I am having trouble getting tiddlymaps operating in the new setup with my old data.

I am running up-to-date Tiddlywiki 5 as a node server, global install, on linux manjaro, also up-to-date.  I did the drag and drop from the old page and that would work until I restarted. When I start the server, I get the error: 
`Error executing boot module $:/plugins/felixhayashi/vis/vis.js: "Global assignment is not allowed within modules on node."`
I removed everything from /usr/lib/nod_modules/tiddlywiki/plugins and reinstalled.  I then deleted all the felixhayashi plugin tiddlers from myactual tiddlywiki/tiddlers folder, created a tiddlywiki/plugins folder, and put the proper contents of the four plugin bundles into that folder as directed, then add the required addition to tiddly.info at the bottom, after the last bracket. I get the same error when I start tiddlywiki again. Any ideas what I am doing wrong here?  THanks, as always, for the great plugin. My work depends on it!

**Comment by flibbles** [comment]
This is because you're using Tiddlywiki v5.3.0, which made several breaking changes for plugins. Felix is gone. I may get around to fixing this when I'm back on Tiddlywiki. In the meantime, V5.2.7 should still work fine though.

**Comment by rcrath** [comment]
@flibbles ok, thnx, and thanx for keeping the project running.  How gone is @felixhayashi  Hope he is ok!

**Comment by flibbles** [comment]
@rcrath, I think he just moved on with his life. He checked back in a while ago to give me write access to this repository, and then retired. I don't even know how to reach him if I had to.

**Comment by flibbles** [comment]
By the way, I think this was also fixed for tiddlyMap too. You need to grab the latest version of vis-network though, which is available [here](https://github.com/felixhayashi/TW5-TiddlyMap/releases/tag/v0.17.16)

**Comment by rcrath** [comment]
I cleaned out the cruft from my earlier attempts and reinstalled all four bundles in a fresh 5.2.7 and all is well. Thnx again.
