### ISSUE TITLE
Tiddler content appearing in scrollable box when hovering over node

### ISSUE THREAD

**Issue by 5rise** [felixhayashi/TW5-TiddlyMap#45]
Basically, like Freeplane where hovering over a node causes the enclosed note to pop out in a fixed width box with a scrollbar.

For TiddlyMap the note would be the tiddler text.

I think this would be a real enhancement of tiddlywiki because you can dip into a node for the underlying detail whilst still maintaining the map view and the relationship between each topic without having to click away from the map.

Thanks,
Jon.

**Comment by felixhayashi** [comment]
Thanks @5rise :)

As for the point of giving the tooltip a scrollbox, this partly depends on visjs giving me a chance to style the tooltip. I already created an issue at their repo for that..

**Comment by 5rise** [comment]
Great. I hope it's possible.
Jon

**Comment by felixhayashi** [comment]
Quoting at @tobibeer from google groups

> I think we may want to explore more flexible "fullscreen modals" that are entirely themable... no predefined headers or even close buttons. If you ask me... full-screen ...no "overlay something, backdrop something". So, the preview would essentially overlay the map entirely until you closed it.

This is a nice idea. I could introduce an option "when in fullscreen mode, open clicked tiddlers as modals" (which is enabled by default). this would also keep the rendering and the widget calls intact. I understand that an overlay without buttons and title may look nicer but for the time being I just want to quickly push useful features and improve them in a later phase.

**Comment by tobibeer** [comment]
@felixhayashi, yes... surely two separate topics.

**Comment by felixhayashi** [comment]
Ok so for now:

* if fullscreen: content opens as modal
* if not fullscreen content opens in story river

I updated the demo site. E.g. click on

![selection_493](https://cloud.githubusercontent.com/assets/4307137/6145636/11dd66ce-b1e4-11e4-96bb-dcedef6b7f51.png)

Looks nice. @5rise I thinks this solves the issue?

-Felix

**Comment by tobibeer** [comment]
:+1:  ...nice. I just wished that at least the modal would be able to show the tiddler title rather than some "Tiddler Preview" title.

**Comment by felixhayashi** [comment]
> I just wished that at least the modal would be able to show a custom title, e.g. the tiddler title, rather than some "Tiddler Preview" title... being the template.

True story

> Also, since when is it "okay" and "cancel" rather than "close"?!?

Need to fix that (#46)

**Comment by 5rise** [comment]
This is brilliant Felix, thanks very much.

Just one small improvement if possible and that would be to close the preview with the keyboard. 
How about if the escape key closes the preview first and a 2nd press closes the full screen? 

Thanks
Jon.

**Comment by tobibeer** [comment]
> How about if the escape key closes the preview first and a 2nd press closes the full screen?

The current implementation of modals in TiddlyWiki seems a bit rudimentary. Neither can you ESC out of one, nor can you click outside of it to close it. These things really need improvements on the TiddlyWiki end of things.

**Comment by 5rise** [comment]
Ah, ok. An alternative thought would be for the close button to have the focus so it would close on pressing the enter key. Forgive me if this is equally difficult at the moment.
Thanks
Jon.

**Comment by felixhayashi** [comment]
> Just one small improvement if possible and that would be to close the preview with the keyboard. How about if the escape key closes the preview first and a 2nd press closes the full screen? 

The escape key in fullscreen cannot be trapped as the browser forces this key to be responsible to close the fullscreen. So there is no way I could use the escape key. But generally I am open to add key combinations to tiddlymap. I'll create another issue for that.

I agree with @tobibeer that it is the job of tiddlywiki itself to offer means to close a modal by clicking outside the modal.

> p.s.didn't meant to close issue - must have done it by mistake

happens often... It's because they put the close button next to the comment button.

**Comment by felixhayashi** [comment]
> Ah, ok. An alternative thought would be for the close button to have the focus so it would close on pressing the enter key. Forgive me if this is equally difficult at the moment.

Hi Jon, I opened another issue for this (#47) and I will close this issue now.

Adding key combos is not that easy to implement and I want to wait a bit with this until I know exactly how to do it and what scenarios I need to support. But I agree that this feature should come into existence at one point.

**Comment by 5rise** [comment]
Hi Felix,

Great. Thanks for all your work on this.

Regards
Jon

**Comment by felixhayashi** [comment]
Hi @5rise,

I added another option that might suit your needs, please see issue #50.

-Felix
