### ISSUE TITLE
plugin fails to load after tiddlywiki upgrade to 5.3

### ISSUE THREAD

**Issue by ssow** [felixhayashi/TW5-TiddlyMap#450]
Hi,

It seems that there is an issue with tiddlymap plugins after upgrading to tiddlywiki 5.3.
The following error is printed when starting nodejs

tiddlywiki[21557]: Error executing boot module $:/plugins/felixhayashi/vis/vis.js: "Global assignment is not allowed within modules on node."

Any clue regarding how to fix this issue ?

Thank you

**Comment by flibbles** [comment]
Have you upgraded to the latest version of vis-network? That _should_ fix the issue.

**Comment by ssow** [comment]
I'm unable to upgrade as the instance does not start :-)

**Comment by flibbles** [comment]
So this is happening in a standalone tiddlywiki file?

**Comment by ssow** [comment]
It's a nodejs installation.

**Comment by flibbles** [comment]
Right. You did say nodejs. My listening skills are poor.

If you're installing your plugins through the browser, you must have all your plugins in a "plugin" directory off your root dir? Is that correct?

**Comment by flibbles** [comment]
All right, I think I figured this out.

1. Download the vis-network json file from [here](https://github.com/felixhayashi/TW5-TiddlyMap/releases/download/v0.17.16/vis-network.json).
2. On the command line, `cd` to the root directory of your project, and then type:
    * `tiddlywiki --import <path/to/that/file.json> application/son`
   ...where <path/to/that/file.json> is probably something like `~/Downloads/vis-network.json`

That *should* sort you out. Sorry you have to go through this. Tiddlywiki V5.3.0 has suddenly decided to disallow Global assignment in nodejs, which is something that the vis-network relied on. The new version has a workaround for this.

**Comment by flibbles** [comment]
Crap. That's not going to work, is it? The command line won't even run because of this issue.

Let me think about this.

**Comment by ssow** [comment]
It does not work as the program stopped during loading :-)
I need to remove the plugins manually, i guess.

**Comment by flibbles** [comment]
Okay, I think I figured it out.
1. Yes, remove the old vis-network plugin manually like you said.
2. You can put that [vis-network.json file](https://github.com/felixhayashi/TW5-TiddlyMap/releases/download/v0.17.16/vis-network.json) directly into your `<root>/tiddlers` directory. That appears to make it load as a plugin, and while it's not a perfect place for it, this will at least allow you to load up your tiddlywiki.

**Comment by ssow** [comment]
I've removed all \$__plugins_felixhayashi_* files and the instance is online.
I guess it should be wise to add a "safe mode" flag to tiddlywiki nodejs which disables plugins loading :-)

Thank you very much for your help.

Sincerely

**Comment by flibbles** [comment]
Sorry you had to fully uninstall TiddlyMap to get back online. If you upgrade to the latest versions of TMap and its dependencies, everything should be functional again.

**Comment by ssow** [comment]
No worries. I've learn something from the experience.
