### ISSUE TITLE
Popup for "toggle tiddlymap actions" doesn't respect palette

### ISSUE THREAD

**Issue by eode** [felixhayashi/TW5-TiddlyMap#453]
I'm running Docker-tiddlywikimap, so I'm on master.

Happy to provide more info if needed.

**Comment by flibbles** [comment]
Yeah. Where is this Toggle Tiddlymap actions? Is that a button somewhere?

(I'm not the author of TiddlyMap. There are many features I don't know about.)

**Comment by flibbles** [comment]
Without more input on this, I cannot proceed. Closing until you return, @eode.
