### ISSUE TITLE
Where is the node-filter for different views of tiddlymap widget saved?

### ISSUE THREAD

**Issue by arunnbabu81** [felixhayashi/TW5-TiddlyMap#456]
Where is the node-filter for different views of tiddlymap widget saved?
Is there any config tiddler where the node-filter is saved for each views? 
I want to use tiddlymap in [this dynamic table concept ](https://demo-hub.tiddlyhost.com/#dynamic-table-demo) by accessing the node filter of the view for tiddlymap widget

**Comment by flibbles** [comment]
Sure.

`$:/plugins/felixhayashi/tiddlymap/graph/views/$(View name)$/filter/nodes!!filter`

**Comment by arunnbabu81** [comment]
Thank you @flibbles for helping out
