### ISSUE TITLE
Modal buttons need to match the topic/question

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#46]
* Close
* Ok, Cancel
* Abort
* Save, Quit

...

**Comment by tobibeer** [comment]
Where would I see those other modal buttons show up?

**Comment by felixhayashi** [comment]
E.g. when you create a new view or add a new node you can also cancel the proces.
When you try to delete a view that is referenced from a tiddler you can only abort.
And so on...

**Comment by tobibeer** [comment]
Yes, of course. Ireally haven't paid much attention to those custom modals so far. There possibly is a lot more logic to them than I imagined. Really need to start reading more code.
