### ISSUE TITLE
How to upgrade standalone plugin?

### ISSUE THREAD

**Issue by pjscott** [felixhayashi/TW5-TiddlyMap#463]
I'm running TiddlyMap standalone in Firefox on Windows and it seems I can only install the plugins by dragging and dropping the links from https://tiddlymap.org/#Installation . But the core plugin on that page is out of date: it installs v0.17.7+9982 whereas Github is at 17.20. I cannot for the life of me figure out how to update the plugin in the standalone to 17.20. Help!  I've tried using the browser tools console and I do not understand how this plugin gets installed.

**Comment by arunnbabu81** [comment]
https://github.com/felixhayashi/TW5-TiddlyMap/releases/tag/v0.17.20

You can download those json files and import or drag and drop them into your wiki

**Comment by pjscott** [comment]
W00T! Just what I needed.  Thank you!
