### ISSUE TITLE
If TiddlyMap can perform filtered display?

### ISSUE THREAD

**Issue by liaodalin19903** [felixhayashi/TW5-TiddlyMap#465]
Hello, may I ask if TiddlyMap can perform filtered display?
For example,
One wants to carry out filtered display based on the selected nodes and the specific categories of Edges.

in this snapshot, I want to only display the `node-1, node-3, node-5` and the `belong-to` links (I selected the node-1 and use the `belong-to` relation)

![image](https://github.com/user-attachments/assets/2293bf8d-d982-4751-b25f-9bd6b9b64bfb)

**Comment by flibbles** [comment]
Sounds like you want live view. You can configure it to only look for specific edges, I think.

**Comment by liaodalin19903** [comment]
> Sounds like you want live view. You can configure it to only look for specific edges, I think.

Thanks for your reply, could you explain more about configure specific edges? is there any official document about it?

**Comment by flibbles** [comment]
Not really. TiddlyMap isn't officially maintained anymore. It's just me keeping the lights on sometimes.

1. Go to live view
2. Go to "Configure View" from the settings drop down.
3. Go to "Edit Filters"
4. Change your edge type filter to be the following:

```
-[!match[belongs to]]
```

That filter specifies to remove all edges which are not the "belongs to" edge.

**Comment by flibbles** [comment]
Maybe live view isn't actually what you want. I misread your first post. You can set up that edge filter for a standard view too. Not just live view.

You'd use an edge filter like `[has[belongs to]]` and set neighbors to 1.

**Comment by flibbles** [comment]
This works for me.

![Screen Shot 2024-11-12 at 10 18 06 PM](https://github.com/user-attachments/assets/8952d3ed-2af9-4648-94d7-1c2fc4256be3)
