### ISSUE TITLE
Adding key combinations to tiddlymap

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#47]
* Library: Visjs already comes with the keycharm library so I think I could reuse that for my purpose.
* For which actions should keycombos exist
  * Opening the main editor in fullscreen
  * closing fullscreen
  * ...
* Which key combos should be the defaults?
* How should the combinations be configurable?

**Comment by tobibeer** [comment]
If you don't have specific usecases / requirements in mind, perhaps not implement any for now? I mean, wanting to put the map in fullscreen... does require first giving it focus. At that point you may just click the fullscreen button.

**Comment by felixhayashi** [comment]
Hi @tobibeer, yes, I really think the same. I should wait with this one and collect some information and write down actual use cases before working on it.

>  I mean, wanting to put the map in fullscreen... does require first giving it focus. At that point you may just click the fullscreen button.

Exactly
