### ISSUE TITLE
Management of edge-types

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#48]
* Deleting an edgetype as a whole (results in a deletion of all edge instances of this type)
* Renaming an edgetype (e.g. when accidentally created a wrong name or if name is not suitable anymore)
* Define Edge properties like has an arrow or is dotted; which color etc. this is related to #4. The Edge manager should be displayed as menu item in the editor.
* Link edges to an "explanation tiddler" that opens when clicking on that edge. This is inspired by the semantic web, where edges (predicates) can be resources as well not just live as mere literals (strings)

**Comment by tobibeer** [comment]
Unless difficult for you to manage, the above list sounds like you may want to create separate tickets for each.

**Comment by andtheWings** [comment]
+1

Especially about the edges having their own properties. Sounds like you're vision in the roadmap for changing the edges would accomplish this.

**Comment by felixhayashi** [comment]
> Unless difficult for you to manage, the above list sounds like you may want to create separate tickets for each.

@tobibeer True, just wanted to list some ideas. Once I am clear about what I am doing, I probably create an issue for every aspect.

> Especially about the edges having their own properties. Sounds like you're vision in the roadmap for changing the edges would accomplish this.

@andtheWings Yes, exactly. So I hope we are soon able to color our edges pink and change the label color to green :) More information on how edges can be styled in the future: http://visjs.org/docs/network.html#Edges_configuration

**Comment by felixhayashi** [comment]
Ok some previews here:

![selection_518](https://cloud.githubusercontent.com/assets/4307137/6543769/eef0246c-c52a-11e4-8e8b-9ff1c4c98d01.png)

![selection_519](https://cloud.githubusercontent.com/assets/4307137/6543770/ff416402-c52a-11e4-8646-db80b246e276.png)

Also:

* The save button does not quit the dialog
* Edgetypes may be filtered
* Scrollbars for filter area and config area

![selection_520](https://cloud.githubusercontent.com/assets/4307137/6543772/4b75581a-c52b-11e4-8bc7-7ba2e586995f.png)

**Comment by felixhayashi** [comment]
![selection_521](https://cloud.githubusercontent.com/assets/4307137/6543797/9e1fba64-c52c-11e4-91dc-dbef1c28b9f2.png)

![selection_522](https://cloud.githubusercontent.com/assets/4307137/6543798/a5593724-c52c-11e4-83c5-009255bb7213.png)

**Comment by felixhayashi** [comment]
I think this feature is worth the refactoring ;)
