### ISSUE TITLE
Halfscreen mode for main editor

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#50]
A "halfscreen" button would make the editor stretch vertically to consume all the vertical space available, hiding the sidebar completely, however, not hiding the story river. This way, more nodes fit on the map while the user can stay productive as he/she can still edit tiddlers.

**Comment by andtheWings** [comment]
+1

**Comment by tobibeer** [comment]
someone is getting real playful :D

curious how that's going to turn out... sounds very powerful for a well focused "map editing mode"

**Comment by felixhayashi** [comment]
> someone is getting real playful :D

Hehe, well spotted :) The more I use my plugin for my own work, the more I am noticing a lot of stuff that is still missing.

> curious how that's going to turn out... sounds very powerful for a well focused "map editing mode"

Yap

**Comment by felixhayashi** [comment]
Can be enabled as depicted below. I am thinking of making this the standard (it only works for the sidebar map editor)...

![selection_500](https://cloud.githubusercontent.com/assets/4307137/6355386/ef33b430-bc55-11e4-81c8-051290005aba.png)

**Comment by felixhayashi** [comment]
![selection_501](https://cloud.githubusercontent.com/assets/4307137/6355754/af3f8374-bc58-11e4-97ef-43afd4ab8497.png)

**Comment by tobibeer** [comment]
I can see the option but I am not seeing it do anything. What am I missing?

**Comment by felixhayashi** [comment]
Hi @tobibeer.

Thanks for telling me. I rewrote the option's info text to highlight that the effect only occurs when the fullscreen button is pressed.

*When the fullscreen-button is pressed, sidebar maps (live view, editor) are enlarged halfscreen instead of fullscreen so the story river stays visible.*

**Comment by tobibeer** [comment]
cool, thanks
