### ISSUE TITLE
Configure tiddlymap shows wrong modal

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#51]
It shows the "initial setup" modal.

**Comment by Peter-Miller** [comment]
Apologies if this the wrong issue but the initial setup modal seems very large and scary if you don't know anything about the plugin. Moreover, on small screens it can be hard to find the OK button. Maybe that's unintended because it isn't right modal ;-)

**Comment by felixhayashi** [comment]
Hi @Peter-Miller,

yes, I know it is large. I think you are right and only the most important options should go into the initial setup modal. Created a ticket for that #52
