### ISSUE TITLE
Straight edge?

### ISSUE THREAD

**Issue by 5rise** [felixhayashi/TW5-TiddlyMap#55]
Hi,

Is it possible to specify that the edges/arrows remain straight?

Thanks,
Jon

**Comment by felixhayashi** [comment]
Yes, go to http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Documentation and open the topic "Tweaking the Graph". Create a tiddler

` $:/plugins/felixhayashi/tiddlymap/config/vis/user`

and store all the desired vis properties there

**Comment by 5rise** [comment]
Hi Felix,

I created a tiddler and named it $:/plugins/felixhayashi/tiddlymap/config/vis/user
Also saved it as application/json tiddler as indicated in documentation
and put "smoothCurves.type": "straightCross" in the content but no joy.
Also tried changing colour as indicated in docs but that had no effect either.

Any ideas?
Thanks
Jon

**Comment by felixhayashi** [comment]
Hi Jon,

please add

    {
      "smoothCurves.type": "continuous",
      "smoothCurves.dynamic": false,
      "smoothCurves.roundness": 0
    }

to `$:/plugins/felixhayashi/tiddlymap/config/vis/user`.

see also http://visjs.org/docs/network.html#Configuration_options

Does this do what you want? Note, that edges of autogenerated graphs may overlap when using non dynamic curves with no roundness.

-Felix

**Comment by 5rise** [comment]
Perfect!
Thanks,
Jon.

**Comment by felixhayashi** [comment]
No problem :)

-Felix
