### ISSUE TITLE
Parse wikitext of caption field

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#57]
The description field is already parsed this way and allows wikitext and widget code. This should be allowed for the caption field as well.

Related to #56

**Comment by felixhayashi** [comment]
Now everything put in the caption field will be treated as wikitext and rendered as text/plain. E.g. adding `<<now>>`

![selection_504](https://cloud.githubusercontent.com/assets/4307137/6412369/22769eb4-be83-11e4-9db2-f937465e22cc.png)

**Comment by damscal** [comment]
I'm experiencing issues when using widgets in the caption field that make use of the <<currentTiddler>> variable, the node label appears blank. Is this behaviour to be expected and are there any workarounds?
Best Regards
