### ISSUE TITLE
Turn internal links into edges automatically if desired

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#58]
Hi, 
getting my head around TiddlyMap today.  Thank you for the open-top part of it.  With the mapping, I was wondering if there is a way to turn internal Tiddly links into edges automatically if desired.  The use case is that I keep my notes and creative writing in tiddlywiki, and make extensive use of internal links.  the organization is nonlinear and the map is too extensive in its nodes to sync all the connections manually.  It would be helpful for me to explore the edges of what was already internally connected, because the graph is too extensive to remember all the connections I have made.  I was hoping to use tiddlymap to do this.  The way I would conceive of using it is to create a map by populating it with a preexisting set of nodes that are part of a topic and tagged as such.  Thus I have about a hundred tiddlers in a project, all of which are tagged with the short title of the project.  Once they are in, there are no connections, even though the project is highly linked via internal hypertext links.  I would like to graph all those internal links as directed edges (undirected would work too, but directed would show which was the source of a link, obviously).  

If I can tag this as a question I will.  If it is not currently possible, would like to tag it as an enhancement.

thanks for considering.

**Comment by felixhayashi** [comment]
HI @rcrath,

As you pointed out correctly tiddlymap only links tiddlers as a whole, ignoring internal links. Tobias also already suggested displaying internal links via TiddlyMap (#14) and of course such a feature makes sense.

However, I need to plan this feature carefully. It may seem simple on the first sight but it is not.

TiddlyMap needs to display and handle these edges differently and also inconsistencies may occur.

* The user cannot reconnect internal links like he/she usually could (by selecting an edge-> editor bar -> edit edge).
* Edges based on internal links cannot be removed via editor or otherwise.
* How to deal with links that are displayed in a tiddler but not created explicitly via the link widget or `[[HelloThere]]` but using e.g. `<$list filter="HelloThere" />`. `[[HelloThere]backlinks[]]` and `[[HelloThere]links[]]` would ignore such kind of links and consequently TiddlyMap would also not be able to show all relationships which may cause confusion or irritate the user.

Until I solved these questions, I want to wait with the implementation. But I am sure that this feature will come into existence at one point.

> If I can tag this as a question I will. If it is not currently possible, would like to tag it as an enhancement.

Only the repo admin can use tags, just don't worry about tagging issues :)

-Felix

**Comment by tobibeer** [comment]
> However, I need to plan this feature carefully. It may seem simple on the first sight but it is not.

Eventually, I see this as something similar to what [x-plore](http://tbgtd.tiddlyspot.com/#x-plore) does in [tbGTD](http://tbgtd.tiddlyspot.com) ...click on the x-plore button in the toolbar.

There isn't a lot of info I'm afraid, mostly just [the code](https://github.com/tobibeer/TiddlyWikiPlugins/blob/master/plugins/x-plore.js).

It was inpsired a lot by Eric's [RelatedTiddlersPlugin](http://www.tiddlytools.com/#RelatedTiddlersPlugin) from TiddlyTools and allows to hook (custom) functions to deliver the (recursive) results.

**Comment by tobibeer** [comment]
> How to deal with links that are displayed in a tiddler but not created explicitly via the link widget or `[[HelloThere]]` but using e.g. `<$list filter="HelloThere" />`.

Simple: You rely on the very core functions and that's it. Whatever a core filter for references returns is what you use as well, whether that's limited or not is a different issue.

**Comment by tobibeer** [comment]
> Edges based on internal links cannot be removed via editor or otherwise.

To me, it's not about different edges, but a new type of "auto-generated-view" ...that does not work on  the basis of certain filters (alon) but instead on the grounds of (custom) lookup functions.

**Comment by felixhayashi** [comment]
> Simple: You rely on the very core functions and that's it. Whatever a core filter for references returns is what you use as well, whether that's limited or not is a different issue.

Yes, I agree, I just wanted to mention that the core functions do not return dynamically created links, which might confuse the user as not all links displayed in the tiddler are displayed in the (live) view.

> To me, it's not about different edges, but a new type of "auto-generated-view" ...that does not work on the basis of certain filters (alon) but instead on the grounds of (custom) lookup functions.

Yes, maybe it is better to fully separate auto-generated-views from user created views. But it also creates shortcomings. For example consider the "live view". It would be nice if manually added edges as well as dynamically created edges would be displayed.

> So, essentially, a user cannot edit such a view at all. If he wants to do so, he needs to edit the underlying tiddler data the way TiddlyWiki itself exposes them. It's really a whole lot more interesting to be able to "just see" that rather than have the icing on the cake and edit any of that as well!

I completely agree. I just think instead of declaring the whole view as read only, it would be better to disable certain functionalities for autogenerated edges. I will have a look how complicated this is. If it is too difficult or too hard to maintain, I will go with your advise and distinguish between read-only/read-write views.

-Felix

**Comment by rcrath** [comment]
THanks for considering this.  I hope it makes it in as having an edge view of my links on a map would be really useful for some of the more complex projects I am working on.

**Comment by tobibeer** [comment]
> I would base the decision at what point to display which type of edge on whether the widget runs in "editor mode" or "display mode" (I updated the vocab list #54 (comment)).

Sure, there can be entirely "display-only" views which bring the desired behaviour. The crucial thing is that you want to recursively apply filters, so perhaps there could be a new "recursive" filter input which could be extended by implementing the required filter, if not already part of the core.

**Comment by felixhayashi** [comment]
Hi @rcrath 

>  I hope it makes it in as having an edge view of my links on a map would be really useful for some of the more complex projects I am working on.

I am pretty sure I will implement this, I just need to plan it carefully.

Hi @tobibeer, 

> The crucial thing is that you want to recursively apply filters, so perhaps there could be a new "recursive" filter input which could be extended by implementing the required filter, if not already part of the core.

Yes, I'll call the filter recursively to produce larger neighbourhoods. This means I also need to mark tiddlers that are already visited to prevent infinite loop ;)

In envision it to be pretty cool to see a map of all tiddlers with all internal links :)

**Comment by felixhayashi** [comment]
Hi @tobibeer @rcrath,

getting closer to the goal. Here are some impressions from my development version (not online):

Create internal link:

![selection_525](https://cloud.githubusercontent.com/assets/4307137/6609155/7a08b4f8-c84e-11e4-850f-096b4deb56b2.png)

Which looks like this once rendered:

![selection_526](https://cloud.githubusercontent.com/assets/4307137/6609153/7a06df34-c84e-11e4-9392-6c79d0ccc2ef.png)

Voila :)

![selection_527](https://cloud.githubusercontent.com/assets/4307137/6609154/7a085fa8-c84e-11e4-9bdd-91f6fe415853.png)

Add styling to the default edge class via manager if desired (see #48):

![selection_528](https://cloud.githubusercontent.com/assets/4307137/6609152/7a05467e-c84e-11e4-9cde-1b6c2458e021.png)

**Comment by felixhayashi** [comment]
Ok I just tested it on the full tw (500+ tiddlers; 1000+ relations) and it is really slow (30 sec to produce the whole graph)... So I need to work on performance...

Anyways, again some impressions:

![selection_532](https://cloud.githubusercontent.com/assets/4307137/6609351/9168ae6c-c850-11e4-851a-f68a63722b55.png)

![selection_531](https://cloud.githubusercontent.com/assets/4307137/6609355/94fc937c-c850-11e4-8480-8652e330255e.png)

![selection_529](https://cloud.githubusercontent.com/assets/4307137/6609360/9ff94734-c850-11e4-9187-5120c6645ca9.png)

**Comment by felixhayashi** [comment]
funny to see that the majority of links is actually going to the "TiddlyWiki" Tiddler :)

**Comment by felixhayashi** [comment]
> Ok I just tested it on the full tw (500+ tiddlers; 1000+ relations) and it is really slow (30 sec to produce the whole graph)... So I need to work on performance...

My algorithm needs less then a second to produce the graph's data so I think vis.js is the performance breaker here.

**Comment by ybabel** [comment]
Seem's great ! Can't wait to test it.

For the performance issue ... with such a big graph, I think it's normal. All we can do is to split it, or reduce it's size by limiting the view to N neighboors (depending on a "center tiddler").

**Comment by felixhayashi** [comment]
Hi @ybabel 

> Seem's great ! Can't wait to test it.

Thanks! I will upload all changes next week.

> For the performance issue ... with such a big graph, I think it's normal. All we can do is to split it, or reduce it's size by limiting the view to N neighboors (depending on a "center tiddler").

Yes, surely the user can reduce the number of tiddlers displayed by changing the underlying node filter but I think some internal optimization is possible here.

-Felix

**Comment by rcrath** [comment]
@felixhayashi Thanks, this looks awesome.  Actually the full graph is a perfect use case for #59, which I still have open with the vis people (links in thread, infovis and a couple other javascript libraries have it so maybe it would not be a huge piece of work for them to import over there).  Only the center and the nearest neighbor or two would be in focus with the outer trees all on the edges of the fisheye view so the big pic is visible, but the details are not overwhelming.  Changing nodes or dragging on background changes center focus to navigate out the tree.  

Anyway, the auto-edges will be hugely useful to me with or withut fisheye once implemented.  Thank you!

**Comment by rcrath** [comment]
Live view is the stuff!  THanks.

**Comment by tobibeer** [comment]
For what its worth, expecting for a  full graph like the above to look meaningful or behave thusly is a bit naive. At that point you'd surely constrain the graph to some node being in focus and than a given number of levels for which you'd want to see the relationships.

**Comment by rcrath** [comment]
@tobibeer the way it has been implemented is that whatever tiddler has focus in the wiki becomes the central node in the live view map, with n degrees from it showing. Opening a new tiddler changes node focus on the map and double clicking on a new node changes focus to it and opens the corresponding tiddler. Really useful and when the maps get to complex, just scale back n.

**Comment by felixhayashi** [comment]
By the way @rcrath I had to remove the feature that the live view can store the positions "per context" as we discussed in another issue (https://github.com/felixhayashi/TW5-TiddlyMap/issues/91#issuecomment-89851588). But I'll probably introduce a feature where you can trigger entire views (you need to define them first, of course) in the live view instead of simply showing an automated neighbourhood arrangement.

**Comment by rcrath** [comment]
@felixhayashi thanks for the heads up.  Will the new feature gracefully handle adding tiddlers after the view has been saved?

**Comment by felixhayashi** [comment]
Sure, all views will be normal views and you just say "when this tiddler is focuessed, open that view".

**Comment by alexhunsley** [comment]
Hi all,

So is automatic edges from internal tiddler links in the current TW or not? Can't work out how to do it, if it is live in the current release.

**Comment by felixhayashi** [comment]
Hi @alexhunsley, this TiddlyMap feature is included but per default links are not shown. just open the view configuration of a view and remove the line from the edge-filter.

![2019-09-13 14:24:34](https://user-images.githubusercontent.com/4307137/64862301-6f911a00-d632-11e9-89f9-4e5e24d4f2f2.png)
