### ISSUE TITLE
hyperbolic view of network graph

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#59]
Hyperbolic trees, as in here:
http://mfellmann.net/wi/
and here (src)
http://hypergraph.sourceforge.net/download.html
make dealing with nodes and edges graphs in a constrained space much more manageable.  The idea is a curved rather than flat 2d map space, a fisheye effect with a centered node the largest and surrounding nodes and edge lengths  growing smaller as they recede.  this way the first few degrees (settable by the "angle" of the fisheye) are always visible, but the further away nodes are accessible just by moving them to the center of focus.  Makes the graph much easier to navigate because more neighbor information is visible and less detail, but the detail is available just by recentering, in which case the old center become the detail.  Hard to explain, but easy to use!

I also have the request in upstream:
https://github.com/almende/vis/issues/652

**Comment by tobibeer** [comment]
I think the answer is pretty clear: So long as VIS does not cater for it, neither will TiddlyMap.

**Comment by felixhayashi** [comment]
Hi @rcrath,

thanks for creating an issue at vis, thus creating awareness. Tobi is right, since TiddlyMap relies on vis, I can only deliver what they offer. So it depends on them and their workload if they implement it or not.

-Felix

**Comment by felixhayashi** [comment]
I will close this issue as it will be automatically supported if vis adds the option; tiddlymap outsources the vis options to be tweaked by the user so I do not need to change anything here.

**Comment by rcrath** [comment]
Hi @felixhayashi , wondering if Vis's [vis-graph3d](https://github.com/visjs/vis-graph3d) might open this back up as a possibility.  It looks like there is the capacity for drawing a distorted cartesian plane, which fisheye is an example of.  I do not have the chops to examine the code to figure out if this is possible with the updated library though. 

Hope this is not considered "necroing" the issue since it is still open.
