### ISSUE TITLE
toolbar on top and bottom

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#62]
Hi, in FiddlyWiki (http://way.net/FiddlyWiki), my TWC, I used view and edit templates to put a toolbar at the bottom as well as the top of the page.  Especially with the view template, this made it so when there were long tiddlers I did not have to scroll back up top to close them.  In a perfect world, they would only appear at the bottom if the top ones were not visible, or perhaps better, if the view template tool bar floated above the tiddler content at the top so that scrolling through content did not move tiddler.  I have not got my head around TW5 yet. I am putting it here because it goes hand-in-hand with the open at top behavior.  Is this possible through styling or editing something as in twc?  as a reference, here is my old TWC view template:
```
<div class='toolbar' ></span> <span macro='toolbar -closeTiddler closeOthers collapseTiddler +editTiddler permalink references jump deleteTiddler synchronize' ></span></div>
<div class='tagged' macro='tags'></div>
<div class='viewer' macro='view text wikified'></div>
<div class='tagClear'></div>
<div class='toolbar' ></span> <span macro='toolbar -closeTiddler closeOthers collapseTiddler +editTiddler permalink references jump deleteTiddler synchronize'></span></div> 
```

**Comment by tobibeer** [comment]
This seems an issue better placed at the TiddlyWiki5 repo.

**Comment by felixhayashi** [comment]
Sorry @rcrath but this has nothing to do with tiddlymap so I will close this issue. If you have a suggestion or a problem related to the "top story view" plugin that I can deal with, please post it at the repo site there: https://github.com/felixhayashi/TW5-TopStoryView).

**Comment by rcrath** [comment]
ok sorry about placement.

**Comment by felixhayashi** [comment]
no problem @rcrath
