### ISSUE TITLE
Improving TiddlyMap's graph data structure

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#64]
An important aspect of TiddlyMap is the underlying data structure that is used to store and retrieve graph data.

Graphs consist of *nodes* (vertices) and *edges*.

Since nodes are only representations of tiddlers, it is straight forward to use these corresponding tiddlers and their fields to store the node data (title, icon, color, tooltip-description).

On the contrary, it is not easy to decide how edges are best to be stored. [At the moment](http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Representation%20and%20storage%20of%20edges), edges are partitioned by their type, which means that all edges of the same type are stored alltogether in a separate tiddler (the so called "edge-store"). Moreover, edge stores are stored below the view's local path or below the global edge path.

While this data structure has some benefits (easy to handle, edge types can be quickly disabled etc.) there are some major drawbacks. Especially graph traversals cannot be efficiently performed since adjacent nodes need to be determined first by scanning through all the edges. But since we want at some point to allow stuff like shortest path calculation (e.g. dikstra) or neighbourhood discoveries, this is a deal breaker.

In order to solve this inefficiency I compared three different approaches:

https://docs.google.com/document/d/1pv-gBYLkN7ipDhrX1sA_x8K0Tp27IkKXmnEZ8RM9RAQ/edit?usp=sharing

In conclusion, I will store the edge data inside each tiddler to turn tiddlymap into a graph store. This means:

1. Edges will no longer be independently stored but instead be regarded as node attributes and correspondingly stored in [adjacency lists](http://opendatastructures.org/versions/edition-0.1e/ods-java/12_2_AdjacencyLists_Graph_a.html) that are stored as part of the tiddler (just like embedded links are stored in the body, however, in our case in a separate field).
2. Each node holds an adjacency lists for every view the node is represented in.

Another benefit of this approach is that afterwards we can create a tw-filter like `[all[current]relations[out]]`, and `[all[current]relations[in]]`.

Edge information (e.g. direction, color, style, weight), however, will be stored separately (a tiddler for each edge type). This avoids redundancy and gives us the freedom to extensively style edge types. Also we can ship tiddlymap with predefined edge-packages that are based on foaf or dublin core etc.

I will also build a "transformer" (not that one from the movie) that automatically translates existing edges so all people already extensively using tiddlymap (@andtheWings; http://danielriggins.com/mednotes/) do not have to worry ;)

**Comment by andtheWings** [comment]
I got excited reading this. Good luck, can't wait to see what you put together!

**Comment by Peter-Miller** [comment]
Out of curiosity is this likely to affect the ability to extract node and edge data for use with external layout tools?

As an aside to @andtheWings, have you considered using the service at http://cactus.nci.nih.gov/chemical/structure as a way to add additional content to your pathway nodes? The twirl option, for example, lets you generate a pseudo-3D representation. OK, it's probably a distraction for you...

**Comment by andtheWings** [comment]
@Peter-Miller, I did not know this was available! Thanks for sharing. :)

**Comment by felixhayashi** [comment]
Hi @Peter-Miller

> Out of curiosity is this likely to affect the ability to extract node and edge data for use with external layout tools?

Yes, I will not use dedicated edge stores anymore so you cannot simply grab all edges from the edge store tiddlers. Edges will now be contained in each tiddler. However, using the Adapter class, you are and will be able to create any format you wish to have for export. See http://bit.ly/tiddlymap_api. But good point, I'll create a standard export menu button "export graph data" that will open a download dialog with a json file containing all edges in a predefined format.

-Felix

**Comment by Peter-Miller** [comment]
Brilliant! Many thanks. Peter

**Comment by ybabel** [comment]
Very interresting improvement.
Maybe I'm just not aware of such functionnality, but, have we multiline field editor in TW5 ?
It may be unconvenient to access to edges field raw data if it's a big JSON field. 
Maybe I misundrestood your evolution.

**Comment by felixhayashi** [comment]
> It may be unconvenient to access to edges field raw data if it's a big JSON field.  
> Maybe I misundrestood your evolution.

Hehe. No, don't worry. I create an editor that allows you too style the edges and change names. See also #48.

**Comment by felixhayashi** [comment]
> Brilliant! Many thanks. Peter

Thanks Peter, no problem.
