### ISSUE TITLE
Update: Browser crashes when it tries to generate a map with many nodes.

### ISSUE THREAD

**Issue by andtheWings** [felixhayashi/TW5-TiddlyMap#66]
So my biggest problem now comes up when I accidentally set the main search bar to the map view rather than the list view. Because the search processes in real-time as I type instead of waiting for me to submit my query, it tends to crash when I first start typing and it tries to display all the nodes that match the first letter. Both Chrome and Firefox will get cranky and ask me if I want to stop the script from running because it's not responding (especially troublesome in Firefox because tabs are not independent from each other). 

I don't really need the map visualization very often for the main search bar. I find it's much more useful to use the search bar in individual map views. Is there any way I could turn off the map view for the main search bar in my instance of TiddlyMap? 

Sidenote: My laptop gets on the struggle-bus whenever it has to do graphically intensive work. It gets hella hot when it does. I found a forum post on how to update the HP drivers for my graphics card and see if that helps any. I'd still like to be able to turn off the search-bar map view if possible.

**Specs:**

- Chrome and Firefox
- Windows 7
- Model: HP ENVY 15 Notebook PC
- Processor: Intel Core i5-2450M (2.5 GHz)
- RAM: 6 gigs
- 64-bit OS
- Graphics: [Radeon HD 7690M](http://www.game-debate.com/hardware/index.php?gid=715&graphics=Radeon%20HD%207690M)

**Comment by felixhayashi** [comment]
I hate the map search ;) It has no benefit whatsoever (at the moment). I think of disabling it completetly...

I strongly recommend danielo's context search plugin! (see main search at the tiddlymap demo site).

> I don't really need the map visualization very often for the main search bar. I find it's much more useful to use the search bar in individual map views. Is there any way I could turn off the map view for the main search bar in my instance of TiddlyMap?

Strange, it should not be activated by default. Maybe it is a relict of a previous tiddlymap release in your wiki.

Change the value in `$:/config/SearchResults/Default` to `$:/core/ui/DefaultSearchResultList`

**Comment by felixhayashi** [comment]
> Specs:

That is a great system you have there. I think #64 will not help improving the speed of the graph-rendering once it is displayed, but it will make loading and saving faster I believe. We will see...

-Felix

**Comment by xnmp** [comment]
This is so frustrating for me, I can't use the search function at all without typing my search into notepad and then copying it into the search field, unless I want to crash my browser. Changing the value in $:/config/SearchResults/Default had no effect. I love all the features of TiddlyMap but this is really making it a pain to use. Is there any way to work around this?

**Comment by danielo515** [comment]
Hello @felixhayashi,
Thank you for mentioning my plugin. May you consider doing the same than my plugin does? As you know , it will not make any calculation or display any result until a configurable amount of characters have been typed in. 

Regards

**Comment by felixhayashi** [comment]
Hi @xnmp 

> This is so frustrating for me

Sorry for that and thanks for reporting. I do not use the graph search at all so I didn't know it is the default search mechanism after tiddlymap is installed. I will completely disable the graph search (because it is not nice anyway) and publish an update. But strange that changing the value in `$:/config/SearchResults/Default` had no effect...

@danielo515 

That would be an idea, but I think it is better to disable the graph search completely, I do not like it at all and it is not an important part of tiddlymap anyways...

-Felix

**Comment by felixhayashi** [comment]
@xnmp

do you use TiddlyWiki 5.1.7 or 5.1.8?

**Comment by xnmp** [comment]
@felixhayashi 5.1.8

**Comment by felixhayashi** [comment]
@xnmp 

I removed the graph search; please read #123 before updating.

**Comment by tobibeer** [comment]
As for the search problems, perhaps what we want is...

https://github.com/Jermolene/TiddlyWiki5/issues/1494

**Comment by felixhayashi** [comment]
Yes, that would be one solution :) Still the graph search is not nice so I'll leave it removed for now.
