### ISSUE TITLE
Private-Public edge concept will be abandoned in favour of better edge filters

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#71]
TiddlyMap serves to use cases:

> *Use Case 1 -- Global Linking*

> Purpose: Turning your wiki into a network of information

> TiddlyMap can be used to express the overall structure of your information contained in your wiki. On a top level, you want to show how each tiddler is related to all the other tiddlers in your wiki. With TiddlyMap, you may globally link your pieces of information in your wiki, thus creating a big holistic network of linked tiddlers. 

> *Use Case 2 -- Private Linking*

> Purpose: To create (almost) isolated concept or mind maps

> When creating concept or mind maps, you may want to restrict the edges to be exclusively displayed in the current view. The edges then only describe relationships that are valid or meaningful in a very narrow context and are solely dedicated to a special topic. They should not be visible outside the view and on the other hand, no edges from outside should appear inside the view.

The "private-" and "public-edge-mode" was introduced to allow the user to deal with these cases (e.g. https://groups.google.com/forum/#!msg/tiddlywiki/Nj885Ia8kGA/bsr0Hc3IpIwJ).

This is problematic:

* Public and private edges can never be mixed
  * The user cannot undo his/her choice after he/she started off in a certain mode.
  * Edges cannot be shared between modes and may have to be created twice, creating redundancy.
* Private relationships are not shown in the Live view which only shows public relationsships. This means relationship information is hidden and the user cannot do anything about it.

Therefore the private-public edge concept will be abandoned in favour of better edge filters:

**Then the user can decide him/herself which edges to display in a graph on the basis of tiddlywiki filters**. E.g. `[suffix[foaf:name]created[...]` or `[tag[office]]`.

**Comment by tobibeer** [comment]
:+1: edge filters
