### ISSUE TITLE
Handling the cloning of tiddlers

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#72]
From the current TiddlyMap docs:

> TiddlyMap comes with the default configuration that every tiddler used in a graph gets automatically assigned an id. The field used as id is per default "id" and not "title". This may create problems when you use tiddlywiki's //cloning// feature as the id field will also be cloned. You may set TiddlyMap to use the title as id field by setting `"field_nodeId": "title"`. The consequence is that all nodes added to a graph via a filter such as `[field:title[XYZ]]` or `[[XYZ]]` will disappear after a renaming operation.

Instead of telling the user to use the title as id field, I will check whether a changed tiddler has a dublicate tiddlymap id field. If so, a dialog will inform the user that tiddlymap will change the field's value into a unique UUID. A checkbox will be visible saying "do not show this dialog again". The way tiddlymap handles this case will be also exposed in the global options dialog.

**Comment by felixhayashi** [comment]
implemented and will be shipped with next release.

additionally, all edges will be removed of a cloned tiddler since this seems to feel more natural and causes less trouble of rewriting the edge ids.

**Comment by tobibeer** [comment]
@felixhayashi, @jermolene: I believe it would be beneficial to be able to tell TiddlyWiki to never duplicate certain fields.

**Comment by Jermolene** [comment]
>  I believe it would be beneficial to be able to tell TiddlyWiki to never duplicate certain fields

The big question is where one would enforce that; if at the level of the tiddler store then the impact would be profound; basically, everywhere where the code does an addTiddler() it would have to specifically check the return value to see if the store rejected the change. Nightmare!

**Comment by tobibeer** [comment]
@Jermolene, sorry, did not look up how cloning works exactly. Maybe **handleNewTiddlerEvent** could check the tiddler fields against those that are blacklisted via some namespace, e.g. `$:/config/fields/do-not-clone/tmap-id`.
