### ISSUE TITLE
Update docs on how to install TiddlyMap under nodejs

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#73]
Hello,
If you download the zip version of the plugin, and extracts the dist folder into the plugins folder of the main tiddlywiky installation and then you use it in any tiddlywiky.info file like this:
```
"felixhayashi/tiddlymap"
``` 
You will get a dependencies error
```
Error executing boot module $:/plugins/felixhayashi/tiddlymap/utils.js:
Error: Cannot find module '$:/plugins/felixhayashi/vis/vis.js'
```

I searched those files and they doesn't seem to exist on your folder, but they are mentioned on the installation for the standalone version.

**Comment by felixhayashi** [comment]
Hi Danielo,

you also need to include the vis.js library into your dist
(https://github.com/felixhayashi/TW5-Vis.js). If you want to use the
"live view" you need also the
https://github.com/felixhayashi/TW5-TopStoryView).

-Felix

**Comment by felixhayashi** [comment]
My tiddlywiki.info looks like this:

    {
      "plugins": [
        "tiddlywiki/github-fork-ribbon",
        "tiddlywiki/tiddlyweb",
        "tiddlywiki/markdown",
        "tiddlywiki/filesystem",
        "tiddlywiki/highlight",
        "felixhayashi/topstoryview",
        "felixhayashi/vis",
        "felixhayashi/tiddlymap",
        "danielo/contextPlugin"
      ],
      "themes": [
        "tiddlywiki/vanilla"
      ],
      "languages": [
        "en-US"
      ],
      "build": {
        "index": ["--rendertiddler","$:/core/save/all","index.html","text/plain"]
      },
      "config": {
        "retain-original-tiddler-path": true
      }
    }

**Comment by danielo515** [comment]
Ok.
It is working now. I was missing the other required plugins. Please note that there is no place on the documentation that mentions this dependencies. It would be nice to include it in some kind of "developers documentation". It is only explained for the standalone version.

Thank you very much @felixhayashi

**Comment by felixhayashi** [comment]
Hi @danielo515 

glad it works now :)

> Please note that there is no place on the documentation that mentions this dependencies. It would be nice to include it in some kind of "developers documentation". It is only explained for the standalone version.

Yes, you are certainly right! I am sorry for that. 

At the moment I am doing a big refactoring (see also #58 (some cool images at the end of the issue), #48, especially #64) but afterwards I'll definitely update the docs and installation instructions, maybe also create a short introductory video.

-Felix
