### ISSUE TITLE
'Add this node' link from the Map-Button is not working on TW5.1.8pre

### ISSUE THREAD

**Issue by ryanl888** [felixhayashi/TW5-TiddlyMap#75]
Hi Felix,
I really like your TiddlyMap plugin and have been learning and using it.  However, I have realized that there seems to be one feature that is not working correctly for me - the 'Add this node' link from the Map-Button on a tiddler. 

Behaviour: When I drag the link into a new view on the Map tab, nothing happens.  I know I should get a (green bar on FF) on the Map tab window - the same as I would get importing a tiddler.

Excepted Behaviour: As mentioned above, I would expect to see the green import bar - then the tiddler show up as a node in the view. I suspect it is not my browser, since I am able to achieve this when testing the TiddlyMap site on github.io!

My Setup: I tried first using my main TW - running on Tiddlyspot in Firefox, Safari, Chrome - not working.  This is basically TW5 pre-release upgraded from an earlier version - to get TW Editor.  I then tried on a blank TW5 pre-release with only TiddlyMap installed - same behaviour on local file on Firefox, Safari, Chrome.  
I am running Mac OS X Yosemite.

Steps to reproduce: On a (Mac OS X - don't know about Windows/Linux) computer, download a fresh copy of 5.1.8 pre-release, install TiddlyMap according to the instructions, create a new tiddler, reload, create a new view (I am not sure if this is necessary), try to use the Map-Button 'Add this node' to drag the link to create the node in the new view.

I searched this forum for any mention of this problem, but cannot see any.  Perhaps it is my system, but I have no idea why that would be - and as I mentioned it is working for me on the TiddlyMap github.io site...  

Regards,
Ryan

**Comment by felixhayashi** [comment]
Hi @ryanl888 

thanks for reporting this. You are right, it doesn't work. In fact, no internal link can be dropped anymore at any place in the wiki.

@Jermolene
Sorry to ask, but how can I reanimate the dropzone widget so it works again for my purposes as discussed (https://github.com/Jermolene/TiddlyWiki5/issues/1067)

**Comment by Jermolene** [comment]
Hi @felixhayashi the problem here is that we made a change to prevent inadvertent drag-and-drop of a tiddler within the same window.

I think that the best solution may well be as I've recommended before: to create your own dropzone widget. When I last looked, you were re-using the existing dropzone widget in a cunning way, but in the process laying yourself open to this sort of unintended behaviour.

**Comment by felixhayashi** [comment]
>  to create your own dropzone widget. When I last looked, you were re-using the existing dropzone widget in a cunning way, but in the process laying yourself open to this sort of unintended behaviour.

Thanks for visiting the thread and for clarifying this!

Until now, the dropzone widget looked promising as a way to have different dropzones and drag n drop stuff within the wik but I guess I have to write my own then.

**Comment by Jermolene** [comment]
>  but I guess I have to write my own then.

If you find there's scope to encapsulate reusable bits of the dropzone widget into utility functions then we should do that.

**Comment by felixhayashi** [comment]
Hi @ryanl888

I decided to remove this feature then for now and to compensate the missing original functionality I enhanced the "add node" dialog (that opens when double clicking on an empty spot in the graph).

In the next release (released next week hopefully) will work this way:

* If you leave the title field blank, a name will be automatically generated for you. E.g. "Node 1" and a tiddler with that name is created in the background.
* By entering a title into the textfield, Tiddlywiki is automatically searched for existing titles.
* By clicking on a title in the list, it will be copied into the above textfield
* By choosing an existing title, you add the existing tiddler as node to the view (more specifically: its id gets added to the view's node filter.) <---- This is equals to the former drag-n-drop.

### Step 1: Searching/Specifying title

![selection_556](https://cloud.githubusercontent.com/assets/4307137/6770591/2607c66c-d0c5-11e4-870e-8f87a33a92b1.png)

### Step 2: It gets added to the view

![selection_558](https://cloud.githubusercontent.com/assets/4307137/6770602/bff7ec66-d0c5-11e4-85bb-f9ad82286a09.png)

**Comment by Jermolene** [comment]
@felixhayashi we could add a hidden preference that disables the prevention of same window dragging, maybe?

It would be a matter of your plugin setting `$tw.config.disableSameWindowDrag` to true in a startup module, and the core having a tiny patch to check that configuration variable before performing the same window dragging text.

**Comment by felixhayashi** [comment]
Hi @Jermolene 

thanks for considering this. Would setting `$tw.config.disableSameWindowDrag` result in the whole wiki displaying the green import bar at the top as well? Because it should be disabled on a wiki level, but enabled on a widget level via attribute. E.g. `<$dropzone allow-internal="true"...` and the wiki's dropzone has `allow-internal` set to `false`.

If this cannot be done easily, I think it is best to take some time and plan this carefully and eventually, I come back at you with some ideas. There is no need for a rush now as I already added a compensation to tiddlymap.

Offtopic: By the way, I will support internal links in the map soon, I am making progress with performance issues and the usual use case is not to display the whole wiki at once ;) - please see https://github.com/felixhayashi/TW5-TiddlyMap/issues/58#issuecomment-78397190

**Comment by Jermolene** [comment]
OK that's good, let's leave it until post-5.1.8

**Comment by ryanl888** [comment]
Hi @felixhayashi 
>If you leave the title field blank, a name will be automatically generated for you. E.g. "Node 1" and a tiddler with that name is created in the background.
>By entering a title into the textfield, Tiddlywiki is automatically searched for existing titles...

Sounds good!  This workaround looks like it will be fine :)  Additionally, I like the idea of integration of the two 'options' (ie create a tiddler/link to a tiddler) within the view tab. Of course, some will undoubtedly prefer to link from the tiddler, but this seems like a more natural workflow to me.  

Regards,
Ryan

**Comment by felixhayashi** [comment]
HI @ryanl888 

> This workaround looks like it will be fine :) 

Yes, I tested it quite a bit and it works smoothly ;)

> Additionally, I like the idea of integration of the two 'options' (ie create a tiddler/link to a tiddler) within the view tab. Of course, some will undoubtedly prefer to link from the tiddler, but this seems like a more natural workflow to me. 

Yes, of course, you will still be able to connect nodes from inside the "map editor" by drawing edges as well as from the tiddler by using the dropdown.

-Felix
