### ISSUE TITLE
TW5.1.8 Issues

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#76]
* ~~Modal layout: header, footer have no spacing~~
* ~~DragNDrop not working anymore (see #75)~~

**Comment by Jermolene** [comment]
Hi @felixhayashi is the modal header/footer problem related to this change?

https://github.com/Jermolene/TiddlyWiki5/commit/421ac16389cf07e8c00611ef5a858da0b89f7584

I think that the old behaviour was wrong.

**Comment by felixhayashi** [comment]
@Jermolene Thanks for giving me a hint.
