### ISSUE TITLE
Allow caption to be used

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#8]
Tiddler titles are very important since they told you what is the tiddler about. The title is not always suitable to be used inside a node graph. Allowing caption as the value to be displayed gives the opportunity to have long and meaningful titles with beautiful node maps.

For example

* title: transaction.propertyname
* caption: property

**Comment by felixhayashi** [comment]
@danielo515 @tobibeer 

Tooltips can now be used by setting the description field of a tiddler. This can support short titles. if no description field exists, the title is used as tooltip.

The field can be changed from `description` to something else e.g. I know you use summary @tobibeer. But I still have to outsource this as a config tiddler...

Example at demo site: "How to deal with large Titles"

-Felix

**Comment by tobibeer** [comment]
Thanks Felix, perpahs open a new dummy issue only to close it ...and perhaps have the description / tooltip topic be a different thing.

**Comment by danielo515** [comment]
@felixhayashi 

This is terrific! Your plugin is getting more and more professional on each update.

**Comment by danielo515** [comment]
Dear @felixhayashi 

Links are dead again

**Comment by felixhayashi** [comment]
@danielo515,

>  Your plugin is getting more and more professional on each update. 

Thanks

> Links are dead again

Which links? You mean http://bit.ly/tiddlymap?

**Comment by felixhayashi** [comment]
> Thanks Felix, perpahs open a new dummy issue only to close it ...and perhaps have the description / tooltip topic be a different thing.

Good point.

**Comment by rcrath** [comment]
>The API for taskgraph is now accessible and has many features for developers:
I created an example here: http://wkpr.de/hosting/tmp/tw5/taskgraph/#Adapter
Seems to be down.  Very interested in it though.

**Comment by felixhayashi** [comment]
@rcrath yes, this old url is not in use anymore. please use the following proxy: http://bit.ly/tiddlymap

**Comment by tobibeer** [comment]
> http://bit.ly/tiddlymap_api

slick

**Comment by rcrath** [comment]
taskgraph=tiddlymap?  I thought it was a separate thing.  thanks.
