### ISSUE TITLE
"Live" tab removed - Live view is now merged into the sidebar editor as selectable view

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#82]
The live view is now available in the editor. Why?

* Less tabs in the sidebar
* You may configure the view, just like any other view
* You can edit the edges!!

If you want to have any view as individual tab in your sidebar tabs list do the following:

Create a tiddler with the following fields:

    title: $:/mySidebarTab1
    caption: MySidebarTabTitle
    tags: $:/tags/SideBar

Now add the following body (or similar) to the tiddler (generate the widget code with the generator in the editor menu):

    <$tiddlymap
      view="My favorite view" 
      click-to-use="false"
      width="calc(100% - 15px)"
      bottom-spacing="35px"
    </$tiddlymap>

**Comment by tobibeer** [comment]
:+1:
