### ISSUE TITLE
GUI sometimes may hang when opening "map" tab in sidebar

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#83]
This happens when a view with many nodes is preselected and the user switches to / opens the "map" tab. It takes a few seconds until the GUI is displayed. The problem is, it looks like the application killed itself. This only happens when the map tab is not open yet; if the map tab is open and the editor is visible and a user switches to a view with many nodes, it doesn't freeze.

**Comment by felixhayashi** [comment]
Solution: delay (100ms) the painting of the graph to allow the gui to render

**Comment by felixhayashi** [comment]
@andtheWings, maybe this bug also affected you.

**Comment by andtheWings** [comment]
Yeah, it does/did.
