### ISSUE TITLE
Edge-type namespaces introduced

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#84]
Please see http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Edge-type%20namespaces

Related to #71

**Comment by andtheWings** [comment]
Cool concept. Could you clarify the text that is in the "View Configuration":

>A namespace (like 'foaf' in 'foaf:person') that will be automatically added to all edge-types you create in this view.
>
>Note: All namespaces are automatically stipped when the edge label is displayed in the graph

In this context do you mean "foaf" like the abbreviation for "friend of a friend"? Also, what does stipped mean?

**Comment by felixhayashi** [comment]
Hi @andtheWings 

> In this context do you mean "foaf" like the abbreviation for "friend of a friend"?

Yes, sorry, I wasn't clear about that. I updated the docs

http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Edge-type%20namespaces

I hope it becomes a bit clearer.

and fixed the typo. I meant "stripped" not stipped :)

**Comment by andtheWings** [comment]
Groovy. Thanks!
