### ISSUE TITLE
Live view edges multiplied by neighborhood scope on focus

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#85]
Thank you for the live edges view.  In a tiddlymap version updated immediately before this report...(side question: How do I determine what version I am running?)

When live view is selected and the neighberhood scope is set to more than 1 step away, the number of edges shown to and from the node with focus is multiplied by number of steps in the neighborhood scope.  So for example, with neighborhood scope set to two steps, with Tiddler A having the focus in a live view map, all links to and from tiddler A will be doubled.  All are orange (no gray ones).  Beyond first step all lines are single.  If steps is set to three, the first step (A=>B) will be tripled, the second step  (B=>C) will be doubled and the third (C=>D) is single (I am pretty sure about this, but because of the complexity of the maps I am working with, it is hard to tell for certain).

I am actually beginning to wonder if this is a feature, since it shows node distance from focused node at a glance, but on a complex map it really makes a mess.  If it is a feature not a bug, could the multiple edges be replaced by thick/closer- thinner/further edges?

Really enjoying using this feature.

**Comment by felixhayashi** [comment]
Hi @rcrath 

thanks for telling me! I just discovered it myself #86 and now see you were faster in finding this bug! :)

> In a tiddlymap version updated immediately before this report...(side question: How do I determine what version I am running?

Open the control panel ($:/ControlPanel) and go to plugins ;)

> Really enjoying using this feature.

Thanks :) Sorry for its bugginess. 

> I am actually beginning to wonder if this is a feature, since it shows node distance from focused node at a glance, but on a complex map it really makes a mess. If it is a feature not a bug, could the multiple edges be replaced by thick/closer- thinner/further edges?

Haha nice idea, no it is REALLY a bug I think it looks too ugly to be a feature. I would not use the thickness of edges for this since thickness usually means relationship strengh. But you can style the original matching nodes. Please see http://felixhayashi.github.io/TW5-TiddlyMap/index.html#Styling%20of%20groups

**Comment by felixhayashi** [comment]
Hi @rcrath 

I fixed this. Thanks.

> but because of the complexity of the maps I am working with, it is hard to tell for certain).

If you (plan to) host a public wiki that uses TiddlyMap, please tell me and I will put it as showcase on the demo site.

-Felix

**Comment by rcrath** [comment]
@felixhayashi I use it for my note taking and it is really useful to have the connections mapped out.  Nothing anywhere close to release, but maybe I could host it as some sort of open process for writing thing.  Let me think about that.

**Comment by felixhayashi** [comment]
> Nothing anywhere close to release, but maybe I could host it as some sort of open process for writing thing. Let me think about that.

Oh, no pressure here, I just wanted to mention it so in case you publish a wiki that uses tiddlymap (like e.g. Daniel's site http://danielriggins.com/mednotes/), would be nice if I could use it as showcase. Once I have collected a handful of sites, I'll create a showcase section on the demo site.

-Felix

**Comment by rcrath** [comment]
I direct a digital humanities initiative at my uni and this would make an interesting showcase for us too without creating too much work. I'd just need to export the particular project and host it on node.js on our server instead of locally.  It would be a good excuse to organize my notes better!  ANyway, I'm working on that stuff today, so let me see if it is feasible.  Really depends on the state of my notes.

**Comment by felixhayashi** [comment]
Hi @rcrath 

Maybe this works:

go to

1. advanced search
1. switch to "filter"
1. use `[tag[YOURTAG]]`
1. click export button next to edit text field
