### ISSUE TITLE
suggestion: move neighborhood scope up in the interface

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#89]
I find myself clicking the option button->config View->neighborhood scope dropdown a lot.  there is a nice open space between the option button and the search bar. could the neighborhood scope go there?  A really simple graphic of linked boxes is what gets the job done in VUE:
```
 <>=<>=<>=<>=<> = 0 steps
<x>=<>=<>=<>=<> = 1 step
<x>=<x>=<>=<>=<> 2 steps
<x>=<x>=<x>=<>=<> 3 steps
```
and so on.  THey are not even labeled in VUE since their function is obvious once you use them, though I found that confusing.  a popover would probably be enough.

**Comment by felixhayashi** [comment]
> I find myself clicking the option button->config View->neighborhood scope dropdown a lot. there is a nice open space between the option button and the search bar. could the neighborhood scope go there?

Good point! While the open space may not be so wide on smaller screens, I also think it would be useful to quickly enlarge the neighbourhood. @andtheWings suggested something similar (#40).

**Comment by felixhayashi** [comment]
Will be the next thing on my list to get implemented ;)

**Comment by rcrath** [comment]
:), graph is much neater too with other changes...Thnx!
