### ISSUE TITLE
Draw raster lines on canvas for snapping nodes

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#94]
Vis.js overrides the canvas so it is not possible at the moment to draw a raster.

See https://github.com/almende/vis/issues/725

Related to #87

**Comment by felixhayashi** [comment]
related to #226

**Comment by felixhayashi** [comment]
Sneak preview of the raster feature: https://www.youtube.com/watch?v=gT-3rfrwNgE

**Comment by tobibeer** [comment]
snaptastic @felixhayashi 👍

**Comment by felixhayashi** [comment]
Thanks @tobibeer ! :)
