### ISSUE TITLE
Babaaom "Neighbourhood scope button"

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#95]
I think "Neighbourhood radar" would be a good name too...

Anyways

![selection_578](https://cloud.githubusercontent.com/assets/4307137/6962982/1f61f350-d93a-11e4-96af-905de094672e.png)

Related to: #40 and #89

**Comment by andtheWings** [comment]
Cooooool

**Comment by felixhayashi** [comment]
I thought so too ;) Couldn't help it and had to add "Babaaom" to the issue title.
