### ISSUE TITLE
Tiddlymap no longer working on iOS devices 

### ISSUE THREAD

**Issue by ryanl888** [felixhayashi/TW5-TiddlyMap#96]
Hi Felix,
I was testing Tiddlymap today and thought I would try it on my iPad (iOS 8.1.2).  I got a JavaScript error (see below).  I tested with iPhone- same iOS # in Safari and Chrome - still got the error.  
![image](https://cloud.githubusercontent.com/assets/11003603/6994239/b7155864-dace-11e4-939b-3b96689a2ad6.jpg)

I seem to remember before I had tried using the demo Tiddlymap site on my iPad and it worked - albeit there was an issue with full screen map - which I didn't mind - this was a few versions ago.  

Now, it seems to not work at all - JavaScript error pops up right away and buttons are inactive after I close the pop up.  Refreshing just brings the popup back.

I searched the forum - no mention of this and didn't see it on demo site either. Is it a known limitation or a bug?  Thanks!

Regards
Ryan

**Comment by felixhayashi** [comment]
Hi @ryanl888 

it is definitely a bug. Thanks for telling me. Your device does not support the fullscreen api it seams. I have to catch the error in any case. I'll give you an update once I fixed it.

-Felix

**Comment by ryanl888** [comment]
Hi @felixhayashi 
Ok sounds good!

**Comment by felixhayashi** [comment]
Hi @ryanl888 

I doublechecked which browsers support fullscreen and iOS Safari does not support fullscreen

http://caniuse.com/#feat=fullscreen

Could you please test the new version whether the error is still displayed? I catch the exception and display a modal instead...

Thanks
-Felix

**Comment by ryanl888** [comment]
Hi Felix,
I did a quick test on my iphone and the error is gone!  Will test more fully later this evening.

Regards
Ryan

**Comment by ryanl888** [comment]
Hi @felixhayashi 
Everything is looking pretty good from my tests.  No error, just minor display bugs - like if I rotate a view in a tiddler on my iPhone, I get a blank screen and need to refresh.  This doesn't happen on iPad.  Should I make this a new issue?

Regards,
Ryan

**Comment by felixhayashi** [comment]
Hi @ryanl888 

> Everything is looking pretty good from my tests. No error

nice, thanks for telling me.

>  This doesn't happen on iPad. Should I make this a new issue?

yes, please. It's easier for me to keep track this way ;)

-Felix

**Comment by ryanl888** [comment]
Hi Felix,Sure will do.
RegardsRyan






On Thu, Apr 9, 2015 at 1:27 PM -0700, "Felix Küppers" <notifications@github.com> wrote:












Hi @ryanl888 




Everything is looking pretty good from my tests. No error




nice, thanks for telling me.




This doesn't happen on iPad. Should I make this a new issue?




yes, please. It's easier for me to keep track this way ;)



-Felix

**Comment by felixhayashi** [comment]
@ryanl888 I fixed the fullscreen so now it should work for iOS Safari as well in v0.10.7.
