### ISSUE TITLE
Artefacts appearing on right side

### ISSUE THREAD

**Issue by twMat** [felixhayashi/TW5-TiddlyMap#97]
From merely looking at the titles in the issues list, I could not see anything that seemed to bring up this so I "hope" it's a new issue:

![skarmklipp1](https://cloud.githubusercontent.com/assets/4534056/6998171/afd6a184-dbd7-11e4-947e-27baa87117ca.PNG)

As illustrated, "stuff" appears to the right, and only in the TiddlyMap frame. I noted this some time ago but just now in trying to reproduce it I realized it comes from when nodes sweep by that area. It happens automatically at start (as the nodes "swivel into place") but also if I drag nodes there. Here's a more extreme example from manual dragging:

![skarmklipp3](https://cloud.githubusercontent.com/assets/4534056/6998225/88a5c868-dbd9-11e4-8ee8-c559d41a373d.PNG)

I get it in Chrome and IE, but not FF (but this may be because I have a plugin showing my tabs to the left instead of at top so the window area is smaller to begin with). I susped, (but having no knowledge of how these things work) that it may have to do with the hardware acceleration and how the screen on my laptop updates. It's a lenovo, maybe 2 years and decent overall performance so it's not odd in any way.

**Comment by felixhayashi** [comment]
Hi @twMat,

I noticed this as well but I thought it only happens on my machine. :confused:

So far, I couldn't figure out what causes this, sometimes it does not happen at all.

In any case, it is a bug and thanks for reporting!

**Comment by felixhayashi** [comment]
Are you using Linux?

**Comment by twMat** [comment]
Win8.1.

**Comment by felixhayashi** [comment]
TiddlyMap does not support Windows

**Comment by felixhayashi** [comment]
Haha no, just joking :) I'll need some time to figure out what is causing this. I hope it is solvable.

**Comment by twMat** [comment]
hehe! Ok, hope you find it.

**Comment by felixhayashi** [comment]
I think I solved this one :) I think it is a vis bug but if I fire a redraw after the canvas is drawn, the graphic errors disappear.

**Comment by twMat** [comment]
Great workin' !
