### ISSUE TITLE
question on installing under node.js

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#98]
Hi, I am running TiddlyMaps on a tiddlywiki running on node.js.  I installed using the standard install instructions without ever seeing the node.js specific instructions until today.  I have not copied any files anywhere or restarted the node.js server, but everything seems to work fine.  Do I need to follow the node.js instructions still?  I don't mind making the changes, but don't want to foul things up that are already (seemingly) working ok.  Also, it took me a while to figure out the node.js paths.  I am guessing that the path "TiddlyWiki5/plugins" is the equivalent of "/usr/lib/node_modules/tiddlywiki/plugins", correct?  I understand that it will obviously be different on different OS.

**Comment by felixhayashi** [comment]
Hi Rich,

> without ever seeing the node.js specific instructions until today. 

Just uploaded these yesterday ;)

> I don't mind making the changes, but don't want to foul things up that are already (seemingly) working ok.

Don't worry, everything is fine.

It works because you probably dragged your old wiki ("import") into your node.js wiki, right? The reason it works here is because you also imported the plugin as tiddler (your node js wiki folder now contains a *.tid file named `$:/plugins/felixhayashi/tiddlymap`; same for vis.js and topstoryview). This is fine, however, then you need to keep updating the plugin via the "import" mechanism and you do not need to add the plugins to the "tiddlywiki.info" file. 

> /usr/lib/node_modules/tiddlywiki/plugins

yes, correct. Seems like you installed it as global node module then...

**Comment by rcrath** [comment]
>It works because you probably dragged your old wiki ("import") into your node.js wiki, right? 

I forget how I upgraded from classic to 5 exactly.  I found upgrade instructions somewhere on the TW site, and I started out on node.js before getting hooked on tiddlymaps.  I installed the your plugins the first and all subsequent times via the drag and drop install instructions on the demo page.  

>The reason it works here is because you also imported the plugin as tiddler (your node js wiki folder now contains a *.tid file named $:/plugins/felixhayashi/tiddlymap; same for vis.js and topstoryview). This is fine, however, then you need to keep updating the plugin via the "import" mechanism and you do not need to add the plugins to the "tiddlywiki.info" file.

ok, great.  My tiddlers folder does not have any subdirs in it. your plugins appear in the tiddlers folder as 
~~~
./tiddlers/$__plugins_felixhayashi_tiddlymap.tid
~~~
with underscores instead of slashes.

>yes, correct. Seems like you installed it as global node module then..

no, the default tw5 plugins seem to be there but not anything I installed. ANything I put in is in the wiki's tiddlers folder.

I am assuming that the reason for the special install instructions is that the way I have it set up, the plugins are only installed for this wiki even though node.js TW can serve up multiple wikis, so the other instructions avoid having to reinstall for each wiki?

I'll close the issue, but let me know if I am grossly misunderstanding something please.

**Comment by felixhayashi** [comment]
Hi @rcrath 

> with underscores instead of slashes.

yes, you are right, tw replaces `/` with `__`

> no, the default tw5 plugins seem to be there but not anything I installed. ANything I put in is in the wiki's tiddlers folder.

This is a correct setup, sorry for causing any confusion...

> I am assuming that the reason for the special install instructions is that the way I have it set up, the plugins are only installed for this wiki even though node.js TW can serve up multiple wikis, so the other instructions avoid having to reinstall for each wiki?

Absolutely correct :)

With your setup, say you deploy 10 wikis, then you need to import for every wiki you deploy the plugins via dragndrop. If you used the other setup where the plugins are put in the plugin directory, it were sufficient enough to update the plugins directory with a new plugin version and consequently all wikis would run with the new version after a restart.

But I should add to the README.md that it is also possible to use the plugin with nodejs using dragndrop import...
