### ISSUE TITLE
Create new view -> Forbidden

### ISSUE THREAD

**Issue by gitany** [felixhayashi/TW5-TiddlyMap#99]
Hello! I'm a newbie who is completely amazed by the power of Tiddlymap.

On the map, I tried to Create a new view, but it was forbidden. I know Tiddlymap is actively being revised, but I wanted to make sure I wasn't missing something, as I was hoping to experiment with creating different maps.

Tiddlymap 0.7.15 was installed today as a standalone (drag & dropped 3 plugins into an empty TiddlyWiki 5.1.7), on Firefox, with TiddlyFox Extension for Firefox. Thanks in advance!

**Comment by felixhayashi** [comment]
> On the map, I tried to Create a new view, but it was forbidden. 

Wooops, sorry about that. I'll fix that immediately.

> Hello! I'm a newbie who is completely amazed by the power of Tiddlymap.

Thanks :)

**Comment by felixhayashi** [comment]
@gitany 

> I know Tiddlymap is actively being revised, but I wanted to make sure I wasn't missing something

Yes, please do not hesitate to ask. Sometimes stupid bugs sneak into the code that I am not aware of ;)

**Comment by gitany** [comment]
Thank you for the quick fix. After playing with TiddlyMap a bit more, I must say I'm simply impressed!

**Comment by felixhayashi** [comment]
> Thank you for the quick fix.

No problem. Thanks for reporting

> After playing with TiddlyMap a bit more, I must say I'm simply impressed! 

Thank you. Took me quite some time to build it ;)
